### ISSUE TITLE
TokenIgnores invalid match

### ISSUE THREAD

**Issue by ranebrown** [vale-cli/vale#101]
I'm attempting to use this regex to disable checks on a specific line after I have reviewed the displayed warning/error: `TokenIgnores = (.*<--!vale-disable-->[\n\r])`

The expected behavior is to disable checks for the specific line that ends with the string `<--!vale-disable-->`.

I am seeing inconsistent behavior in which errors are disabled.

For example, in this case the warning on the second line is disabled instead of the first line:
```
* Complete career objective statement <--!vale-disable-->
    * Briefly describe your eventual career objective.
    * So the cat was stolen.
```

In this case all the warnings/errors are disabled:
```
* Complete career objective statement <--!vale-disable-->


    * Briefly describe your eventual career objective.
    * So the cat was stolen.
```

Here, the error is disabled on the correct line:
```
* Complete career objective statement
    * Briefly describe your eventual career objective.
    * So the cat was stolen. <--!vale-disable-->
    * Briefly describe your eventual career objective.
```

Thanks!

**Comment by jdkato** [comment]
The issue is that you're using `TokenIgnores` (an [inline-level](https://spec.commonmark.org/0.28/#inlines) operator) in a [block-level context](https://spec.commonmark.org/0.28/#container-blocks). This will likely produce invalid markup, which can result in unexpected behavior.

For your use case, I'd suggest using Vale's [context-specific configuration](https://errata-ai.github.io/vale/config/#using-comments):

```markdown
* Complete career objective statement
    * Briefly describe your eventual career objective.

    <!-- vale off -->

    * So the cat was stolen.

    <!-- vale on -->

    * Briefly describe your eventual career objective.
```

**Comment by ranebrown** [comment]
Is there a way to use `BlockIgnores` to make this work then? I would really prefer to have a single comment at the end of a line instead of adding two additional lines for each check I want to disable.

**Comment by jdkato** [comment]
No, `BlockIgnores` requires starting and ending delimiters too (e.g., as in the documentation,`{< file "hello.go" go >}` and `{</ file >}`).

If you're having to disable certain checks consistently, I'd suggest disabling them in the [`.vale.ini`](https://errata-ai.github.io/vale/config/#valeini) file.

**Comment by ranebrown** [comment]
It's more of a case by case basis which is why I was looking for an alternative method. If there isn't any other option or plan to add a feature I guess this can be closed. Thanks for the responses.
