### ISSUE TITLE
Vale finds issues outside of the specified scope

### ISSUE THREAD

**Issue by alcazaco** [vale-cli/vale#105]
OS: Windows 10
Installed from msi package
version 1.3.0.

Hi!
I want to display warnings for links with the `here` text. The new version (1.3.0) supports applying rules for the **links** scope.

The problem is that vale may display error message in the wrong scope.

My rule code:
```
extends: existence
message: "Do not name links like '%s'."
level: warning
ignorecase: true
scope: link
tokens:
  - here
```

My test text:
```
Write us here: email@example.com. Click [here](https://www.example.com/) for more information.
```

The result:
![image](https://user-images.githubusercontent.com/20209898/51487024-48d85780-1db3-11e9-9e40-0a06ad86e9bb.png)

When the sentences are separated with a new line, everything works correctly:
![image](https://user-images.githubusercontent.com/20209898/51487167-ab315800-1db3-11e9-98ea-1d7840900c2d.png)

PS. I could reproduce the issue with your [test example](https://github.com/errata-ai/vale/commit/4f962181bd5c96b9f185ad188067f315d70ff8ef#diff-b7caedea2d83a7b93024df87a3e5a886R5) by changing the sentence order:

![image](https://user-images.githubusercontent.com/20209898/51487753-dec0b200-1db4-11e9-9929-ee87635657ef.png)

**Comment by jdkato** [comment]
Thanks for the report.

The issue here is that Vale is *reporting the location incorrectly*, not that it's finding an issue outside of the specified scope (in other words, the warning will go away if you remove `[here](https://www.example.com/)`).

This isn't straightforward to fix, as I discussed in https://github.com/errata-ai/vale/issues/95#issuecomment-441308412. However, as shown in your examples, this should only happen when the offending, link-scoped text also occurs (verbatim) earlier in the *same paragraph*.

**Comment by jdkato** [comment]
This should be fixed in the next release.

**Comment by alcazaco** [comment]
Hi!

I use Vale v2.2.2 (the same issue occurs on v2.3-beta).

I have the following rule:

```yml
extends: substitution
message: "Better say '%s'"
level: warning
ignorecase: false
code: false
swap:
  '(?:\s)Abc': "ABC"
```

Here I want to make users write the product name as "ABC", but allow them to write like "MyCompanyName.Abc" (with a dot (`.`) before the ABC product name, that is suitable for namespaces or package names).

Let's take a look at the test sentence:

> `Install the [CompanyName.Abc](http://example.com) package to add the Abc product to your application.`

Here I want to leave the `[CompanyName.Abc](http://example.com)` as is, but display a warning for `... to add the Abc product`.

I try to check this sentence in Vale:

```console
PS C:\Work\temp\vale-temp> vale --ext='.md' 'Install the [CompanyName.Abc](http://example.com) package to add the Abc product to your application.'      

 stdin.md
 1:26  warning  Better say 'ABC'  MyRules.NamingRules

✖ 0 errors, 1 warning and 0 suggestions in stdin.
```

Vale finds an error in the `[CompanyName.Abc](http://example.com)` part of the sentence. That is **wrong**.

Lets change the checked sentence:

```console
PS C:\Work\temp\vale-temp> vale --ext='.md' 'Install the [CompanyName.ABC](http://example.com) package to add the Abc product to your application.'

 stdin.md
 1:70  warning     Better say 'ABC'          MyRules.NamingRules

✖ 0 errors, 1 warning and 0 suggestions in stdin.
```

Now, Vale displays an error exactly in the right place. This issue looks similar to the original issue.
