### ISSUE TITLE
Cannot build on alpine with clang

### ISSUE THREAD

**Issue by tyhal** [vale-cli/vale#112]
- OS: Alpine Linux
- Install method: go get in docker
- Vale version: building head ( aff8077 )

Setting requirements for build
```
RUN apk --no-cache add clang libc-dev binutils
ENV CC=clang
ENV CXX=clang++
```

Returns

```
 > [godeps 4/9] RUN go get -u github.com/errata-ai/vale:
#24 7.622 # runtime/cgo
#24 7.622 /usr/bin/ld: cannot find crtbeginS.o: No such file or directory
#24 7.622 /usr/bin/ld: cannot find -lgcc
#24 7.622 /usr/bin/ld: cannot find -lgcc_s
#24 7.622 /usr/bin/ld: cannot find -lgcc
#24 7.622 /usr/bin/ld: cannot find -lgcc_s
#24 7.622 /usr/bin/ld: cannot find crtendS.o: No such file or directory
```

But just switching to gcc fixes this

```
RUN apk --no-cache add gcc libc-dev binutils
```

**Comment by jdkato** [comment]
My guess would be that this is an issue with  clang (not with Vale specifically). 

A brief search suggests that this may be fixed in clang >= 3.4.2-5. What version of clang are you using?

**Comment by tyhal** [comment]
```
/ # clang --version
Alpine clang version 5.0.1 (tags/RELEASE_502/final) (based on LLVM 5.0.1)
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by jdkato** [comment]
Sorry for the delayed response.

It's not clear to me what the issue is (or if it's even on Vale's end). 

If you find that there's something I can do to fix this, though, I'd be glad to make the changes.

**Comment by tyhal** [comment]
Ok I'll see if I can narrow it down 👍

**Comment by tyhal** [comment]
Ok so unrelated to vale, cgo needs to have gcc installed regardless of using clang as it needs libgcc.so and libgcc_s.so

If I want to not have gcc installed I can use `ENV CGO_ENABLED=0`, but then I don't need clang either ¯\\\_(ツ)_/¯

To build with clang as much as possible:

```
FROM golang:1.11-alpine3.9 as build
RUN apk --no-cache add clang clang-dev musl-dev git gcc
ENV CXX=clang++
ENV CC=clang
RUN go get github.com/errata-ai/vale
```
