### ISSUE TITLE
configuration cached

### ISSUE THREAD

**Issue by shudson310** [vale-cli/vale#113]
I recently upgraded Vale to v1.3.2 on Mac 64-bit.

As part of the upgrade, I changed the location where I put my styles files.

I updated the StylesPath in my .vale.ini file, but when running vale, it still tries to use the old path (and doesn't use the new path).

Are the settings cached somewhere that I can clear?

**Comment by jdkato** [comment]
No, Vale doesn't do any caching. Have you inspected the output of `vale dc`?

**Comment by shudson310** [comment]
Yes, when I originally set up vale, we were using a styles path of /user/Documents/common/tools/vale/styles  Now we want to use /user/Documents/tools/vale/styles (no common). When I run vale, it seems to use the original styles path, even though I updated the path in the .vale.ini file. vale dc shows the original path, not the path from the updated .vale.ini file.

**Comment by jdkato** [comment]
Were you able to figure this out?

If not, I'd guess that perhaps it's reading from an old `.vale.ini` file?

**Comment by shudson310** [comment]
Unfortunately, no. I only have one .vale.ini file in my home directory. All I did was update the styles path, but Vale doesn't recognize it. It continues to use the original styles path. I uninstalled Vale, reinstalled, but it still seems to reflect the old path - hence my question about cached settings...

**Comment by shudson310** [comment]
OK, I closed my Terminal on Mac, and restarted the terminal. The new path seems to be recognized. Perhaps it was the Terminal that was caching?

**Comment by jdkato** [comment]
It's certainly possible.

I'll consider this resolved for now.
