### ISSUE TITLE
Support lint of XML files (configurable)

### ISSUE THREAD

**Issue by shudson310** [vale-cli/vale#114]
RFE to support checking of DITA and DocBook XML files. Similar to HTML parsing, should be able to configure certain elements to be ignored (like can be done for HTML script, style, pre, code, and tt tags).

**Comment by ChrisChinchilla** [comment]
That would be cool, then Vale is also opened up to possibilities of integration in all those lovely XML editing tools ;)

**Comment by felicitymay** [comment]
This would help us too. We have one proprietory XML file format, and it would be nice to be able to parse MadCap Flare files too.

**Comment by jdkato** [comment]
I'm looking to add this soon but, as someone who isn't particularly familiar with the world of  proprietary XML software, I'm not exactly sure of the best way to go about this.

Would it be sufficient to process XML documents according to a user-specified `.xsl` file? I'm assuming proprietary XML software either provides this or offers export-to-HTML functionality instead.

**Comment by jdkato** [comment]
This will be available in the next release.
