### ISSUE TITLE
BlockIgnores not working for .mdx files

### ISSUE THREAD

**Issue by gaurav-nelson** [vale-cli/vale#115]
I can't get `BlockIgnores` to work. I want to ignore text in code blocks. I verified the regex on https://regex101.com/r/prulD0/2

**My `.mdx` file.**
```markdown
---
title: "Doc title"
description: "Title description."
tags: ["tag1", "tag2"]
published: true
featured: false
---

import customComponent from "components/customComponent";
import customComponent2 from "components/customComponent2";

Customers interact with products using different input methods: keyboard, mouse, touch, voice, and more. So use generic verbs that work with any input method. Don't use input-specific verbs, such as click or swipe. Instead, use the verbs listed here.

Content on the first screen (also called above the fold) is the most likely to be read. Many readers won’t scroll further without a compelling reason. So as always, keep it short, and lead with what’s most important to the customer. Keep in mind that what appears above the fold varies by device and screen resolution.

Numerous studies have shown that readers look at specific areas of a page first. In left-to-right languages, people read in an F shape, giving the most attention to the upper-left corner of a page. Put your most important information there. Or try placing an offer or a Buy or Download button there. If the navigation is on the left, put your most important information in the upper-left corner of the text pane.

1. Run the `install` script to configure XYZ, 

    ```bash
    unzip -d foldername filename.zip

    ./foldername/subfolder/install.sh
    ```
2. Run second command
	```bash
		command -i more | grep something
	```
```

**Vale config**
```yaml

# Example Vale config file (`.vale.ini` or `_vale.ini`)

# Core settings
StylesPath = vale

# The minimum alert level to display (suggestion, warning, or error).
#
# CI builds will only fail on error-level alerts.
MinAlertLevel = warning

# Global settings (applied to every syntax)
[*]
# List of styles to load
BasedOnStyles = Microsoft
# Style.Rule = {YES, NO} to enable or disable a specific rule
# vale.Editorializing = YES
# You can also change the level associated with a rule
# vale.Hedging = error
BlockIgnores = (?s) *(\x60\x60\x60[a-z]*\n[\s\S]*?\x60\x60\x60)

# Syntax-specific settings
# These overwrite any conflicting global settings
# [*.{mdx}]
```

- OS `Ubuntu 18.04 on Windows`
- Install method `Go`
- Vale version `master`

**Comment by gaurav-nelson** [comment]
The output I get is: 
```bash
 vale test.mdx

 test.mdx
 4:8    error    Punctuation should be inside    Microsoft.Quotes
                 the quotes.
 27:12  warning  Use first person sparingly      Microsoft.FirstPerson
                 ('i').

✖ 1 error, 1 warning and 0 suggestions in 1 file.
```

that `27:12` is `-i` option from code block.

**Comment by jdkato** [comment]
MDX isn't one of Vale's [supported formats](https://errata-ai.github.io/vale/formats/). Any format not listed as supported is simply linted line-by-line, without any syntax-related functionality.

I'm open to adding support for more formats, but I think MDX would be difficult to handle well.

**Comment by gaurav-nelson** [comment]
Thanks for explanation @jdkato 

After I read your comment, I changed the extension o my file as `test.md` and it works fine. It shows no errors for code blocks even without `BlockIgnores`. (As by default, vale ignores indented blocks, fenced blocks, and code spans.)

Is there a config I can apply to say treat `*.mdx` files as `*.md`?
OR add limited support for MDX, like before processing, we ignore all JSX stuff and only test markdown things.

From what I understand, [MDX](https://mdxjs.com/getting-started/#mdx) includes:
1. HTML tags, JSX blocks, Data, and documents
    - example: `(?s) *(<[^>]*>)` https://regex101.com/r/3SMeCS/2
2. Import statements
    - example: `(?s) *(import.*?\n)` https://regex101.com/r/gypy5X/1 (not perfect)
3. Export statements
    - example: https://regex101.com/r/nVceX9/1 (not working but, we can figure it out)

Please let me know I'll be happy to help.

**Comment by jdkato** [comment]
> Is there a config I can apply to say treat `*.mdx` files as `*.md`?

Not yet.

I do think, though, that this is the best way to "support" MDX since Vale relies on Go's [`html`](https://godoc.org/golang.org/x/net/html) package to do all of its syntax-related processing. In other words, we'd treat MDX as Markdown and consider the JSX parts as "non-standard markup" (i.e., use `BlockIgnores` and `TokenIgnores`).

I'll try to put out a release with support for custom syntax mapping next week (which I'm sure has uses beyond this issue) and then we can see how well MDX can be handled with `BlockIgnores` and `TokenIgnores` alone.

**Comment by gaurav-nelson** [comment]
You're a superstar 🌟 Thank you for your help.

**Comment by jdkato** [comment]
@gaurav-nelson: This is available on master now (`go get -u github.com/errata-ai/vale`), if you'd like to test it out prior to an official release.

You can associate an "unknown" format with one of Vale's supported formats via the new `formats` section in your `.vale.ini`:

```ini
StylesPath = ci/vale/styles
MinAlertLevel = warning

# The "formats" section allows you to associate an "unknown" format
# with one of Vale's supported formats.
[formats]
mdx = md

[*.md]
BasedOnStyles = write-good, Joblint
```

**Comment by gaurav-nelson** [comment]
Thank you again. It is working as expected. 🥇

**Comment by skm14747** [comment]
Hi @jdkato @gaurav-nelson 

was facing a similar issue. Adding formats seems to be working but `BlockIgnores` seems to be ignoring everything after code(```)  block.



`StylesPath = .github/styles

MinAlertLevel = error

Vocab = HMSVocab

Packages = Google

[formats]
mdx = md

[*.md]


BasedOnStyles = Vale, Google


BlockIgnores = (?s) *(\x60\x60\x60[a-z]*\n[\s\S]*?\x60\x60\x60)

TokenIgnores = [a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}`

**Comment by jaredsmith** [comment]
> was facing a similar issue. Adding formats seems to be working but `BlockIgnores` seems to be ignoring everything after code(```) block.

I have seen this as well.

**Comment by jdkato** [comment]
For the record, `formats` merely instructs Vale to treat what would otherwise be an "unknown" file format as one of its supported ones. 

This isn't a great solution for MDX, though, because it's largely distinct from Markdown. So, as said above, you'll need to do some work with `BlockIgnores` / `TokenIgnores` to see reasonable results.
