### ISSUE TITLE
Rules inspired by LanguageTool

### ISSUE THREAD

**Issue by CsatiZoltan** [vale-cli/vale#116]
Your [Microsoft](https://github.com/errata-ai/Microsoft) repository includes a handful of rules. What about including rules what LanguageTool uses? It could further expand the power of vale.
The attached screenshot is an example the usefulness of LanguageTool (I used it as a Firefox plugin).
![example](https://user-images.githubusercontent.com/12742890/55249065-804c0000-524b-11e9-89a6-bf3f41e8d4a4.PNG)

**Comment by jdkato** [comment]
Grammar-related rules are something I'd like to introduce soon. There are a number of implementations details that need to be figured out, but it's definitely on the way.

**Comment by ChrisChinchilla** [comment]
I have a very, very rough future tense one in progress…

**Comment by jdkato** [comment]
This will be available with the next release of Vale Server.

**Comment by teeann** [comment]
Is `LanguageTool` rules already available in `vale`? I cannot seem to get it working.

**Comment by ChrisChinchilla** [comment]
@teeann I had this same question a couple of days ago, and this functionality was removed.

**Comment by jdkato** [comment]
Vale (the CLI tool) never had any direct integration with LanguageTool.

You can create similar rules to LanguageTool using the [sequence](https://docs.errata.ai/vale/styles#sequence) extension point, though. There are a few examples (more to come) at the new [Rule Explorer](https://share.streamlit.io/jdkato/rules/main/app/main.py) under the category "grammar".
