### ISSUE TITLE
Creating a style that checks YAML tags in a markdown file.

### ISSUE THREAD

**Issue by jmayntzhusen** [vale-cli/vale#117]
Hi there!

I am quite new at using Vale, so this may be a stupid question. My issue is that I have several markdown files that contain YAML at the top, something like this:

```
---
yamltag: true
---
# Heading here
```

I noticed though when I wrote a new style it would ignore the data wrapped inside '---'. 

I found this issue: https://github.com/errata-ai/vale/issues/24 and it sounds like it should be able to parse the lines?

My style .yml file looks like this:
```
extends: existence
message: "No yamltag has been set"
level: error
tokens:
  - yamltag
```

**Comment by jdkato** [comment]
Vale purposely ignores front matter (I consider it to be a [fenced block](https://errata-ai.github.io/vale/formats/#markdown)). #24 is referencing standalone JSON or YAML files, which are indeed linted line-by-line.

If you're attempting to validate the presence or value type of front matter entires, I'd recommend doing this as a separate step (from prose linting) using a library like [`gray-matter`](https://github.com/jonschlinkert/gray-matter).

**Comment by jmayntzhusen** [comment]
Thanks for the quick reply!

Will pair up Vale with something else then for my front matter, thanks! 🙂
