### ISSUE TITLE
Duplicate words missed inside code fences and frontmatter in Markdown

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#123]
Noticed this in the 1.4.0 on OSX. Can't recall if this worked correctly before

**Comment by jdkato** [comment]
It's not just duplicate words: Vale deliberately ignores the content in front matter (#122) and code fences. This hasn't changed (significantly) since the release of Vale.

I'm not opposed to making this configurable, but it probably won't happen soon (there are a number of other changes that I'm working on at the moment).

**Comment by nschonni** [comment]
Fair enough. I just noticed that it was missing a few things doing a regular regex check instead.
Does it need a Blackfriday update, or is it more involved? I'll try to take a look, but I haven't done much/any Go

**Comment by jdkato** [comment]
Blackfriday doesn't support front matter at all (as far as I know). However, my current approach is to preemptively convert front matter to code fences prior to any markup processing. So, in theory, you shouldn't have to edit Blackfriday to make this configurable.

That said, my ultimate goal is to drop the current method of Markdown -> HTML altogether in favor of using [Pandoc's AST](https://pandoc.org/scripting-1.11.html). This would allow Vale to support a number of new formats (namely, LaTeX and XML), fix issues like #95, and drop its Blackfriday, docutils, and Asciidoctor dependencies.

**Comment by jdkato** [comment]
In the next release, you'll be able to selectively disable markup processing (such as skipping code blocks) by defining `scope: raw` in a given rule.
