### ISSUE TITLE
GitHub Actions & Docker Image

### ISSUE THREAD

**Issue by warrenbuckley** [vale-cli/vale#124]
Hello,
I am wondering if the Docker Image for Vale has been used in GitHub Actions at all in conjunction with GitHub Checks. To give PRs submitted to docs repos on GitHub, contextual error messages inline of the PR/diff view of a GitHub PR.

Curious to know if this has been done before or not.

Thanks,
Warren :)

**Comment by jdkato** [comment]
The only project I know of is [github-action-vale-lint](https://github.com/gaurav-nelson/github-action-vale-lint).

**Comment by ChrisChinchilla** [comment]
I had it working with the Vale Docker image, I am yet to finish that experiment, work got busy. But I had no idea about that repo, so that's very useful :)
