### ISSUE TITLE
Allow in-place edits for some style types

### ISSUE THREAD

**Issue by patcon** [vale-cli/vale#125]
First off, thanks so much for the amazing tool!

I feel that the title is self-explanatory. Having an in-place edit mode would allow a plugin like [`danger-suggester`](https://github.com/r7kamura/danger-suggester) to work :)

At first guess, this could include `substitution` and `capitalization` types.

Curious to hear whather you'd be open to accepting such a feature!

**Comment by jdkato** [comment]
I've never personally been a fan of such a feature (#70 discusses this as well), as I think simply performing an in-place edit is rarely going to actually improve writing. In other words, I think Vale is great at identifying issues, but correcting these issues often requires restructuring and rephrasing that no tool (at the moment) is capable of doing.

(This is certainly the case with `substitution`, which often returns more than one suggestion in the form of "Use 'this' or 'that'".)

**Comment by patcon** [comment]
Hm. Ok, that's fair :) The one friendly counter might be that my impression was that `vale` was geared toward groups writing their own custom style guides. Users can choose to write their styles to be very opinionated -- say, if I'm writing docs with some folks, and we're just writing after agreeing amongst ourselves. And so this could quite easily be a helpful feature for groups like that.

(I should admit that I'd rank this as a pedantic convo/feature on my part, if I didn't know about tools like `danger-suggester`!)

But if the above isn't compelling, then I'm definitely in favour of closing this out :)

**Comment by jdkato** [comment]
That's true -- my intentions are indeed to make Vale flexible enough to let users make a lot of their own decisions. The problem (at least from my perspective) with this particular feature is that its functionality depends on writing rules a *certain* way, as shown with `substitution` above.

A reasonable compromise might be to ensure that `--output=JSON` provides enough information to make this relatively easy to implement on a case-by-case basis. Here's an example using [`proselint.GroupTerms`](https://github.com/errata-ai/vale/blob/master/rule/proselint/GroupTerms.yml) (a rule that follows the necessary single-replacement format) and a Python script:

```python
# replace.py
import re
import sys
import json

# Add your own rules here:
rules = ["proselint.GroupTerms"]
pattern = re.compile(r"'(.+?)'")

data = json.load(sys.stdin)
for src, alerts in data.items():
    # Open the file for reading and perform the replacements:
    with open(src, "r") as f:
        content = f.read()
        for alert in [a for a in alerts if a["Check"] in rules]:
            matches = pattern.findall(alert["Message"])
            content = content.replace(matches[1], matches[0])

    # Write the new file contents back:
    with open(src, "w+") as f:
        f.write(content)
```
To get your desired behavior, you can then invoke the following command:

```shell
$ vale --output=JSON test.md | python3 replace.py
```

**Comment by patcon** [comment]
Ah, that's a great point! Thanks for considering, @jdkato! Hm. OK, I suppose any little helper script/cli would be fit elsewhere and at most be linked as related from the README, right?

**Comment by jdkato** [comment]
Yes -- since it only works for certain extension points (implemented a certain way), it's hard to provide a general solution.
