### ISSUE TITLE
False positive double word in code fence block

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#126]
Not sure where this one is coming from, but it's flagging https://github.com/MicrosoftDocs/vsts-docs/blame/67fcf884eb51fb8ce58e4bd68875bd2243a1711f/docs/pipelines/process/expressions.md#L130
```
docs/pipelines/process/expressions.md
 130:1  error  'variables' is repeated!  vale.Repetition 
```
There is no duplicate word combo, even with odd whitespace between.
Run on 1.4.0 on OSX

**Comment by jdkato** [comment]
It's essentially the same issue as #95:

```markdown
then [release variables](../release/variables.md) variables are available.
```
The error is correct, the location isn't.

**Comment by jdkato** [comment]
I'm going to close this in favor of #95.
