### ISSUE TITLE
Include reference styles in other languages

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#13]
(**Note**: this depends on further development of the prose library.)

`lintProse` is our only English-specific component.

1. We could add a `Language` configuration key:

   ```ini
   # .vale
   Language = German
   ...
   ```
2. We could compile for different languages.
3. Languages could be specified on a per-rule basis. (This would probably be the most ideal solution...)

**Comment by jdkato** [comment]
We're now down to one blocking component: sentence tokenization. In theory, this shouldn't be much of an issue since the [library Vale uses](https://github.com/neurosnap/sentences) is multilingual.

**Comment by jdkato** [comment]
After playing around with incorporating other languages from [sentences](https://github.com/neurosnap/sentences), I've come to realize a few things:

- the `sentences` library isn't very accurate for languages other than English, which probably shouldn't be too much of a surprise considering the README states:

    > I have not tested this tokenizer in any other language besides English.

- The extra training data will nearly double Vale's binary size.

So, this is on hold until I finish porting the [`pragmatic_segmenter`](https://github.com/diasks2/pragmatic_segmenter) to the [`prose`](https://github.com/jdkato/prose) library. In the meantime, though, all non-sentence scope rules (i.e., excluding things like sentence length, commas per sentence, etc.) should mostly work fine in other languages.

**Comment by stephanschubert** [comment]
Any news on this?

**Comment by jdkato** [comment]
It should work fine if you're just looking for patterns, words, or phrases. 

Sentence segmentation and POS tagging aren't close to being ready, though.
