### ISSUE TITLE
line breaks in CLI output makes regex parsing difficult

### ISSUE THREAD

**Issue by MaliusArth** [vale-cli/vale#132]
- Vale version: 1.4.2
Because the vs code vale extension does not allow passing command line arguments I tried writing a task with a corresponding problemMatcher.
In the process, I've found that the CLI output can break the regex parsing when a line exceeds a certain line width and by splitting the message into multiple lines.
```

 /path/to/file.txt
 17:22    warning     Consider removing 'possibly'    vale.Hedging        
 126:55   warning     Consider removing 'several'     vale.Editorializing 
 129:33   error       'already existing' is           vale.Redundancy     
                      redundant                                           
 165:44   warning     Consider removing 'in general'  vale.Hedging        
 216:30   warning     Consider removing 'several'     vale.Editorializing 
 387:13   suggestion  'TODO' left in text             vale.Annotations 
```

It would be very helpful if there was a possibility to overwrite the max line width so that it would not interfere with regex parsing.

Here's my vs code task (works as long as the messages don't exceed max line width):

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "run vale on file (CLI)",
			"group": "build",
			"type": "shell",
			"command": "vale",
			"args": [
				"--no-exit",
				"--output",
				"CLI",
				"${file}",
			],
			"problemMatcher":
			{
				"fileLocation": "absolute",
				"source": "vale",
				"applyTo": "allDocuments",
				"pattern": [
					{
						"regexp": "^\\s+([^\\s].*)$",
						"file": 1,
					},
					{
						"regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info|suggestion)\\s+(.*?)\\s\\s+(.*)$",
						"line": 1,
						"column": 2,
						"severity": 3,
						"message": 4,
						"code": 5,
						"loop": true
					}
				]
			},
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": true,
				"clear": true,
				"revealProblems": "onProblem",
			}
		}
	]
}
```

If there was a way to set or disable the line width via command line argument it would render a separately maintained vs code extension pretty much obsolete.

**Comment by MaliusArth** [comment]
I'm using `--output line` for now but that's missing the severity value, unfortunately. Is it possible to add that value to the line output style? This would be an alternative solution for this easy yet powerful way of vs code integration.

**Comment by jdkato** [comment]
You can use `--output=line` (which is easier to handle with regex than the default output style) or `--no-wrap`.

See https://errata-ai.github.io/vale/usage/#using-the-cli.

**Comment by MaliusArth** [comment]
Nice, `--no-wrap` is exactly what I needed.
I didn't want to limit myself to one severity level with `--output=line`.
Thanks!
