### ISSUE TITLE
IgnoredScopes / SkippedScopes

### ISSUE THREAD

**Issue by MaliusArth** [vale-cli/vale#133]
What values are supported for these variables?
I'm writing LaTeX and it seems like \label{name}'s get linted even though I've added label to IgnoredScopes.

**Comment by jdkato** [comment]
LaTeX is not a supported format, which means that most scope-related features do not work.

See #54 for a related discussion.

**Comment by dylan-k** [comment]
What values are supported for these variables?

**Comment by jdkato** [comment]
@dylan-k: See [config#ignoredscopes](https://docs.errata.ai/vale/config#ignoredscopes).

**Comment by rmoff** [comment]
https://docs.errata.ai/vale/config#ignoredscopes is 404, should be https://vale.sh/docs/topics/config/#ignoredscopes
