### ISSUE TITLE
Does consistency style support regex

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#136]
I am attempting to create a style that searches for inconsistent use of quote marks, i.e. mixing smart and non-smart in one document etc. Before I get to lost in regex, does the style (https://errata-ai.github.io/vale/styles/#consistency) even support regex pairs in the declaration?

**Comment by jdkato** [comment]
Yes, it does.

However, you can't actually write a rule that looks for smart quotes -- one of Vale's preprocessing steps is to convert "smart" characters into their ASCII equivalents.

I ran into this issue myself not too long ago and I'm unsure if this is indeed the best way to handle them: On one hand, it's nice for rules to be able to work on all quote types (which was my initial reasoning), but it would definitely be more flexible if users had to specify the exact characters they're looking for. 

I think I'm going to change this in the next release.

**Comment by ChrisChinchilla** [comment]
OK then, I guess in the meantime I'll stop working on a style that I can't actually create ;)

Good job I asked. Grammarly has an equivalent rule, so I was trying to replicate it. I got some of the way, but not fully.

**Comment by jdkato** [comment]
This is possible now on master (I'll put a release out next week):

```yaml
extends: consistency
message: "Inconsistent use of '%s' ('smart' mixed with 'dumb')"
level: error
nonword: true
either:
  '"': '[”“]'
```

**Comment by ChrisChinchilla** [comment]
Thanks @jdkato I assume that's the release that just landed. I will test for my use case asap.

**Comment by ChrisChinchilla** [comment]
That works nicely @jdkato ! Need to think a bit about how to check for mixed type in a document, but it's a really good start :)
