### ISSUE TITLE
Creating a style to check for line length of code blocks in Markdown files

### ISSUE THREAD

**Issue by gerhardgossen** [vale-cli/vale#137]
I want to check that code blocks are shorter than a given number of characters to avoid horizontal scrolling. It seems like Vale only reads the contents of comments inside code blocks and ignores the code itself.

Example: For a maximum length of 10 the following lines should be flagged:
```
01234567890
// 34567890
```
whereas the following lines would be OK:
```
0123456789
// 3456789
```
Can I use Vale for such a check?

**Comment by jdkato** [comment]
Not yet, as you assumed, the content of code blocks is ignored.

We discussed making this configurable in #123 and it's still something I plan on doing.
