### ISSUE TITLE
Spelling picks up term within inline code style

### ISSUE THREAD

**Issue by felicitymay** [vale-cli/vale#140]
Windows 10, Vale v1.7.0 installed by downloading the MSI installer from the website.

I have a restructured text file with the following sentence:

```Alternatively, we could have implemented these three checks more verbosely using ``hasName``, ``getNumberOfParameters``, and ``getParameter(0).getType() instanceof TypeObject``.```

The Spelling rule that we're using gives an error for "instanceof" - which surprised me. Normally it's good at ignoring things in double backticks. The rule is defined as:

```
# This enables spell checking using the built-in US English dictionary

extends: spelling
message: "Did you really mean '%s'?"
ignorecase: true
level: error
ignore: vale-styles/Semmle/ignore.txt
```
Any idea what the problem might be?

**Comment by felicitymay** [comment]
Perhaps clearer to put examples as gists. See: https://gist.github.com/felicity-semmle/c916d1bbbe5a3f482fc16e21e45c0e50 for an rst file and Vale output with the example above and another on I came across while fixing Vale errors today.

**Comment by jdkato** [comment]
It appears that `rst2html.py` is interpreting some of the markup inside of the inline literals and adding `<span>`s that are throwing off Vale:

```rst
``getParameter(0).getType() instanceof TypeObject``
```
becomes

```html
<p>
  <tt class="docutils literal">
    <span class="pre">getParameter(0).getType()</span> instanceof TypeObject
  </tt>.
</p>
```

While

```rst
``getParameter(0)getType() instanceof TypeObject``
```

(without the period) becomes 

```html
<p>
  <tt class="docutils literal">getParameter(0)getType() instanceof TypeObject</tt>.
</p>
```

The same goes for the use of `::` in your gist.

---

I suppose this should be considered a bug with Vale, but it also seems like a violation of the [reStructuredText spec](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-literals):

> Inline literals may contain any characters except two adjacent backquotes in an end-string context (according to the recognition rules above). No markup interpretation (including backslash-escape interpretation) is done within inline literals.

I'll try to fix this and #119 in the next release, but it'll probably be a few days.

**Comment by felicitymay** [comment]
Thanks for looking into this. It sounds as if I should have been raising it as an issue with rst2html.

If you're able to fix this, that would be great. I'll watch out for the next release.

**Comment by jdkato** [comment]
This should be fixed in the next release.

**Comment by felicitymay** [comment]
Many thanks. I'll keep my eyes open for the next release.
