### ISSUE TITLE
Difficulty setting up `BlockIgnores`

### ISSUE THREAD

**Issue by felicitymay** [vale-cli/vale#141]
Windows 10, Vale v1.7.0 installed by downloading the MSI installer from the website.

Having got vale set up for `.rst` files, I'm now ready to try it on a non-standard format. Our query help files are written in a fairly simple XML format, and setting the format as equivalent to `html` works well. However, some of the files include a `<sample>` section with code. I think my regular expression is correct (it's based on the example in the documentation) but the blocks aren't being ignored. If someone's able to help me work out what the problem is I'd be grateful.

The regular expression and an example are here: https://regex101.com/r/CEHfdk/1.

My `vale.ini` file contains:

```
[formats]
qhelp = html

# Specify how to test a particular type of files
#-----------------------------------------------
[*.{rst,qhelp}]

# Ignore any inline sample code in qhelp files
BlockIgnores = (?s) *(<sample [^>]*>.*?<\/?sample>)
```
The output I get is: ` 23:10  suggestion  Try to simplify this sentence.  Microsoft.Semicolon`. So clearly I've misconfigured something. Any suggestions?

**Comment by jdkato** [comment]
There are two problems:

- `BlockIgnores` are for non-standard blocks (or sections) within *supported* formats&mdash;such as templating within Markdown. No syntax-related features work in unsupported formats.
- HTML, by specification, *can't* have non-standard blocks (or it would simply be invalid HTML). Other formats (.md, .rst, .adoc) have non-standard blocks that can still be converted to valid HTML.

#114 tracks adding support for XML.

**Comment by felicitymay** [comment]
Ah. Thanks for the explanation. That makes sense. Is there a "debug" option for Vale? It would be nice not to have to ask so many questions 😄.

**Comment by jdkato** [comment]
Not currently, but it does do quite a bit of internal error-handling that I could expose through something like `--output=debug`.

**Comment by felicitymay** [comment]
That might be helpful if it's fairly easy to do. Do you want to close this issue? It seems to be covered by your plans.
