### ISSUE TITLE
RST replacement directives that include substitutions appear to break vale.

### ISSUE THREAD

**Issue by esmerel** [vale-cli/vale#145]
- MacOS (not sure it's relevant)
-  Homebrew (I think)
- vale version 1.7.0

I have this set of substitutions in an RST file - the

`.. |alt| replace:: \ |acquia-product:alt|\
.. _alt: /lift/exp-builder/install/

.. |lplplink| replace:: \ |acquia-product:lplp|\
.. _lplplink: /lift#packages

.. |lplpolink| replace:: \ |acquia-product:lplpo|\
.. _lplpolink: /lift#packages

.. |liftapilink| replace:: \ |acquia-product:liftapi|\
.. _liftapilink: /lift/omni/rest_api/`

When these replacements are present in my file, vale doesn't work in VSC. If I take them out, everything's great.

I went to the command line, and tried vale on the same file, which returns
`vale lift/profile-mgr.rst
exit status 1
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.`

However, if I try the same file on the command line while ignoring syntax 
`vale --ignore-syntax lift/profile-mgr.rst`, I get the expected results (all the vale warnings and errors)

Replacements that aren't using substitutions work fine - this one works. 
``.. |salt| replace:: **salt**
.. _salt: http://en.wikipedia.org/wiki/Salt_(cryptography)``

Now, we're aware that this substitution method is uh, not ideal (at the time, we didn't know better.) If anyone else makes the mistake we did, I wanted to ensure there was a public record. We're now internally working on correcting our replacement directives :D

**Comment by esmerel** [comment]
Today I found this one:

.. |ch| replace:: \ |acquia-product:ch|\
.. _ch: https://www.acquia.com/products-services/acquia-lift

This one works - the difference is that this is a full URL, the non working ones are relative paths.

**Comment by esmerel** [comment]
More poking revealed additional oddities. There's definitely some confusion between allowed spaces in RST, and vale. I took a couple of screencasts and put them on my google drive to show. I'm making a change, and then saving. So, change -> save -> back to original -> save.

https://drive.google.com/file/d/1uDe9_a27wn7Hhm-e-kFyvGYav45Pv9LB/view?usp=sharing
https://drive.google.com/open?id=1WaK0iOJj63JaXOqekc73ksSwD-8gOsDJ

**Comment by jdkato** [comment]
The only processing step Vale does with reStructuredText content is call `rst2html` with these parameters:

https://github.com/errata-ai/vale/blob/54660c63eb52ab87cdfd6eb48f8fdf6d977023ab/lint/markup.go#L33-L42

Beyond that, from Vale's perspective, all markup is processed as HTML&mdash;so there's no Vale-specific spacing rules or anything like that.

If you could provide a complete file that demonstrates the breaking behavior, it would be much easier for me to look into this.

**Comment by esmerel** [comment]
Sure! 
[profile-mgr.txt](https://github.com/errata-ai/vale/files/3561791/profile-mgr.txt)

This is an rst file copied into txt for upload. It's built live at https://docs.acquia.com/lift/profile-mgr/

**Comment by jdkato** [comment]
`rst2html` is crashing:

```console
$ rst2html.py --quiet --link-stylesheet --no-file-insertion --traceback profile-mgr.rst
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 23, in <module>
    publish_cmdline(writer_name='html', description=description)
  File "/usr/local/lib/python3.7/site-packages/docutils/core.py", line 354, in publish_cmdline
    config_section=config_section, enable_exit_status=enable_exit_status)
  File "/usr/local/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/local/lib/python3.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/local/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/docutils/transforms/references.py", line 706, in apply
    nested_name = normed[nested_ref['refname'].lower()]
KeyError: 'acquia-product:lplp'
```

**Comment by jdkato** [comment]
There's really nothing Vale can do if `rst2html` crashes (this will probably be fixed by #147), but it should provide a more useful error message in any case.

I'll add a more detailed error message using the soon-to-be-released `--debug` output format.

**Comment by esmerel** [comment]
That makes total sense, and that's great. This was beyond what I could debug!

**Comment by jdkato** [comment]
Error messages for this have been added and will be available in the next release's `--debug` mode.
