### ISSUE TITLE
Smart quotes configuration?

### ISSUE THREAD

**Issue by faunaee** [vale-cli/vale#148]
I'm currently on Vale 1.4.2, and would like to upgrade to 1.7.1. During testing with 1.7.1, the change in 1.6.0 that stops converting smart quotes to dumb quotes now reports 100's of spelling errors in my documentation, complaining about `doesn`, `couldn`, `isn`, etc.

My doc toolchain, Antora, automatically converts dumb quotes to HTML entities, e.g. `&#8217;` and the "old" sanitization configuration worked well with my dictionary. Note that I run Vale on the Antora-generated HTML; there's no need for Vale to run asciidoctor on each source file a second time. Also, I primarily use Vale to facilitate spell checking; I only have a few other styles active at this time.

I tried adding `‘` to my dictionary's affix file, but that doesn't appear to match the HTML entities in use.

It might be useful if Vale supported a flag to control whether smart quotes were sanitized to dumb quotes. at least prior to spell checking.

Until then, I'll stay on 1.4.2.

I use Vale on Mac OS, but it's also run during CI builds on Linux hosts. Either way, Vale is installed via Go Releaser.

**Comment by jdkato** [comment]
In the next release, you should be able to configure this via `ICONV` definitions in your affix file.

**Comment by faunaee** [comment]
Awesome, thanks!

**Comment by jdkato** [comment]
This should be fixed in the latest release.
