### ISSUE TITLE
Improve the release workflow

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#150]
For v2.0.0+ versions of Vale, there are going to be some development and release workflow changes.

Currently, the process is quite simple: development takes place on `master` and releases are tagged at various times. 

Going forward, this is going to change. The goal will be for `master` to *always* represent the state of the latest release (in terms of both `go get` and the state of the live documentation) --  Essentially, it's going to be a read-only release branch. Development will take place on versioned branches (e.g., `v2.0.1`).

**Comment by jdkato** [comment]
On a related note, I'd like to refine / be more clear about the available installation methods (of which there are currently too many, IMO):

- [x] (updated) [Chocolatey](https://chocolatey.org/packages/vale)
- [Snapcraft](https://snapcraft.io/install/vale/debian) [Linux; outdated]
- [x] (updated) [Docker](https://hub.docker.com/r/jdkato/vale)
- [x] (updated) [Homebrew](https://github.com/ValeLint/homebrew-vale) [macOS]
- [x] (updated) `go get`
- [x] (updated) [GoDownloader](https://install.goreleaser.com/projects/)
- MSI [Windows]
- [x] (updated) Binaries
- [x] [AUR](https://aur.archlinux.org/packages/vale/) [Linux]

probably more ...

**Comment by s-kostyaev** [comment]
@jdkato currently install with `go get` is broken:
```
$ go version
go version go1.13.1 darwin/amd64
$ go get -u github.com/errata-ai/vale
package github.com/errata-ai/vale: no Go files in /Users/user/go/src/github.com/errata-ai/vale
```
go try to find it in branch `v2`

PS This one works fine:
```
$ GO111MODULE=on go get -u github.com/errata-ai/vale@latest
```

**Comment by ChrisChinchilla** [comment]
Not sure if I misunderstood your comments here (https://github.com/errata-ai/vale/pull/160) but I would advocate for not removing the homebrew formula, and am happy to look after it if it's too much work, as I rely massively on it, and I hope/think others do too.

**Comment by ChrisChinchilla** [comment]
Maybe even some of the others, I am a big fan of convenient install packages and allowing people to install the way they want, especially developer tools.

**Comment by jdkato** [comment]
I'm definitely not going to remove it, but I would like to offload maintenance of the platform-specific install methods. Homebrew has been largely kept up-to-date because I personally use macOS, but Chocolatey and others are significantly outdated.

Ideally, I'd like to only publish the release binaries and the Docker image -- which should be enough to allow contributors to maintain any other option.

**Comment by ChrisChinchilla** [comment]
@jdkato I have the most experience with Homebrew, but I am happy to learn how to do the others… There may be others more experienced though, or we can collaborate :)

**Comment by issyl0** [comment]
I would also like to see the Homebrew installation method continue to exist. Is there any appetite for getting the Homebrew formula building from source for potential inclusion in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)? I'm happy to try and do this (in a personal capacity, as a Vale user). If we can, that would save @jdkato the effort of being the only one maintaining the Vale formula in its own tap.

**Comment by issyl0** [comment]
I tried this out, and it works great. The from-source formula is [here](https://github.com/issyl0/homebrew-core/commit/74eb8269fed5809fd5e7eb3fc440e0b7d82ac675). I'll submit a PR to Homebrew/homebrew-core, if you'd like that?

**Comment by jdkato** [comment]
@issyl0: I'm fine with switching to a from-source, `homebrew-core` formula -- the version is determined from the `url`, correct?

**Comment by issyl0** [comment]
Great, thanks @jdkato. I've raised a PR over in https://github.com/Homebrew/homebrew-core/pull/47167.

**Comment by ChrisChinchilla** [comment]
Someone beat me to Homebrew, but also been playing with Linux and Windows recently, and yes, they need updating, so I'll look into those over Christmas break.

**Comment by jdkato** [comment]
@ChrisChinchilla: If you'd like access to the [Chocolatey package](https://chocolatey.org/packages/vale), I'll add you as a maintainer.

**Comment by ChrisChinchilla** [comment]
@jdkato I'll dig in over the Holidays. Did you also create the debian, arch, etc packages? Or are they community maintained? They seem in varying states of up to dateness, and I'd love to keep as many of those as I ca up to date too.

**Comment by ChrisChinchilla** [comment]
@jdkato So yes, feel free to add me, I'm most likely to maintain them under the "test the docs" umbrella

**Comment by jdkato** [comment]
@ChrisChinchilla: I'll need your Chocolatey username to add you as a maintainer.

And yes, I created the [snap package](https://snapcraft.io/install/vale/debian). I ran into a [number of issues](https://github.com/errata-ai/vale/issues?utf8=%E2%9C%93&q=snap) with it, but it's quite possible that things have changed or I missed something in my initial attempt.

**Comment by ChrisChinchilla** [comment]
@jdkato I honestly can't find how to create one right now (which bodes well), but it will likely be `chrischinchilla`. I'll also look at Linux packages, see if there's a way to create as many as possible, as easily as possible.

**Comment by jdkato** [comment]
If you haven't found it yet, you can sign up for Chocolatey here: https://chocolatey.org/account/Register.

**Comment by ChrisChinchilla** [comment]
@jdkato Yup `ChrisChinchilla`, will look at Linux packages now too, there are some services that will create a few for you. Would you like contributions into this repo, or keep the packaging repos separate?

**Comment by ChrisChinchilla** [comment]
@jdkato I now have a working snap, it shows version as `master` which I think is something we hit in the past (I am checking out the `v1.7.1` tag, but it's a very good start!

**Comment by issyl0** [comment]
Homebrew on Linux is a thing! :trollface: But seriously, great work here! 💯

**Comment by ChrisChinchilla** [comment]
@issyl0 Yeah, and as awesome as that is, I am not . sure how many really use it…

I also contacted the current AUR maintainer, to bring them into the conversation.

Finally @jdkato why do you say the Docker image is out of date?

**Comment by jdkato** [comment]
@ChrisChinchilla: I've added you as a maintainer on Chocolatey. It says your status is "Pending Approval" -- I'm not sure if Chocolatey needs to approve you or the [original maintainer](https://github.com/Kristinita), but you should have full access soon.

And the Docker image *was* out of date when I created this issue, but I've since been publishing a new version with each release of Vale.

**Comment by ChrisChinchilla** [comment]
@jdkato I just saw a new version come through, was that you? Did you change your mind on maintenance, or is that automatic?

**Comment by jdkato** [comment]
Yes, that was me.

My mind hasn't changed -- I just wanted to get the review process going, as Chocolately is the last package that needs to be updated:

[![Packaging status](https://repology.org/badge/vertical-allrepos/vale.svg)](https://repology.org/project/vale/versions)

Once it's updated, I'm going to release new GitBook-hosted documentation for Vale.

**Comment by jdkato** [comment]
Now that all packages are up to date, I'm going to consider this issue resolved. Feel free to comment further, though.

**Comment by ChrisChinchilla** [comment]
@jdkato Excellent on all fronts. I'll start digging around the chocolatey setup soon, I also had a long message from the AUR maintainer I still need to read through. Also thinking of looking at deb, rpm etc packages

**Comment by ChrisChinchilla** [comment]
@infotexture and @issyl0 Also re - https://github.com/Homebrew/homebrew-core/pull/50612 as Vale 2.0 had some (sort of) breaking changes, I wonder if it's worth maintaining a brew `vale@1` type formula too? It's pretty easy

**Comment by infotexture** [comment]
Bumped the Homebrew formula again to 2.2.2 with https://github.com/Homebrew/homebrew-core/pull/55907, as the process hasn't been automated thus far.

**Comment by ChrisChinchilla** [comment]
@infotexture Sorry missed this, I started working through this and then got stuck on Chocolately and haven't had time to get back to it yet. Homebrew at least I think we can automate pretty easily.
