### ISSUE TITLE
BlockIgnore for multi-line comments

### ISSUE THREAD

**Issue by jghauser** [vale-cli/vale#151]
I'm using vale 1.7.1 on Arch Linux.

I use the following setup to get easily foldable comments in vim:

    
    

I would like these not to be linted. I've tried adding the following to `.vale.ini`:

    BlockIgnores = (?s) *()

It doesn't seem to do anything at all. I've tested the regex [here](https://regex101.com/r/mFM0kZ/6)

**Comment by jdkato** [comment]
Thanks for the report.

What markup language are you using?

**Comment by jghauser** [comment]
Markdown

**Comment by jdkato** [comment]
I haven't been able to reproduce this. Here's a minimal example from the test suite:

```ini
# .vale.ini
[*.md]
BasedOnStyles = vale

BlockIgnores = (?s) *(<!-- NOTES fold-begin --><!--.*?<!-- fold-end -->)
```

```markdown
# `test.md`

This is is a sentence.

<!-- NOTES fold-begin --><!--

This is is a sentence.

-->
<!-- fold-end -->

This is is a sentence.
```

```console
$ vale test.md

 test.md
 3:6   error  'is' is repeated!  vale.Repetition 
 12:6  error  'is' is repeated!  vale.Repetition 

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

(Note that line 7 is correctly ignored.)

---

Could you post your `.vale.ini` file?

**Comment by jghauser** [comment]
I figured out what causes the issue in my case. It's that used `[*]` instead of `[*.md]`. But I'm not sure why that should make any difference. I thought using `[*]` simply means that the settings are applied to all files. I'm happy that it works though!

**Comment by jghauser** [comment]
This is my (working) .vale.ini (stops working if I change to `[*]`):

    # This goes in a file named either `.vale.ini` or `_vale.ini`.
    
    StylesPath = .config/vale/styles/
    # Options: suggestion, warning or error
    MinAlertLevel = suggestion
    
    # Just for markdown
    [*.md]
    # List of styles to load.
    BasedOnStyles = vale, proselint, write-good
    # Ignored Blocks
    BlockIgnores = (?s) *()
    # Specific rules
    write-good.E-Prime = NO
    write-good.So = warning
    write-good.ThereIs = warning
    proselint.Very = warning
    proselint.Cliches = warning
    proselint.Hyperbole = warning

**Comment by jdkato** [comment]
> I thought using [*] simply means that the settings are applied to all files. I'm happy that it works though!

This *should* be the case, so I consider this to be a bug. I'll fix it in the next release.

**Comment by jghauser** [comment]
I just tried a similar thing with a `TokenIgnores` and I think the issue might be the same. Just to give you a heads up.

Thanks a lot for this very useful software and the quick reply!

**Comment by jdkato** [comment]
This has been fixed (for both `TokenIgnores` and `BlockIgnores`) and will be available in the next release.
