### ISSUE TITLE
XDG location for configuration file on Linux

### ISSUE THREAD

**Issue by jghauser** [vale-cli/vale#152]
It would be nice if vale looked for the config file at the location specified by the environment variable `$XDG_CONFIG_HOME`, which is where most programs store their configurations. See also [the XDG base directory specifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

If this were to be implemented, it would also be nice to allow `vale.ini` config files, that is non-hidden files. `$XDG_CONFIG_HOME` is generally already specifying a hidden folder, namely `~/.config`.

**Comment by jdkato** [comment]
You can look for a file named `vale.ini` in `$XDG_CONFIG_HOME` by using the [`--config`](https://errata-ai.github.io/vale/usage/#using-the-cli) option. 

Beyond that, I don't think I'll be adding any platform-specific search locations.
