### ISSUE TITLE
Accept name in rule files

### ISSUE THREAD

**Issue by brandonkal** [vale-cli/vale#155]
Currently Vale determines a rule's name by file location. Ideally it should be possible to define this in the file itself. This would allow transfer over the wire and bundling documents into a single file for easier distribution of a style guide.

Thank you.

**Comment by jdkato** [comment]
This is something that I considered in the early days of development and I certainly understand the perceived benefits of single-file styles, but I ultimately decided that having each rule in its own file provided a nicer editing experience than a single large YAML file -- the goal, IMO, is to be as human-readable as possible. I also think that, in terms of distribution, compressed archives serve as an adequate compromise. 

(Supporting both options would also be a fairly significant undertaking at this point.)

**Comment by brandonkal** [comment]
Would you accept a PR to allow setting a rule's name in the file?
