### ISSUE TITLE
Linting rST files gives `can't run rst2html: (/usr/bin/python, )!`

### ISSUE THREAD

**Issue by ArtFlag** [vale-cli/vale#157]
Hello,

- OS: MacOS
- Install method: Homebrew
- Vale version: 1.7.1
- Python
```
 ~/repo: pip -V                                                                                                                             
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
 ~/repo: python -V                                                                                                                                     
Python 3.7.5
```

After a clean reinstall of my system, I get `can't run rst2html: (/usr/bin/python, )!` for each parsed rST file when I:

1. Go to a Sphinx project (we will parse rST files).
1. Run `vale source` (where the rST files are).

I didn't have this issue in the past.  MD files are parsed properly.

I also get `Unexpected token c in JSON at position 01` in VSCode when I try to lint (I know it's an issue for a [different repo](https://github.com/testthedocs/vscode-vale), but putting both in this message might help future users).

Any idea?

**Comment by jdkato** [comment]
[`rst2html`](https://errata-ai.github.io/vale/formats/#restructuredtext-markup) is either not installed or isn't available on your `PATH` (the former is more likely, as it should be added to the `PATH` automatically on installation).

**Comment by ArtFlag** [comment]
Brilliant, thanks a lot.
If that's ok, I will send out a PR to update the install instructions and mention that extra tools are required, depending on what the user lints.
I bet you that I will fall in this trap next time I format 🙂
