### ISSUE TITLE
Asciidoc issues

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#161]
Here’s something interesting. I was testing adding support for asciidoc to the VSCode extension, and nothing would happen when I updated the extension.

So I tested running vale on the command line, and when I ran it over _.adoc_ files I would get a lot of messages saying that my styles couldn’t be found, plus `exit status 1`. But when I ran over markdown or RsT, things worked fine. So I decided to test with inbuilt styles, and just received `exit status 1` on _.adoc_ files. This test was with a very vanilla ini file with no paths to custom styles etc, and only used the vale styles, which I think are internal?

From the file not found errors it looks like it’s trying to find styles relatively, or there’s some path issue. Now, I do have an odd setup with a lot of aliases (created with `ln -s`) to vale config files and style paths to do testing. But they work with every other file format and running `vale dc` picks them up fine.

So I wonder, is it anything to do with the asciidoctor dependency? I dug into the go code and noticed a todo to remove that, why is it needed? Or do you think this might be something else?

**Comment by jdkato** [comment]
[Asciidoctor](https://asciidoctor.org/) needs to be installed and available on your path (`which asciidoctor` should tell you if this is already the case). This is necessary because there's currently no viable AsciiDoc parser available for Go.

If that doesn't fix your issue, I'd be interesting in knowing the following:

1. What version of Vale are you using?
2. > .. a lot of messages saying that my styles couldn’t be found ...

    What does this say, exactly?

**Comment by ChrisChinchilla** [comment]
I do have asciidoctor installed and available.

I have vale 1.7.1 (latest afaik), actually, all of the above might be a red herring and it might be asciidoctor related, digging in to see…

**Comment by ChrisChinchilla** [comment]
Ignore me, fixed it. There seems to be a lot of conflicts between asciidoctor (via Homebrew) and variants of rbenv. I zapped all my ruby installations, reinstalled asciidoctor and vale functions fine. Which isn't a great long term solution, but at least it shows it's not a vale issue.
