### ISSUE TITLE
Weird behaviour of exclamation mark rule with markdown image syntax

### ISSUE THREAD

**Issue by emmenko** [vale-cli/vale#164]
- OS: macOS
- Install method: direct download of the binary
- Vale version: `1.7.1`

There seem to be a problem with exclamation marks in markdown files.
The rule `Google.Exclamation` is somehow complaining about the exclamation mark of the markdown image syntax. This happens though only of specific cases:

* image syntax only (no errors)

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1110551/69864608-9a892280-129f-11ea-961c-baac8c270955.png">

* image syntax with text ending with exclamation mark (notice the file has no new line at the end).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1110551/69864677-c4dae000-129f-11ea-93fe-a5e3fe8dec67.png">

* image syntax with text ending with exclamation mark, with new line at the end of the file

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1110551/69864726-e0de8180-129f-11ea-9aa0-cf33d47119a2.png">

Is this a bug somewhere? Or how is this suppose to work?

**Comment by jdkato** [comment]
Thanks for the report -- this is indeed a bug. I've released a new version of the [Google style](https://github.com/errata-ai/Google/releases/tag/v0.3.1) (`v0.3.1`) that should have fixed it.

**Comment by emmenko** [comment]
Thanks a lot! 🙌
