### ISSUE TITLE
can you make vale work with BBEdit?

### ISSUE THREAD

**Issue by catlook** [vale-cli/vale#165]

**Comment by jdkato** [comment]
There are no Vale-specific changes necessary for use with BBEdit -- it should work fine, provided BBEdit is configured appropriately. There are two options (as far as I know; I'm not a BBEdit user myself):

1. You can write an extension using the scripting interface (`~/Library/Application Support/BBEdit/Scripts`), as described in the "Filters and Scripts" section of the user manual.
2. You can use the built-in, command-line tool `bbresults` to view Vale's output for a file within BBEdit:

    ```shell
    $ vale --output=line test.md | bbresults -p '(?P<file>.+?):(?P<line>\d+):(?P<col>\d+):(?P<type>.+?):(?P<msg>.*)$'
    ```
    Where `test.md` could be any file path.

**Comment by jdkato** [comment]
I'm going to close this for now, but feel free to respond if I didn't adequately answer your question.

**Comment by ChrisChinchilla** [comment]
@catlook and @catlook I was looking at BBEdit and some other text editors recently for a video round-up and noticed that it, amongst others, now supports LSP, so I may look at adding Vale support through that for a few editors; now I understand how it works better.
