### ISSUE TITLE
Broken file links

### ISSUE THREAD

**Issue by gunar** [vale-cli/vale#167]
It would be interesting to have Vale let me know when links to files (e.g. `[link](./file.md)`) get broken (e.g. when deleting `./files.md`).

**Comment by jdkato** [comment]
I've considered adding such functionality, but I've decided to keep Vale focused on "prose" (which, in this case, would be the "link" text rather than the URL/path itself).

If you're looking for a link checker, though, I've personally liked [`raviqqe/liche`](https://github.com/raviqqe/liche).
