### ISSUE TITLE
Capitalization test for multi-word phrases?

### ISSUE THREAD

**Issue by amyq** [vale-cli/vale#168]
I'm attempting to implement some tests, and I'm running into a limitation of the capitalization test. I'm guessing the capitalization test splits on word boundaries, and I'm running into some multi-word phrases that need to match specific capitalization rules. 

For example: `Let's Encrypt` and `GitLab Runner`.

Is there an easy way around this problem that I'm missing, or is the only current approach to break the phrases apart, putting each individual word on a new line?

**Comment by jdkato** [comment]
Are you trying to match `Let's Encrypt` or ignore it? 

If it's the latter, then #154 discusses this issue (which I do intend on changing). If you're trying to *match* those phrases, could I see an example of the `.yml` file?

**Comment by amyq** [comment]
I'm attempting to ignore the phrase `Let's Encrypt`, exactly like what's being described in https://github.com/errata-ai/vale/issues/154 - I'll close this issue out, since it's a duplicate, and follow along there.
