### ISSUE TITLE
Linux should not install to home dir

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#17]
I'm fairly sure *most* people do not want the default install location to be `macOS and Linux: ~/vale`

Maybe `~/bin/vale` ?

**Comment by jdkato** [comment]
Yeah, I think "our recommendations" was a poor choice of words. In reality, I meant "you can put it anywhere but, for the sake of example, we're putting it here."

I think it's really a matter of personal preference. For example, on macOS you could install it to:

- `/usr/local/bin`: this is probably the most natural location, but I know some people prefer to leave this to package managers like Homebrew (which I intend to add Vale to).
- `~/bin`: this doesn’t require elevated privileges, but is only available for one user.
- `$GOPATH/bin`: this is what most Go programmers/contributors would do, I assume.
- `some/path/vale/bin` where `some/path/vale/` would also contain your styles.

Overall, I thought keeping the Vale binary and its styles in a single location would be good for people who don't have any other preference. But I probably should expand on this more.

**Comment by plaindocs** [comment]
Simplicity vs preference can be tricky - agreed. 

I don't think you can assume your users are go programmers, and I definitely think either `/usr/local/bin` or `~/bin/` would be better defaults than `~/`.

**Comment by jdkato** [comment]
An update on this:

- Releases are now signed.
- I've edited the wiki and added a tutorial for macOS that uses `~/bin` (Windows and Linux are on the way).
- I've added Vale to Homebrew.
- For the next release, I plan on including a .msi file that defaults to `C:\Program Files (x86)\Vale`

**Comment by jdkato** [comment]
I'm closing this as Vale can now be install through Homebrew (`/usr/local/bin`), a Windows Installer package (`C:\Program Files (x86)\Vale`), or manually.

I'm also going to be moving away from the wiki in favor of https://github.com/ValeLint/docs, which is hosted at https://valelint.github.io/.
