### ISSUE TITLE
More details on Dockerfile

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#172]
I've been working on some GitLab repositories to get vale working nicely in their pipelines feature, but have got quite stuck, and it looks vaguely similar to #128

It's very hard to debug exactly what's going on, and I see why you took some of the decisions with the GitHub action now, but trying the Dockerfile as is with pipelines constantly gives the `WARNING: Missing or invalid config file.` error. I can see that for the Docker instructions you mention copying in to the running container styles, docs folder etc., which makes sense. But with pipelines, you can't do that. In theory the contents of the repo pipelines is running over contain styles, config and docs, and with the correct parameters passed to Vale, it should in theory find everything it needs.

Now, I don't expect you to know much about pipelines, but looking at the Dockerfile, I don't really understand what's going on it, and that might help me debug. I can see you use an Alpine image, but how does Vale get there? It kind of looks like it's just in the image, but it's not part of Alpine (is it?). 

Are you able to give me a bit more detail about what the Dockerfile is doing? Maybe it will help me figure this out and if I need to create a custom image instead.

Thanks!

**Comment by jdkato** [comment]
When I build the image, a pre-built version of Vale is copied from the host (the local system) into the container's filesystem:

https://github.com/errata-ai/vale/blob/e607f94e6fa1c23887fe30df2e52c601fc4250af/Makefile#L76-L80

https://github.com/errata-ai/vale/blob/e607f94e6fa1c23887fe30df2e52c601fc4250af/Dockerfile#L11

And, while I haven't worked with GitLab much, it sounds like Pipelines work similarly to Actions (which also operate on a repository context). How does your `ENTRYPOINT` call Vale?

**Comment by ChrisChinchilla** [comment]
Ah, Ok, thanks this helps me figure out if the default Docker image will work, or if there needs to be a custom one. Unfortunately GitLab pipelines doesn't really expose much, including an `ENTRYPOINT`, but this helps me dig in more.
