### ISSUE TITLE
Docs issue: ignored elements in DITA markup

### ISSUE THREAD

**Issue by infotexture** [vale-cli/vale#173]
The [DITA markup](https://errata-ai.github.io/vale/formats/#dita-markup) section of the docs says:

> By default, `script`, `style`, `pre`, `code`, and `tt` tags are ignored.

— but it looks like this text was repurposed from _(an earlier version of?)_ the [HTML markup](https://errata-ai.github.io/vale/formats/#html-markup) section, as several of these elements don't exist in DITA, and other related DITA elements such as `<codeph>` that are commonly used to wrap code snippets are not listed here.

I searched the Vale codebase hoping to find the list of DITA elements that are excluded from checks, but I'm coming up empty.

I'd be happy to submit a pull request to clarify this in the docs if anyone can point me to the place where ignored elements are defined for DITA.

**Comment by jdkato** [comment]
Vale doesn't operate on DITA source itself (or any other format, for that matter). Prior to any processing, it performs a conversion (or "transformation") to HTML5:

https://github.com/errata-ai/vale/blob/e607f94e6fa1c23887fe30df2e52c601fc4250af/lint/markup.go#L452-L453

So, for example, `codeph` would just be `code` from Vale's perspective. That said, to match the non-XML sections, the docs probably should list the element names *prior* to conversion.

**Comment by infotexture** [comment]
Thanks for clarifying. Makes sense to state that explicitly and mention the source elements whose content will be ignored.
