### ISSUE TITLE
Feature Request: ignore-syntax as a scope (not just CLI Flag)

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#178]
I realize this may not be feasible based on how Vale does it's linting, but I figure it's worth asking.

We would like to create styles that lint for structural issues within markdown files. We are able to use `--ignore-syntax` to test our potential styles, and they work, but it means we can't combine "bare markdown" styles and "content check" styles into one test. Half need the CLI flag, the other half do not.

If we could make styles with `scope: ignore-syntax` such that it has the same effect as the CLI flag, it would be extremely powerful, letting us enforce standards in a way that we aren't able to do right now. For example, we could check for relative link use (mandatory in our project), reference style links (must avoid), etc.

We would use it to supplement our use of `markdownlint`, and perhaps one day have a full suite of styles that would let us drop `markdownlint` completely.

**Comment by jdkato** [comment]
Something like `scope: ignore-syntax` is possible and I'll look into adding it in the next release (it probably has utility beyond markup linting, too).

That said, with specific regard to `markdownlint`-like linting, my response has typically been that such functionality is out of scope. I'm of the belief that a well-implemented linter for Markdown (or another such format) shouldn't rely on regex for its understanding of the format.

**Comment by Ravlen** [comment]
@jdkato Yes, I saw a previous comment you made about that, and the point is definitely valid. We do like what `markdownlint` does, and are using it to enforce "general" standards, but we also like Vale and would love to be able to use it to enforce additional "customized" standards. The ability to do this quickly with regex, while making use of Vale's other features (alert levels, different types of styles), would be a huge benefit. We see a lot of exciting potential with this scope.

**Comment by jdkato** [comment]
This will be available in the next release via a new `scope: raw` option.

**Comment by Ravlen** [comment]
@jdkato That's fantastic news! Thanks so much!
