### ISSUE TITLE
Hugo switched from Blackfriday to Goldmark

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#179]
Not sure if you were hitting any issues with Blackfriday for the Markdown processing, but Hugo has switched a few months ago https://gohugo.io/news/0.60.0-relnotes/
Since this library is mostly concerned with text rather that some CommonMark edgecases, it might not make sense to switch, but I thought I'd share in case you hadn't seen it.

**Comment by jdkato** [comment]
I made the same switch for [v2.0](https://github.com/errata-ai/vale/releases/tag/v2.0.0).

**Comment by nschonni** [comment]
OK, I just did a repo search before and found stuff like https://github.com/errata-ai/vale/blob/ebc6f80540de684b4cd2290609d14e11dd563457/vendor/modules.txt#L83-L84 so I thought it was still on Blackfriday, guess it's probably just a subdependency now
