### ISSUE TITLE
Running on DITA throws “No XSLT transform provided!”

### ISSUE THREAD

**Issue by infotexture** [vale-cli/vale#182]
Running Vale on the [DITA-OT docs](https://github.com/dita-ot/docs) with `vale topics` throws the `No XSLT transform provided!` error _(twice!)_ and a series of errors that suggest Vale is processing DITA files as text, rather than as DITA XML:

```
No XSLT transform provided!
No XSLT transform provided!

 topics/building-output.dita
 1:3   error  Did you really mean 'xml'?      Vale.Spelling 
  ⋮
```

_(macOS, Vale 2.1.0 installed via Homebrew)_

The [DITA \[ markup \]](https://errata-ai.gitbook.io/vale/getting-started/markup#dita-markup) section of the docs is a bit sparse on how Vale finds the local installation of DITA-OT apart from the fact that it needs to be on `$PATH`. In my case it is (and `which dita` returns the correct path to the toolkit installation), but I'm wondering whether Vale is really finding the toolkit. 🤔 

The [XML \[ markup \]](https://errata-ai.gitbook.io/vale/getting-started/markup#xml-markup) section of the docs mentions the [Transform](https://errata-ai.gitbook.io/vale/getting-started/configuration#transform) option and shows an example for DocBook, but I assume this setting should not be necessary when checking `*.dita` files. 

The “No XSLT transform provided!” error seems to suggest that setting might be necessary after all, but I'm not sure if that's a red herring here. 

Checking the configuration with `vale ls-config` reveals an empty `"Parsers": {},` entry, not sure if that's a problem. The [Installation](https://errata-ai.gitbook.io/vale/#installation) docs say:

> …you'll also need to install a parser

but it's not clear to me whether such parsers need to be explicitly registered somehow in `.vale.ini`, or whether having them installed on the system should be enough.

Happy to submit a docs PR to help clarify this, but I'm not sure yet how to resolve the issue.

**Comment by jdkato** [comment]
This is how things are *intended* to work:

- For `*.dita` files, you simply need to install the DITA-OT toolkit and add its `bin` directory to your `$PATH`. No further configuration is necessary&mdash;if Vale is unable to locate the toolkit, it will print an error message ("dita-ot not found!") and you'll see no linting results for `*.dita` files.

- For `*.xml` files, you need to have `xsltproc` installed and provide a version 1.0 XSL Transformation for converting to HTML (via the `Transform` option). If these conditions aren't met, an error message will be shown ("xsltproc not found!" or "No XSLT transform provided!") and you'll see no linting results for `*.xml` files.

(The `"Parsers": {}` option is unrelated and will be removed altogether from the `ls-config` output in a future release.)

---

With specific regard to your case, it appears that Vale is handling `*.dita` files correctly: you're not seeing the "dita-ot not found!" error message and you have linting results (`topics/building-output.dita`) in your example.

The two instances of "No XSLT transform provided!" likely mean that the directory you ran Vale on contains files with the `.xml` extension in addition to `.dita` files, and that you haven't defined the `Transform` option. 

You should be able to get rid of these error messages by limiting your results to only `*.dita` files in your `.vale.ini` file.

If this doesn't appear to describe your case, could you please provide your `.vale.ini` file and the command your running (e.g., `$ vale ...`)?

**Comment by infotexture** [comment]
> You should be able to get rid of these error messages by limiting your results to only `*.dita` files 

Thanks, that worked. There were indeed both XML and DITA files in that directory, and passing the `--glob='*.dita'` option made the duplicate transform errors go away.

> With specific regard to your case, it appears that Vale is handling `*.dita` files correctly

It certainly parses the files, but the errors suggest it may not be recognizing them as DITA and converting to HTML beforehand (as I understand it should).

Things that are flagged as spelling errors include the standard XML doctype header:

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

and DITA elements such as `<shortdesc>` and `<cmdname>`, which shouldn't be present as such in the HTML output if Vale was parsing that instead of the DITA source file:

```
 1:3   error  Did you really mean 'xml'?      Vale.Spelling 
 7:4   error  Did you really mean             Vale.Spelling 
              'shortdesc'?                                  
 7:31  error  Did you really mean 'cmdname'?  Vale.Spelling 
```

**Comment by jdkato** [comment]
I can't reproduce these results. Here's what I get using Vale `v2.1.0` and a basic configuration:

```console
$ tree -a
.
├── .vale.ini
├── styles
│   └── vocab.txt
└── topics
    ...
$ cat styles/vocab.txt
dita
$ cat .vale.ini
StylesPath = styles

[*.dita]
BasedOnStyles = Vale
$ vale topics/building-output.dita
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```

Could you please provide your `.vale.ini` file and the full command your running?

**Comment by infotexture** [comment]
@jdkato 🙏 Thanks, it works for me too with your basic config above.

After confirming that, I was able to trace the problem to a spurious `[formats]` entry in my `.vale.ini`, which I had copied from another project:

```ini
[formats]
dita = DITA
```

When I removed this, everything worked as expected. 🎉 

_(/cc @shudson310)_
