### ISSUE TITLE
[rst] Text not checked if part of certain directives

### ISSUE THREAD

**Issue by ArtFlag** [vale-cli/vale#183]
```
- OS:macOS
- Install method: HB
- Vale version: 1.7.1
```

Body text that is part of certain directives like `only` and `admonition` is not check by Vale. 

See the absence of underline in some of the `e.g`:
<img width="167" alt="Screenshot 2020-03-20 at 10 35 22" src="https://user-images.githubusercontent.com/25686502/77151593-8d828000-6a96-11ea-9e78-7257fe6e287f.png">

That's a problem for certain cases, like people who use the `only` directive to tag entire pages of content for specific audiences.

Is the source of this issue in rst2html or Vale?

**Comment by jdkato** [comment]
It's `rst2html`. You can verify this by running your file through its converter, which will output something along the lines of the following:

```html
<div class="system-message">
<p class="system-message-title">System Message: ERROR/3 (<tt class="docutils">test.rst</tt>, line 18)</p>
<p>Unknown directive type &quot;only&quot;.</p>
<pre class="literal-block">
.. only:: internal

   e.g
</pre>
</div>
```

You can try using the new [`SphinxBuildPath`](https://errata-ai.gitbook.io/vale/getting-started/configuration#sphinxbuildpath-core) option to get around this.
