### ISSUE TITLE
panic: runtime error: slice bounds out of range [684:683]

### ISSUE THREAD

**Issue by shudson310** [vale-cli/vale#186]
Running vale from a Jenkins script (also fails from command line). Linux 3.10.0-862.6.3.el7.x86_64 
vale version v2.0.0

When running on a large directory of many small .dita files, this error is thrown:
panic: runtime error: slice bounds out of range [684:683]

goroutine 28 [running]:
github.com/errata-ai/vale/core.initialPosition(0xc001efb600, 0x2b3, 0xc001efadad, 0x2, 0xc0008e0cd0, 0x2, 0x2, 0xc000547440, 0xc0005454e0, 0x18)
	/Users/jdkato/Documents/Code/Go/vale/core/util.go:245 +0x4fc
github.com/errata-ai/vale/core.(*File).FindLoc(0xc000914140, 0xc001efb600, 0x2b3, 0xc001efab00, 0x2b3, 0x0, 0x31, 0xc0008e0cd0, 0x2, 0x2, ...)
	/Users/jdkato/Documents/Code/Go/vale/core/core.go:189 +0xcd
github.com/errata-ai/vale/core.(*File).AddAlert(0xc000914140, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0006e0da0, 0x11, 0x0, 0x0, ...)
	/Users/jdkato/Documents/Code/Go/vale/core/core.go:235 +0x170
github.com/errata-ai/vale/lint.Linter.lintText(0xc000094d00, 0xc0002c9000, 0xc000914140, 0xc001efab00, 0x2b3, 0xc001efab00, 0x2b3, 0x0, 0x0, 0xc0008e0ca0, ...)
	/Users/jdkato/Documents/Code/Go/vale/lint/lint.go:303 +0x4a8
github.com/errata-ai/vale/lint.Linter.lintLines(0xc000094d00, 0xc0002c9000, 0xc000914140)
	/Users/jdkato/Documents/Code/Go/vale/lint/lint.go:273 +0x276
github.com/errata-ai/vale/lint.Linter.lintFile(0xc000094d00, 0xc0002c9000, 0xc00088afc0, 0x66, 0x0)
	/Users/jdkato/Documents/Code/Go/vale/lint/lint.go:239 +0x133
github.com/errata-ai/vale/lint.Linter.lintFiles.func1.1.1(0xc00006db00, 0xc000094d00, 0xc0002c9000, 0xc00006daa0, 0xc0008d2080, 0xc00088afc0, 0x66)
	/Users/jdkato/Documents/Code/Go/vale/lint/lint.go:152 +0x67
created by github.com/errata-ai/vale/lint.Linter.lintFiles.func1.1
	/Users/jdkato/Documents/Code/Go/vale/lint/lint.go:150 +0x2be

**Comment by jdkato** [comment]
How many files are in your directory? I've been trying to reproduce this using directories of 1,000+ `.dita` files and I've yet to experience a crash.

**Comment by shudson310** [comment]
Only 398 files. It does seem to be working again, so perhaps there was an invalid file that has since been correctly validated? My builds are correctly working now.
