### ISSUE TITLE
Docker Image doesn't use v2.1

### ISSUE THREAD

**Issue by benfreke** [vale-cli/vale#189]
Hi

I'm just at the start of a project of using Vale to lint our Asciidoc files using the official Docker image. 

It's already got Asciidoctor installed which is awesome! 

But it's not running the latest image. When I run the Image with `vale -v` I get `vale version v2.0.0-beta.2`

Could the official image please be updated to the latest version of Vale, and use tags so I can ensure I'm always using version 2.1? I'm happy to help with that, but the listing on Docker Hub didn't link back to a Github repo for me to test this with. Is it just the `Dockerfile` in the root of this repo?

For context, the plan is to have a central image that we use in CI to enforce Spelling and Grammar rules for multiple repositories that we use Antora to create a static technical documentation site from.

**Comment by jdkato** [comment]
Yes, I'll update this soon.
