### ISSUE TITLE
Go Installer Not Working

### ISSUE THREAD

**Issue by andrei572** [vale-cli/vale#192]
Goreleaser not working as described in [doc https://errata-ai.gitbook.io/vale/getting-started/installation#using-vale-with-a-continuous-integration-ci-service](https://errata-ai.gitbook.io/vale/getting-started/installation#using-vale-with-a-continuous-integration-ci-service)

Details: 

- OS: macOS, Linux
- Install method: Go
- Vale version: Any

This fails silently:
```
curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest
```
If I download the script and run it, here's what I get:
```
$ ./vale.sh -d latest
ValeLint/vale info checking GitHub for tag 'latest'
ValeLint/vale debug http_download https://github.com/ValeLint/vale/releases/latest
ValeLint/vale debug http_download_curl received HTTP status 000
ValeLint/vale crit unable to find 'latest' - use 'latest' or see https://github.com/ValeLint/vale/releases for details
```
Thanks!

**Comment by jdkato** [comment]
This should be working now.

**Comment by andrei572** [comment]
It is working. Thanks much.

**Comment by faizaankhan** [comment]
@jdkato This is failing silently yet again, goreleaser not working.

**Comment by jdkato** [comment]
See #418.
