### ISSUE TITLE
Vale ignoring part of a sentence?

### ISSUE THREAD

**Issue by hepabolu** [vale-cli/vale#198]
I am running Vale as a GitHub action on documents for a book. Every now and then I want to turn Vale off for just part of a sentence. Is there a way to tell Vale to just ignore a specific rule for just one paragraph or sentence?

Example:

```
I like this very very much
```

will trigger the repeat rule. I don't want to turn the repeat rule off entirely and I don't want to rewrite the above sentence like 

```
I like this
<!-- Vale off -->
very very
<!-- Vale on -->
much
```

because that makes the actual text very hard to read.

I cannot find anything in the documentation that explains how to do it (other than the example above).

**Comment by jdkato** [comment]
> Is there a way to tell Vale to just ignore a specific rule for just one paragraph or sentence?

[Yes](https://errata-ai.gitbook.io/vale/getting-started/markup#markup-based-configuration):

```text
<!-- vale Vale.Repetition = NO -->

This is my paragraph.

<!-- vale Vale.Repetition = YES -->
```
