### ISSUE TITLE
Tokenize hyphenated words to check separately

### ISSUE THREAD

**Issue by wilada** [vale-cli/vale#199]
The default filters for spelling rules ignore hyphenated words:

```
var defaultFilters = []*regexp.Regexp{
        regexp.MustCompile(`(?:\w+)?\.\w{1,4}\b`),
        regexp.MustCompile(`\b(?:[a-zA-Z]\.){2,}`),
        regexp.MustCompile(`0[xX][0-9a-fA-F]+`),
        regexp.MustCompile(`\w+-\w+`), // ignores a hyphenated word
        regexp.MustCompile(`[A-Z]{1}[a-z]+[A-Z]+\w+`),
        regexp.MustCompile(`[0-9]`),
        regexp.MustCompile(`[A-Z]+$`),
        regexp.MustCompile(`\W`),
        regexp.MustCompile(`\w{3,}\.\w{3,}`),
        regexp.MustCompile(`@.*\b`),
}
```

However, if I disable these using the `custom: true` option (I need to use this option to disable the acronym filters independently), I haven't been able to figure out a way to allow a spelling rule to check each side of the hyphen independently. Instead, I have to add each hyphenated combination to ignore list if I want to spell-check those words. While I don't have a huge number of these, it would be nice if `Vale` provided an option to handle this either with the built-in `Spelling` rule or via custom rules.

Would it make sense to have an option that makes the `WordTokenizer` split across hyphens?

**Comment by jdkato** [comment]
Yes, I think we should expose the pattern used in `WordTokenizer` as a configuration option. I should have this available in the next release.

**Comment by jdkato** [comment]
I've decided (for performance reasons) to work towards using [`prose.v2`](https://github.com/jdkato/prose) for tokenization, which doesn't use regex at all. This means that that'll no longer be a pattern to expose as a setting, but I do think that splitting hyphenated words makes for a better experience -- especially with all of the other options for ignoring / filtering words.

So, I'm going to make this the default behavior in the next release.
