### ISSUE TITLE
Skipping combination of words

### ISSUE THREAD

**Issue by hepabolu** [vale-cli/vale#200]
I am running Vale as a GitHub action on documents for a book written in asciidoctor. 
Sometimes Vale complains about a word that is part of a name, e.g.

```
FireFox Dev Tools
John Doe
```

Vale complains about 'Dev' and 'Doe'. I want to allow these words only in these combinations so that Vale picks up any of those words when they don't appear in this combination. So I added the combinations to the vocab.txt, but Vale keeps complaining.

What do I need to do?

**Comment by jdkato** [comment]
Spell check operates on single words only, so this isn't supported in `vocab.txt`.
