### ISSUE TITLE
2020 Development Goals

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#202]
I'd like this year to be a big one for Vale and its related projects. And, as part of that, I'd also like to be more transparent about what I'm currently working on&mdash;here's a basic outline of what's in the pipeline.

(The goals below apply to Vale and Vale Server as well as the Docker repo, GitHub Action, styles library, editor plugins and web-based plugins.)

## Documentation

My biggest goal is to improve the existing documentation for all Vale-related projects. 

- [x] **Unify all of ours docs**. I'd like to unify our various documentation sources *without breaking any existing links*. The current plan is to move all documentation to [Antora](https://antora.org/) (making use of its support for multiple repos) and redirect all existing links (every page from GitBook, Docusaurus and MkDocs, etc.) to their new counterpart.

- [x] **Make our docs more interactive**. I'd like to incorporate [termible](https://termible.io/) to allow users to demo Vale inside the docs themselves.

- [x] **Create a course for Vale and Vale Server**. I'd like to create a course similar to [*Advanced NLP with spaCy*](https://course.spacy.io/en) that walks through the process of using Vale and Vale Server.

     > I decided to focus on creating an online rule editor instead of this course (for now).

## Vale

- [x] incorporate more natural language processing (NLP) features. Vale is built on top of [`jdkato/prose`](https://github.com/jdkato/prose) and already makes significant use of tokenization and segmentation, but almost every extension point could make use of part-of-speech tagging as well.

   > This has been started by implementing the new `Sequence` check (see #110).

- [x] Re-write the GitHub Action to make use of GitHub's new "Problem Matchers."

   > Problem Matchers don't seem to be an upgrade: they only support two annotation levels (warning and error) and have issues with reporting duplicate annotations (https://github.com/actions/runner/issues/504#issuecomment-647903579).

## Vale Server

- [x] Release clients for a number of commercial writing applications (Confluence, Adobe FrameMaker, MadCap Flare, MS Word).

  > The Chrome extension has been completely re-written and now supports a wide range of sites, including Confluence and WordPress. Dedicated extensions are still on the way, but this is now a legitimate option in the meantime.

- [x] Implement a number of new ways to handle multiple `StylePath`s, allowing for better syncing options across multiple writers. 

- [x] Release new versions of the Sublime Text, Atom, and VS Code plugins with support for the Vale CLI.

- [x] Extend context menu actions in the editor clients&mdash;for example, "Ignore Rule" (disabled the rule in the config file), "Ignore Word" (adds a selected word to an ignore file), etc.

## Styles

- [ ] v1.0.0 of `Microsoft`
- [ ] v1.0.0 of `Google`
- [x] v0.1.0 of `IBM`
- [ ] v0.1.0 of `PlainLanguage`

**Comment by ChrisChinchilla** [comment]
@jdkato I am happy to keep lending a hand with a lot of this (or as much as I have time for), specifically

- continuing to work on preconfigured style guides (some are already mostly in progress)
- at least doing research for the commercial tools, testing, and user research
- helping with the multiple style paths or "inheritance" as I already have some ideas I implement for this
- Helping merge the two VS Code extensions and continuing to help add features moving forward. There are also other writing tools I'd like to investigate (one for me would be Scrivener), but I am not sure how many have plugin architectures any more
- Courses and docs, of all shapes and sizes, I have worked on several before and am already helping people a lot, would love to continue that with you
- NLP work sounds awesome, it's an area I have been toying with for creative coding fun, but that is some work, and will be an interesting balance to tread, as one of the main positives of Vale is that it doesn't send your writing to a server somewhere, unlike "other" tools

Just let me know, and I can also free up / prioritise time :)

**Comment by jdkato** [comment]
Thanks, @ChrisChinchilla.

I have new releases of both Vale and Vale Server that I'd like to get out by next week, but then perhaps we can discuss the next task(s) to focus on.

**Comment by ChrisChinchilla** [comment]
@jdkato 🤘Let's do it

**Comment by jaredmorgs** [comment]
This all sounds really exciting. And what follows is a long post, for which I apologize.

I'd rather recommend that an organization go with a paid open-source solution like Vale Server for style linting and maybe even spell checking with the various styles available over a commercial solution like Grammarly. 

The problem I'm trying to resolve in my mind at the moment is how would I get someone outside of tech to adopt Vale Server, and how would it solve problems in the tools they use like Google Docs, Confluence, Jira, and other web-based tools.

The thing about how Grammarly integrates with anything in your browser is really attractive and makes its grammar and style linting prolific. 
I'm not sure what would be involved in bringing Vale's infrastructure into line with this way of working. 

From what I can see the Chrome extension Grammarly offers offloads all the work to their servers for analysis. 
So it makes me wonder if instead of offloading the work to a cloud server, could a Vale browser extension could offload the work to Vale Server on your PC?

The other thing that is blocking us from rolling out Vale Server is the fact it doesn't have full cross-platform support (yep, Linux is a thing for one of our writers in our team). 
If I was going to push a business case for getting Vale Server rolled out organization-wide, then these things feel like important considerations in the shortlisting process.

**Comment by jaredmorgs** [comment]
@jdkato are you comfortable with migrating docs to Antora or could you use some help from the ever-helpful Antora community?

**Comment by jaredmorgs** [comment]
For Grammarly Business, the cost is about US$12 per user per month for the 100 user tier, which obviously makes Vale Server a clear winner on price with its one-time licensing cost. 
Grammarly Premium is currently running me A$200 a year, which is about 50c a day. 
On the prickly topic of price, as the features of Vale Server begin to catch up with what Grammarly does with NLP, I personally hope that you **ask for more money for the product**. 

Even if the price for Vale Server went up to $70 from $40 or you adopted a monthly licensing cost for larger businesses I would advocate for it.

**Comment by jdkato** [comment]
> So it makes me wonder if instead of offloading the work to a cloud server, could a Vale browser extension could offload the work to Vale Server on your PC?

This is how it works already -- the idea of bringing to Vale to browser-based applications was the primary motivation for creating Vale Server. There are currently clients for both [Google Docs](https://errata-ai.github.io/vale-server/docs/gdocs) and [Chrome](https://errata-ai.github.io/vale-server/docs/chrome) (the latter of which is definitely still a WIP, though).

> are you comfortable with migrating docs to Antora or could you use some help from the ever-helpful Antora community?

I actually decided to consolidate using Docusaurus 2 instead of Antora (nothing against Antora; Docusaurus 2 simply had enough of the features I was looking for) and the new docs are *almost* done.

**Comment by ChrisChinchilla** [comment]
@jdkato The new docs are almost done? Argh, you're too fast for me ;)

Can you share the branch? And I'll rapidly get that "user survey" out in preparation for a review.

**Comment by jdkato** [comment]
The work is taking place here: https://github.com/errata-ai/vale-server/tree/feat/v2. There's no rush, though, because even when the goals here are "done" I'll still be updating the content.
