### ISSUE TITLE
ignoring autogenerated files

### ISSUE THREAD

**Issue by flashpixx** [vale-cli/vale#204]
I just run vale unter my CI pipeline (with the vale docker container). I'm using Google, Proelint & Write-Good styles. Im working with Markdown, Python, Java, JavaScript & Go. 
My current test project is just working well, but I have got a problem to ignore specific files, which are autogenerated by other tools e.g. in Python for versioning [Versioneer](https://github.com/warner/python-versioneer).

A short information about that tool Versioneer. On a Python project I create a file for generating package versions. Versioneer generates a versioneer.py file (autogenerated) with a lot of code and documentation inside and I must add this file to my project for compiling.
In my vale.ini file I just using this configuration:
```
StylesPath = .
MinAlertLevel = warning

[*.{go,py,java,js,jsx}]
BasedOnStyles = proselint, write-good, google

[README.md]
BasedOnStyles = proselint, write-good, google
```
and you see that all Python files are scanned *.py but in my case the autogenerated versioneer file has got also the extension *.py. The suggestion to use a shell script for that problem to filter the files, is very hard, because I need to figure out on which project which file are stored in which directory and which files must be skipped, so I need a project dependend configuration for vale, and cannot a global independed configuration for all my projects.

Imho it would be nice, if I can configure it like a gitignore file inside the vale.ini file. An ignore list of file and directory patterns e.g.
```
ignore = codestyle/, versioneer.py
```
so this ignores any file and any subdirectory in any directory which is named "codestyle" and ignores any "versioneer.py" file in any directory.
Thanks

**Comment by jdkato** [comment]
As I said in #88, ignoring files is something that I consider to be out of scope for Vale.

That said, in your case, you should be able to achieve what you want by simply specifying what you *do* want Vale to lint:

```text
$ vale README.md <dir1> <dir2>
```

**Comment by flashpixx** [comment]
I have read #88 but there are a lot of tools which are generating files into the source tree in my case I have got multiple repositories with similar but not equal structure. So your approach does not work directory directly (my file is part of dir1), so I need to write my own glob function which is project dependend.
Vale is used for multiple repositores with a global configuration, so it is hard to define the vale call for each repository individual so it quit easier that vale can filter the globed files.

In my case I would like to use vale in multiple repositories in different combination but with a single globale configuration. Also other tools like pylint supports a skipping option for files or  directories too. So I think it would be nice that vale does this similar, because it it make it much easier to use value in large projects.
