### ISSUE TITLE
"brew tap ValeLint/vale" command shows "Repository not found" error

### ISSUE THREAD

**Issue by ketansevekari** [vale-cli/vale#205]
- OS = macOS 
Getting the following error:
my_home_directory ~ % brew tap ValeLint/vale
==> Tapping valelint/vale
Cloning into '/usr/local/Homebrew/Library/Taps/valelint/homebrew-vale'...
Username for 'https://github.com': gitusername
Password for 'https://gitusername@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/ValeLint/homebrew-vale/' not found
Error: Failure while executing; `git clone https://github.com/ValeLint/homebrew-vale /usr/local/Homebrew/Library/Taps/valelint/homebrew-vale` exited with 128.

**Comment by jdkato** [comment]
The new command is just `brew install vale`.
