### ISSUE TITLE
error on pylint with disabling value

### ISSUE THREAD

**Issue by flashpixx** [vale-cli/vale#209]
I'm using in a python script [pylint](https://www.pylint.org/) and I must add a disable call for pylint

```python
logger = sc._jvm.org.apache.log4j  # pylint: disable=protected-access
```
I cannot use the [ignore pattern](https://errata-ai.github.io/vale/config/#ignoring-parts-of-your-documents) because pylint needs this strict format of the comment. So can the ignore pattern be extended for something like

```python
# value: off
logger = sc._jvm.org.apache.log4j  # pylint: disable=protected-access
# vale: on
```

Thanks

**Comment by jdkato** [comment]
Closed in favor of #263.
