### ISSUE TITLE
Markdown in ERB files

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#210]
I'm trying to lint a combination of markdown and ERB templating, but I'm finding the ignore syntax isn't working.

I'm trying to exclude syntax like 

```
<%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=unknown" %>

and 
<% for theme in ["slack", "github", "saturn", "flickr", "solarized", "mono"] %>

```

The following config works for the markdown just fine, but doesn't exclude the ERB syntax.

```
[formats]
erb = md
txt = md

[*.erb]
TokenIgnores = (<%.*%>), \
                          (<%=.*?%>)

[*]
Vale.Spelling = error
```

and the same regex in BlockIgnores also doesn't work.

Thanks

**Comment by jdkato** [comment]
Since you told Vale to treat all `erb` files as `md`, you want to assign your `TokenIgnores` to `md` rather than `erb`:

```ini
[formats]
erb = md

[*.md]
TokenIgnores = (<%.*?%>)

[*]
BasedOnStyles = Vale
```

(Also, `(<%.*?%>)` should be able to replace both of your current patterns.)

**Comment by plaindocs** [comment]
Thanks @jdkato 

That doesn't seem to work for me. Couple of questions:

* the files are actually `*.md.erb`, but the syntax should still be `erb = md` right? 
* txt is automatically treated as markdown which is why you removed it from the list?

**Comment by jdkato** [comment]
> the files are actually *.md.erb, but the syntax should still be erb = md right?

Yes, assuming you want the files to be treated as Markdown.

> txt is automatically treated as markdown which is why you removed it from the list?

No, `txt` is not automatically treated as Markdown -- that was simply an omission in my example.

If this isn't working for you, could you share (or link to?) an example file?

**Comment by plaindocs** [comment]
Sure thing. I'm looking at PR https://github.com/buildkite/docs/pull/740

And when I remove `github` from the vocab list, using the config above I get 

```
 pages/integrations/build_status_badges.md.erb
 55:32  error  Did you really mean 'github'?  Vale.Spelling 
```

from https://github.com/buildkite/docs/blob/sw-spelling/pages/integrations/build_status_badges.md.erb#L55

<3

**Comment by plaindocs** [comment]
The full config I've got locally is 

```ini
StylesPath = vale

MinAlertLevel = warning

[formats]
erb = md
txt = md

[*.md]
TokenIgnores = (<%.*?%>)

[*]
Vale.Spelling = error
```

**Comment by plaindocs** [comment]
~Oh, I see the problem. I need to have the check in the same grouping as the exclusion.~

nonsense

**Comment by jdkato** [comment]
Okay, there are two issues here:

First, `TokenIgnores` aren't suitable for snippets like

```erb
<table class="status-badges__examples">
  <tbody>
    <tr>
      <th>Default</th>
      <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=passing" %></td>
      <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=failing" %></td>
      <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=unknown" %></td>
    </tr>
    <% for theme in ["slack", "github", "saturn", "flickr", "solarized", "mono"] %>
      <tr>
        <th><code><span class="muted">?theme=</span><%= theme %></code></th>
        <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=passing&theme=#{theme}" %></td>
        <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=failing&theme=#{theme}" %></td>
        <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=unknown&theme=#{theme}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
```
since the entire block is technically non-standard Markdown (it's neither Markdown nor HTML).  Essentially, `TokenIgnores` correspond to Markdown code spans (``` `...` ```) and `BlockIgnores` correspond to code blocks (like above).

Second, while looking into this, I discovered that `v2.2.0` introduced a bug with `BlockIgnores`&mdash;which is why you'll see `IgnorePatterns` used below. This will be fixed in the next release (probably today).

(`IgnorePatterns` == `BlockIgnores`. They became `BlockIgnores` when `TokenIgnores` were implemented, but still work for compatibility reasons.)

---

All that said, I believe this is closer to what you want:

```ini
[formats]
erb = md
txt = md

[*.md]
IgnorePatterns = (?s) *(<table [^>]+?>.*?</table>)

[*]
BasedOnStyles = Vale
```
With this config, I get the following results on your example file:

```console
$ vale build_status_badges.md.erb

build_status_badges.md.erb
 3:100   error  Did you really mean 'readmes'?  Vale.Spelling 
 7:3     error  Did you really mean 'toc'?      Vale.Spelling 
 120:53  error  Did you really mean             Vale.Spelling 
                'buildkite'?                                  

✖ 3 errors, 0 warnings and 0 suggestions in 1 file.
```

**Comment by plaindocs** [comment]
I super appreciate your help on this.

I don't want to ignore content in tables though. I could easily have a table with normal content. 

```
<table class="status-badges__examples">
  <tbody>
    <tr>
      <th>Default</th>
      <td>these are normal words</td>
      <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=failing" %></td>
      <td>and these are words to lint as well</td>
    </tr>
```

So I'm thinking of that table as a normal html table allowed inside a normal markdown, with a few bits of ERB code which I want to ignore. 

I could lint the output, but I'd rather not.

**Comment by jdkato** [comment]
> So I'm thinking of that table as a normal html table allowed inside a normal markdown, with a few bits of ERB code which I want to ignore.

This isn't possible with `TokenIgnores` or `BlockIgnores`: An HTML table with ERB code is no longer a valid HTML table and Vale won't be able to understand it.

If you don't want to ignore *all* tables, you have a few options:

1. Write all tables with "normal" content using Markdown syntax (rather than HTML);
2. surround non-standard tables with [`<!-- vale off --> ... <!-- vale on -->`](https://errata-ai.gitbook.io/vale/getting-started/markup#markdown-html) comments; or
3. add an attribute or class to non-standard tables that allow them to be differentiated from normal tables:

    ```
    IgnorePatterns = (?s) *(<table class="erb .*?">.*?</table>)    
    ```

    ```erb
    <table class="erb status-badges__examples">
      <tbody>
        <%
          examples = [
            "9c0,f93,0ad",
            "9c0,f93,0ad,d6d6d6",
            "9c0,f93,0ad,d6d6d6,000",
            "9c0,f93,0ad,d6d6d6,000,fff"
          ]
        %>
        <% for example in examples %>
          <tr>
            <th><code><span class="muted">?theme=</span><%= example %></code></th>
            <% for status in %w( passing failing unknown ) do %>
              <td><%= image_tag "#{ENV["BADGE_DOMAIN"]}/sample.svg?status=#{status}&theme=#{example}" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    ```

Of course, this doesn't account for mixed-content tables but, as I said above, there's no way to ignore embedded content in a non-standard block.

**Comment by plaindocs** [comment]
Roger that. Clean explanation appreciated. Thanks.

**Comment by plaindocs** [comment]
Sooo, to make sure I *fully* understand. 

HTML inside markdown (as per "spec") is fine and linted, right? But I'm getting errors related to this:

```
Alternative formats (via `Accept` header or file extension):

<table>
<tbody>
  <tr><th><code>text/plain</code></th><th><code>.txt</code></th><td>The job’s environment in a <code>KEY=VALUE</code> format suitable for parsing by tools such as <a href="https://github.com/bkeepers/dotenv">dotenv</a></td></tr>
</tbody>
</table>
```

And also errors *inside* markdown URLs. `/apis/` in there somehow. I'm thinking this is related to the mixed content model somehow. This is one of the *.erb pages which are treated as markdown. 

```
You can use meta-data to identify builds when searching for builds in the REST API:

https://buildkite.com/docs/apis/rest-api/builds

For more information see the [Buildkite REST Builds API documentation](https://buildkite.com/docs/apis/rest-api/builds).
```

**Comment by jdkato** [comment]
> HTML inside markdown (as per "spec") is fine and linted, right? 

Yes, as long as it's valid HTML.

> But I'm getting errors related to this:
> 
>
> ```html
> Alternative formats (via `Accept` header or file extension):
>
> <table>
> <tbody>
>   <tr><th><code>text/plain</code></th><th><code>.txt</code></th><td>The job’s environment in a <code>KEY=VALUE</code> format suitable for parsing by tools such as <a href="https://github.com/bkeepers/dotenv">dotenv</a></td></tr>
> </tbody>
> </table>
> ```
When I run Vale on this snippet using your provided config, I get a single `Vale.Spelling` error for `dotenv`. And since `dotenv` is used as the link's text (which is linted), this seems like expected behavior?

>And also errors inside markdown URLs. /apis/ in there somehow. I'm thinking this is related to the mixed content model somehow. This is one of the *.erb pages which are treated as markdown.
>
> ```markdown
>You can use meta-data to identify builds when searching for builds in the REST API:
>
>https://buildkite.com/docs/apis/rest-api/builds
>
>For more information see the [Buildkite REST Builds API documentation](https://buildkite.com/docs/apis/rest-api/builds).
> ```

The unformatted link (line 3) is going to be linted as plain text. If it were formatted as a Markdown link or an HTML link, the error would go away.

**Comment by plaindocs** [comment]
Understood, and clear. :-)

**Comment by plaindocs** [comment]
> Since you told Vale to treat all `erb` files as `md`, you want to assign your `TokenIgnores` to `md` rather than `erb`:

Hey @jdkato has this reverted? Or was it mistaken first time round?

**Comment by plaindocs** [comment]
> Since you told Vale to treat all `erb` files as `md`, you want to assign your `TokenIgnores` to `md` rather than `erb`:
> 
> ```ini
> [formats]
> erb = md

is it possible that this reverted? Or is it still true? @jdkato (happy to open a new thread if that makes sense)

**Comment by jdkato** [comment]
My intent is for this to still be true.
