### ISSUE TITLE
Follow the XDG standard on Unix

### ISSUE THREAD

**Issue by adamtabrams** [vale-cli/vale#211]
For macOS and Linux please follow the the [XDG Directory Spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). This would mean that `vale` would look for its global config at $XDG_CONFIG_HOME/vale/vale.ini. And if that environment variable isn't set, it would default to $HOME/.config/vale/vale.ini.

**Comment by jdkato** [comment]
While I understand the need and desire for standardization of configuration files, I don't think this need strictly applies to Vale for two reasons:

1. Vale doesn't write its own configuration or data files, which means it doesn't "pollute" the user's system by using its own arbitrary or non-standard locations by default.

2. You can specify the location of your own config file using `--config` (e.g., `vale --config "$XDG_CONFIG_HOME/vale/vale.ini"`).

(related to #152)

**Comment by adamtabrams** [comment]
@jdkato I don't really see how vale not writing the config file makes any difference? But regardless, wouldn't it be possible to have vale check for the config in $XDG_CONFIG_HOME before checking in $HOME. Then you would allow for people to follow the standard, and you'd let the users decide what's best for them. 

Also, the `--config` option does allow for an arbitrary config path (and a shell alias could be made for this too), but vale is a linter. And a lot of people integrate their linters with their text editors. For example, I use the ALE plugin with vim. And there's no way for me to call `--config` in that usecase. But really, even if there were, that's not really not a great to enable that functionality.

**Comment by aecepoglu** [comment]
But vale does require a config file. On a fresh install `vale file.txt` will complain about the lack of a `vale.ini` file
