### ISSUE TITLE
A new (better) way to handle exceptions

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#213]
## The Problem

A number of Vale's checks support specifying a list of tokens or patterns that shouldn't raise an alert (`capitalization`, `spelling`, `conditional`, etc.)

However, currently, there's no way to specify these independent of a style. This means that, for example, if an organization wants to use the `Microsoft` style as a starting point for their own style guide, they have two options for handling exceptions:

1. Modify the third-party style directly (e.g., `Microsoft`); or
2. Disable certain third-party rules and re-implement them in their own style.

(1) Makes it difficult to keep up with upstream releases and (2) can get repetitive quick.

## The Solution

I've been working on an undocumented feature over the past few releases that I'm calling "vocabularies." This has been around in Vale Server (in some form) for a while, but I'd like to ensure that styles are 100% compatible between the two projects.

The idea is pretty simple: the following directory structure is added to the `StylesPath`:

```
Vocab
└── <Some-Name>
    ├── accept.txt
    └── reject.txt
```

where `accept.txt` and `reject.txt` are plain-text files that take one entry per line (similar to how `ignore` files work now, but both would be case-sensitive):

- All entries in `accept.txt` are automatically added to a case-insensitive substitution rule (Vocab.Terms), ensuring that any occurrences of these words or phrases exactly match their corresponding entry in `accept.txt`. Each term is automatically added to every exception list in all inherited styles—meaning that you now only need to update your project’s vocabulary to customize third-party styles.

- Entries in `reject.txt` are automatically added to an existence rule (Vocab.Avoid) that will flag all occurrences as errors.

This would be used like so:

```ini
StylesPath = "..."

# Here's were we define the exceptions to use in *all*
# `BasedOnStyles`.
Vocab = Some-Name

MinAlertLevel = suggestion

[*]
# Automatically respects all custom exceptions
BasedOnStyles = Microsoft
```

This means that your exceptions can be developed independent of a style, allowing you to use the same exceptions with multiple styles or switch styles without having to re-implement them.

Thoughts or suggestions?

**Comment by stewartadam** [comment]
@jdkato under this new system, wanted to raise visibility that if `accept.txt` is used for spelling exceptions, `Vale.Terms` will throw an error when the opposite capitalization is used. For example, `observability` was added to `accept.txt` which then caused issues if `Observability`, capitalized, was ever used in a markdown document header.

Adding both words to `accept.txt` doesn't work because Vale appears to prefer whichever appears first in the file.

IMO spelling exceptions and preferred terminology should be decoupled.

**Comment by jdkato** [comment]
> under this new system, wanted to raise visibility that if `accept.txt` is used for spelling exceptions, `Vale.Terms` will throw an error when the opposite capitalization is used. For example, `observability` was added to `accept.txt` which then caused issues if `Observability`, capitalized, was ever used in a markdown document header.

Yes, @stewartadam, you've described the *intended* functionality.

> Adding both words to `accept.txt` doesn't work because Vale appears to prefer whichever appears first in the file.

If you solely want to use `accept.txt` has a spelling-exception list, then you can disable `Vale.Terms`. If you want to use both `Vale.Terms` and `Vale.Spelling` but also include some case-insensitive entries, then you can provide a regular expression such as `[Oo]bservability` for said entries.

> IMO spelling exceptions and preferred terminology should be decoupled.

If you'd still like them to be "decoupled," disable `Vale.Terms` and implement your own `MyStyle.Terms` rule.

**Comment by stewartadam** [comment]
This is helpful, thank you! The spellchecking tip might be a good example to add to the docs, as reading through the docs trying to find how to add exceptions for the built-in `Vale.Spelling`, my conclusion was to either use Vocab functionality, or I needed extend `Vale.Spelling` myself and then specify an exception file. 

Vocab and `accept.txt` seemed like the saner choice given it's built-in functionality and re-use across styles, but having this example would have been very helpful in determining how to format the exceptions file or adjusting the Vale.Terms config.
