### ISSUE TITLE
Passing content through stdin doesn't seem to work

### ISSUE THREAD

**Issue by AlexJitianu** [vale-cli/vale#214]
Hello,

I'm trying to run vale from the command line on Windows 10 and pass text via stdin. 

Running vale against a file `vale --config="D:\tools\tmp\vale\.vale.ini" sample.md` gets me a correct warning:

```
sample.md
 1:1  warning  Use the Oxford comma in a list  base.OxfordComa
               of three or more items...
```

But when I try this: `vale --config="D:\tools\tmp\vale\.vale.ini" --ext='.md' 'A,B and C'` I get no warning whatsoever. 

- OS: Windows 10
- Install method:  direct download
- Vale version: 2.2.2 

I apologize if it's something obvious that escapes me...

Thank you,
Alex

**Comment by jdkato** [comment]
Can you share your `.vale.ini` and `base.OxfordComa` files?

**Comment by AlexJitianu** [comment]
These ones: https://github.com/AlexJitianu/dita-meets-markdown/tree/master/demo-files/vale

I tried different approaches for .vale.ini, inspired from Vale docs, to no avail...

**Comment by jdkato** [comment]
You need a space between "A," and "B" for the pattern to match (as you have in `sample.md`):

```console
$ vale --ext='.md' 'A,B and C'
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
$ vale --ext='.md' 'A, B and C'

 stdin.md
 1:1  warning  Use the Oxford comma in a list  base.OxfordComa
               of three or more items.

✖ 0 errors, 1 warning and 0 suggestions in stdin.
```

(Run from within the `demo-files/vale` directory.)

**Comment by AlexJitianu** [comment]
I now see that in my initial post I missed a space in the analyzed text, but that was just a typo. I double checked, I used the same text with stdin and file content. With stdin it doesn't report anything. 
Did you test it on Windows and did it work in your case? Perhaps it is something related with the Windows launcher. Currently I don't have access to a Linux machine, perhaps I'll be able to connect to one tomorrow and test on it the same scenario...

**Comment by jdkato** [comment]
Yes, I tested on Windows (it also works on macOS and Linux for me) with the files you provided and got the results posted above. 

How is `D:\tools\tmp\vale\.vale.ini` different from the config file in `demo-files/vale`?

**Comment by AlexJitianu** [comment]
It's not! I did everything again on my personal computer. Here is what I did:
1. I downloaded Vale 2.2.2 for Windows. I unzipped it, add it to path/
2. I cloned https://github.com/AlexJitianu/dita-meets-markdown/tree/master/demo-files/vale and opened a cmd inside this folder
3. I run with stdin and file
![image](https://user-images.githubusercontent.com/7802649/84602804-96ff6680-ae92-11ea-859e-39ba36016eb6.png)

I don't understand what I'm doing wrong...

**Comment by jdkato** [comment]
When using the basic Command Prompt application, you need to use double quotes for stdin strings:

![command-prompt](https://user-images.githubusercontent.com/8785025/84603307-3a745b00-ae42-11ea-908a-f823fff1e5a7.png)

That said, your experience with Vale (and other tools) would probably be better using a more dev-focused app like Windows Terminal:

![PowerShell](https://user-images.githubusercontent.com/8785025/84603334-7f988d00-ae42-11ea-98b1-3136f7353b5b.png)

**Comment by AlexJitianu** [comment]
Wow! I'm glad to see that it was this easy! Perhaps it's worth putting a note in the documentation. 

Do you have any advice on how to pass/escape newlines in the text to the process?  I use Java to start Vale and I am passing newlines as characters, without any processing. Reports are all on line 1, like newlines are ignored.
Content: 

```
Line 1
Line 2
I love my parents, LadyGaga and HumptyDumpty.
```

Report:

```
{
  "stdin.md": [
    {
      "Action": {
        "Name": "",
        "Params": null
      },
      "Check": "base.OxfordComa",
      "Description": "",
      "Line": 1,
      "Link": "https://docs.microsoft.com/en-us/style-guide/punctuation/commas",
      "Message": "Use the Oxford comma in a list of three or more items.",
      "Severity": "warning",
      "Span": [
        1,
        45
      ],
      "Match": "Line 1 Line 2 I love my parents, LadyGaga and"
    }
  ]
```

Thank you,
Alex

**Comment by AlexJitianu** [comment]
Never mind my last question! I spoke to soon. It's not related with Vale but with [Java API](https://stackoverflow.com/questions/12393010/java-runtime-exec-removes-newlines-from-arguments). It's working as a charm! :)

**Comment by AlexJitianu** [comment]
I have one more question. Sometimes, Markdown starts with a YAML header which starts with 3 dashes. If I validate such content through stdin:

`vale --ext='.md' '--- A, B and C'`
I get an error:
`Incorrect Usage. bad flag syntax: --- A, B and C`
Apparently it's enough to put a different character at position zero, but perhaps you have a different recommendation.

Thank you!

**Comment by jdkato** [comment]
When the header is correctly formatted (e.g., `---\n...\n---`, Vale will ignore it automatically.
