### ISSUE TITLE
Spellcheck commit messages in the Pull Request.

### ISSUE THREAD

**Issue by proofit404** [vale-cli/vale#216]
Hi, thank you for an awesome tool!

I tend to use @semantic-release in the open-source libraries I develop my self.

Using this approach the changelog file will be generated from the commit messages we wrote.

I already check that commits have a correct structure using this command:

```
npx commitlint --from master
```

It would be useful if I could somehow spellcheck commit messages.

Is it possible to do it somehow?

Any suggestions are welcome.

Have a wonderful day :tada:

Best regards,
Artem.

**Comment by jdkato** [comment]
Vale has no commit-specific features, but you should be able to integrate it with any tool that exposes the commit messages through an API.

It seems like you could even do this with [`commitlint`](https://commitlint.js.org/#/reference-plugins) itself: implement a plugin that calls Vale on the message and fails if it finds a spelling mistake.
