### ISSUE TITLE
Vale does not ignore code blocks in markdown

### ISSUE THREAD

**Issue by alcazaco** [vale-cli/vale#217]
Hi!

Looks like Vale does not ignore code blocks. Even with the `code: false` string in a style:

![image](https://user-images.githubusercontent.com/20209898/85126626-86eeda80-b236-11ea-99a8-06d0dec1eee7.png)

Vale version: 2.2.2

**Comment by jdkato** [comment]
This is a UI-only issue with Vale Server's Studio editor (it has been fixed for the next release). The code block is ignored correctly using the Vale CLI and any of Vale Server's clients.
