### ISSUE TITLE
Call for user research sessions

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#220]
Thanks for using Vale! The project is overhauling its documentation to suit common use cases people have with the CLI and server version and we're interested in knowing how you currently use either/both tools.

I am looking for people to undertake user research video calls to find out more about how people use Vale CLI and server to help us update the documentation to be most useful to people moving forward.

If you're interested, please sign up for a session here - https://bit.ly/2CKp7Ur

I will record calls, but if you're not OK with that, you can let me know in the form to sign up for a session.

In these calls, I'd love to hear how you use the tools, the sorts of configuration you use, and how, and what you are using Vale for.

**Comment by Ravlen** [comment]
@ChrisChinchilla I tried to sign up, but the link says "the calendar is off"? 🙇

**Comment by ChrisChinchilla** [comment]
@Ravlen Sorry my Doodle trial expired! Try again, it's back on!

**Comment by ChrisChinchilla** [comment]
@jdkato I'd probably keep this open a little longer…
