### ISSUE TITLE
How do I update the docs sidebar?

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#224]
Someone pointed out that the link to the vale styles in the test the docs repo is misleading as it leads to a repo that has now largely changed. However, I can't see how to change that. Any ideas?

**Comment by jdkato** [comment]
There are currently two sidebars in question:

1. The now-deprecated [GitBook sidebar](https://errata-ai.gitbook.io/vale/), which only I can change from the admin dashboard.

2. The new sidebar at https://docs.errata.ai/vale/about, which can be changed [from here](https://github.com/errata-ai/vale-server/blob/master/website/sidebars.js).

I've gone ahead and removed the test the docs link from both for now. If there's another link you'd like me to add instead, let me know.

--- 

I know the location of Vale's documentation has changed too much; I really didn't want to change it again, but GitBook proved to be a poor choice on my part and I took the opportunity to change it one last time with the launch of the new https://docs.errata.ai/ site, as mentioned in #202.

I've tried to mitigate the impact of the move by ensuring that notices (and redirects, where possible) are on every relevant page.

**Comment by ChrisChinchilla** [comment]
OK, I am nearly done updating all the TTD styles to use the new template and testing framework, from there I am going to transfer them to the Good docs project as good stewards moving forward, so I'll have a link or two quite soon for a whole set of new "editorial" styles people can draw inspiration from.

**Comment by ChrisChinchilla** [comment]
@jdkato I found a way we can tag community styles, so added the link to a new PR. Will also need to update the CLI site (which I think you need to do?). 

I tagged "community" styles - https://github.com/topics/vale-linter-style

There's one further step, which is adding some sort of "how to create a style" guide, that mentions how to tag a style. We also need a "how to create an extension that uses Vale" guide anyway, so I' adding those to my list for the near future. But I won't go into it too much here as it's off topic.
