### ISSUE TITLE
Automate Homebrew releases

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#225]
Could we add this to the repo?

https://github.com/mislav/bump-homebrew-formula-action

I also don't mind setting up a "packaging repo" to trigger many of these processes, if that's possible and you'd rather keep things separated.

**Comment by jdkato** [comment]
Yes, I can add this here.

**Comment by ChrisChinchilla** [comment]
So I think this is done @jdkato ?

**Comment by jdkato** [comment]
No, I haven't done this yet.

**Comment by jdkato** [comment]
I don't think this is necessary anymore.

I'm not sure who/how it's done, but the Homebrew formula seems to update with every release.

**Comment by ChrisChinchilla** [comment]
@ChrisChinchilla Looks like a bunch of people are handling it manually - https://github.com/Homebrew/homebrew-core/commits/9060e4a72d47114ce6e52c75d327860bc9d8863e/Formula/vale.rb I mean you could automate it, but it's also a nice community task.
