### ISSUE TITLE
False positives, and varying output on multiple runs with no changes

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#229]
The last version I was running was 2.2.2, on MacOS Mohave.

I just updated to 2.3.2 and now see some anomalies. My coworker just tested on 2.3.0 and sees the same issues, so it seems like it was introduced with that release.

I've rerun all our tests including the warning and suggestion level tests, and they report a different number of issues each time.

Two examples (but not limited to these two tests). 

### Example 1

The repetition test is finding doubled words where none exist. It might be finding the same word on a line above or below the reported problem, and thinking it's adjacent somehow, or getting confused by table formatting:

Style:

```yaml
extends: repetition
message: '"%s" is repeated.'
level: error
alpha: true
tokens:
  - '[^\s]+'
```

Output (CLI). Note that rerunning will give a different number of results each time:

```
 api/protected_branches.md
 312:1  error  "in" is repeated.  gitlab.Repetition

 user/clusters/applications.md
 1340:1  error  "the" is repeated.  gitlab.Repetition 
```

- `api/protected_branches.md`: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/protected_branches.md#L312
- `user/clusters/applications.md`: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/user/clusters/applications.md#L1340

### Example 2

Style:

Look for two sentences missing the space between them (like: `These two sentences.Are missing the space`)

```yaml
extends: existence
message: '"%s" must contain one and only one space.'
level: error
nonword: true
tokens:
  - '[a-z][.?!,][A-Z]'
```

Output (CLI). Note that rerunning will give a different number of results each time:

```
 install/aws/index.md
 245:1   error  "s.A" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 349:1   error  "s.F" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 446:5   error  "r.A" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 454:9   error  "e.A" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 644:3   error  "p.G" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 644:9   error  "p.S" must contain one and      gitlab.SentenceSpacing 
                only one space.                                        
 755:13  error  "s.U" must contain one and      gitlab.SentenceSpacing 
                only one space.
```

These seem to be almost all in markdown lists, but often reporting the wrong line, or the plugin is reporting a line different than the CLI. Every time I save, different lines are flagged:

<img width="1419" alt="Screen Shot 2020-08-17 at 12 25 29" src="https://user-images.githubusercontent.com/36979740/90354610-c5611400-e084-11ea-8dc5-d3e13d765e12.png">

install/awe/index.md: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/install/aws/index.md#L446

**Comment by Ravlen** [comment]
I looked through the changelog for 2.3.0 and couldn't see anything obvious that would cause this...

**Comment by jdkato** [comment]
Thanks for the report.

There are two different issues at play here (although both are related to 2042b61661bb5f3836c884197ec398ad92fceba2).

The `repetition` alerts are actually "correct"; it's a case that Vale wasn't able to detect before v2.3.0:

> [`protected_branches.md#L257`](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/protected_branches.md#L257): `[added to the API in](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/3516) in GitLab 10.3 EE.`

> [`applications.md#L1142`](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/user/clusters/applications.md#L1142): `This can be done by reading the
[the Vault documentation](https://www.vaultproject.io/docs/internals)`

The problem is that we're getting the location wrong due to #95. I was pretty sure that I fixed this, but I have to think more about how to handle these nested-makup cases.

---

The second issue is that these lines

```markdown
1. Click **Configure Instance Details**.
   1. In the **Network** dropdown, select `gitlab-vpc`, the VPC we created earlier.
```
are being linted together, but Vale's Markdown parser is dropping the leading space before the nested list item.

---

I should have both issues fixed fairly soon.

**Comment by jdkato** [comment]
Okay, I think both of these issues are fixed.

When I run a build from master (soon-to-be v2.3.3) on the entirety of the GitLab `doc` folder, I get the following:

```console
$ vale --minAlertLevel='error' doc

 doc/api/protected_branches.md
 258:1  error  "in" is repeated.  gitlab.Repetition 


 doc/api/scim.md
 5:1  error  "the" is repeated.  gitlab.Repetition 


 doc/ci/environments/deployment_safety.md
 35:1  error  "keyword" is repeated.  gitlab.Repetition 


 doc/user/group/saml_sso/index.md
 266:1  error  Use "Omnibus GitLab" instead    gitlab.Substitutions 
               of "GitLab Omnibus".                                 


 doc/user/project/pages/custom_domains_ssl_tls_certification/index.md
 103:1  error  "record" is repeated.  gitlab.Repetition 
```
I've confirmed that the errors (and their locations) are accurate.

(FWIW, Vale is also now about 48% faster at linting the `doc` folder than `v2.2.2`.)

**Comment by Ravlen** [comment]
@jdkato Wow, that was way too fast, that was heroic! Also, thank you so much for verifying on our docs themselves, that's really useful information!

I'll see if I can build it locally from master myself, and then I'll be able to test out pre-release features myself too (my coworker already does this, but I haven't gotten it to work with the plugin just yet, and have been holding off).

The 48% speed increase is not something I realized, and I'll definitely upgrade the pipelines ASAP so that we all see the benefit right away! 🙇

**Comment by jdkato** [comment]
I'm going to assume this is fixed, but feel free to comment further.

**Comment by Ravlen** [comment]
@jdkato We've got it running in the CI, and I've got it running locally. Looks solid, thanks again!
