### ISSUE TITLE
Implement detection for reserved IP Addressess

### ISSUE THREAD

**Issue by rebortg** [vale-cli/vale#230]
Hi,

i write much on the docs for the VyOS Software router project and want to implement the wrong usage of IP Addresses.
There are some reserved Address space which represent public IP Addresses, but these are only for documentation purpose . ([see here](https://docs.vyos.io/en/latest/contributing/documentation.html#address-space))

i try to build this with the _existence_ style and raw regex with no success.
Did you have any tips? Or is there a way for hook into vale with a plugin or something?

**Comment by jdkato** [comment]
Could you share the `existence` rule that you tried to implement?

I think that will help me better understand the issue.

**Comment by rebortg** [comment]
at the moment i have a quick and dirty python script:
https://github.com/vyos/vyos-documentation/blob/master/ci/vyos-linter.py

it filter all ip addresses (and a little bit more) with regex and test against the python ipaddress module. All the IP Address which are good for the documentation are marked as private by the python module.

This is i want to get with vale.

Do there are two steps detect a IP Address pattern, then filter good or bad pattern. But i don't find a negative regex possibility or how i do a two step test.
for example:

good sentence:
Set the interface address 10.0.1.1 to connect to the internet.

bad sentens:
Set the interface address 5.5.5.5 to connect to the internet.

**Comment by jdkato** [comment]
I don't think there's a straightforward way to convert your Python logic into a Vale rule currently.

Plugins are something that I considered in the past, but non-native plugins (e.g., calling out to Python) were too slow and native Go plugins don't support Windows.

I may revisit non-native plugins in the future though.
