### ISSUE TITLE
MD formatting is ignored when used inside HTML tags

### ISSUE THREAD

**Issue by janisz** [vale-cli/vale#231]
If md file contains HTML tag with md link inside, vale parse links and produce errors

e.g.: 
```
<p>The quick brown [fox](https://fox.com) jumps over the lazy dog</p>
```
results with 
```
 1:26  error  Did you really mean 'https'?  Vale.Spelling 
```

- OS: Linux
- Install method: direct download
- vale version 2.3.4

**Comment by janisz** [comment]
I  checked and it looks like vale do not render MD if it appear inside raw HTML tags

```
<p>The quick brown fox jumps over the lazy dog `https`</p>
```

```
 1:49  error  Did you really mean 'https'?  Vale.Spelling 
```

**Comment by jdkato** [comment]
This is expected behavior, as Vale supports [GitHub-Flavored](https://docs.errata.ai/vale/scoping#markdown) Markdown (a superset of CommonMark).

**Comment by NicolasMassart** [comment]
I can't really understand how this can be expected?
You also said that on the links issue #185 
What is the workaround?

**Comment by jdkato** [comment]
@NicolasMassart: Can you elaborate on what you don't understand?

This issue is about including markup inside raw HTML, like the following:

> <p>The quick brown fox jumps over the lazy dog `https`</p>

vs. markup on its own:

> The quick brown fox jumps over the lazy dog `https`

The first example isn't supported on GitHub (note the unformatted "https") or when using Vale since they both use [CommonMark](https://commonmark.org/).

---

#185 is simply a misunderstanding of Markdown, as explained in https://github.com/errata-ai/vale/issues/185#issuecomment-610000763.

**Comment by NicolasMassart** [comment]
Hi @jdkato 
My point is more on #185 to be honest. See my comment in this issue.
I did not know the Span-level vs Block-level HTML tags.
I landed on this issue first while searching for the issue with link tags, so forget it on this one, my point is only relevant for #185.
Thanks.

**Comment by NicolasMassart** [comment]
@jdkato I had an interesting case that I think may be linked to this HTML behaviour.
When you have an HTML comments on the same line that an MD syntax that should be ignored, link URL or inline code, Vale will ignore the excluded syntax still check the URL or code.

For example the following line:

```
* <!-- markdown-link-check-disable-line --> [Filecoin](https://filecoin.io/)
```

 triggers an issue as the `https://filecoin.io/` is checked.

```
 19:56  error    Did you really mean 'https'?    Vale.Spelling                
 19:64  error    Use 'Filecoin' instead of       Vale.Terms                   
                 'filecoin'.   
```

However, if you add the comment after the link, it works fine for Vale (and my link checker too).
So I have a workaround here, but it's a strange behaviour.

**Comment by jdkato** [comment]
To be clear: neither this issue as a whole nor the case described above are directly related to anything Vale is doing itself. Vale uses [`goldmark`](https://github.com/yuin/goldmark), a CommonMark-compliant library, to do all of its Markdown processing.

So, whenever there appears to be "strange" Markdown-related behavior a good first step is usually to enter the snippet into either [the CommonMark demo](https://spec.commonmark.org/dingus/) or GitHub itself (which follows the same standard as Vale). 

When we do this with regard to the case above, it becomes quite clear what is happening:

Comment before:

*  [Filecoin](https://filecoin.io/)

Comment after:

* [Filecoin](https://filecoin.io/)

**Comment by NicolasMassart** [comment]
I have a workaround here so that's not a big deal. At least if anyone else has the same issue, there's an answer here. Thanks @jdkato for your help.
