### ISSUE TITLE
Include severity in `--output line`

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#232]
The line output is great because it's easy to parse, but you lose the message severity which makes it considerably less useful. 

The only way I can see around it is to add the severity to the filename for the rule. It's clunky, and would only work for first-party rules without trouble.

Right now I'm working with BBEdit's `bbresults` tool, but we'll use similar techniques when we deploy this in our CI/CD environment.

**Comment by nostodnayr** [comment]
I modified the output and built a custom version of vale and at least when working with BBEdit, I find this output most useful: 

`file:line:column:check:severity:message`

I had `(check)` at the end of the message, but I expect for writers knowing this isn't that useful. It's only helpful now as I'm debugging. I would probably discard the `check` in most cases.

If you wanted to stay closer to the UNIX 'standard', `file:line:column:check:severity:message`, where a 'dumb' parser may reasonably expect to match any character that follows the colon after `check`. If you know what you're looking for, though, you'll get the richer information.

**Comment by jdkato** [comment]
Using [`--no-wrap`](https://docs.errata.ai/vale/cli#--no-wrap) should make the default output just as easy to parse.

**Comment by nostodnayr** [comment]
> Using [`--no-wrap`](https://docs.errata.ai/vale/cli#--no-wrap) should make the default output just as easy to parse.

True, and I've tried that, but the file is only printed once in that case, which doesn't agree with `bbresults` certainly.

**Comment by jdkato** [comment]
I can't say that I'm overly familiar with `bbresults`, but I think it's fair to say that:

1. Altering `--output=line` would constitute a breaking change, which means it'd probably be better to just add a new output format; and

2. it's not reasonable to expect Vale to personally accommodate every other tool -- especially when they're so limited in what they expect and Vale already offers multiple options that provide the required information.

For example, you can get your required format trivially by writing a simple wrapper using your favorite scripting language (Python shown below):

```python
import sys
import json

data = json.load(sys.stdin)
for src, alerts in data.items():
    for a in alerts:
        print('{0}:{1}:{2}:{3}:{4}:{5}'.format(
            src,
            a['Line'],
            a['Span'][0],
            a['Check'],
            a['Severity'],
            a['Message']))
```

```console
$ vale --output=JSON fix.md | python bbresults.py 
fix.md:3:13:Microsoft.Vocab:suggestion:Verify your use of 'allows' with the A-Z word list.
fix.md:3:27:Microsoft.Adverbs:warning:Consider removing 'easily'.
```

**Comment by nostodnayr** [comment]
I don't expect Vale to make accommodations for every tool, but the line output is lacking information available in other formats. I don't see the value in printing the rule, but not the severity.

Whilst my use case right now is bbresults, I want to be able to get the information and parse it without relying on another tool later, too.
