### ISSUE TITLE
Debug 

### ISSUE THREAD

**Issue by dkolepp** [vale-cli/vale#237]
I am trying to develop a style rule that uses the `sequence` extension type.  The rule is not behaving as expected, and wish to see how vale is creating NLP tokens for the text.  Is there a way to turn on logging, for example, to diagnose when a `sequence` rule is not flagging errors that it should find?  

In essence, is there a way to see/output of how vale "tokenizes" a test document? 

I am:

* using AsciiDoctor  source files.
* using vale on RHEL/Fedora-based systems.
* currently using vale `2.3.3`

**Comment by jdkato** [comment]
You can use the [tag command](https://docs.errata.ai/vale/cli#tag-v230) to see how the sentence in question is tagged.

**Comment by dkolepp** [comment]
Perfect - thanks!

**Comment by dkolepp** [comment]
Would it be useful to (cross) reference this in the documentation that describes the `sequence` extension point?

**Comment by dkolepp** [comment]
Also, is there a way to see how `vale` processes the markup.  If my source file is asciidoc (or Markdown):

```
Use the `/tmp/hello.txt` file as a test.
```

Is there a way to see how that is tokenized?  I assume it is different that just:

```
$> vale tag "Use the `/tmp/hello.txt` file as a test."
```

**Comment by jdkato** [comment]
No, not currently.

The behavior depends on a number of factors (scope, CLI flags, etc.) that aren't accounted for in the `tag` command.

An online rule editor that incorporates this information will be releasing soon, which should make the rule-creation process much easier.

**Comment by jdkato** [comment]
The rule editor is out now -- see https://vale-studio.errata.ai/. It's currently Markdown-only, but AsciiDoc support will be added in a future release.

**Comment by dkolepp** [comment]
Exciting - thanks!
