### ISSUE TITLE
Vale processes Markdown autolinks as language

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#239]
Vale processes [Markdown autolinks](https://daringfireball.net/projects/markdown/syntax#autolink) as text, so a URL can trigger an alert.

The link in this text:

    Visit <https://example.com/your-data/> to learn more.

…will be caught by this rule:

	level      : error
	message    : Use "%s" instead of "%s".

	extends: substitution
	ignorecase: true

	swap:
	  data: information

**Comment by jdkato** [comment]
This is expected behavior, see https://github.com/errata-ai/vale/issues/185#issuecomment-610000763. If you don't want the link linted, then it shouldn't be included in the link title (which is, by definition, "language").
