### ISSUE TITLE
Hyphen in a rule name breaks in-file directives

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#240]
Vale 2.4.0

We use hyphens and underscores in rule names to aid in organisation. For example: `words-passive_voice`, `words-do_not_use`, `punctuation-hyphens`.

If I try to turn off one of these in a file, using `<!-- vale 1Password.words-do_not_use = NO -->`, the directive isn't parsed successfully. Only tested on Markdown content.

**Comment by jdkato** [comment]
This should be fixed in v2.4.2.
