### ISSUE TITLE
Combine Vocabularies

### ISSUE THREAD

**Issue by tigermonkey** [vale-cli/vale#241]
Is it possible to combine vocabularies? For example, if I am writing about bioinformatics I may want to combine two vocabularies, like so:

```
Vocab = Biology, CS
```

I guess there can be ambiguities if a word appears in the `accept.txt` of one Vocab and the `reject.txt` of another.

**Comment by jdkato** [comment]
No, this isn't currently supported.

**Comment by jdkato** [comment]
This will now be supported in the next release.

**Comment by rogeruiz** [comment]
@jdkato has this _next release_ version been released yet? I'm seeing errors when trying to use multiple `Vocab` definitions.

**Comment by jdkato** [comment]
No, not yet. I actually forgot that I didn't release yet -- I'll get it out next week.

**Comment by rogeruiz** [comment]
Thank you @jdkato!

I managed to get everything working by building the project from source with `v2` as the base. Any plans for having the Homebrew installation allow for a `---HEAD` flag? I can update the formula. But I wanted to make sure it'd be okay.

**Comment by jdkato** [comment]
I try to ensure that the main branch (currently `v2`) is always buildable, so it should generally work.
