### ISSUE TITLE
Question: Writing .vale.ini to work around Hugo translations (article.fr.md)

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#245]
We use Hugo and have translated pages living in the same repository as our standard language content. (`article.md`, `article.fr.md`, and so on.)

Most of our Vale rules are specific to the English content (article.md), but some operate on all files.

I’ve been using a configuration file like this:

```
[*.{de,es,fr,it,jp,ru}.md]
BasedOnStyles = 
OurStyle.general_rule = YES

[*.md]
BasedOnStyles = OurStyle
```

I did it this way to avoid turning off all the rules that don’t apply to the translations. Is this the best way to accomplish this, or is there a better way?

(Copied from WTD Slack for posterity and visibility.)

**Comment by jdkato** [comment]
This looks fine to me. The "best" way will almost certainly be subjective.

**Comment by nostodnayr** [comment]
Thanks, @jdkato. Perhaps not 'best', but my previous implementation was to use `BasedOnStyles = none`, which relied on a silent error to work. Vale now fails on this error, so I wanted to make sure I wasn't setting myself up for failure again. (I probably am, and turning off rules is probably better, but I'll ride it out for the time being. 😄)

**Comment by jdkato** [comment]
The only part that doesn't make sense to me is `BasedOnStyles = `. Is this a typo or is the empty value now a replacement for `none`?

**Comment by nostodnayr** [comment]
The empty value is a replacement for `none`.

**Comment by jdkato** [comment]
In that case, I would probably split the rules into two styles: `General` and `En` (or whatever you choose to name them):

```ini
[*.{de,es,fr,it,jp,ru}.md]
BasedOnStyles = General

[*.md]
BasedOnStyles = General, En

**Comment by nostodnayr** [comment]
Oh, brilliant! Of course, that makes perfect sense. Thanks again. :-)

**Comment by nostodnayr** [comment]
I implemented this as suggested, @jdkato, but the problem is that, using the example, the `En` set is still called on the translation files because they match `*.md`.

The only alternative I've found is to start with a blunt `[*]` rule and use `[*.{de,es,fr,it,jp,ru}.md] to override it.

```ini
[*]
BasedOnStyles = General, En

[*.{de,es,fr,it,jp,ru}.md]
BasedOnStyles = General
```

The only problem in this case is that it could potentially get files it shouldn't. My spelling rule is quite unhappy with `.DS_Store` for example. Any ideas for how I can make this a little more robust?

**Comment by jdkato** [comment]
The most basic solution would be to target `en` files directly with `*.en.md`. You could also leave your config file as-is and use `--glob` to limit your search to `.md` files: `vale --glob="*.md" docs`.

**Comment by nostodnayr** [comment]
Unfortunately, untranslated/English files are just `file.md`, whereas translations get the language infix `file.fr.md`. 😒

**Comment by jdkato** [comment]
The second suggestion should still work in that case: call Vale with `--glob='*.md'` to exclude non-`.md` files (e.g., `.DS_Store`) prior to evaluating the section patterns.

**Comment by ghost** [comment]
Is there a way to evaluate not only the file name but also the file path in the pattern for `BasedOnStyles`? I would like to apply different rules for English and German source files (RestructuredText), but in our case we have the two languages in different directories: "en/src/*.rst" vs. "de/src/*.rst".

Thank you very much for your help!

**Comment by jdkato** [comment]
Not in `BasedOnStyles`, but you can do this in the section definitions:

```ini
StylesPath = styles
MinAlertLevel = suggestion

[en/src/*.rst]
BasedOnStyles = Style1

[de/src/*.rst]
BasedOnStyles = Style1
```

**Comment by ghost** [comment]
Thanks a lot for the hint - it works fine for us :-).
