### ISSUE TITLE
Capitalisation issue with some existing rules

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#246]
Since Vale 2.4.0 I have a strange issue that I'm not even sure is really an issue, or maybe more of a docs clarification (that I can submit a PR for).

I have some _vale.ini_ files that had a couple of prebuilt `vale` rules, for example:

```
vale.Annotations = warning
vale.Editorializing = warning
vale.Hedging = suggestion
vale.Litotes = warning
vale.Repetition = error
```

Sine the update these have to be capitalised, and fails to find them if not, so:

```
Vale.Annotations = warning
Vale.Editorializing = warning
Vale.Hedging = suggestion
Vale.Litotes = warning
Vale.Repetition = error
```

I am yet to see if others have the same affect. So let me know if you think this is more of a docs issue, or if it's a regression.

**Comment by NicolasMassart** [comment]
See https://github.com/errata-ai/vale/releases/tag/v2.0.0 release note:
>The built-in vale style has been re-named to Vale

**Comment by ChrisChinchilla** [comment]
Ahhhh, OK then :)
