### ISSUE TITLE
urls are passed to style checking

### ISSUE THREAD

**Issue by flashpixx** [vale-cli/vale#249]
I'm using vale 2.4.0 and in my source code (Golang) I have got this comment line

```
// @todo https://medium.com/@jcox250/password-hash-salt-using-golang-b041dc94cb72
```

with the Google Stylechecker I get an error:

```
error  Put a nonbreaking space between the number and the unit in '041d'.  google.Units 
```

In my opinion URL string should be skipped everytime

**Comment by jouni** [comment]
In Asciidoc, we are also seeing that link urls are sometimes also checked:

```asciidoc
https://foo.com[Check this out]
```

That can trigger an error like `Did you really mean 'https'?`

**Comment by jdkato** [comment]
This issue is specifically about source code. 

The AsciiDoc link you've provided *shouldn't* be linted (see #320 for URL-related details), but it's possible that an ignore pattern or something else in the file is interfering.

Is the repo open source? If so, could you share your `.vale.ini` and the file in question?

**Comment by jouni** [comment]
Ah, right, apologies for mixing contexts. I didn’t pay attention to that detail, just latched onto “URL strings should be skipped every time”.

Yeah, our docs are open source ([.vale.ini](https://github.com/vaadin/docs/blob/latest/.vale.ini)). Here’s one specific case where `https` is unnecessarily marked as an error: https://github.com/vaadin/docs/pull/130/files#file-articles-ce-tutorial-asciidoc-L47

**Comment by jdkato** [comment]
Embedded markup will be supported in the next release.

**Comment by pt1961** [comment]
@jdkato, I followed this ticket from #320:

> There is currently no support for ignoring URLs in source code. https://github.com/errata-ai/vale/issues/249 tracks adding this feature.

Using the Google style, `vale` produces an error for a source code comment in C with a URL:

`// https://test.org/81d92baa`

```
error      Put a nonbreaking space         Google.Units
              between the number and the
              unit in '81d'.
```

Is there another ticket tracking progress for support for ignoring URLs in source code?

**Comment by jdkato** [comment]
This is possible if you use an embedded markup format that is already supported, as [shown here](https://github.com/errata-ai/vale/releases/tag/v2.19.0). There's no support for simply ignoring raw URLs.
