### ISSUE TITLE
Vale gives no feedback when specified config is missing

### ISSUE THREAD

**Issue by wouter-veeken** [vale-cli/vale#251]
To keep this very brief, when I run:

```
vale --debug --config="nonexistent.ini" README.md
```

and there is no `nonexistent.ini`, I expect Vale to either exit or at the very least provide some feedback that the file can't be found and it's falling back to the nearest `vale.ini`.

This is causing me problems because I'm creating containerized Vale tests for our internal GitLab instance. I'm providing a custom config which should override any `vale.ini` files already present in the repo. When Vale can't find my custom config in the GitLab runner environment for some reason (still figuring out why this happens in some runners), it silently falls back to the repo-native `vale.ini`, sending me up the garden path when debugging.

**Comment by jdkato** [comment]
Work related to improving error-handling is underway (#238). In a future version (probably the next one), you'll see an error message like the examples in the linked issue when this happens.

**Comment by wouter-veeken** [comment]
SGTM!
