### ISSUE TITLE
Unexpected/incorrect regex matching in ASCIIdoc only

### ISSUE THREAD

**Issue by wouter-veeken** [vale-cli/vale#255]
I have this rule:

```
extends: existence
message: "'%s': This punctuation should have no space before it, and 1 space after."
level: error
nonword: true
tokens:
  - '[^,]+ [,:;]'
  - '[,:;]{2,}[A-ÿ]'
  - '[,:;][A-ÿ]'
```

The rule is supposed to detect incorrect spacing around punctuation marks. Somehow the third pattern (`[,:;][A-ÿ]`) is matching against this:

```
Kajigger covers these use cases:

- *Kajigger now*: the more straightforward case when a pirate kajiggers immediately.
```

Vale's feedback:

```
3:1    error       ':`': This punctuation should   BEnglish.CommaSpacing
                    have no space before it, and 1
                    space after.
```

The stray backtick in the quoted part is probably a clue.

Good to know:
- When I remove the `:` in line 1, there is no longer a match on line 3.
- This only happens in ASCIIdoc. When I change the extension from `.adoc` to `.md`, Vale doesn't flag this line. My `vale.ini` uses the same settings for `.adoc` and `.md`.

Let me know if you need more info!

**Comment by jdkato** [comment]
Thanks for the report.

I'll look into this and try to fix it in the next release.

**Comment by jdkato** [comment]
I finally had a chance to look into this and I'm unable to reproduce the results. 

What version of Vale are you using? Are you able to produce the results using only the 3-line snippet above?

**Comment by jdkato** [comment]
@wouter-veeken: Is this still a problem for you?

**Comment by wouter-veeken** [comment]
@jdkato apologies for my slow response! Still an issue on vale version 2.6.2 I'm afraid. But there seems to be more to it in terms of the context in which this occurs. I want to keep the doc I'm working with intact so you can see exactly when/how this happens, but I can't share it here. Will contact you on Slack about this.
