### ISSUE TITLE
v2.5.1 Go installation fails

### ISSUE THREAD

**Issue by paddyroddy** [vale-cli/vale#256]
Go installation with latest version v2.5.1 doesn't work

![image](https://user-images.githubusercontent.com/15052188/97349399-57f11100-1887-11eb-9104-760997ac3266.png)

**Comment by jdkato** [comment]
The binaries are typically attached via Travis CI, but the build timed out for some reason. I restarted it and it completed, so this should be working now.

**Comment by paddyroddy** [comment]
yep all good
