### ISSUE TITLE
Is data kept local?

### ISSUE THREAD

**Issue by ggravlingen** [vale-cli/vale#257]
Running vale CLI version v2.5.1 on Linux Ubuntu 18.04 installed using the binary from Github.

I've been looking through the documentation and also searched the issues here on Github, but cannot find the answer to the question if anything is being sent from Vale to any servers outside of my environment? I've also monitored outbound traffic but it doesn't look like anything is being sent to any servers. Can you please confirm that my data is kept local?

**Comment by ChrisChinchilla** [comment]
@ggravlingen Everything is local, no processing happens on any servers, Vale is quite different from many other tools like it :)

**Comment by ggravlingen** [comment]
Great news, thank you for the quick reply!

**Comment by jdkato** [comment]
For the record, this is also true for Vale Server (which runs its server locally).
