### ISSUE TITLE
Feature request: Include link in output

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#260]
As per the first example you see at https://docs.errata.ai/vale/styles, we can include a `link: ` entry in a style YAML. I think it would be extremely useful to have an option to enable the output of that link in error messages.

So, for example, using our [Alert Box rule](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/AlertBoxStyle.yml):

```
 README.md
 21:1  error  Alert box " NOTE: **Note:** This alert box is not following standards." must use the formatting in the style guide.  gitlab.AlertBoxStyle 

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

Would instead look like:

```
 README.md
 21:1  error  Alert box " NOTE: **Note:** This alert box is not following standards." must use the formatting in the style guide.  gitlab.AlertBoxStyle 
 Link: https://docs.gitlab.com/ee/development/documentation/styleguide.html#alert-boxes

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

This could be turned on and off within individual rules, but I think the minimal solution would be to turn it on and off globally in the config file. Something like `OutputStyleLinks = true`?

**Comment by Ravlen** [comment]
@jdkato WDYT? I think this suggestion would be useful for everyone, not just GitLab 😅

**Comment by jdkato** [comment]
There have been a number of requests to make minor adjustments to existing output formats and my response has typically been to repurpose the JSON output -- such as shown in https://github.com/errata-ai/vale/issues/232#issuecomment-685836520.

However, I've recently had the idea of introducing an `--output=custom` option that makes uses of Go's [template](https://golang.org/pkg/text/template/) library. 

I think this will address all of these issues in a fairly straightforward and useful way: You'll have template-level access to the entire slice of Alerts while being able to make use of the built-in utility functions (such as the coloring, underlining, etc.).

**Comment by jdkato** [comment]
Custom output formats are now available on master, but I'd like to dicuss the implementation a little before releasing. The syntax will problably seem familiar if you've used Hugo (or Go templating in general).

- The format requested in #232 could now be implemented with the following template (`line.tmpl`):
 
    ```
    {{- range . -}}
      {{- .Path}}:{{.Line}}:{{index .Span 0}}:{{.Check}}:{{.Severity}}:{{.Message}}
    {{end -}}
    ```
    ```console
    $ vale --output='line.tmpl' file.md
    test.md:3:1:vale.Annotations:suggestion:'NOTE' left in text
    ```
- The format requested in this issue is possible with something like the following (`cli.tmpl`):

    ```
    {{- $e := 0 -}}
    {{- $w := 0 -}}
    {{- $s := 0 -}}
    {{- $f := 0 -}}
    
    {{$last := ""}}
    {{- range $index, $alert := . -}}
    
    {{- $error := "" -}}
    {{- if eq .Severity "error" -}}
        {{- $error = .Severity | red -}}
        {{- $e = add $e 1 -}}
    {{- else if eq .Severity "warning" -}}
        {{- $error = .Severity | yellow -}}
        {{- $w = add $w 1 -}}
    {{- else -}}
        {{- $error = .Severity | blue -}}
        {{- $s = add $s 1 -}}
    {{- end}}
    
    {{- if ne $alert.Name $last -}}
    {{$last = $alert.Name}}
     {{$f = add $f 1}}
     {{$alert.Name | underline}}
    {{- end}}
     {{.Line }}:{{index .Span 0}}<align>{{$error}}<align>{{.Message}}<align>{{.Check}}
     Link: {{.Link}}
    {{end}}
    {{$e}} {{"errors" | red}}, {{$w}} {{"warnings" | yellow}} and {{$s}} {{"suggestions" | blue}} in {{$f}} files.
    ```

    ```console
    $ vale --output='cli.tmpl' test.md
     test.md
     1:24	error	Use 'Web source' instead of 'Web Source'.	Test.rule
     Link: example.com

     1 error, 0 warnings and 0 suggestions in 1 files.
    ```

Thoughts @Ravlen, @nostodnayr?

**Comment by nostodnayr** [comment]
@jdkato This is fantastic. Thank you! :tada: Removing the scripting language dependency makes a big difference for us. I think it'll make it easier once we're ready to start pushing vale into other parts of the company. For them, they can have the output where and how they want, but for me, it's easier to maintain a few templates.

I'm passingly familiar with Go's templating, though I'll soon know a lot more, I wager. 😆 In `cli.tmpl`, `$f` increments by the number of alerts, not files. Is there an 'outer' file loop missing?

**Comment by jdkato** [comment]
> In cli.tmpl, $f increments by the number of alerts, not files. Is there an 'outer' file loop missing?

This was a typo. If you move `{{$f = add $f 1}}` under `{{$last = $alert.Name}}`, it should work as expected (now updated above).

**Comment by jdkato** [comment]
I've released an initial version of this. The data structure has changed slightly from the example above&mdash;here's the equivalent `line` output template:

```
{{range .Files}}
{{- $path := .Path -}}
{{- range .Alerts -}}
{{$path}}:{{.Line}}:{{index .Span 0}}:{{.Check}}:{{.Severity}}:{{.Message}}
{{end -}}
{{end -}}
```
The CLI version is shown in the [release notes](https://github.com/errata-ai/vale/releases/tag/v2.6.0).

**Comment by Ravlen** [comment]
@jdkato Wow, that was fast! We saw your comment about using using a python script, and got it working in our project (https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46725). Since we are heavily Ruby-based, one of our team members rewrote it in Ruby:

```ruby
#!/usr/bin/env ruby
#
# Get the JSON output from Vale and format it in a nicer way
# See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46725
#
# Usage:
#   vale --output=JSON filename.md | ruby vale.rb
#

require 'json'

input = ARGF.read
data = JSON.parse(input)

data.each_pair do |source, alerts|
  alerts.each do |alert|
    puts "#{source}:"
    puts " Line #{alert['Line']}, position #{alert['Span'][0]} (rule #{alert['Check']})"
    puts " #{alert['Severity']}: #{alert['Message']}"
    puts " More information: #{alert['Link']}"
    puts
  end
end
```

I didn't merge the code yet, as I wanted everyone to double check it... Now that this is available, I'll try it out and see what works best, thanks so much!

**Comment by jdkato** [comment]
If you're already familiar with a scripting language (and the extra dependency isn't a problem), then that's probably a better way to go, IMO.

Go's templating can be a little unusual if you're not used to it.

**Comment by Ravlen** [comment]
@jdkato Yeah, our linting image already has ruby installed, but not python, so it makes perfect sense to go with ruby for this. Ref: https://gitlab.com/gitlab-org/gitlab-docs/container_registry/eyJuYW1lIjoiZ2l0bGFiLW9yZy9naXRsYWItZG9jcy9saW50IiwidGFnc19wYXRoIjoiL2dpdGxhYi1vcmcvZ2l0bGFiLWRvY3MvcmVnaXN0cnkvcmVwb3NpdG9yeS8xMzEzMDUwL3RhZ3M%2FZm9ybWF0PWpzb24iLCJpZCI6MTMxMzA1MCwiY2xlYW51cF9wb2xpY3lfc3RhcnRlZF9hdCI6bnVsbH0=
