### ISSUE TITLE
<!-- vale off --> doesn't work inside a block element

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#261]
Vale 2.5.1

Not sure if this is expected but `<!-- vale off -->` used inline doesn't turn off processing for the span of text. I'd prefer to use that rather than 'comment out' an entire paragraph.

**Comment by jdkato** [comment]
This is indeed intended behavior.

You can, however, make the comment more specific by targeting a particular rule -- e.g., `vale Style.Rule = NO`.

**Comment by nostodnayr** [comment]
Right, we were just looking for a quick on/off switch if possible without going to the specific rule. (Which also only works at a block-level.) Understandable. Thanks for the feedback as always. :-)
