### ISSUE TITLE
Regex across line break does not match indented blocks

### ISSUE THREAD

**Issue by TortillaDoc** [vale-cli/vale#262]
- OS Windows 10
- Install method Chocolatey
- Vale version 2.5.0

Given is this YAML style:
```
extends: substitution
message: Consider using '%s' instead of '%s'
level: warning
ignorecase: false
swap:
  a[\n\r\s]+b: A B
```
And a Markdown file with this content:
```
1: a b

2: a
b

  3: a b
  
  4: a
  b

```
The vale output is:
```
PS C:\Work\vale> vale TestMe.md

 TestMe.md
 1:4  warning  Consider using 'A B' instead    Test.Substitution
               of 'a b'
 3:4  warning  Consider using 'A B' instead    Test.Substitution
               of 'a b'
 6:6  warning  Consider using 'A B' instead    Test.Substitution
               of 'a b'

✖ 0 errors, 3 warnings and 0 suggestions in 1 file.
```
Examples 1-3 in the Markdown file trigger the rule as expected. Example 4, where the block is indented *and* has a line break between a and b, does not. What could be the reason for this behavior? 

Cross-checking this with https://regoio.herokuapp.com/ seems to confirm that at least the regex is correct:
![rego](https://user-images.githubusercontent.com/37544914/98162269-6a9bc380-1ee1-11eb-8e58-7a6780a832cd.png)

Unfortunately, this is a showstopper for us since indentation is a common feature in Markdown, and we break long lines for better readability in editors.

Any hints?

**Comment by jdkato** [comment]
By default, Vale doesn't operate the raw markup content itself; it uses an HTML-based, AST-like data structure that allows its styles to be compatible across many markup formats, but naturally doesn't preserve whitespace. See https://github.com/errata-ai/vale/issues/196#issuecomment-620230303 for more information.

You can disable this functionality by using [`scope: raw`](https://docs.errata.ai/vale/scoping#markup), which will give your expected results in this case. 

The need to do this should be rare (especially if you're not targeting markup-specific syntax), though. If you have a less contrived example, I may be able to provide more specific advice.

**Comment by TortillaDoc** [comment]
> You can disable this functionality by using [`scope: raw`](https://docs.errata.ai/vale/scoping#markup), which will give your expected results in this case.

Thanks, that solved my issue 😃
