### ISSUE TITLE
BlockIgnore for accross multiple blocks

### ISSUE THREAD

**Issue by flashpixx** [vale-cli/vale#263]
I'm using Vale 2.5.1 and this is my vale.ini

```
StylesPath = style
MinAlertLevel = warning

[*.{go,py,java,js,jsx,tex}]
BasedOnStyles = proselint, write-good, google
BlockIgnores = (?s) *(ValeOFF.*?/ValeOFF)

[README.md]
BasedOnStyles = proselint, write-good, google
```

but my BlockIgnores is not working and my goal is to ignore multiple comment blocks. This is the file structure as example for Python:
```
import

# ValeOff

""" a 
long 
description
"""

def ABCD()
     r"""
     comment
     """"
# a long line comment


# /ValeOFF
```

So is it possible to ignore everything between `ValeOFF` and `/ValeOFF`? I have also C, Java, JS, JSX, TeX, and Go files, which should use the same ignore pattern.

**Comment by jdkato** [comment]
This is effectively the same issue as #209: currently comment-based configuration and `IgnorePatterns` are only available for `markup` files (not `code`).

This is something that I'd like to work on soon.
