### ISSUE TITLE
Regular expressions in substitutions are always case-sensitive

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#264]
Vale 2.6.1

In a rule that's `ignorecase: true`, I would expect regular expressions in replacements to also be case-insensitive.

## Example

Input:  `Select the Provision Manager and click Update Group Members.`
Caught by this rule:

```
level      : error
message    : Use "group member", "family member", or "team member".
link       : https://support.1password.com/style-guide/#member

extends: substitution
ignorecase: true

swap:
  '(?:[^\s]*) members?': '(?:group|family|team) members?'
```

I'm working around this for now with `(?i)` prepended to the replacement value.

**Comment by jdkato** [comment]
This is a regression related to 9d2784471edbd40d72cb396da0e7477308e84197. It'll be fixed in the next release.
