### ISSUE TITLE
`vale tag` command not working in builds after 2.5.1

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#265]
The `tag` command stopped working in the Vale 2.5.1 release. This persists in 2.6.1.

If you use it with no configuration file present, it fails with an error. If Vale finds a configuration file, it gives you a sham lint on stdin.

```
~ $ vale25 tag "These are words to make a sentence."
These/DT are/VBP words/NNS to/TO make/VB a/DT sentence/NN ./.
```

```
~ $ vale251 tag "These are words to make a sentence."

E100 [.vale.ini] Runtime error

open : no such file or directory

Execution stopped with code 1.
```

```
~/has-config $ vale251 tag "These are words to make a sentence."

✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```

**Comment by jdkato** [comment]
Thanks for the report.

This should have been mentioned in the release notes, but the core of this functionality has moved to the [newly-released rule editor](https://vale-studio.errata.ai/) (which addresses the limitations mentioned in #237 with `tag`).
