### ISSUE TITLE
Minor bug in example template

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#269]
In the example at https://docs.errata.ai/vale/cli#template-examples, the final line seems to be outputting the number of files that had an alert at error/warning/suggestion level. When I run the example template with 1300'ish files, (and one set to fail during testing), I get:

```
1 errors, 0 warnings and 0 suggestions in 1 file.
```

If no files fail, it says `0 files`. Seems that the `$f` variable is only incrementing when an alert is thrown... or maybe `.Files` is only returning files with alerts? It's a very minor thing, and we've still switched to using a template, but might as well point it out. cc @jdkato

**Comment by jdkato** [comment]
> `.Files` is only returning files with alerts?

This indeed seems to be the case.

**Comment by jdkato** [comment]
This will be fixed in the next release, but it'll probably be a few days. I want to make sure I get it right + fix #267 before releasing.

**Comment by Ravlen** [comment]
@jdkato No worries, take your time to make sure you got it right, we are in no rush!

**Comment by Ravlen** [comment]
@jdkato Actually, I mentioned the problem to a co-worker, who mentioned it to another co-worker, who opened a PR to try to fix it for the technical writing team 😅  https://github.com/errata-ai/vale/pull/270
