### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#27]
This line 

https://travis-ci.org/writethedocs/www/builds/212845872#L253

contains `warningm` which looks like it could a parsing bug somewhere.

**Comment by jdkato** [comment]
When I look at that line on Travis CI, I see:

```
54:37  warning  Consider removing 'just'  WTD.Just 
```

At 54:37 in `conf/speaking.md`, I see:

```
* Have a PDF backup of your slides, just in case :)
```
Am I missing something?

**Comment by plaindocs** [comment]
Odd. Some glitch in the matrix then. Closing.
