### ISSUE TITLE
Quad backticks in markdown shifts the result numbers

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#271]
Very minor issue, but if you are using quad backticks in a markdown file (so that you can have triple backticks render in a code block), it shifts the results off by one character (sometimes one word) for each quad backtick pair.

So, for example, with a rule looking for the word "easy", each quad backtick shifts the results left (it's the same in CLI):

<img width="843" alt="Screen Shot 2020-11-16 at 15 48 41" src="https://user-images.githubusercontent.com/36979740/99221117-5467fe80-2823-11eb-8249-012e52aa13bc.png">

From:

`````
This is how to write a CI YAML code block:

````markdown
```yaml
job:
  script:
    - echo "Wow"
```
````

Another easy example:

````markdown
```yaml
job:
  script:
    - echo "Wow"
```
````

Was that easy?
`````

It's written that way, so that the triple backticks render properly, for example:

This is how to write a CI YAML code block:

````markdown
```yaml
job:
  script:
    - echo "Wow"
```
````

Another easy example:

````markdown
```yaml
job:
  script:
    - echo "Wow"
```
````

Was that easy?

cc @jdkato

**Comment by jdkato** [comment]
This will be fixed in the next release.

**Comment by Ravlen** [comment]
@jdkato Thank a ton!
