### ISSUE TITLE
Exclusions don't seem to work properly in scope: raw

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#272]
Another minor bug, but it seems like exclusions don't work as expected for rules using `scope: raw`. I can add the standard exclusions for all of our rules that *don't* use `scope: raw`, but none of the rules that DO use it can't be excluded properly.

See how the first rule gives suggestions, then within the exclusion block it does not. Then the second rule (which uses `scope: raw` does not exclude the alert:

<img width="588" alt="Screen Shot 2020-11-16 at 16 00 34" src="https://user-images.githubusercontent.com/36979740/99221980-fb00cf00-2824-11eb-81b5-90e9ee55259b.png">

The weird thing is that if you forget to add the second line (to re-enable the rule), it then excludes the rule from the entire file, including lines BEFORE the exclusion. Non-`scope: raw` rules work as expected, only excluding everything after the exclusion line:

<img width="875" alt="Screen Shot 2020-11-16 at 16 03 54" src="https://user-images.githubusercontent.com/36979740/99222232-78c4da80-2825-11eb-8ae5-d99b79b5d449.png">

cc @jdkato

**Comment by jdkato** [comment]
This is the same issue as #194: any HTML-related scoping / configuration features aren't compatible with `scope: raw` (this includes HTML comments, `BlockIgnores`, `TokenIgnores`, `IgnoredClasses`, and `SkippedScopes`).

> The weird thing is that if you forget to add the second line (to re-enable the rule), it then excludes the rule from the entire file, including lines BEFORE the exclusion. 

It's not clear to me what's happening here since this shouldn't be related to ignore comments (as mentioned above). Is it possible that the comment placement is interfering with the rule's regex?

**Comment by Ravlen** [comment]
@jdkato Ahh, when it started to work partially (when I added the first line), I thought you might have implemented it and I just missed it in a minor release or something.

It's definitely not being caught by the regex, I think. I changed the regex to be just `Internal`, and the behavior is the same. Add the exclusion start, and it's turned off for the whole page. Add the exclusion end, and it's as if there is no exclusion at all.

<img width="701" alt="Screen Shot 2020-11-18 at 15 57 57" src="https://user-images.githubusercontent.com/36979740/99496041-ed7b4e80-29b6-11eb-860e-319048454b7b.png">

<img width="701" alt="Screen Shot 2020-11-18 at 15 58 06" src="https://user-images.githubusercontent.com/36979740/99496145-126fc180-29b7-11eb-975e-59f809eacecb.png">

**Comment by jdkato** [comment]
Could you share the `gitlab.InternalLinkExtension` rule?

**Comment by Ravlen** [comment]
@jdkato Whoops, missed the ping. Here you go (from: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/InternalLinkExtension.yml):

```yaml
extends: existence
message: 'Link "%s" must use the .md file extension.'
link: https://docs.gitlab.com/ee/development/documentation/styleguide.html#links-to-internal-documentation
level: error
scope: raw
raw:
  - '\[.+\]\((https?:){0}[\w\/\.-]+(\.html).*?\)'
```

It was written a while back, and we've learned a lot more about Vale since then, it's very possible we're doing something that we shouldn't. Still, I tested it by removing all the regex and just looking for a single word in a `scope: raw` rules, and saw the same behavior. For example:

```yaml
extends: existence
message: 'Don't use within.'
level: error
scope: raw
raw:
  - 'within'
```

- <img width="474" alt="Screen Shot 2020-12-01 at 8 48 25" src="https://user-images.githubusercontent.com/36979740/100679163-3b7a5400-33b2-11eb-9cd8-1a71f9c549d6.png">
- <img width="474" alt="Screen Shot 2020-12-01 at 8 49 39" src="https://user-images.githubusercontent.com/36979740/100679191-4d5bf700-33b2-11eb-8504-2da01d5a3310.png">
- <img width="474" alt="Screen Shot 2020-12-01 at 8 51 28" src="https://user-images.githubusercontent.com/36979740/100679256-71b7d380-33b2-11eb-8f82-cc376c802ad9.png">

**Comment by jdkato** [comment]
This has been fixed in the sense that ignore comments will now (correctly) not effect `scope: raw` rules, but the limitations mentioned in https://github.com/errata-ai/vale/issues/272#issuecomment-728248444 still apply.
