### ISSUE TITLE
Attempt to parse .travis.yml as a rule file since version 2.4.1

### ISSUE THREAD

**Issue by sethfischer** [vale-cli/vale#273]
This issue notes a change in behaviour between vale version 2.4.0 and version 2.4.1. The change in behaviour persists to the latest version 2.6.3.

- OS: Linux Ubuntu 20.04
- Install method: download `*_Linux_64-bit.tar.gz` from https://github.com/errata-ai/vale/releases
- Vale version: >2.4.0

When [errata-ai/Google](https://github.com/errata-ai/Google) is included in a project as a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), versions >2.4.0 attempt to parse `Google/.travis.yml` as a rule file.

`.gitmodules` is created with `git submodule add https://github.com/errata-ai/Google styles/Google`:

```ini
[submodule "styles/Google"]
    path = styles/Google
    url = https://github.com/errata-ai/Google.git
```

`.vale.ini`:

```ini
StylesPath = styles

[*.rst]
BasedOnStyles = Vale, Google
```

Test document `document.rst`:

```rst
===============
A test document
===============

A paragraph with a spellling error.
```

Vale version 2.4.0 produces the following output:

    $ vale --version
    vale version 2.4.0
    $ vale document.rst

    document.rst
    5:20  error  Did you really mean             Vale.Spelling
                'spellling'?

    ✖ 1 error, 0 warnings and 0 suggestions in 1 file.

Vale version 2.4.1 to 2.6.3 produce the following output:

    $ vale --version
    vale version 2.6.3
    $ vale document.rst
    E201 Invalid value provided [/path/to/project/styles/Google/.travis.yml:1:1]:

    1* language: python
    2  cache: bundler
    3  python:

    Missing the required 'extends' key.

    Execution stopped with code 1.

It appears that from version 2.4.1 vale attempts to parse `.travis.yml` as a rule file.

Being able to include a style as a Git submodule has the advantages:

1. All project users are locked to the same version.
2. There is a clear history of what version of the style was being used at any point in time.
3. When changes are pushed to the upstream style, the changes to the Git submodule do not need to immediately follow.

What is the expected behaviour?

**Comment by jdkato** [comment]
Two points:

- `errata-ai/Google` is technically an invalid `StylesPath` entry; the `Google` subdirectory (`errata-ai/Google/Google`) is the actual style. This subdirectory is provided as a versioned release asset named `Google.zip`.

- This has always been the case but, prior to v2.4.1, Vale would ignore invalid entries. And, although this behavior was useful in this specific scenario, I think it was undesirable at best (and was seen as a bug by many) in almost every other situation.

So, I'd say that the post-2.4 behavior is "expected" and makes it much easier to debug misbehaving styles and rules.

That said, I  think there are at least two possible solutions here:

1. You could set `StylesPath = styles/Google`.

2. You could maintain your `styles` directory as its own repo and then include *that* as a submodule.

**Comment by sethfischer** [comment]
Thanks @jdkato
