### ISSUE TITLE
proof format of captions (table and figure)

### ISSUE THREAD

**Issue by stalsma** [vale-cli/vale#274]
I searched the docs and all issues, big didn't find mention of proofing captions.  I have a requirement that table and figure captions should be labelled, numbered, and described.

> Table 2: Additional Resources
> Figure 1: Diagram showing....

I was expecting to find something under scope (_table.caption_, or _figure.caption_).  Is there a way of targeting specific HTML tags?  Looks like _figure_ may be entirely excluded anyway.

**Comment by jdkato** [comment]
As you suspected, this isn't currently supported.
