### ISSUE TITLE
Inconsistent message for extends: substitution

### ISSUE THREAD

**Issue by ghost** [vale-cli/vale#275]
- OS: Windows 10
- Install method: Download
- Vale version: 2.6.3

* Full test environment: <https://github.com/dfinr/vale-test-cases/tree/main/multiple%20substitutions>
* Markdown test file: <https://github.com/dfinr/vale-test-cases/blob/main/multiple%20substitutions/testMarkdown.md>
* Style rule: <https://github.com/dfinr/vale-test-cases/blob/main/multiple%20substitutions/.vale/MyRules/Substitutions.yml>

## Issue

The message uses the word `or` in two cases, and the pipe symbol in one case.

## Command-line Test
```
PS > .\vale --output line .\testMarkdown.md

.\testMarkdown.md:3:15:MyRules.Substitutions:Use 'import or load' instead of 'ingest'.
.\testMarkdown.md:3:48:MyRules.Substitutions:Use 'import|load' instead of 'ingest'.
.\testMarkdown.md:5:8:MyRules.Substitutions:Use 'import or load' instead of 'ingest'.
```

## Vale Studio
This test is also reproducible on Vale Studio.
<https://vale-studio.errata.ai/>

![image](https://user-images.githubusercontent.com/61550036/100010113-c5686280-2d9d-11eb-92d1-4c4cd53cff5a.png)

**Comment by jdkato** [comment]
Thanks for the detailed report. This should be fixed in the next release.
