### ISSUE TITLE
strangeness with conditional regex; \d finds '0,1,3,4,6,7,9', but not '2,5,8'

### ISSUE THREAD

**Issue by stalsma** [vale-cli/vale#277]
vale v2.6.2. via homebrew on macOS

I'm trying to implement what I thought would be a simple rule:
> Spell out numbers under 10.
Exceptions:
> Use numerals to write about money, pages, percentages, measurement or time (age, weeks, months, years, hours)

B/c the `substitution` extension point doesn't allow exceptions, I went with a conditional.

```
extends: conditional
message: "Spell out numbers under 10. Found digit '%s'"
ignorecase: true
level: suggestion
scope: sentence
# capture single digit, followed by opt. :.-[digits] (so decimal nrs, time rages, time of day); we filter them later
first: '\b(\d(?:[:\-\.]\d+)?)\b'
# if we only have a single digit, then there is a list of permitted units
second: '\b(\d)\b\s+(?:diabetes|percent|am|pm|weeks|months|years|hours|pages|cm|mm|g|kg)'
exceptions:
  # permit times (x:yy), ranges (x-y), and floats (x.yz)
  - '\b\d+[:\-\.]\d+\b'
```

The rule almost works,. but it doesn't find 2, 5, or 8. The regexp works when I test it externally (https://regoio.herokuapp.com).  But not in the context of Vale

Test input:
```
<p>Test it 0 times.</p>
<p>Test it 1 time.</p>
<p>Test it 2 times.</p>
<p>Test it 3 times.</p>
<p>Test it 4 times.</p>
<p>Test it 5 times.</p>
<p>Test it 6 times.</p>
<p>Test it 7 times.</p>
<p>Test it 8 times.</p>
<p>Test it 9 times.</p>

3:30
1-2
1.2
1.25
```

Output
```
 212:12   suggestion  Spell out numbers under 10. Found digit '0'                                                                                                     
 213:12   suggestion  Spell out numbers under 10. Found digit '1'                                                                                                     
 215:12   suggestion  Spell out numbers under 10. Found digit '3'                                                                                                     
 216:12   suggestion  Spell out numbers under 10. Found digit '4'                                                                                                     
 218:12   suggestion  Spell out numbers under 10. Found digit '6'                                                                                                     
 219:12   suggestion  Spell out numbers under 10. Found digit '7'                                                                                                     
 221:12   suggestion  Spell out numbers under 10. Found digit '9'  
```

**Comment by ChrisChinchilla** [comment]
Hey @stalsma I don't know if a pre-existing rule such as this (https://github.com/testthedocs/JQuery/blob/master/JQuery/Numbers.yml) helps you start?

**Comment by stalsma** [comment]
Perhaps I was unclear w my description.  The behavior above is what _IS_ happening. I need to find all digits.

**Comment by jdkato** [comment]
First of all, it's not clear to me what markup format you're using; the example snippet seems to be an unusual mix of plain text and HTML.

Assuming it's Markdown, your rule works for me: it finds the intended digits (including 2, 5, and 8). This leads me to believe that there's something else in your file that is relevant here -- it appears to be over 200 lines?

**Comment by stalsma** [comment]
You're correct in that the html file is fairly long.  It is basically a single file I using to develop a list of rules.

Based on your tip, I started deleting everything that came before the section of the test, and it found all my digits.  What is happening is that the rule gets hung up on a `<link` tag for an external stylesheet in the header.  Despite the scope being set to `sentence`, none of the instances in the body get found.

Here's a test file:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Style Testbed</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  crossorigin="anonymous">
</head>
<body>

<h1>Numbers, Dates, Percentages, &amp; Time</h1>

<h2>Incorrect Examples</h2>

<p>Test it 0 times.</p>

<p>Test it 0 times.</p>

</body>
</html>
```

And the output where the 0 is found in the header, but not the body:

```
vale --output=line StyleTester-dup.html               
StyleTester-dup.html:5:78:palmettoGBA.Numbers:Spell out numbers under 10. Found digit '0'
```

Is this expected behavior?  I changed the scope to `paragraph', and alternatively, removed it entirely, but the result is the same.

**Comment by jdkato** [comment]
This also is not reproducible for me:

```console
$ vale test.html
 test.html
 13:12  suggestion  Spell out numbers under 10.     Test.rule 
                    Found digit '0'                           
 15:12  suggestion  Spell out numbers under 10.     Test.rule 
                    Found digit '0'                           
```
But I do have some general thoughts:

1. You should only use fine-grained scopes like `sentence` or `paragraph` for rules that require information specific to that scope (e.g., sentence length). Otherwise, you'll incur the performance overhead for no reason.

2. Make sure your HTML is valid (your first code snippet was not valid HTML). There are many online or CLI validators you can use.
