### ISSUE TITLE
Extension based configuration for non-markup files

### ISSUE THREAD

**Issue by DevinCodes** [vale-cli/vale#280]
First of all, thank you so much for creating and maintaining Vale! It's been a breeze so far to implement it, and I'm impressed by the ecosystem built around it. Keep it up! 🎉 

In our project, we have different YAML files that (may) contain markdown. To let Vale parse the YAML as Markdown, we've added `yml = md` to the `[formats]` section in the Vale configuration.

However, we've come across the need to disable specific rules _only_ for the YAML files, and not for the Markdown files. I was wondering if it's possible to do something like this in the `_vale.ini`:

```ini
[formats]
yml = md

[*.md]
BasedOnStyles = Vale, Algolia

[*.yml]
BasedOnStyles = Vale, Google
Google.Colon = NO

```

I've tried this locally, but it seems that the `yml=md` line under `[formats]` causes Vale to interpret YAML as Markdown files even when it comes to applying file specific rules. Is this indeed the case?

If this is not possible to do, is there a workaround to achieve the same (besides using 2 different configuration files)?

Thank you in advance for the reply, please let me know if you need more information. And thank you again for your work on this 🙌

**Comment by jdkato** [comment]
I'm glad you're enjoying Vale so far.

> In our project, we have different YAML files that (may) contain markdown. To let Vale parse the YAML as Markdown, we've added `yml = md` to the `[formats]` section in the Vale configuration.

This is a misuse of the `[formats]` option. Its intended purpose is to allow you to associate a file extension that Vale doesn't recognize with a recognized extension.

In other words, `ext1 = ext2` needs to be true from a syntactic perspective. This isn't the case for *Markdown* and a *YAML file with embedded Markdown*; the latter is still a *YAML* file and you won't receive the expected results by associating it with Markdown.

My suggestion here is to take one of two approaches:

1. Use a script to parse your YAML files and specifically pass the values with Markdown-formatted content to Vale. This can be done through `stdin` using the `--ext='.md'` flag.

2. Generate your YAML files from already-linted Markdown files. The feasibility of this approach depends on your specific case, but I think it's much easier to maintain Markdown content when it's not embedded in another file type. I've written more about this approach here: https://gist.github.com/jdkato/156944741f134dca3d0a18dafcfa9803.

> I've tried this locally, but it seems that the `yml=md` line under `[formats]` causes Vale to interpret YAML as Markdown files even when it comes to applying file specific rules. Is this indeed the case?

Yes, this is currently the case.

**Comment by jdkato** [comment]
I'm marking this as resolved, but feel free to comment further if needed.

**Comment by DevinCodes** [comment]
Thank you for the reply! I'll look into the approaches you proposed to see which one works best for our use case!
