### ISSUE TITLE
Thoughts about improving error handling

### ISSUE THREAD

**Issue by amotl** [vale-cli/vale#284]
Dear Joseph,

first things first: Thanks a stack for conceiving and maintaining this fabulous tool. You are doing an excellent job here.

## Introduction
I am a first-time user of Vale coming here from [1] conceived by @mechanomi and currently work on https://github.com/crate/crate-docs/pull/42 and https://github.com/crate/crate-docs/pull/43. So, please apologize if I am getting something wrong.

As we are currently upgrading from Vale 1.4.2 to Vale 2.6.5, I believe it would be a good idea to share some of our observations with you.

[1] https://github.com/crate/crate-docs

## Error message when configuration file is missing
With Vale 1.4.2, the message was
```
WARNING: Missing or invalid config file.

See https://github.com/errata-ai/vale#usage for information about creating a config file.
```

With Vale 2.6.5, the message is
```
E100 [.vale.ini] Runtime error

open : no such file or directory

Execution stopped with code 1.
```

Maybe you want to restore the message like it was with Vale 1.x. The message _Missing or invalid config file_ as well as directly referring to the documentation makes things a bit more clear to the user. As this program is about clear and concise language in general, I hope this reasoning will resonate with you.

## Error reporting with empty or missing `StylesPath`
This report is exclusively about Vale 2.6.5. I didn't check how the situation was with Vale 1.4.2.

1. So, everything is fine when using a minimal configuration file like
   ```
   StylesPath = "styles"

   [*]
   BasedOnStyles = proselint, write-good
   ```

2. When using a configuration file like
   ```
   StylesPath = "styles"

   [*]
   BasedOnStyles = foobar
   ```
   Vale croaks as expected:
   ```
   E100 [loadStyles] Runtime error

   style 'foobar' does not exist on StylesPath

   Execution stopped with code 1.
   ```

3. Also, when configuring an invalid `StylesPath`, Vale croaks appropriately:
   ```
   E201 Invalid value provided [vale.test.ini:1:15]:

      1* StylesPath = "styles"
      2

   The path 'styles' does not exist.

   Execution stopped with code 1.
   ```

4. However, when omitting the `StylesPath` setting like
   ```
   [*]
   BasedOnStyles = proselint, write-good
   ```
   Vale silently skips this misconfiguration and will report
   ```
   ✔ 0 errors, 0 warnings and 0 suggestions in stdin.
   ```
   without signalling any error or warning whatsoever and exits with return code `0`.

5. The same happens when omitting the `StylesPath` setting and configuring an invalid style like
   ```
   [*]
   BasedOnStyles = foobar
   ```

I believe that is an important detail which might be improved in order to prevent users accidentally tripping into this. I have been running into it before knowing anything about Vale and assuming that the configuration file [2] would actually have been valid. In turn, while it pretended to be valid, Vale did not apply any style checks at all and did not even warn about that the configured styles would not exist on the (unconfigured) `StylesPath`.

I hope my report helps in order to slightly improve the quality of this program.

Keep up the spirit and with kind regards,
Andreas.

[2] https://github.com/crate/crate-docs/blob/0.4.0/src/_vale.ini

**Comment by amotl** [comment]
Hi again,

> I didn't check how the situation was with Vale 1.4.2.

I checked again using Vale 1.4.2. And indeed, a minimal configuration file like
```
[*]
BasedOnStyles = proselint, write-good
```
works without further ado. So, our `_vale.ini` [2] was correct when using Vale 1.4.2.

I figure that Vale 1.x apparently was able to use some built-in styles while Vale 2.x would not include them or is just not able to address them properly? Maybe I am missing some configuration trick in order to let `StylesPath` address the styles already shipped with the Vale distribution binary?

With kind regards,
Andreas.

[2] https://github.com/crate/crate-docs/blob/0.4.0/src/_vale.ini

**Comment by ChrisChinchilla** [comment]
Hey @amotl :👋. I used to work for Crate ;)

This is a fair jump in version change, but yes you're kind of on the right path, Vale used to ship with some inbuilt styles, but no longer does.

With regards to point 5 of your main comment (https://github.com/errata-ai/vale/issues/284#issue-759846914) I have experienced this issue myself, i thought this had been resolved myself, and it came up a couple of times in our user testing sessions, so I'll wait for @jdkato to ship in on that one.

**Comment by amotl** [comment]
Dear Chris,

> I used to work for Crate ;)

Cheers! ;]

> Vale used to ship with some inbuilt styles, but no longer does.

Thanks for confirming this. We addressed that within https://github.com/crate/crate-docs/pull/43.

> With regards to point 5 of your main comment, it came up a couple of times in our user testing sessions, so I'll wait for @jdkato to ship in on that one.

Thanks! I believe adding a sanity check for cases 4. and 5. would be very important. On both cases, Vale should croak like
```
E100 [loadStyles] Runtime error

style 'XYZ' does not exist on StylesPath

Execution stopped with code 1.
```

With kind regards,
Andreas.

**Comment by jdkato** [comment]
The changes between v1 and v2 were described here: https://github.com/errata-ai/vale/releases/tag/v2.0.0.

Error handling has improved dramatically since v1 (and even more so recently, #238), but there are indeed still cases that need to be caught or could be improved.

**Comment by jdkato** [comment]
Cases (4) and (5) are now correctly caught.

**Comment by amotl** [comment]
Hi Joseph,

b0e576c7 looks good, thank you very much for this improvement.

With kind regards,
Andreas.
