### ISSUE TITLE
Panic error in Vale related to Vocab accept.txt

### ISSUE THREAD

**Issue by ghost** [vale-cli/vale#287]
## Summary

The Markdown file `testPanic.md` causes Vale to error with `panic: runtime error: index out of range [1] with length 1`

## Environment

- OS: Windows 10
- Install via: Chocolatey
- Vale version: 2.6.4
- Run under PowerShell

## Test Case
Full test environment: <https://github.com/dfinr/vale-test-cases/tree/main/heading%20panic%20error>

* `test.md` contains **pizza-pizza** in heading. 
* `testPanic.md` contains **hubba-hubba** in heading. 
* The term **hubba** appears in Vocab accept.txt:  `.vale/Vocab/MyRules/accept.txt`

**Note:**  Removing **hubba** from Vocab accept.txt resolves the error.

Correct test result for `test.md`:

    PS > vale .\test.md

     .\test.md
     1:4  error  Heading level two should use    MyRules.HeadingsH2
             title case.

    ✖ 1 error, 0 warnings and 0 suggestions in 1 file.

Panic test result for `testPanic.md`:

    PS > vale .\testPanic.md
    panic: runtime error: index out of range [1] with length 1

    goroutine 54 [running]:
    github.com/errata-ai/vale/v2/check.title(0xc000c25250, 0xb, 0xc0002b2070, 0x1, 0x1, 0xc00008aa80, 0xc000006568, 0xc976a0)
        /home/travis/gopath/src/github.com/errata-ai/vale/check/variables.go:42 +0x31c
    github.com/errata-ai/vale/v2/check.NewCapitalization.func3(0xc000c25250, 0xb, 0xc0002b2070, 0x1, 0x1, 0xc00008aa80, 0xc000356750)
        /home/travis/gopath/src/github.com/errata-ai/vale/check/capitalization.go:64 +0x6d
    github.com/errata-ai/vale/v2/check.Capitalization.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000c249a0, 0xe, 0xc000c249c8, ...)
        /home/travis/gopath/src/github.com/errata-ai/vale/check/capitalization.go:88 +0x93
    github.com/errata-ai/vale/v2/lint.(*Linter).lintBlock.func1(0xc0000650e0, 0xc000c25270, 0xc000c25250, 0xb, 0xc000bb9880, 0x12, 0xc000863400, 0xf99ec0, 0xc00049c7e0)
        /home/travis/gopath/src/github.com/errata-ai/vale/lint/lint.go:253 +0xb4
    created by github.com/errata-ai/vale/v2/lint.(*Linter).lintBlock
        /home/travis/gopath/src/github.com/errata-ai/vale/lint/lint.go:251 +0x265

**Comment by jdkato** [comment]
Should be fixed in v2.6.6.
