### ISSUE TITLE
Bug with `<>` markdown links causing warnings in wrong place

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#288]
@jdkato A user reported a small bug caused by using `<https://example.com>` style links: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49636#what-does-this-mr-do

I know the problem with these, as you can consider them the same as `[https://example.com](https://example.com)`, so the text between `[]` is linted. The problem is that the warning is in the wrong place, almost as if code/text gets inverted in the eyes of Vale after it hits a warning in that type of link.

For example, we have a rule that checks for `config` by itself (should be `configure/configuration`). But when you have a `<>` link, the warning can slip out to the wrong place:

<img width="730" alt="Screen Shot 2020-12-10 at 14 25 55" src="https://user-images.githubusercontent.com/36979740/101725725-7ee06b00-3af4-11eb-8f78-b3ee1d8efb8a.png">

Remove the `config` from the URL, and it's fine:

<img width="730" alt="Screen Shot 2020-12-10 at 14 26 09" src="https://user-images.githubusercontent.com/36979740/101725812-a800fb80-3af4-11eb-9ecb-550239a97f98.png">

Or keep the URL unchanged, but use a normal `[link](URL)` markdown link:

<img width="730" alt="Screen Shot 2020-12-10 at 14 26 28" src="https://user-images.githubusercontent.com/36979740/101725846-bc44f880-3af4-11eb-8ed5-7aaf9b00d8a6.png">

**Comment by jdkato** [comment]
This is a known issue and it's not straightforward to fix. At the moment, the best explanation I can give is that this style of link isn't supported by Vale. You do have two options, though:

1. As you stated above, you can use `[...](...)`-style links.

2. You can explicitly ignore these links using something like:

    ```ini
    TokenIgnores = (<http[^\n]+>+?)
    ```
    See [Non-standard markup](https://docs.errata.ai/vale/scoping#non-standard-markup) for more information.

I'll make a note of this in the documentation.

**Comment by Ravlen** [comment]
@jdkato Ahh sorry, I didn't notice the previous issue about this. I was thinking of add the URL in backticks inside `[...](...)` links, but I like the idea of TokenIgnores. Thanks for the tip!
