### ISSUE TITLE
Add 'inline rule scoping'

### ISSUE THREAD

**Issue by brest-amzn** [vale-cli/vale#290]

**Comment by jdkato** [comment]
I'm not sure that I understand this issue. Could you elaborate on what you mean by "Add scoping"?

**Comment by brest-amzn** [comment]
It would be great if Vale allowed you to specify an inline 'rule scope' at the top of your markdown file. This would let you specify subsets of rules per document. For example, let's say you had a set of rules that you want to trigger on API reference docs, but you don't want them to trigger on tutorials or conceptual docs. You could use a comment at the top of the doc to specify the set of rules you want to include/not include. This would function similar to the <---vale on--> <---vale off---> feature. 

I know you can technically create a separate Vale configuration file with a subset of rules and use the Vale client to switch back and forth, but that's not really scalable and it's hard to remember to do sometimes. With this feature, writers could use different "templates" that contain different rules as needed.

Here is an example of a .md file that uses  <---api reference--> as a qualifier.


```
Title: My API reference doc
url: /docs/my-api-reference-doc.html

<---api reference--> 

The following API reference topic covers.....Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```
This would trigger rules that are stored in `styles/api-reference/` 


```
//List of conditional styles to load
BasedOnStylesConditional =  api-reference
```

**Comment by brest-amzn** [comment]
(whoops! sorry, I accidently submitted the ticket before I finished typing everything)

**Comment by brest-amzn** [comment]
Another good reason to have a feature like this is sometimes the same value/word means something different across different docs. Meaning, you could use this feature to change rules for different services/products. For example, I might want to use a conditional/spelling rule to catch the term `ProfileId` however, in some other docs it might be spelt like `profileID` or  `ProfileID`  (our writing tasks span across many different technologies/services that don't always share a common base).

**Comment by jdkato** [comment]
Thanks for the suggestion.

Scoping and in-line config comments are going to be getting an update soon (including #259) and something along this idea will be implemented.

**Comment by jdkato** [comment]
You can accomplish this by providing a cascading config:

```ini
StylesPath = styles
MinAlertLevel = suggestion

[*.html]
# Most general config
BasedOnStyles = Vale

[/docs/my-api-reference-doc.html]
# applies to a certain file
BasedOnStyles = api-reference
```

I think keeping Vale's config confined to `.vale.ini` will be easier to maintain.
