### ISSUE TITLE
DITA performance issues

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#291]
The goal of this issue is to track Vale's performance on DITA files. 

At the moment, it's pretty bad: Vale can lint, for example, a reasonably large Markdown file (~2k lines) in under 1 second but takes ~5s to lint even the simplest of DITA files. This level of performance (or lack thereof) makes it difficult to run Vale on both DITA projects as a whole (from the CLI) and even single files from an editor.

The bottleneck here is the `dita` command from the DITA OT, which takes up *most* of the processing time.

**Comment by infotexture** [comment]
@jdkato The complexity of DITA processing is certainly an obstacle to performance parity with simpler markup variants that Vale can parse directly without first converting to an intermediate format such as HTML.

That said, the latest version of DITA-OT provides a variety of performance enhancements including new options for parallel and in-memory processing that can significantly reduce processing time under the right circumstances. 

Not all of these will be relevant for Vale's use case, but the latest release should be faster even with the default settings. 

For details, see https://www.dita-ot.org/3.6/release-notes/#v3.6. 

/cc @jelovirt & @robander

**Comment by jdkato** [comment]
> The complexity of DITA processing is certainly an obstacle to performance parity with simpler markup variants that Vale can parse directly without first converting to an intermediate format such as HTML.

This isn't the case for *any* of the supported formats&mdash;they're all converted to HTML prior to any processing. I deliberately don't do any parsing myself because I think (1) it would quickly become unmaintainable (it's better, imo, to offload that work to dedicated projects) and (2) I use HTML as a common ground between formats.

On the Vale side of things, the biggest performance hurdle is the overhead associated with having to call external command-line tools (only Markdown has a native Go implementation).

I've been putting a lot of work into this lately, though: the next release of Vale will pretty much eliminate this overhead for AsciiDoc and reStructuredText, and I'm working on doing the same for DITA.

I've also noticed that DITA-OT 3.6 is around 20% - 30% faster than the previous version, so I think the next few releases of Vale will see significant performance boosts for all three of DITA, AsciiDoc, and reStructuredText.

**Comment by jelovirt** [comment]
This is a classic case where JVM has greater startup duration and because JIT hasn't done it's optimizations yet, the total processing time is unfortunately long.

One way to tackle this would be to use a daemon to keep the JVM alive and reuse it.

**Comment by kirkilj** [comment]
@jelovirt  We currently generate HTML in the EclipseHelp format. I'm assuming we'd need to inject the Vale phase before the HTML gets packaged or extract everything after the war is built and then run Vale, which adds a bit of overhead. Thoughts?

**Comment by jelovirt** [comment]
@kirkilj EclipseHelp has no extension points to add Ant target dependencies between generating. You can have a custom target to replace [`dita2eclipsehelp`](https://github.com/dita-ot/org.dita.eclipsehelp/blob/master/build_dita2eclipsehelp_template.xml#L24) and add Vale phase there.

I assume you have a good reason to use EclipseHelp instead of HTML5?
