### ISSUE TITLE
default StylesPath

### ISSUE THREAD

**Issue by paper42** [vale-cli/vale#295]
I think it would be beneficial to have StylesPath set to a specific string if the user did not overwrite it with a config file. Default could be `/usr/share/vale/`, but it should be a compile time option. This would allow Linux distributions to ship styles without the user having to figure out where the styles were installed.

**Comment by bollwyvl** [comment]
As mentioned over on #576, the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) provides some useful, not-having-an-adventure norms for where to put such things, even on windows, with existing `go` [implementations](https://github.com/adrg/xdg) (and many other languages).
