### ISSUE TITLE
By default, Vale should ignore AsciiDoc block attributes

### ISSUE THREAD

**Issue by ggrossetie** [vale-cli/vale#296]
- OS: Linux 
- Install method: Direct download
- Vale version: `vale version 2.6.8`

`.vale.ini`

```ini
StylesPath = docs/.vale
MinAlertLevel = suggestion

[*.adoc]
BasedOnStyles = test
```

`docs/.vale/test/Substitutions.yml`

```yml
extends: substitution
message: Consider using '%s' instead of '%s'
level: error
ignorecase: true
swap:
  asciidoc: AsciiDoc
```

`docs/test.adoc`

```adoc
= Document Title

Here's a sample Asciidoc document:

[source,asciidoc]
----
some asciidoc
----

Asciidoctor is a fast, open source text processor and publishing toolchain
for converting asciidoc content to HTML5, DocBook, PDF, and other formats.
```

#### Current result

```console
$ vale docs/test.adoc

 docs/test.adoc
 3:17  error  Consider using 'AsciiDoc'       test.Substitutions 
              instead of 'Asciidoc'                              
 5:9   error  Consider using 'AsciiDoc'       test.Substitutions 
              instead of 'asciidoc'                              

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

#### Expected result

The language attribute in the source block should be ignored by default.
Arguably, it could be useful to apply style rules on block attributes but that should definitely be a dedicated scope.

Interestingly, `vale` does not see the last violation line 11 (after the source block): "for converting asciidoc content to HTML5, DocBook, PDF, and other formats.". Should I open a dedicated issue?

**Comment by jdkato** [comment]
> Interestingly, vale does not see the last violation line 11 (after the source block): "for converting asciidoc content to HTML5, DocBook, PDF, and other formats.". Should I open a dedicated issue?

This is basically the Asciidoc equivalent of https://github.com/errata-ai/vale/issues/248#issuecomment-706411208. It should be fixed in the next release.
