### ISSUE TITLE
Ignore tokens from the capitalization

### ISSUE THREAD

**Issue by ggrossetie** [vale-cli/vale#299]
The `capitalization` rule is really helpful but I wonder if it would be possible to ignore some tokens from the match.

For instance, some words should always be written in lowercase even if I want to use a `$title` capitalization on my document title.

A few examples:

```
= Run Commands Using npm Scripts
```

```
= reveal.js Options
```

```
= Combine XMLHttpRequest Requests With HTML (HyperText Markup Language) 
```

In the above examples, "npm" and "reveal.js" must be lowercase. Similarly, "HTML", "XMLHttpRequest" and "HyperText" are using a specific casing and should be ignored.

**Comment by jdkato** [comment]
As a rule creator, you can define exceptions in the [rule definition itself](https://docs.errata.ai/vale/styles#capitalization). You can also define them in a rule-agnostic way through a custom [Vocab](https://docs.errata.ai/vale/vocab).

**Comment by ggrossetie** [comment]
Thanks for the pointers.
Sorry, I totally missed the `exceptions` attribute :sweat:
