### ISSUE TITLE
Auto update for styles

### ISSUE THREAD

**Issue by refaelsh** [vale-cli/vale#304]
Hi all,

As far as I can understand from the docs (and please correct me if I am wrong), I need to manually download styles (can it made automatic please?). Since its manual, how can they be automatically updated?
Its a kind of a bother to go and check manually wether the styles were update and download them manually again.

Thanks all.

**Comment by jdkato** [comment]
This depends on how you're using Vale. Both the [GitHub Action](https://github.com/errata-ai/vale-action) (CI use) and [Vale Server](https://errata.ai/vale-server/) (local use) support automatic updates.

**Comment by refaelsh** [comment]
I am using Vale locally on my laptop with my Asciidoctor writing --> GitHub Action is not applicable.
'Vale Server' - the application is not Open Source --> I would prefer not to use it.

Any more suggestions please on how to keep the styles automatically updated?

**Comment by ChrisChinchilla** [comment]
@refaelsh In the meantime, a semi-manual way to do this is check out all styles as GitHub repos. I can't speak for updating styles automatically via the Vale binary, but we could do it through the VSCode extension (for example), it's been something I've been thinking about for a while.

It's more I don't want to step on the toes of Vale Server, as that is how the project funds development, so sometimes certain features might only be available there… If that's not the case, I can look at adding it to extensions, but I am not a Go developer for Vale itself…

**Comment by refaelsh** [comment]
> @refaelsh In the meantime, a semi-manual way to do this is check out all styles as GitHub repos. 

Excellent idea. Thank you.

> but we could do it through the VSCode extension (for example), it's been something I've been thinking about for a while.

Vim? :-) I use Vim :-) Just saying :-)

> It's more I don't want to step on the toes of Vale Server, as that is how the project funds development, so sometimes certain features might only be available there… If that's not the case, I can look at adding it to extensions, but I am not a Go developer for Vale itself…

I understand.

**Comment by ChrisChinchilla** [comment]
@refaelsh There used to be a Vim extension I think, no idea if it's still maintained, not heard much about it, so I assume not.

I don't use Vim and never have, but if you want to create an extension, we are happy to help 😁. Mostly Vale outputs JSON, and then you parse the output into the editor…

**Comment by refaelsh** [comment]
There is a Vim extension for Vale, its part of [Ale](https://github.com/dense-analysis/ale) - I already use it and its great (the only part missing, as stated before, is auto updating of styles).
I mentioned Vim because you mentioned that it is possible  theoretically to auto update styles in VS Code plugin - I use Vim.

**Comment by ChrisChinchilla** [comment]
@refaelsh Good to hear it still works. What I meant was, it was a feature I could add to the VSCode extension (that builds on top of functionality not present in Vale itself), but I don't have the knowledge to do that to the Vim one. I am sure whoever maintains it will be open to feature suggestions or code contributions :)
