### ISSUE TITLE
Vale existence rule with backticks no longer works

### ISSUE THREAD

**Issue by eread** [vale-cli/vale#306]
An `existence` rule that tries to catch, for example, `` ```sh `` no longer works.

Version 2.6.2 would catch such a string. Version 2.6.3 (and presumably later) doesn't. Neither `` \` `` nor `\x60` work.

Here is some context: https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1144#note_482235607.

**Comment by jdkato** [comment]
The problem here is actually the info string (the text after the backticks): this is basically the reverse of https://github.com/errata-ai/vale/issues/248, which ensured that matches *don't* occur here.

`scope: raw` will now be respected in these cases, though.
