### ISSUE TITLE
Bug with 'occurrence' causing warnings in wrong place 

### ISSUE THREAD

**Issue by brest-amzn** [vale-cli/vale#307]
Occurrence rules seem to trigger the warning in the wrong place. They used to work fine, but I noticed it changed in one of the recent updates.

For example, this rule is straight out of your docs.

```
extends: occurrence
message: "More than 3 commas. Can you reduce the complexity of the sentence?"
level: suggestion
# Here, we're counting the number of times a comma appears
# in a sentence.
#
# If it occurs more than 3 times, we'll flag it.
scope: sentence
ignorecase: false
max: 3
token: ','
```

However, it's flagging the first comma in an unrelated sentence (when it should be flagging the next sentence).
<img width="1585" alt="example1" src="https://user-images.githubusercontent.com/55214086/104221024-310d9a00-53f5-11eb-921f-fdcf1531fe93.PNG">

Example text

Flagging (in bold)

The ASP isn't actually a component of the SDK. It's software that lives on a chip (SOC) or firmware on a dedicated digital signal processor (DSP). Its job is to clean up the audio and create a single audio strea**m, e**ven if your device uses a multimicrophone array. Techniques used to clean the audio include acoustic echo cancellation (AEC), noise suppression, beam forming, voice activity detection (VAD), dynamic range compression (DRC), and equalization.

Expected flagging 

The ASP isn't actually a component of the SDK. It's software that lives on a chip (SOC) or firmware on a dedicated digital signal processor (DSP). Its job is to clean up the audio and create a single audio stream, even if your device uses a multimicrophone array. **Techniques used to clean the audio include acoustic echo cancellation (AEC), noise suppression, beam forming, voice activity detection (VAD), dynamic range compression (DRC), and equalization.**

**Comment by jdkato** [comment]
Thanks for the report. This will be fixed in the next release.
