### ISSUE TITLE
Some errors and warnings are marked in incorrect places, after Asciidoc source code blocks

### ISSUE THREAD

**Issue by jouni** [vale-cli/vale#308]
macOS, Vale 2.8.0 (via Homebrew), Atom 1.53.0, atomic-vale 1.9.0

I think this is a regression in 2.8.0. Haven’t had such issues before.

Input:

```asciidoc

There are problems with this.

[source, typescript]
----
----

There are problems with this.

```

Output – notice where the second error indicator appears, on the same line as the source code block:
<img width="417" alt="Screen Shot 2021-01-13 at 12 31 42" src="https://user-images.githubusercontent.com/66382/104440658-4c1a0e80-559b-11eb-9228-72444a6a63bc.png">

If I change the source block to use backticks (Markdown syntax), then the errors are marked in the correct place:
<img width="371" alt="Screen Shot 2021-01-13 at 12 33 29" src="https://user-images.githubusercontent.com/66382/104440856-8c798c80-559b-11eb-94db-c5cff029672d.png">

**Comment by jouni** [comment]
Hmm, I’m not sure if this is actually a problem in Vale, after all. I downgraded to 2.7.1, and I see the same behavior. Weird. 

Now I suspect it’s actually some plugin updates in Atom that mess where the indicators are shown, because VS Code shows them in the correct place (even after updating to 2.8.0 again).

<img width="397" alt="Screen Shot 2021-01-13 at 12 57 11" src="https://user-images.githubusercontent.com/66382/104443244-db74f100-559e-11eb-9fa1-2123f132b5aa.png">

**Comment by jouni** [comment]
Something odd is going on, regardless of the Vale version or editor (this is in VS Code):
![Screen Shot 2021-01-13 at 14 12 22](https://user-images.githubusercontent.com/66382/104450904-7bd01300-55a9-11eb-8c6a-fefa1eb20555.png)

Again, the error is indicated in the correct place if I change from `[source, TypeScript]` to Markdown back ticks.

If you want to take a closer look, here’s the source: https://github.com/vaadin/docs/blob/master/articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc

**Comment by jdkato** [comment]
This will be fixed in the next release.
