### ISSUE TITLE
No spelling errors are reported

### ISSUE THREAD

**Issue by refaelsh** [vale-cli/vale#309]
Hi all,

According to this [table](https://github.com/errata-ai/vale#functionality) from the README, this tool should also report spelling errors. Well, it does not happens to me, no reports on spelling errors.
Is this a bug or am I missing some setting?

Thanks all.

**Comment by jdkato** [comment]
You need to have `BasedOnStyles = Vale`, `Vale.Spelling = YES`, or a custom `spelling`-based rule enabled.

**Comment by refaelsh** [comment]
I understand. Thank you very much.

**Comment by refaelsh** [comment]
I tried it, it works, adding `Vale` to `BasedOnStyles`. I was not aware there is such a style called `Vale` (it appears to be "build-in"?), where it is stated in the docs?
