### ISSUE TITLE
Running vale on Alpine Linux

### ISSUE THREAD

**Issue by tsmaeder** [vale-cli/vale#310]
I was trying to update vale to latest (2.8.0) in our Alpine Linux (using the tar.gz from the github releases page), but I get errors saying "not found". Doing `ldd vale` showed that it seems dynlinked to libc. However the vale image on docker hub is based on Alpine and works just fine. (I extracted it from the image and put it in ours: works!)
What am I missing here?

**Comment by jdkato** [comment]
This should be resolved with the latest release (v2.8.1).
