### ISSUE TITLE
Vale spelling catching "ve" on You've

### ISSUE THREAD

**Issue by andreysamode** [vale-cli/vale#311]
Vale.Spelling seems to be catching "ve" in "You've" in the following text:
"You've had your turn. I--I've not."

To reproduce:

```
vale# echo "You've had your turn. I--I've not." | ./vale

 stdin.txt
 1:5  error  Did you really mean 've'?  Vale.Spelling

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

Oddly, removing the second sentence makes the error go away.

vale version 2.8.0

**Comment by jdkato** [comment]
This will be fixed in the next release.
