### ISSUE TITLE
Vale throws "lstat : no such file or directory"

### ISSUE THREAD

**Issue by th0ger** [vale-cli/vale#313]
I'm trying Vale for the first time, following the official guide, but keep getting:
```
`lstat : no such file or directory`
```

- OS: Ubuntu 20.04.1 (WSL 2).
- Install method: Installed homebrew (on ~/.linuxbrew), added `brew` to `$PATH`, then `brew install vale`.
- Testing install: `vale -v` -> `vale version 2.8.0`
- `git clone git@github.com:errata-ai/vale-boilerplate.git`
- `cd vale-boilerplate`
- `vale README.md` -> `lstat : no such file or directory`
- `cat README.md | vale ` -> `lstat : no such file or directory`

**Comment by jdkato** [comment]
Please see https://github.com/errata-ai/vale/issues/305#issuecomment-761623272.
