### ISSUE TITLE
Is it possible to run Vale in Android shell?

### ISSUE THREAD

**Issue by andreysamode** [vale-cli/vale#314]
Thanks for this incredible tool. I'm a long-time proselint user and this takes it to another level.

Would it be possible to run Vale in an Android shell?

**Comment by jdkato** [comment]
If you can use the published Linux binary or build one from source for your platform, then yes. But you'll have to try it.

**Comment by andreysamode** [comment]
Thanks for you reply. I just tried the Linux binary and it gave me this error:
`vale[17]: syntax error: 'H�P' unexpected`
I tried the Mac binary and it gave me this error:
`syntax error: '(' unexpected`

So I guess it'll need to be compiled for the super-limited POSIX-style Android shell.
Any hints on that front?

**Comment by andreysamode** [comment]
Got it figured out. For reference, here's how to do it on a Mac:

`sudo port install go`
Download Android NDK and unzip to Desktop/android-ndk-r21d
Download source vale, unzip and cd into it
`GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=~/Desktop/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi23-clang go build -o valeAndroid ./cmd/vale`

```
adb shell push valeAndroid /data/local/tmp
adb shell
cd /data/local/tmp
./valeAndroid
```

Note that the architecture will need to be adjusted accordingly. My device is running Android 6.0 (API 23) on a ARM v7l architecture.
