### ISSUE TITLE
Support for mixed md/rst files

### ISSUE THREAD

**Issue by th0ger** [vale-cli/vale#316]
We use [Sphinx](https://www.sphinx-doc.org/en/master/) together with the [m2r2 extension](https://pypi.org/project/m2r2/).
Our documentation is primarily Markdown, but with RestructuredText elements here and there. For example [directives](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/basics.html#directives) for references, images etc.

The docs are precompiled from `.md` to `.rst`, then to `.html`.

Vale is run on the `.md` files but throws a lot of false warnings due to the RestructuredText parts. Can I tell Vale to ignore this?

I don't consider `<!-- vale off -->...<!-- vale on -->` a solution, it would be required on each and every place and clutter up the code completely.

**Comment by jdkato** [comment]
You can run Vale on the generated HTML.

**Comment by th0ger** [comment]
Thank for your suggestion. HTML is certainly one route to go, but it has some impacts: VSCode Vale extension can't be used when writing. And the line:col position in html does not match the markdown position, so it's harder to track back.

**Comment by th0ger** [comment]
I'm testing BlockIgnores (and maybe TokenIgnores).
Can you tell why this doen't work?

The markdown contains a [ReStructuredText cross reference](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-objects):

```
Markdown content. Followed by RST directive

.. _foofoo:

Some more content. A spelling eror.
```

The regex `(?s) ?(^\.\.\s+.*?\:)` matches the reference and tested with [regex101](https://regex101.com/r/7whQ5x/1).

```
=== .vale.ini ===
StylesPath = styles
MinAlertLevel = suggestion

Vocab = myVocab

[*.{md,rst}]
BasedOnStyles = Vale

[*]
BlockIgnores = (?s) ?(^\.\.\s+.*?\:)
```

But this stiil gives "Did you really mean 'foofoo'?"
