### ISSUE TITLE
Supporting symlinks when using BasedOnStyles

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#319]
I appreciate this is a super niche use case and there might even be technical reasons it isn't supported.

But for a degree of flexibility and the ability to share one folder of styles into multiple paths, I have often use symlinks in project local styles directories.

I noticed after much experimentation that you can enable individual rules that are in symlinked directories, but not folders of rules brought in by `BasedOnStyles`, is there any way to add support for that without breaking something else? I've often recommended this as a way to set Vale up, which may not have been correct, but it made a vague sort of sense at the time… if not, I should probably find a better method instead ;)

**Comment by jdkato** [comment]
This isn't supported by [Go's stdlib](https://golang.org/pkg/path/filepath/#Walk) (which Vale currently uses), but there are other options that could be used.

That said, is there any reason why you can't just point `StylesPath` to a shared location? It seems like that accomplishes, essentially, the same thing.

**Comment by ChrisChinchilla** [comment]
@jdkato kind of, it also meant that you could ship non-user specific .vale.ini files, as they always point to a locally created alias, but in theory I guess the work to tell a user to create an alias vs the work to tell them to change a path is about the same

**Comment by ChrisChinchilla** [comment]
Ah yes, also specifically for people like you and I who also maintain some styles, the ability to use aliases helped because you can have one git checked out style repository, but have an alias to the actual sub folder with the rules. But I appreciate that is a niche use case, I just need to rethink my own setup

**Comment by jdkato** [comment]
I've been meaning to try https://github.com/karrick/godirwalk anyways, so this might be possible in the next release.

**Comment by ChrisChinchilla** [comment]
@jdkato Huh, OK! In the meantime I have been working on a small helper shell script that downloads the latest versions of rule sets from GitHub releases, which also makes it more reproducible and good for CI usage too

**Comment by jdkato** [comment]
This should be possible now (although I still don't necessarily advise it).

**Comment by ChrisChinchilla** [comment]
Thanks @jdkato I may have found a more elegant and universal solution anyway, which I will document soon :)

but this is also useful for personal setup
