### ISSUE TITLE
Spelling.yml bug -- false positive due to a preceding dash character "-"

### ISSUE THREAD

**Issue by brest-amzn** [vale-cli/vale#324]
I am getting a false positive with the spelling rule because of an earlier dash (-) in the sentence. 

<img width="1508" alt="fp" src="https://user-images.githubusercontent.com/55214086/105762136-da31b580-5f08-11eb-81f8-579e7593883c.PNG">

**Text to replicate problem** 

```
Contains information about the `mediaplayer` running on the device.

The unique name of a software component running on the device, limited to 256 characters. Use reverse-DNS notation for component names to guarantee global uniqueness. For example, you might report a custom media player as `mediaplayer` 
```

**If I delete the dash in "reverse-DNS", the error goes away**

```
The unique name of a software component running on the device, limited to 256 characters. Use reverse DNS notation for component names to guarantee global uniqueness. For example, you might report a custom media player as `mediaplayer` 
```

I am just using the default spelling rule.

```
extends: spelling
message: "Did you really mean '%s'?"
level: error
code: false
filters:
  - ...
```

**Example of fixed**

<img width="1504" alt="fix" src="https://user-images.githubusercontent.com/55214086/105762281-0baa8100-5f09-11eb-8a66-a0b042ed8bc6.PNG">

**Comment by jdkato** [comment]
Are you using any `BlockIgnores` or `TokenIgnores` in your `.vale.ini` file?

**Comment by brest-amzn** [comment]
You are correct. I am. Thanks, deleting the TokenIgnore made the error go away.

However, I still have a question. Can you tell me why it's causing the error? or point me to another git issue or docs with more information? What's actually causing the poorly configured TokenIgnore to throw an additional flag in an unrelated part of the sentence?  If anything, I would a expect a bug related to a TokenIgnore to unintentionally "ignore" more things after it, instead of triggering an additional flag (for example, accidently capturing more of the intended query with regex .* or something)

I assume it's something related to the flags that erroneously show up when you mix unsupported flavors of markdown with html ( e.g - kramdown syntax instead of CommonMark).

**Comment by jdkato** [comment]
Without the seeing pattern I can only give a rough explanation, but it's almost always that the pattern results in invalid markup.

For example, the pattern could end up ignoring too much of the document (resulting in less errors) or could unintentionally ignore half a code block or something (which could result in *more* errors due to parsing failures later down).
