### ISSUE TITLE
Vale 2.9.0 fails with .rst files on Windows

### ISSUE THREAD

**Issue by klm1** [vale-cli/vale#326]
Windows 10, version 20H2
Installed version 2.9.0 via `choco install vale`

Vale fails on scanning RST files, e.g.:

`vale file.rst`

produces

```
E100 [lintRST] Runtime error

rst2html not found
```

I did try installing rst2html via pip3 but still get the same error.

Could the choco package be missing something?

**Comment by klm1** [comment]
Looks like rst is not included by default. Will install an additional parser.

**Comment by frankharkins** [comment]
@klm1 what did you install to get this working?

**Comment by kenmorse** [comment]
@frankharkins I believe it was Docutils (based on this page: https://vale.sh/docs/topics/scoping/#restructuredtext

`pip install docutils`

**Comment by frankharkins** [comment]
@kenmorse thanks! And did you need to do anything else? We have it installed but it's still not working. I assume we need to do something so that the `docutils` works?

**Comment by kenmorse** [comment]
@frankharkins It's been long enough that I don't remember the details. The docs also reference Sphinx (which I do have installed as well). My recollection was that Sphinx itself wasn't enough but installing docutils did the trick. I've looked at both pip and brew listings on my dev Mac but don't see anything else that looks related.

**Comment by frankharkins** [comment]
No problem, thanks for investigating

**Comment by jdkato** [comment]
You need `rst2html` available on your `$PATH`. `pip install docutils` should be all you need.

**Comment by frankharkins** [comment]
Thanks, for some reason it didn't automatically add to `$PATH`. Here's what worked in the end:

1. Install `docutils`

   ```sh
   pip install docutils
   ```
2. Find the Python scripts directory ([source](https://stackoverflow.com/questions/62162970/programmatically-determine-pip-user-install-location-scripts-directory))

   ```sh
   python -c 'import os,sysconfig;print(sysconfig.get_path("scripts",f"{os.name}_user"))'
   ```
3. Add to path (we used [this guide](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/))
