### ISSUE TITLE
Linting edge case: Pipe (|) in backticks in a table causes linting within the code

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#327]
@jdkato An edge case we just discovered, is that the `|` character causes vale to lint within backtick sections by accident, if it's in a table:

```markdown
| Table | Table |
|-------|-------|
| Word  | `Notword|` |
```

<img width="695" alt="Screen Shot 2021-02-10 at 10 29 18" src="https://user-images.githubusercontent.com/36979740/107451816-6be92600-6b8b-11eb-8559-9cc6b5e64e09.png">

**Comment by jdkato** [comment]
Thanks for the report.

This is an upstream bug (and a pretty widespread one at that): Vale's internal (third-party) Markdown parser and GitHub's custom library (among others) fail to render this snippet correctly:

| Table | Table |
|-------|-------|
| Word  | `Notword|` |

I've opened https://github.com/yuin/goldmark/issues/194 to see what the maintainer has to say.

**Comment by Ravlen** [comment]
@jdkato Thanks a lot!

**Comment by jdkato** [comment]
Per the advice in the linked issue, you'll need to escape the pipe: 

```markdown
| Table | Table |
|-------|-------|
| Word  | `Notword\|` |
```
