### ISSUE TITLE
Question: Non-English Dictionaries

### ISSUE THREAD

**Issue by ghost** [vale-cli/vale#328]
I ran into issues when trying to use a non-English Hunspell dictionary. When configuring German, Portuguese or Swiss dictionaries for testing, error messages like `Unable to process "Abarbeitungs/hij": unable to find affix key 104` occur. Are there any known issues with other languages than English? Does anyone have experience with non-English dictionaries? I tried dictionaries from https://github.com/wooorm/dictionaries.

Thanks in advance!
Hans-Jörg

**Comment by paddyroddy** [comment]
I have this problem with `en_GB` from https://extensions.libreoffice.org/en/extensions/show/english-dictionaries `Unable to process "abdominoscopy/M\tNoun: uncountable": unable to find affix key 9`

**Comment by ChrisChinchilla** [comment]
@paddyroddy Hmm, well that is an English dictionary, and actually I use en_GB and en_AU myself, so there might be an issue with the particular dictionary file you're using. @jdkato I'm happy to test this one, I can also possibly have a look at the German issue (as I live there), but I know Vale support for non-English is a little more patchy.

**Comment by paddyroddy** [comment]
I used the most recent one, and the previous one and both had this issue. I'm currently using the oldest one on that link, and it works fine

**Comment by maglo** [comment]
I have the same problem:

```yaml
extends: spelling
message: "Did you really mean %s?"
dicpath: /usr/share/hunspell
dictionaries:
  - sv_SE
```

```
/work # ls -lah /usr/share/hunspell/
total 4M
drwxr-xr-x    2 root     root        4.0K Apr 19 12:56 .
drwxr-xr-x    1 root     root        4.0K Apr 19 12:56 ..
-rw-r--r--    1 root     root       32.2K Apr 19 12:56 en_GB.aff
-rw-r--r--    1 root     root        1.0M Apr 19 12:56 en_GB.dic
-rw-r--r--    1 root     root        3.0K Apr 19 12:56 en_US.aff
-rw-r--r--    1 root     root      538.3K Apr 19 12:56 en_US.dic
-rw-r--r--    1 root     root      104.5K Apr 19 12:56 hyph_en_GB.dic
-rw-r--r--    1 root     root      103.9K Apr 19 12:56 hyph_en_US.dic
-rw-r--r--    1 root     root      100.6K Apr 19 12:56 hyph_sv.dic
-rw-r--r--    1 root     root       18.1K Apr 19 12:56 sv_SE.aff
-rw-r--r--    1 root     root        2.2M Apr 19 12:56 sv_SE.dic
```

Dictionary files downloaded from https://cgit.freedesktop.org/libreoffice/dictionaries/plain/sv_SE/

these files work with `sphinxcontrib-spelling` - unsure about the usage of the `aff` file there though.

```
/work # vale --glob=*.rst docs/user-guide/
E201 Invalid value provided [/styles/Basalt/Spell.yml:1:1]:

   1* extends: spelling
   2  message: "Did you really mean %s?"
   3  dicpath: /usr/share/hunspell

Unable to process "-/-06XY": unable to find affix key 88
```

Setting 

```yaml
dictionaries:
  - en_US
```

works fine

Setting

```yaml
dictionaries:
  - en_GB
```

generates

```
E201 Invalid value provided [/styles/Basalt/Spell.yml:1:1]:

   1* extends: spelling
   2  message: "Did you really mean %s?"
   3  dicpath: /usr/share/hunspell

Unable to process "abdominoscopy/M\tNoun: uncountable": unable to find affix key 9
```

**Comment by jdkato** [comment]
This will be fixed in the next release.

**Comment by jdkato** [comment]
This should be fixed now.
