### ISSUE TITLE
Feature Request: Auto Fix Issues

### ISSUE THREAD

**Issue by TheSecMaven** [vale-cli/vale#329]
I may have missed this, but this tool is super helpful (Just getting exposed!) so want to see if I am or what the thoughts on this are.

I got suggestions for things to fix like 
```
 5:103  error  Did you really mean             Vale.Spelling 
               'serrvice'?                                   
```

I know each case isn't the same, but it would be nice to have a way to specify that I want Vale to turn it into the word it thinks it is, or even specify common misspellings, and thee word that it should be. Maybe similar things are in other places that I haven't seen, but having some form of "auto fix" would be super helpful for large scale use cases.

**Comment by ChrisChinchilla** [comment]
@mkkeffeler This is possible in Vale Server (the commercial version of Vale), but yes you're right, even there it's not always possible to know what a "fix" actually should be.
