### ISSUE TITLE
Feat: Org mode support

### ISSUE THREAD

**Issue by tecosaur** [vale-cli/vale#330]
Hello!

It would be great if this supported Org mode.

I'd guess that Hugo's Org parsing library should make this a lot easier to implement 🙂.

**Comment by jdkato** [comment]
There has been some work on this in #234.

**Comment by tecosaur** [comment]
Oh cool! I hadn't even noticed 😅

**Comment by rudolf-adamkovic** [comment]
+1 for Org mode support.

**Comment by jdkato** [comment]
This is available now on the `v2` branch and will be included in the next release.

**Comment by johnhamelink** [comment]
[flymake-vale](https://github.com/tpeacock19/flymake-vale/pull/4)'s latest commit allows Vale's file extension flag to be specified (or detected from the file extension), meaning org-mode buffers now behave much better with vale in conjunction with the new changes in the v2 branch. Here's an example of `org-msg-mode` working with `flymake-vale` with the `.org` extension passed to Vale.

I thought I'd leave a note of this here as I think it's a good showcase of the work in the v2 branch!

![image](https://user-images.githubusercontent.com/101739/177050301-8e01a4f4-3177-4293-80b3-dea422380ba3.png)

**Comment by jdkato** [comment]
The underlines seem to be off by 2 in some places. Is that reproducible with just the CLI?

**Comment by johnhamelink** [comment]
If I run `vale` on `example-email.org` (which I got by writing the draft buffer to disk):

```org
User-agent: mu4e 1.8.2; emacs 29.0.50
From: Alice InWonderland <alice@my.email>
Date: Sun, 03 Jul 2022 18:36:44 +0100
To: Bob McBurgers <bob@someone.else>
Subject: Lorem Ipsum
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \n:t d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: nil
:attachment: nil
:alternatives: (text html)
:END:

Hi there,

It's really impressive to see Vale working flawlessly with Mu4e and
=org-msg-mode=. Notice how the subject's content has been checked, but
the =+OPTIONS= have been ignored? That's because Vale's =org-mode= parser
is working.

```

With my `~/.vale.ini` looking like this:

```
StylesPath = "/home/john/.config/vale/styles"

MinAlertLevel = suggestion
Vocab = "base"

Packages = Hugo

[*.{txt,org,md}]
BasedOnStyles = Vale, write-good, proselint, alex, Joblint
```

I get this:

```
❯ vale example-email.org

 example-email.org
 1:25   error       Did you really mean 'emacs'?    Vale.Spelling      
 1:25   suggestion  Don't specify a development     Joblint.DevEnv     
                    environment unless absolutely                      
                    necessary.                                         
 5:10   error       Did you really mean 'Lorem'?    Vale.Spelling      
 5:16   error       Did you really mean 'Ipsum'?    Vale.Spelling      
 17:1   suggestion  Try to avoid using 'It's'.      write-good.E-Prime 
 17:6   warning     'really' is a weasel word!      write-good.Weasel  
 18:54  suggestion  Try to avoid using 'been'.      write-good.E-Prime 
 18:54  warning     'been checked' may be passive   write-good.Passive 
                    voice. Use active voice if you                     
                    can.                                               
 19:21  suggestion  Try to avoid using 'been'.      write-good.E-Prime 
 19:21  warning     'been ignored' may be passive   write-good.Passive 
                    voice. Use active voice if you                     
                    can.                                               
 19:35  suggestion  Try to avoid using 'That's'.    write-good.E-Prime 
 20:1   suggestion  Try to avoid using 'is'.        write-good.E-Prime 

✖ 3 errors, 3 warnings and 6 suggestions in 1 file.

```

In contrast to the results in the screenshot above. I note that the file has an extra line at the top which isn't shown in the buffer - I'm unsure why that is.

I think the skewing is happening because I'm hiding the emphasis characters in the org-msg buffer.

**Comment by tpeacock19** [comment]
I've just pushed another commit (https://github.com/tpeacock19/flymake-vale/commit/bd4975328d98e63b5bdb69a0936f61bc7da39708) that should address the misalignment from hidden characters.

**Comment by johnhamelink** [comment]
@tpeacock19 yep, that fixes this issue

![image](https://user-images.githubusercontent.com/101739/177053887-163a345c-7d14-4694-875b-4f82caad1354.png)
