### ISSUE TITLE
Problem with TokenIgnores not ignoring certain content

### ISSUE THREAD

**Issue by lee-dohm** [vale-cli/vale#333]
I'm currently evaluating using Vale to lint the GitHub documentation at https://github.com/github/docs but I'm running into a problem with `TokenIgnores` seemingly not ignoring content it should be. I have a minimal repro case at https://github.com/lee-dohm/vale-test. Is there something I'm doing wrong?

## Steps to reproduce

1. [Clone the repo](https://docs.github.com/en/github/using-git/which-remote-url-should-i-use) at https://github.com/lee-dohm/vale-test
1. Execute the command: `vale test.md`

**Expected:** No errors \
**Actual:** 1 error

Notice that the first Liquid tag containing the text is flagged as an error, but the second identical Liquid tag on the same line is not.

## Extra info

* I've created [a test case at regex101](https://regex101.com/r/Zy0Dv1/2/) that shows that the pattern that I'm using for `TokenIgnores` is ignoring what I expect, no more, no less
* Using `vale ls-config` shows that there doesn't seem to be a parsing error in the configuration file

## Configuration

* **OS:** macOS 11.2.1
* **Installation method:** Homebrew
* **Vale version:** vale version 2.9.1

**Comment by jdkato** [comment]
The problem here is actually the link destination:

```markdown
[Reaching {% data variables.contact.github_support %}](/enterprise/{{ currentVersion }}/admin/enterprise-support/reaching-github-support)
```

The spaces in `{{ currentVersion }}` are a violation of the [CommonMark spec](https://spec.commonmark.org/0.29/#link-destination) and result in the URL being processed as normal text. If you're able to remove the spaces, everything should work as expected.

---

To provide some background, Vale uses a CommonMark-compliant parser to power its syntactic understanding of Markdown (e.g., ignoring code and URLs). So even minor deviations from the standard can result in unexpected results.

Ignore patterns are designed to help make Vale usable on non-standard Markdown (such as the use of Liquid tags) by mapping "unknown" syntax to either code blocks (`BlockIgnores`) or code spans (`TokenIgnores`).

**Comment by lee-dohm** [comment]
Ah ha! My eyes glossed over that syntax. It looks like `{{ ... }}` is another kind of Liquid template syntax, so I'll try ignoring those too and see how it comes out.

I notice that the documentation mentions a `--debug` flag but it doesn't seem to be accepted by v2.9.1. Is there some way that I can get more insight into why Vale is behaving the way it is when the output doesn't seem right?

**Comment by lee-dohm** [comment]
Changing the `TokenIgnores` to the following fixed it:

```text
TokenIgnores = ({%[^%]+%}), \
               ({{[^}]+}})
```

Thanks very much for your help!

**Comment by lee-dohm** [comment]
I'm really sorry. I jumped the gun on my testing and it appears this isn't fixed with the addition of the new ignore pattern. I've also added a new test case that shows that this isn't limited to blocks that contain the Liquid object references:

```markdown
The GitHub PubSubHubbub endpoint is: `{% data variables.product.api_url_code %}/hub`. A successful request with curl looks like:
```

The above is flagged as two errors:

```text
 X:65   error  Did you really mean 'api'?      Vale.Spelling 
 X:69   error  Did you really mean 'url'?      Vale.Spelling 
```

When it shouldn't be checking the content within the tag there at all. And the backticks should be converting all of that to a `tt` element, I think? And I've got `tt` set as an ignored scope.

I've updated https://github.com/lee-dohm/vale-test to include this additional test case along with the added `TokenIgnores` pattern.

**Comment by jdkato** [comment]
There are now multiple topics at play here. I think if we take it one at a time it'll be easier to work through.

1. The first issue, as described in your original post, is that CommonMark URLs can't contain spaces. This isn't a Vale-specific issue and it *can't* be fixed with `TokenIgnores`. 

   This

    ```markdown
    [Reaching {% data variables.contact.github_support %}](/enterprise/{{ currentVersion }}/admin/enterprise-support/reaching-github-support)
    ```
    needs to become this

    ```markdown
    [Reaching {% data variables.contact.github_support %}](/enterprise/{{currentVersion}}/admin/enterprise-support/reaching-github-support)
    ```

2. The second issue is that you want to ignore Liquid tags of the form `{% ... %}`:

    ```ini
    StylesPath = vale
    
    Vocab = Docs

    IgnoredScopes = code, tt, em

    [*.md]
    BasedOnStyles = Vale, Docs

    # TokenIgnores maps its matches to code spans in Markdown (`...`). This
    # means that a Liquid tag like {% data %} will become `{% data %}` and
    # be ignored.
    #
    # However, we need to exclude tags that are already formatted as code
    # spans to avoid creating instances like ``{% data %}``.
    TokenIgnores = [^`]({%[^%]+%})
    ```

If you make these two changes, everything will work as expected. I know this may seem convoluted but supporting non-standard Markdown isn't easy to do.

**Comment by lee-dohm** [comment]
Ok, I was misunderstanding how `TokenIgnores` was working. I thought it would essentially convert the following text:

```text
foo {% bar %} baz
```

to:

```text
foo  baz
```

The comments in your example make things much more clear. I think that we're going to keep running into edge cases like these scattered throughout our documentation. So I may need to write a parser that nulls out Liquid template directives before passing things to Vale 🤔 

Thanks very much for your patience and the clear examples!

**Comment by lee-dohm** [comment]
For example, here's another case that the updated `TokenIgnores` rule you suggest doesn't work for:

```text
* {% data reusables.apps.general-apps-restrictions %}{% endif %}
```

I assume because it replaces the first instance on the line, resulting in:

```text
* `{% data reusables.apps.general-apps-restrictions %}`{% endif %}
```

And then the second Liquid directive is skipped over because of the preceding backtick, resulting in the error:

```text
X:55  error  Did you really mean 'endif'?  Vale.Spelling 
```

**Comment by jdkato** [comment]
I'm certainly open to considering new ways to support non-standard markup, but the problem with "nulling out" matches from `TokenIgnores` (from Vale's perspective) is that it would make reporting correct locations quite difficult.

 Something like

```
* {% data reusables.apps.general-apps-restrictions %}{% endif %}
```

could be fixed with ``[^`]({%[^\n]+%})``.

**Comment by lee-dohm** [comment]
> the problem with "nulling out" matches from TokenIgnores (from Vale's perspective) is that it would make reporting correct locations quite difficult.

Yes, I see your point 🤔 

I'll keep investigating. Thanks again for your assistance! Even in doing this first pass investigation with only the built-in rules, the tool has already found true errors for us to fix 🙇‍♂️
