### ISSUE TITLE
Huge memory consuption on simple rulesets

### ISSUE THREAD

**Issue by andrewshadura** [vale-cli/vale#335]
I’m trying to make use of Vale to stylecheck [some documentation](https://gitlab.apertis.org/docs/apertis-website/-/tree/master/content/) and I’m running into frequent out of memory issues.
Initially I thought I’d feed the whole content directory at once, but even with `Vale` ruleset only enabled, I’d get a crash in GitLab, while on my local machine I’d get at least about 2 GB RAM and 5 GB virt eaten and all four cores 100% busy for pretty long time, making the GUI unusable. I then made it run through each subdirectory separately, and it worked, but only until I added `write-good` ruleset, when it started crashing on `concepts` subdirectory in GitLab. Since `write-good` gives a lot of false positive on this one due to a different style, I thought I might use a separate config, but it turns out Vale doesn’t support combining multiple config files to avoid repetition.

I’m using the official Vale Docker images on Linux, but I’ve also tried building from the source with the same results.

**Comment by jdkato** [comment]
You can try running 

```console
$ GOMAXPROCS=1 vale <some directory>
```
See https://golang.org/pkg/runtime/#GOMAXPROCS.

**Comment by andrewshadura** [comment]
I’m not sure this was understood properly. This is not a question, it is a bug: I’d expect Vale to:
1. consume much less resources
2. manage resources appropriately not to run out of them

Closing the bug doesn’t seem right to me.

**Comment by andrewshadura** [comment]
For example, the memory consumption is not addressed at all by your suggestion to limit the number of CPUs in use.
