### ISSUE TITLE
Vocab doesn't overrule other styles

### ISSUE THREAD

**Issue by prussrobin** [vale-cli/vale#336]
Hi,

we are trying to implement the vocabularies but seem to run into an issue. It looks like the accept.txt and reject.txt only overrule the Vale style. However, we would like to use it to keep the other styles (eg. write-good and Microsoft) as clean as possible so that we can update them regularly without having to re-apply our changes.

Is it possible to make the the Vocab overrule the other styles aswell?

**Comment by jdkato** [comment]
It does. Any rule that extends `spelling`, `capitalization`, or `conditional` will respect entries in `accept.txt`.

See #227 for more information.
