### ISSUE TITLE
[RFC] Moving to Docker-only installation

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#338]
I'm looking for thoughts on moving Vale to a Docker-only installation. In other words, instead of uploading the pre-built binaries to GitHub, I'd just publish the Docker image.

The motivation behind this is that I'd like to have more freedom to incorporate non-Go dependencies without having to worry about complicating the installation process. For example, as I stated in my [call for funding](https://jdkato.medium.com/the-future-of-vale-announcing-the-3x10-funding-campaign-5e665bac974a), I want to add support for multiple languages via spaCy (a Python library).

The idea of distributing a CLI tool through Docker isn't novel&mdash;both [Code Climate](https://github.com/codeclimate/codeclimate) and [AWS](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html) use similar techniques.

This will require changes to the way Vale is currently distributed with package managers, such as Homebrew and Chocolatey, but doesn't necessarily mean it will no longer be possible (Code Climate, for example, uses  Homebrew to distribute a bash wrapper script).

**Comment by ChrisChinchilla** [comment]
Unless I am misunderstanding something, I am pretty sure a lot of people use Vale outside of Docker, and actively use the binaries via a package manager, or the binary alone.

I have personally never used it with Docker at all, and had quite a few issues with getting things to work as intended when I tried. It might also break a lot of local setups, but I am not sure.

What would the process be for still creating options for package managers? Does adding non Go binaries complicate the process that much, bearing in mind the focus should be on end users wherever possible

**Comment by jdkato** [comment]
I don't think the change would be that dramatic:

- Users installing via Homebrew, Chocolatey, or Snapcraft (coming soon), will probably not even notice and their workflows will be exactly the same since the changes are all backend details.

- Users installing manually via the GitHub releases (or custom script that uses them), will either need to keep using an older version or update their install process to use Docker.

There will also be some minor performance overhead, but I think the new features would be worth it.

**Comment by ChrisChinchilla** [comment]
OK, then I don't think I really understand what this RFC is, just about building packages? Because the title of the issue makes it sound like installation with Docker will be the only option. I'll attempt to read the posts you link to and maybe summarise for others…

**Comment by jdkato** [comment]
Yes, it would (1) require changes to how the packages are built and (2) mean that Docker becomes a dependency of Vale.

This isn't going to happen immediately (if at all), though. I'm working on releasing a demo build (Docker + a Homebrew tap), so that should makes things more clear.

**Comment by jdkato** [comment]
I've played around with this idea quite a bit and I'm not happy with the performance impact.

I think I'm going to keep Vale standalone and introduce the more advanced NLP stuff as an (optional) additional download.
