### ISSUE TITLE
publish latest released docker image in hub.docker

### ISSUE THREAD

**Issue by sunix** [vale-cli/vale#343]
Hello,
It looks like the `latest` tag doesn't have the corresponding version tag in https://hub.docker.com/r/jdkato/vale/tags?page=1&ordering=last_updated
Would it be possible to publish the latest released with the tags named `v2.10.1` ? the last named version tag is `v2.9.1`.

**Comment by vinokurig** [comment]
The latest release is `v2.10.2`, it would be nice to have it as well.

**Comment by jdkato** [comment]
This is out now.

**Comment by sunix** [comment]
Thanks !
