### ISSUE TITLE
Compound words (phrases) in spell-check

### ISSUE THREAD

**Issue by fshowalter** [vale-cli/vale#345]
It  ~appears~ (confirmed in #200) phrases in `vocab.txt` don't work for spelling checks. This makes compound words and names difficult. For I only want `vu` to flag as a misspelling if it's not part of `déjà vu`, I only want `La` to flag as a misspelling if it's not part of `La Scala`, etc.. 

I ~assume~ (confirmed in #200) this is due to the spell-check parsing word-by-word and matching against the vocab lines for exclusions, so it would only see `vu` and not `déjà vu`, etc.

Based on your response to #200 this is by design so I'll abort trying to add it.

**Comment by jdkato** [comment]
Related to #346.
