### ISSUE TITLE
Is it possible to add words with dashes to the whitelist?

### ISSUE THREAD

**Issue by andreysamode** [vale-cli/vale#346]
Is it possible to add words with dashes to the accept.txt?

I added "matter-of-factly", but still get a spellcheck error:

```
# echo "matter-of-factly" | ./vale

 stdin.txt
 1:11  error  Did you really mean 'factly'?  Vale.Spelling

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

Thanks!

**Comment by jdkato** [comment]
No, not currently.

The problem is that the phrase is tokenized prior to spell checking. In a future release (perhaps the next one), you'll be able to change this, though.

**Comment by andreysamode** [comment]
Looking forward to it. Thanks for the great work!

**Comment by plaindocs** [comment]
Adding hyphen for findability. :-p

**Comment by jdkato** [comment]
This is supported now.

**Comment by andreysamode** [comment]
Excellent! Thanks!
