### ISSUE TITLE
Running Vale with the write-good, Microsoft, or Google styles seems to produce an E201 error,

### ISSUE THREAD

**Issue by rolfedh** [vale-cli/vale#348]
- OS: Fedora 34
- Install method: brew
- Vale version 2.10.2

Running Vale with the write-good, Microsoft, or Google styles produces a E201 error, and complains about "Missing the required 'extends' key", like the example shown here:

```
(base) [rolfedh@fedora-desktop studious-fortnight]$ vale README.md 
E201 Invalid value provided [/home/rolfedh/studious-fortnight/styles/write-good/.travis.yml:1:1]:

   1* language: python
   2  cache: bundler
   3  python:

Missing the required 'extends' key.

Execution stopped with code 1.
(base) [rolfedh@fedora-desktop studious-fortnight]$ 
```
You can see the full contents of my doc project, including the current `.vale.ini` file which is configured for write-good, at https://github.com/rolfedh/studious-fortnight.

Previous attempts with Google and Microsoft styles made similar complaints about their respective `/coverage/bias-free.yml` files missing the extends key even though none of their `/coverage/*` files contain extends keys. Those only appear in the rules files.

**Comment by jdkato** [comment]
Your `StylesPath` needs to only contain the actual styles, not their entire repositories. The style directories themselves are released as versioned assets  of the form `Style.zip` (see https://github.com/errata-ai/Google/releases, for example).

In other words, your current use of submodules isn't going to work. See https://github.com/errata-ai/vale/issues/273 for a related discussion.
