### ISSUE TITLE
Exceptions for "existence" rules no longer work

### ISSUE THREAD

**Issue by florian-richter** [vale-cli/vale#349]
I use a modified version of the [HeadingAcronyms](https://github.com/errata-ai/Microsoft/blob/master/Microsoft/HeadingAcronyms.yml) from the Microsoft ruleset, but I want to exclude a few acronyms that I find acceptable in headings.
This used to be supported by adding a list of `exceptions` to the yml file.
As far as I can tell, this was removed without a replacement in this [commit](https://github.com/errata-ai/vale/commit/4dfe2880fcf7ce4aadc8fcfd3cdddef5ca0bc58f).
Is there any way to change the rule to support the old behavior (preferably without a really long regex)?

Vale version: 2.10.2

**Comment by florian-richter** [comment]
I found a solution. You can use the raw tag:

```
raw:
  - (?!DISABLEDACRONYM)
```

**Comment by Mikail1010** [comment]
Hi! Could some explain how this issue was solved?

Here is a sample i am trying with extends existence


  ```
tokens:
  - 'm[aeiou]n
exceptions:
  - man
```

However it is still pointing out man as an wrong.

Am I doing something wrong?
