### ISSUE TITLE
Vale hangs indefinitely when processing Asciidoc file

### ISSUE THREAD

**Issue by ericbmerritt** [vale-cli/vale#351]
When trying to run vale on Asciidoc, vale just hangs. It looks like it's trying to call an internal adoc service defined in adoc.go on 127.0.0.1 on port 7070, but that never service never seems to comes up. So it just keeps trying to reconnect in a loop. I have been unable to figure out why. There doesn't seem to be any way to get output from vale, so it's hard to get additional information. 

vale does work when you pass `--ignore-syntax` and asciidoctor works just fine outside of vale.

* Ubuntu
* Vale version 2.10.2
* Asciidoctor version 2.0.15

Below I have attached an strace from a run.
[out.txt](https://github.com/errata-ai/vale/files/6649549/out.txt)

**Comment by jdkato** [comment]
Thanks for the report.

I wasn't able to reproduce the behavior exactly, but the next release will ensure that after a certain timeout Vale falls back to calling the CLI directly (instead of waiting for the server).

**Comment by ericbmerritt** [comment]
I can only reproduce it on one host myself. So no surprise there. Having some type of timeout makes sense. It may also make sense to add a option on the cli to force the 'going through the command line' behavior. That way if you know the problem is going to occur, you don't have to wait for the timeout each time.
