### ISSUE TITLE
Trouble ignoring slack channel names with hash/pound symbol

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#352]
I'd like to ignore all slack channel names like `#testthedocs` in my text (not marked as code).

I can't ignore the in the spellcheck, because the tokenizer doesn't include the `#`, and I can't ignore it as a token ignore because the `#` is treated as a comment in the `ini` format. Even `\x{23}`. 

Am I missing something?

**Comment by jdkato** [comment]
You should be able to escape `#`:

```ini
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
TokenIgnores = (\#\w+)

BasedOnStyles = Vale
```

(incorrect syntax highlighting notwithstanding ...)

**Comment by plaindocs** [comment]
Interesting, I was trying to escape the `\#` before without success, but your suggestion does work.

Adding `(\#[\w-]+)` to my TokenIgnores **adds** around 20 warnings to my run, but looks like it is successfully ignoring the slack channel I'm using to test, so I'll investigate that further.

If I wanted to include `**#words**` it would be something like `([\*\*]?#[\w-]+[\*\*]?)` - looks like it works.

Thanks once again

**Comment by jdkato** [comment]
If you're seeing an *increase* in alerts, my guess is that the `TokenIgnores` pattern is resulting in invalid markup somewhere along the line. 

It's hard to say why exactly this might be the case, but perhaps the use of `#` is matching a markup element it shouldn't? Are you using Markdown?

**Comment by plaindocs** [comment]
That does make sense. There is a mix of ReStructuredText and Markdown. 
I don't suppose there is a way to dump ignored strings? Might be a useful thing.

**Comment by jdkato** [comment]
No, not really.

If you could share one of the files that had an increase in alerts, I'll take a look though.

**Comment by jdkato** [comment]
Closing for now.

Feel free to share the file, though.
