### ISSUE TITLE
Parts-of-speech tagging for substitution rules?

### ISSUE THREAD

**Issue by kai687** [vale-cli/vale#353]
Hi, 

The documentation doesn't mention the `pos:` option for substitution rules, but it's mentioned in the code in `substition.go`. So, I'm assuming parts-of-speech tagging works for substitutions. I can't figure out how to use it. For example, the (now removed) Microsoft `Backend.yml` rule: 

```
pos: 'back-end/NN|backend/(?:JJ|NN)|back/\w+ end/JJ|back/(?:JJ|RB) end/\w+'
```

I'd like to troubleshoot a rule of ours, which always seems to flag `back end` as nouns incorrectly.

**Comment by jdkato** [comment]
This was an experimental feature that was never officially released.

The goal is that the [`sequence`](https://docs.errata.ai/vale/styles#sequence-v230) extension point and [Vale Studio](https://vale-studio.errata.ai/) will serve many of the same needs while also making the rules easier to debug. 

Both are still a work-in-progress, though.

**Comment by kai687** [comment]
Thanks a lot for your answer @jdkato!

**Comment by jdkato** [comment]
Quick update here: You may want to check out #356, which outlines the how to use NLP with the new `sequence` extension.
