### ISSUE TITLE
Vale Plugin for Obsidian Text Editor?

### ISSUE THREAD

**Issue by dylan-k** [vale-cli/vale#355]
[Obsidian ](https://obsidian.md/)is a text editor designed for writing with markdown files, built using Electron. Would it be possible to make something like the VScode extension that would [bring Vale to Obsidian](https://forum.obsidian.md/t/vale-plugin/20528)?

**Comment by jdkato** [comment]
The answer to this question depends almost entirely on Obsidian's API; if they expose a VSCode-like interface for developing plugins, then it should be possible.
