### ISSUE TITLE
Vale.Spelling does not run with bracketed Vocab accept word

### ISSUE THREAD

**Issue by plumbis** [vale-cli/vale#359]
- **OS** MacOS 11.4 (x86)
- **Install** Homebrew
- **Vale Version** 2.10.4

A simple example of this can be seen in this repo:
https://github.com/plumbis/vale-test

If a vocab `accept.txt` has a line that is enclosed in brackets Vale.Spelling does not run. 

**Examples:**
- no accept.txt content:
```
cat .vale/styles/Vocab/Docs/accept.txt                                                                                                                                 

vale  --config .vale/.vale.ini test.md                                                                                                                                
 test.md
 5:11  error  Did you really mean             Vale.Spelling
              'missspelling'?

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

- add `[test|TEST]` to accept.txt
```
cat .vale/styles/Vocab/Docs/accept.txt                                                                                                                                 
[test|TEST]

vale**  --config .vale/.vale.ini test.md
✔ 0 errors, 0 warnings and 0 suggestions in 1 file
```

- replace with single character match in accept.txt. 
```
cat .vale/styles/Vocab/Docs/accept.txt                                                                                                                                 
[t|T]est

vale  --config .vale/.vale.ini test.md                                                                                                                                
 test.md
 5:11  error  Did you really mean             Vale.Spelling
              'missspelling'?

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

**Additional Notes:**
* This does not happen with words in `reject.txt`. Behavior is normal.
* This does not happen when using parenthesis `( )` instead of brackets `[  ]`. Behavior is normal.

**Comment by jdkato** [comment]
Thanks for the report. This should be fixed in the next release.

**Comment by jdkato** [comment]
I finally had a chance to look into this and it's actually expected behavior.

> This does not happen when using parenthesis ( ) instead of brackets [ ]. Behavior is normal.

These are different cases: parenthesis match against the enclosed *word*, while brackets match against the enclosed *characters*.
