### ISSUE TITLE
Add more output options

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#36]
At the least, I'd like an option that incorporates `link` and `description`.

**Comment by hftf** [comment]
The `--output=context` would have been useful to me, but sadly it seems it was dropped in e65b9a4.

**Comment by jdkato** [comment]
Yes, I found the performance hit of storing a sentence or paragraph for each alert to be too high.

That said, you can find a simple example of using `--output=JSON` to achieve similar results here: https://github.com/errata-ai/vale/issues/69#issuecomment-397117660.
