### ISSUE TITLE
TokenIgnores not working

### ISSUE THREAD

**Issue by rudolf-adamkovic** [vale-cli/vale#361]
I am trying to make `TokenIgnores` work on

```
bash-5.1$ vale -v
vale version 2.10.5
```

In [the documentation](https://docs.errata.ai/vale-server/concepts/scoping#non-standard-markup), I found a `TokenIgnores` regexp that matches inline math`$...$`.

I added the regexp to my `.vale.ini`:

```
bash-5.1$ vale ls-config
{
<snip>
  "TokenIgnores": {
    "*": [
      "($+[^\\n$]+$+)"
    ]
  },
<snip>
}
```

Then, I tested:

```
bash-5.1$ echo 'This $is very interesting$!' | vale --ext=.md

 stdin.md
 1:6  warning  'very' is a weasel word!   write-good.Weasel 

✖ 0 errors, 1 warning and 0 suggestions in stdin.
```

Why is `vale` not ignoring the text between `$...$`?

**Comment by jdkato** [comment]
A shown in the documentation, you need to escape (`\`) the `$` symbols:  `TokenIgnores = (\$+[^\n$]+\$+)`.

**Comment by rudolf-adamkovic** [comment]
@jdkato Thank you _so much_ for your help!
