### ISSUE TITLE
Vale 2.11 produces unexpected repetition warnings

### ISSUE THREAD

**Issue by lornajane** [vale-cli/vale#369]
- OS: GitHub action
- Vale version 2.11.0

Vale has started producing what seems like incorrect warnings in a PR of a file we didn't change (upgraded from 2.10.2 to 2.11.0).

For example where we have the text:

```
For multi-node clusters, Aiven for OpenSearch automatically increases the ``number_of_replicas`` value to 1 if it is set to 0. This is done to avoid data loss if one node is lost.
```

The error says:
```
 [error] Vale.Repetition

'i' is repeated!
```
It says one character is repeated, but in the text it doesn't seem to be. I've disabled the `Vale.Repetition` rule for now but I'd appreciate some advice on this (it's a public repo if that helps https://github.com/aiven/devportal)

**Comment by jdkato** [comment]
Thanks for the report.

This will be fixed in the next release.
