### ISSUE TITLE
[Question] How to use Joblint via Vale?

### ISSUE THREAD

**Issue by Kristinita** [vale-cli/vale#48]
### 1. Briefly

I don't understand, how I can use at the same time [**proselint**](http://proselint.com/) + [**Joblint**](http://joblint.org/) + write-good — linters with [**green development status**](https://github.com/ValeLint/vale#reference-styles) — for my documents via Vale.

### 2. Settings

Content of my `SashaEquality.md` file:

```markdown
policewoman skillz
```

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Vale — 0.8.1,
+ Joblint — 2.3.2,
+ proselint — 0.8.0

### 3. Expected behavior

**If** `joblint SashaEquality.md`:

```markdown
D:\Киролайна>joblint SashaEquality.md

Joblint

Issue tally:
Culture  |█  (1)

• Use of bro terminology (error)
  policewoman skillz
    ✔ Remove these words.
    ✘ Bro culture terminology can really reduce the number of
    people likely to show interest. It discriminates against anyone who
    doesn't fit into a single gender-specific archetype.
```

### 4. Actual behavior

**If** `vale SashaEquality.md`:

```shell
D:\Киролайна>vale SashaEquality.md

 SashaEquality.md
 1:1  error  Consider using 'police          vale.GenderBias
             officer(s)' instead of
             'policewoman'

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

I can see [**proselint error**](https://github.com/amperser/proselint/blob/master/proselint/checks/sexism/misc.py#L31), but I can't see Joblint error.

### 5. Did not help

I download `Joblint.zip` file and place it to `D:\Киролайна\Styles` folder. I create `.vale` file in `D:\Киролайна` folder. It content:

```python
# Core settings
StylesPath = D:\Киролайна\Styles
MinAlertLevel = warning # suggestion, warning or error

# Global settings (applied to every syntax)
[*]
# List of styles to load
BasedOnStyles = Joblint
# Style.Rule = {YES, NO} to enable or disable a specific rule
vale.Editorializing = YES
# You can also change the level associated with a rule
vale.Hedging = error
…

# Syntax-specific settings
# These overwrite any conflicting global settings
[*.{md,txt}]
…

```

No effect.

Thanks.

**Comment by jdkato** [comment]
Hi,

The first thing to note is that Vale doesn't attempt emulate the output style of the other tools (it also doesn't depend on them being installed). So, given your `SashaEquality.md` file and desired configuration, the expected output would be:

```text
 SashaEquality.md
 1:1   error  Consider using 'police          proselint.GenderBias
              officer(s)' instead of
              'policewoman'.
 1:13  error  Avoid using 'skillz'            Joblint.Bro

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

To achieve this, you'll want a `.vale`  file with the following contents:

```ini
StylesPath = D:\Киролайна\Styles

[*]
# ^ Any file format
BasedOnStyles = Joblint, proselint, write-good
# ^ The styles we want to use
```
(You can also name it `_vale`, which is more common on Windows.)

Your directory structure should now be something like this:

```text
D:\Киролайна/
├──.vale
├──Styles/
│  ├── Joblint/
│  ├── proselint/
│  ├── write-good/
└── SashaEquality.md
``` 

Where `Joblint`, `proselint`, and `write-good` are the styles you can download in the README.

**Comment by jdkato** [comment]
I'm going to close this, but feel free to comment further if I didn't answer your question.
