### ISSUE TITLE
Vale does not recognise  javadoc comments 

### ISSUE THREAD

**Issue by FedorRomanov** [vale-cli/vale#51]
Together with C-style comments Java also [javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#format) comments:

> The first line contains the begin-comment delimiter ( /**).

Example:
```
/**
 * Returns an Image object that can then be painted on the screen. 
 *
 * @param  url  an absolute URL giving the base location of the image
 * @param  name the location of the image, relative to the url argument
 * @return      the image at the specified URL
 * @see         Image
 */
 public Image getImage(URL url, String name) {
  // methodimpl.
 }
```
When parsing javadoc comments as above in _java_ files, Vale complains about repeating star
```
 47:6   error    '*' is repeated!              vale.Repetition
 83:6   error    '*' is repeated!              vale.Repetition
 86:6   error    '*' is repeated!              vale.Repetition
```

As javadoc-comments are widely used in java programs these false-positives errors greatly impede Vale result analysis.
I think  that _core/format.go_ file needs to be modified. Now it treats java-comments as c-comments(obviously C does not support javadoc):
```
var CommentsByNormedExt = map[string]map[string]string{
	".c": {
		"inline":     `(//.+)|(/\*.+\*/)`,
		"blockStart": `(/\*.*)`,
		"blockEnd":   `(.*\*/)`,
	},
.....
	`\.(?:java|bsh)$`:                             {".c", "code"},
....
}
```

**Comment by jdkato** [comment]
Thanks for the report.

I've actually been working on another project that is specifically designed for extracting comments from source code in a more robust and extensible way. So, this issue is definitely on my radar.

**Comment by jdkato** [comment]
This should be fixed now. Although I haven't actually changed the way comments are handled yet -- I just made `repetition` a little more precise.
