### ISSUE TITLE
add tag to suppress Vale errors/warnings for specific case

### ISSUE THREAD

**Issue by FedorRomanov** [vale-cli/vale#52]
Some errors/warnings reported by Vale are perfectly valid English prose. Ultimately, Vale just provides suggestions, potential issues and only author should decide if text needs corrections of not.
 It would be very handy to have an ability to suppress such specific 'style smells' by using special tag, e.g.
```
<!DOCTYPE html>
<html>
<p>In many cases, ......be returned.<!--novale.begin-->Note that<!--novale.end--> the geocoder is very tolerant...
</html>
```
When processing the such tag vale should *not* report an issue:
```
1:426   warning  Consider removing 'Note that'  vale.Editorializing
```
Similar tags could be added for other file formats(Java, C, PHP, e.t.c.)

**Comment by jdkato** [comment]
This is currently available in Markdown, HTML, and reStructuredText (see https://valelint.github.io/docs/config/#using-comments).

**Comment by refaelsh** [comment]
> This is currently available in Markdown, HTML, and reStructuredText (see https://valelint.github.io/docs/config/#using-comments).

The link does not works. I was googling exactly this issue, but the link does not works.

**Comment by andrewferrier** [comment]
It appears that the documentation has moved here: https://vale.sh/docs/topics/config#markup-based-configuration
