### ISSUE TITLE
The Economist style guide link in README is broken

### ISSUE THREAD

**Issue by languitar** [vale-cli/vale#53]
Seems the economist changed the website and the existing link points to nowhere.

**Comment by jdkato** [comment]
Thanks for pointing this out. 

Unless I'm missing it, it doesn't appear that there's an online version of the guide anymore.

**Comment by languitar** [comment]
You could at least link to one of their books: https://www.amazon.de/Economist-Style-Guide-12th-ebook/dp/B01N9TXC27/ref=sr_1_4?ie=UTF8&qid=1513677620&sr=8-4&keywords=the+economist+style+guide

or archive.org?

**Comment by jdkato** [comment]
I've added a link to their store: https://shop.economist.com/products/style-guide.
