### ISSUE TITLE
Install styles

### ISSUE THREAD

**Issue by languitar** [vale-cli/vale#55]
Would it be possible to add a real install target to the makfile that also installs the existing styles (somewhere to `/usr/share/vale`)? Would be much easier to use them if they are immediately available.

This is the result of discussions regarding the package for archlinux: https://aur.archlinux.org/packages/vale/, where the policy is that packages generally only contain what upstream provides.

**Comment by jdkato** [comment]
Yes, I'd be willing to add such functionality to Vale's Makefile.

However, after a cursory glance at the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vale) file, it appears that there are some relevant build steps already in place:

```sh
package() {
    # cd "${srcdir}/build"
    msg2 'Installing...'
    install -Dm755 "${srcdir}/gopath/src/github.com/ValeLint/vale/bin/vale" "${pkgdir}/usr/bin/vale"
    install -Dm644 "${srcdir}/${pkgname}-${pkgver}/LICENSE" "${pkgdir}/usr/share/licenses/vale/LICENSE"
    install -d "${pkgdir}/usr/share/vale/styles"
    cp -r "${srcdir}/gopath/src/github.com/ValeLint/vale/styles"/* "${pkgdir}/usr/share/vale/styles/"
    chmod -R 644 "${pkgdir}/usr/share/vale/styles"/*
    find "${pkgdir}/usr/share/vale/styles" -type d -exec chmod 755 {} \;
}
```
Is there a reason why this is insufficient?

**Comment by languitar** [comment]
The installation of styles was added on my request, but the package maintainer would like to see this upstream.

**Comment by shudson310** [comment]
Using the Homebrew install of vale on Mac. I can't figure out where to place my custom styles. I have them in a dir, which is specified in the .vale.ini file in my home dir, but my custom styles don't seem to be included?

When I run vale, I get: 
vale *.md .
MyStyle.terms: yaml: line 6: did not find expected key

**Comment by jdkato** [comment]
@shudson310: It looks like your style is being included, but it contains a syntax error on line 6. Could you post the contents of `MyStyle.terms`?

**Comment by shudson310** [comment]
@jdkato here is my file. I couldn't even get a subset to work, and validated it on yamlint
[terms.yml.txt](https://github.com/errata-ai/vale/files/2011296/terms.yml.txt)

**Comment by jdkato** [comment]
There are a number of syntactic and stylistic errors in that file (mostly related to spacing). Here's the output from [adrienverge/yamllint](https://github.com/adrienverge/yamllint):

```
terms.yml
  1:1       warning  missing document start "---"  (document-start)
  7:2       error    syntax error: expected <block end>, but found '<block mapping start>'
  10:7      error    too many spaces before colon  (colons)
  11:8      error    too many spaces before colon  (colons)
  14:3      error    wrong indentation: expected 1 but found 2  (indentation)
  14:8      error    too many spaces before colon  (colons)
  21:3      error    wrong indentation: expected 1 but found 2  (indentation)
  21:8      error    too many spaces before colon  (colons)
  23:8      error    too many spaces before colon  (colons)
  31:3      error    wrong indentation: expected 1 but found 2  (indentation)
  31:11     error    too many spaces before colon  (colons)
  32:3      error    duplication of key "critical" in mapping  (key-duplicates)
  32:11     error    too many spaces before colon  (colons)
  33:3      error    duplication of key "critical" in mapping  (key-duplicates)
  33:11     error    too many spaces before colon  (colons)
  36:3      error    wrong indentation: expected 1 but found 2  (indentation)
  36:5      error    too many spaces before colon  (colons)
  356:15    error    no new line character at the end of file  (new-line-at-end-of-file)
```

Additionally, any special character as defined by [Go's regex syntax](https://golang.org/pkg/regexp/syntax/) needs to be escaped (with a `\` ) when not being used as part of a pattern. For example, here's a rule relating to the use of "e.g." in the [`TheEconomist`](https://github.com/errata-ai/vale/blob/master/styles/TheEconomist/Punctuation.yml) style:

```yaml
extends: substitution
message: Use '%s' instead of '%s'
level: error
scope: text
ignorecase: false
nonword: true
swap:
  e\.g\.: eg
  i\.e\.: ie
  \b(?:eg|ie)[^,]: eg, or ie,
```
Note the use of `e\.g\.` instead of `e.g.`.

I'm currently working on re-writing Vale's documentation and creating a [style boilerplate](https://github.com/errata-ai/vale-boilerplate), which I hope will make this process easier in the future.

**Comment by shudson310** [comment]
Thanks for the tip. I was able to use the yamllint tool to find the problems with my rules. I have it all working now. Still amazed at how fast it processes files. Thanks!

**Comment by jdkato** [comment]
Vale now ships with styles for proselint, write-good, and Joblint. I'll likely be adding more in the future, too.
