### ISSUE TITLE
line output format: wrong (relative) filename

### ISSUE THREAD

**Issue by blueyed** [vale-cli/vale#56]
Running `vale --output line /some/path/README.md` in `/some/path` will display:

> /README.md:22:45:vale.Hedging:Consider removing 'probably'

The leading slash is wrong here.

It looks like it is made relative to the current working directory, but then not sliced correctly: running it from `/some` will use `/path/README.md` (where is should be `path/README.md` for the correct relative path).

The default output format ("CLI") and "JSON" are using the full path however always.

vale version 0.9.0

**Comment by NewProggie** [comment]
I just stumpled upon this bug myself. A quick workaround (for my workflow at least) is to pipe the output of vale through sed and just prepend the missing path elements.

**Comment by jdkato** [comment]
I've changed "line" to default to returning full paths (as "CLI" and "JSON" also do). The old behavior has moved to a flag, `--relative`, which still needs to be fixed.
