### ISSUE TITLE
Language awareness or choice

### ISSUE THREAD

**Issue by jsmm** [vale-cli/vale#57]
I am using the linter in a language other than English. I have disabled all the already available English styles. Linting in several languages would be possible if it were possible to assign styles to languages and to switch languages after. 
Whether you consider this feature worth to be implemented or not, this really is a great and easy tool to use. Thank you.

**Comment by jdkato** [comment]
Hi,

Thanks for the suggestion. 

Better multilingual support has been a goal of mine for a while -- in fact, some potential configuration options were mentioned in #13.

Do you have an example of how you'd like this to work? Would it be via the configuration file or inside of the actual YAML rule definitions?
