### ISSUE TITLE
Cannot match "</quote>" in XML

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#571]
- OS: Linux
- Install method: vscode extension
- Vale version: 2.20.2

I am editing an XML document and want to match `</quote>,` to suggest moving the comma inside the quotation. But the XML plugin probably removes all <markup> and it is then impossible to match for me. Any suggestion please?

**Comment by jdkato** [comment]
You can use [`scope: raw`](https://vale.sh/docs/topics/scoping/#markup).

**Comment by tbazant** [comment]
thanks, works!
