### ISSUE TITLE
How to match a single quote?

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#572]
- OS: Linux
- Install method: vscode extension
- Vale version: 2.20.2

I  need to match a phrase surrounded by a single quote characters, such as `'dont say that'`. While for `"dont say that"` i succeeded with
```
tokens:
  - '"[^"]+"'
```
the following just does not work:
```
tokens:
  - "'[^']+'"
```
Any idea?

**Comment by jdkato** [comment]
You need to add `nonword: true`.

**Comment by tbazant** [comment]
> - "'[^']+'"

works, thanks!
