### ISSUE TITLE
Add single quotes in documentation example when list is involved

### ISSUE THREAD

**Issue by iilyak** [vale-cli/vale#574]
The documented `BlockIgnores` [here](https://vale.sh/docs/topics/scoping/#non-standard-markup) require single quotes.

The following doesn't work
```
BlockIgnores = (?s) *({< output >}.*?{< ?/ ?output >}), \
(?s) *({< highlight .* >}.*?{< ?/ ?highlight >})
```

This form works
```
BlockIgnores = '(?s) *({< output >}.*?{< ?/ ?output >})', \
'(?s) *({< highlight .* >}.*?{< ?/ ?highlight >})'
```

**Comment by iilyak** [comment]
This has been tested with the following

```
# We ignore the following
# - frontmatter like blocks (we cannot check if it is at the begining of the file)
# - codeblocks inside "```"
BlockIgnores = '(?s) *(^---$.*?^---$)',\
    '(?s) *(```.*?```)'
```

The strange thing is that `TokenIgnores` has the opposite behaviour. It doesn't work with single quotes and does work when there is not quote.

The following works
```
# We ignore the following
# - {{ ... }}
# - {: ... }
TokenIgnores = (\{\{[^\n$]+\}\}),\
    (\{:[^\n$]+\})
```

**Comment by jdillard** [comment]
I have a feeling the space that is in `BlockIgnores`, but not in `TokenIgnores`, might have some effect. I feel this unknown should be tested further and resolved before the docs are updated.

Also, possibly (un)related, if you add `BlockIgnores` and `TokenIgnores` to your config, they don't seem to show up in `vale ls-config`:
```json
{
  "BlockIgnores": {},
  [...]
  "TokenIgnores": {},
  "WordTemplate": "",
  "DictionaryPath": "",
  "NLPEndpoint": ""
}
```

**Comment by jdkato** [comment]
I can't reproduce either of these issues (quoting or `ls-config`).

```
BlockIgnores = '(?s) *(^---$.*?^---$)',\
    '(?s) *(```.*?```)'
```

Both of these blocks (front matter and "```"-delimited code) are ignored by default.

**Comment by jdillard** [comment]
heh, I accidentally put the format-specific settings in the core settings area :facepalm: 

I don't know if there is config validation, but it might be worth checking if there are format-specific settings in the core area to prevent foot shooting.
