### ISSUE TITLE
Linting non-existing file returns 1 file

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vale-cli/vale#58]
Perhaps related to #22, linting a path that does not exist will yield `✔ 0 errors, 0 warnings and 0 suggestions in 1 file.`

Probably should be zero files to avoid giving the impression that something was actually linted.

**Comment by jdkato** [comment]
Thanks for the report -- I'll look into it.

**Comment by jdkato** [comment]
I had a chance to look into this: Vale isn't actually misrepresenting a nonexistent file, it's treating the path as `stdin`. For example,

```console
$ vale actually # where 'actually' is technically a nonexistent file

stdin.txt
1:1  warning  Consider removing 'actually'  vale.Editorializing 

✖ 0 errors, 1 warning and 0 suggestions in 1 file.
```
For clarity, I'm thinking of changing "in n file(s)" to "in stdin" for this case.
