### ISSUE TITLE
Local package by path renames source ini file.

### ISSUE THREAD

**Issue by napcs** [vale-cli/vale#583]
Vale version 2.23.0
macOS Monteray (M1 Max)

If I specify a local package that has a `.vale.ini` file and a `styles` directory like this:

```
Packages =  /Users/brianhogan/dev/vale-custom
```

and I run `vale sync`, the package loads fine but the source `.vale.ini` file gets renamed.

Looking at the code, it looks like the rename is happening before the file copy operation:

https://github.com/errata-ai/vale/blob/v2/cmd/vale/sync.go#L153

**Comment by jdkato** [comment]
This will be fixed in the next release.
