### ISSUE TITLE
Add support for linting `alt`/ `title` attributes

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#59]
We currently ignore all HTML tag attributes but, unlike the others, `alt` and `title` actually contain real text.

Some examples:

###### Markdown

```
![Logo](/images/logo.png)
```
###### AsciiDoc 

```
image:logo.png[Logo]
```

###### reStructuredText

```
.. image:: /images/logo.png
   :alt: Logo
```

**Comment by GuessWhoSamFoo** [comment]
If you like appealing to the SEO crowd, consider generalizing this to og metadata as well. Thanks for opening this issue!

**Comment by jdkato** [comment]
This should be working now.
