### ISSUE TITLE
Vale on Snap does not download/sync packages

### ISSUE THREAD

**Issue by davidsneighbour** [vale-cli/vale#590]
- OS: Ubuntu 22.04
- Install method: Snap
- Vale version: latest version on Snap via `snap install --edge vale`

Using the Snap vale the whole "use a name of a package on the official package hub and run `vale sync` to load it" does not work. "Not work" in sense of it does not download the packages, it does not synch, it does nothing other than complaining that the packages are not known. Removing the Vale package from Snap and downloading a precompiled vale from Github into the path solves this. 

To my knowledge Snap has issues accessing anything inside of the home directory on "normal" packages and requires a `--classic` parameter on install to take the tool out of the sandbox. Maybe that "just" solves the issue. 

Either way, I don't think the installation instructions should list the Snap package as the main way to add Vale to a system. It doesn't work for this kind of applications.

---

Disregard the rest of the original issue, I see it's already there... 

Something like the following works and can be easily done by anyone with requirements to run Vale:

- Download the latest version from LINK
- extract via `tar -xvzf download.tar.gz` (where download is the latest version and system name)
- move the file to `/usr/bin` (or any other location that is in the $PATH) with `sudo mv download/vale /usr/bin/`
- restart the terminal and test
--

**Comment by jdkato** [comment]
> Either way, I don't think the installation instructions should list the Snap package as the main way to add Vale to a system. It doesn't work for this kind of applications.

It's possible (see, e.g., Hugo) but the current version is quite outdated, so I've removed it from the docs for now.
