### ISSUE TITLE
Smart quote tokens not parsed

### ISSUE THREAD

**Issue by m-czernek** [vale-cli/vale#591]
We are having difficulties writing a rule that catches single smart quote character.

Given the following rule:

```
extends: existence
message: Use straight quotes instead of smart quotes.
level: error
nonword: true
action:
tokens:
  - “
  - ”
  - ’
```

We can catch the first two tokens (double smart quotes); however, the `U+2019` single smart quote is not caught by vale:

```
Hello”world. <- error (correct)
Hello’world. <- no error (incorrect)
```

This is on Fedora Linux with the latest vale installed directly from the Github release as a binary (using my RPM method):

```
$ vale -v
vale version 2.24.0
```

**Comment by jdkato** [comment]
I'm assuming you're using AsciiDoc, right?

If so, see https://github.com/errata-ai/vale/issues/206#issuecomment-638923406.

**Comment by m-czernek** [comment]
We do use AsciiDoc.

Borrowing from your comment:

> If you use a smart character in your rule, then Vale won't be able to find the word in the source document because it was written with a regular character. The only way for this to work at the moment is to use a smart character in the document and the rule.

That is exactly the behavior I would expect, i.e.:

* If the rule contains the `'` character, then it matches iif the source uses the `'` character.
* If the rule  contains the `’` character, then it matches iif the source uses the `’` character.

As these two characters are different, I would expect them to require separate rules (if the users of Vale choose to do so of course). 

Could we by any chance have a way to disable the assumption (e.g. by using env variables, some config option somewhere, etc.) that smart quotes are identical to standard quotes? 


Just to provide a little bit of context, smart quotes are bad for parts of technical texts. For example, they make any terminal commands unusable, e.g. `$ ls /tmp | grep ’example’` errors out in a shell yet to an inexperienced user, it is not obvious why.

We wanted to create a rule that would catch IDEs or operating systems (macOS in particular) converting quotes to smart quotes without authors noticing.

**Comment by jdkato** [comment]
> Could we by any chance have a way to disable the assumption (e.g. by using env variables, some config option somewhere, etc.) that smart quotes are identical to standard quotes?

I think you've misunderstood the issue -- there's no such assumption on behalf of Vale. The issue is that Asciidoctor performs a "dumb" -> "smart" conversion, so there's no way to know what the source actually was. The ideal solution would be an option to disable this behavior in Asciidoctor, but that doesn't exist (to my knowledge).

A workaround is to use `scope: raw` in your rule.

**Comment by jdkato** [comment]
(https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/#apostrophe-syntax)

**Comment by m-czernek** [comment]
Just tried `scope: raw` and it seems to do what I'd expect it to do. Thank you for your help!
