### ISSUE TITLE
Feature Request: Markup-based configuration in org-mode files

### ISSUE THREAD

**Issue by rwilson4** [vale-cli/vale#593]
Vale version: 2.23.3

I use Vale mostly in org-mode in Emacs. Works great! I'd like to be able to disable Vale for certain sections. This is supported in HTML and Markdown but doesn't seem to be supported in org-mode. Actually, the ideal behavior for me would be to "opt in" certain sections to linting. I don't really care about linting every single section, just sections I intend to export for external audiences.

The most "org-anic" (get it?) way of accomplishing that would be:
- global default of linting or not linting everything, perhaps set in .vale.ini
- file-level override of global default, set with a file-level property, LINT, set equal to t or nil.
   - Setting LINT=nil at the file level means "don't lint this file, except for sections marked as LINT = t"
 - sections can have a property, LINT, that overrides the file-level property.

**Comment by jdkato** [comment]
This will be available in the next release. The implementation is the same as it is in other formats (effectively, "opt out"): 

- https://vale.sh/docs/topics/scoping/#non-standard-markup
- https://vale.sh/docs/topics/config/#markup-based-configuration
