### ISSUE TITLE
Inline code is not ignored by Vale.Spelling

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#594]
I thought by default, inline code should be ignored by vale?

![Screenshot at Mar 27 09-43-05](https://user-images.githubusercontent.com/39619599/227822460-93793b53-52c7-483f-99cc-ec2693a93891.png)

Source can be found [here](https://github.com/api7/docs/pull/65/files#diff-cde104ebd752eda7205c7fec9e362c60117d2c5f7524da304fdfcbf68a6bcfe7R70)

i've also tried adding `TokenIgnores = `(`[^`]*`)` ` in `.vale.ini` but it didn't work either. 

Any help would be appreciated.

**Comment by jdkato** [comment]
You have two instances of "httpbin" on that line -- one that is formatted as inline code and one that is not. Vale is reporting the latter:

> ... port 80 of the **httpbin** service in the backend.

**Comment by kayx23** [comment]
oops... my bad... thank you!
