### ISSUE TITLE
Feature: Xcode specific output format

### ISSUE THREAD

**Issue by jeroenleenarts** [vale-cli/vale#603]
For Xcode Vale can be integrated as a build step.

In fact, I am about to release a blog post on this very topic and I added it to a public repository already.

See this commit: https://github.com/GetStream/stream-chat-swift/commit/89ed43a0fe979f397f9eb1da1ae214f03474ee61
This is working.

It would be amazing if Vale would get support for Xcode specific output format, it would allow Xcode to show the resulting linter warnings inline in the code editor and list them in the issue navigator.

An output format that works for Xcode is this one:
```
{{range .Files}}
{{- $path := .Path -}}
{{- range .Alerts -}}
{{$path}}:{{.Line}}:{{index .Span 0}}: {{.Severity}}: {{.Check}}:{{.Message}}
{{end -}}
{{end -}}
```

On top of that, integration with Xcode requires a little bit of finese.
- Any markdown you want to display in Xcode, should be part of the project, making sure it is not part of a target.
- A Script Build step needs to be added running a CLI command that results in a specific format (see above).
- This build step should not do any conditional execution. (Xcode has a mechanism enabling conditional execution of build steps if certain files are touched. Vale executes quickly enough to not be an issue in this regard at all.)
- Xcode parses build step output by default and picks up any line items as issues if they adhere to a specific format.

My suggestion is to add an output option to the `--output` argument called `xcode` which outputs vale's findings formatted as indicated by the snippet in this issue. Having an Xcode option and a proper description, with screenshots and steps to take, on the integration page of Vale, would open up broader usage of Vale in any Xcode-based project.

I can add this output format myself if you'd like.

**Comment by jdkato** [comment]
I think documenting the steps for integrating with Xcode would indeed be helpful. 

However, as I've said in other issues (such as #365), the *purpose* of output templates is to be able to support these use cases. I don't see the need to add a named option for every integration.

**Comment by jeroenleenarts** [comment]
Allright, I will add it to library.json once my blog post is live. :)
