### ISSUE TITLE
Single vale.ini to apply rules to different folders

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#605]
Hi, is it possible to create a single .vale.ini that applies different rules to different folders. I know it's possible using different vale config files in different folders, but the request is that we have a single .vale.ini file to control everything. So I'm investigating if it's possible.

I want a single style to apply to an upper level folder, but two styles to apply to a lower level folder... in this case, the welcome folder.

This is what my directory looks like:

```
.
├── index.adoc
└── welcome
│   └── index.adoc
├── .vale
│   └── styles
│       ├── Style1
│       ├── Style2
├── .vale.ini
```

This is what my .vale.ini looks like:
```
StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = Style1, Style2

[[!.]*.adoc]
BasedOnStyles = Style1

# Additionally apply Style2 to .adoc files in the welcome folder
[*welcome/*.adoc]
BasedOnStyles = Style1, Style2
```

This works when I run vale at the command line from the higher level folder. Style1 only runs on index.adoc. And Style 1 and Style2 run on welcome/index.adoc . However, if I change directory into the welcome folder, and then run vale again, only Style1 runs. At the lower level folder, I think Vale is looking at the .vale.ini and not running style2 because it doesn't see a welcome folder at that level. But it runs as desired at the higher level folder because it can see the welcome folder.

Is there any way to apply different styles to different folders using a single .vale.ini?

**Comment by jdkato** [comment]
Yes, the sections are evaluated relative to the `.vale.ini` file. Changing this would break the ability to write things like:

```ini
[README.md]
BasedOnStyles = Vale
```

So, you'll either need to run Vale from the root or use a subfolder configuration.
