### ISSUE TITLE
Support populating `%s` specifiers with capture groups

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#612]
_Originally posted by @jdkato in https://github.com/errata-ai/vale/discussions/609#discussioncomment-5666196_

**Comment by daobrien** [comment]
This would be a great improvement. We'd take advantage of this immediately. Thanks

**Comment by jvoisin** [comment]
I wanted to take advantage of this to correct things like `le avion → l'avion`, `le ane → l'âne` in French :<

**Comment by jdkato** [comment]
I'm going to try to get this into the next release.
