### ISSUE TITLE
Inline code in a table being picked up by a rule

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#613]
Hi, I have a custom `Whitespaces.yml` rule of the following:

```
extends: existence
message: "'%s' should have one whitespace. If it is an expression, please put it in inline code to not fail on this check."
level: error
nonword: true
tokens:
  - '[a-zA-Z] {2,}[a-zA-Z]'  # hello  world
  - '[a-zA-Z] {1,}[.?!,]'    # hello ?
  - '[.?!,][A-Z]'            # hello.World
  - '[.?!,] {2,}[A-Z]'       # hello.  World
```

In markdown file, I have something like the following:
![image](https://user-images.githubusercontent.com/39619599/233831976-ee8ff8de-23e2-4e2c-8540-52270fd67284.png)

To my surprise, Vale marked it: 
![image](https://user-images.githubusercontent.com/39619599/233831714-8663818e-b00a-4065-9124-15bcbbb54cba.png)

Note that I have not altered globally config anywhere. Previously all code were escaped for checking. 

Any idea?

**Comment by jdkato** [comment]
The "!AND" (unformatted) on line 33 is exactly what your rule is looking for?

What is surprising here?

**Comment by jdkato** [comment]
I think you actually want your third pattern to be something like `[a-z][.?!,][A-Z]`.

**Comment by kayx23** [comment]
> The "!AND" (unformatted) on line 33 is exactly what your rule is looking for?
> 
> What is surprising here?

@jdkato Thanks for your suggestions. 

The surprise is `!AND(A,B)` is inline code but it's being picked up by the rule. I was under the impression that code blocks and inline code will not be checked (on a global scale) according doc from [here](https://vale.sh/docs/topics/scoping/#html), but just realized this is stated for HTML not markdown. I previously interpreted that as when markdown is rendered to html, those rules still apply. I guess not?

**Comment by jdkato** [comment]
> The surprise is `!AND(A,B)` is inline code but it's being picked up by the rule.

It's *not* the inline code that is resulting in a match. You have an instance of "!AND" (and "!OR") that are not formatted as inline code.

**Comment by kayx23** [comment]
@jdkato I know, I mean I thought **content in inline code** were globally not checked? because that's code?

**Comment by jdkato** [comment]
> @jdkato I know, I mean I thought **content in inline code** were globally not checked? because that's code?

Yes, this is correct.

![233831976-ee8ff8de-23e2-4e2c-8540-52270fd67284](https://user-images.githubusercontent.com/8785025/233878454-e5ed8312-98e4-4278-bd7d-c82689720fe6.png)

The issue, as shown above, is that "!AND" and "!OR" are *not* inline code. Therefore, the pattern `[.?!,][A-Z]` will match, as it should.

**Comment by kayx23** [comment]
@jdkato JEEZ. SORRY IM BLIND.
