### ISSUE TITLE
Code block not skipped if using ``pwsh-session``

### ISSUE THREAD

**Issue by germa89** [vale-cli/vale#619]
### Check for existing issues

- [X] Completed

### Environment

Ubuntu

### Describe the bug / provide steps to reproduce it

If I am using Google style and skipping code blocks, the following rst won't generate an error:

```rst
.. code:: pwsh

   & myprogram
   To disable this check, set the BLABLA environment
```

However if I have:

```rst
.. code:: pwsh-session

   & myprogram
   To disable this check, set the BLABLA environment
```

I get:
```
[Google.WordList] Use 'select' instead of 'check'.
```

**Comment by jdkato** [comment]
This will be fixed in the next release.
