### ISSUE TITLE
Comments in rst broken

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#62]
Heya,

Looks to me like 

```
.. vale off

This is some text ACT test

This is some text ACT test

.. vale on
```

isn't working at the mo. I also used it on WTD here https://github.com/writethedocs/www/commit/08ee26350149a1c23801567f4ac6bc6f2ad2b700 and they are also getting detected.

**Comment by jdkato** [comment]
I've attempted to test all of your examples and here are my results:

1. When I run Vale (0.10.1; stock config) on the provided snippet, I get the expected:

    ```
    ✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
    ```
    Similarly, [this test file](https://raw.githubusercontent.com/ValeLint/vale/master/fixtures/comments/test.rst) passes on AppVeyor, Travis CI, and locally.

2. When I run Vale (using WTD's config) on `about-us.rst`, `recap-retrospective.rst`, and `team.rst`, I get:

    ```
     team.rst
     214:16  error  Consider using 'graduates'      vale.GenderBias 
                    instead of 'Alumni'      
    ````
   
    If I remove the comments, I get:

    ```
     recap-retrospective.rst
     39:56  error    Consider using 'everyone'       vale.GenderBias 
                     instead of 'guys'                               
    
     about-us.rst
     36:240  warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                      'Unnecessary words'                                           
     51:27   warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                      'Unnecessary words'                                           
     team.rst
     212:16  error  Consider using 'graduates'      vale.GenderBias 
                    instead of 'Alumni'
    ```

So, it appears that Vale 0.10.1 is indeed incorrectly reporting the 'Alumni' issue (which appears to be a bug with how comments and headings interact) but the others should be working. 

I'm assuming you received different results?

**Comment by plaindocs** [comment]
```
~/WTDdocs (master) $ vale docs/about-us.rst 

 docs/about-us.rst
 38:240  warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                  'Unnecessary words'                                           
 57:27   warning  'for free' - See section        TheEconomist.UnnecessaryWords 
                  'Unnecessary words'                                           

✖ 0 errors, 2 warnings and 0 suggestions in 1 file.
 ~/WTDdocs (master) $ awk 'FNR>=34 && FNR<=42' docs/about-us.rst 
We want to:

.. vale off

* Build a sustainable organization with paid staff to run the community operations instead of relying on volunteers for ongoing global maintenance and support. Our network of volunteers is invaluable, but we cannot expect people to "do it for free" in the long term.

.. vale on

* Create stable infrastructure for the community to grow on top of so that we are not relying on specific individuals to manage ongoing operations. This allows people to step up or down from teams and roles without damaging the framework of the community.
```

**Comment by plaindocs** [comment]
I can understand the comment heading working differntly to other paragraph level code. (Although it is still probably a bug) 

I'm also getting these kinds of lines for *each* file, which doesn't seem normal but I'm not sure if related or not.

```
ERROR 2018/03/16 18:11:43 organizer-guide/confs/venues-logistics.rst
ERROR 2018/03/16 18:11:43 organizer-guide/confs/volunteers.rst
```

**Comment by plaindocs** [comment]
Yeah, so I seem to have had a corrupt binary, as evidenced from #63 and now all of these pass, even the Heading...

**Comment by plaindocs** [comment]
Thanks again @jdkato !

**Comment by jdkato** [comment]
No problem -- feel free to report any other issues you run into.

(And I'll investigate this disappearing heading + comment bug.)
