### ISSUE TITLE
Add Support for Regex Match Transformations in Actions

### ISSUE THREAD

**Issue by p0fi** [vale-cli/vale#621]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be really cool if we could have a way to offer actions that could fix for example casing with regex support. I would like to specify a regex pattern to match something and then offer a transformation (e.g. casing change to PascalCase or something like that) of that exact match as an action. This seems not possible today.

**Comment by jdkato** [comment]
This will be possible in the next release.
