### ISSUE TITLE
How to have only one vale rule check for code block?

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#625]
By default, Vale ignores inline code and fenced code block in markdown. I would like to have a custom rule (e.g. `CheckCodeString.yml`) to check if the existence of a string in code blocks, without altering the global setting of omitting code. 

I have attempted to set the `scope` in config to various things in [this doc](https://vale.sh/docs/topics/scoping) but none worked. 

Hope to get some help here. Thanks!

**Comment by jdkato** [comment]
You want `scope: raw`.
