### ISSUE TITLE
Unclear Error Message for Invalid `.yml` Config

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#626]
![image](https://user-images.githubusercontent.com/39619599/236814439-6074b9c9-7338-4bd5-92b2-a8f14aee37bd.png)

The actual error is I incorrectly put the closing quotation mark in the middle of the message for some reason. Yet it was difficult to tell what the issue was from the given information. Any room for improvement here?

**Comment by jdkato** [comment]
These messages are coming from an external library. In cases where the YAML is invalid (like this one), I think showing the file + context + error is as good as it's going to get.

**Comment by kayx23** [comment]
Ok. However I don't agree the error message is clear. Try to look at the messages in the screenshot without my arrow pointing out where the problem is -- what does the issue seem to be for you?

**Comment by jdkato** [comment]
Well, it *is* clear to me ... but that's largely besides the point. 

My intent was not to say that the message is perfect (or even *good*), but a "fix" here is not something I see myself dedicating time to as it's something that needs to be done on the YAML-parsing side (not strictly relevant to Vale).

If you'd like, you can contribute an improvement to the upstream library: https://github.com/go-yaml/yaml.

I would also suggest installing some form of a YAML linting plugin for your editor of choice, which should help highlight such issues:

![Screenshot 2023-05-19 at 11 27 58 PM](https://github.com/errata-ai/vale/assets/8785025/7b6da7fb-821e-475b-badc-f493d41a5593)

**Comment by kayx23** [comment]
Ok, that makes sense. And thanks for the suggestion.
