### ISSUE TITLE
Pattern in substitution is not recognized unless it has a space

### ISSUE THREAD

**Issue by theletterf** [vale-cli/vale#627]
### Check for existing issues

- [X] Completed

### Environment

OS: macOS
Install method: Homebrew
Vale version: 2.25.0
Also tested in Vale Studio

### Describe the bug / provide steps to reproduce it

The pattern in this rule is ignored or doesn't trigger matches:

```
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
action:
  name: replace
swap:
  'Control \+': Control+
```

It works if a space is added after `\+` though:

```
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
action:
  name: replace
swap:
  'Control \+ ': Control+
```

**Comment by jdkato** [comment]
This is expected behavior. You presumably want to add `nonword: true`.

Clicking the regex101 button (`</>`) in Vale Studio is a good way to see what is happening here.
