### ISSUE TITLE
scope: sentence does not ignore <pre> markup

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#629]
### Check for existing issues

- [X] Completed

### Environment

Linux
VSCode
2.20.2

### Describe the bug / provide steps to reproduce it

Scoping other than `raw` still checks inside `<pre class="screen"/> markup but should ignore it.

`.vale.ini` config:

```
StylesPath = /home/tbazant/devel/
MinAlertLevel = suggestion
[asciidoctor]
experimental = YES
[*.xml]
Transform = /usr/share/xml/docbook/stylesheet/suse2022-ns/xhtml/docbook.xsl
BasedOnStyles = suse-vale-styleguide
[*.{md,txt,adoc}]
BasedOnStyles = suse-vale-styleguide
```

The bug is visible in:

![obrazek](https://github.com/errata-ai/vale/assets/2240174/30139525-c3fd-48a9-9e92-afe84a0739fc)

Vale rules in action:

```
cat Colons.yml
extends: existence
message: "'%s' should be in lowercase."
nonword: true
level: warning
scope: sentence
tokens:
  - ': [A-Z]'

cat NoQuotes.yml
extends: existence
message: "Consider replacing quotation marks with <quote/> in '%s'."
scope: sentence
nonword: true
level: warning
tokens:
  - '"[^"]+"'
  - "'[^']+'"
```

**Comment by jdkato** [comment]
I can't reproduce this. Can you share the relevant XML file?

Also, as an aside, neither of these rules *should* be sentence-scoped as it unnecessarily incurs performance overhead. Generally, you should use the default scope `text` (i.e., omit the `scope` key) unless the rule specifically requires another.

**Comment by tbazant** [comment]
The file is at https://github.com/SUSE/doc-modular/blob/d1549959152686aef4c34af2e17ae18f0c87b1b6/references/systemd-timer-manage.xml, starting with line 51

**Comment by tbazant** [comment]
Strangely, if i create HTML with the same type of problem, it works as expected:
![obrazek](https://github.com/errata-ai/vale/assets/2240174/479f35e8-e055-4823-a75b-a84df4700411)

**Comment by jdkato** [comment]
The issue here is that the generated HTML includes the following:

```html
<div class="crumbs">
  <div class="growth-inhibitor">
    ...
  </div>
</div>
```
where "..." is the entire, unprocessed text of the XML file. In other words, something like "Run helloworld.service" is appearing twice: once outside of the `pre` tag (in the `crumbs` div) and once where it should be.

Do you know if there's a parameter Vale can use to disable this?

**Comment by tbazant** [comment]
you are right, it's a problem of the source stuff, thanks a lot!!!
