### ISSUE TITLE
Vale does not display version info

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#63]
```
$ go/bin/vale -v
vale version 
````

**Comment by jdkato** [comment]
That's odd.

1. When I build from source or install from Homebrew, I get `vale version 0.10.1`.
2. When I install with `go get github.com/ValeLint/vale`, I get `vale version master` (as can be seen from this [CI build](https://travis-ci.org/ValeLint/docs/builds/354444299#L488)).

It looks like you've installed via `go get`, correct?

**Comment by plaindocs** [comment]
`go get` correct.

**Comment by plaindocs** [comment]
I wonder if the binary is getting corrupted or something.

**Comment by plaindocs** [comment]
I can try building from source. I need to set some go dirs?

**Comment by jdkato** [comment]
Since you appear to have a `$GOPATH` set up already (`~/go`, it appears), should just need to run `make build` from the root directory.

**Comment by plaindocs** [comment]
OK, deleted the contents of the `go` dir, reinstalled with `go get` and now get 
```
$ vale -v
vale version master
```
