### ISSUE TITLE
Support Ignore Paths

### ISSUE THREAD

**Issue by ijrsvt** [vale-cli/vale#630]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to run `vale` on a repo, but there is a single sub-folder that I would like to ignore.

**Comment by jdkato** [comment]
You can do this with the [`--glob`](https://vale.sh/manual/glob/) flag; see https://github.com/errata-ai/vale/discussions/623#discussioncomment-5835732 for an example.
