### ISSUE TITLE
Ignore intended non-text in comments, e.g.: URLs, `inline code`

### ISSUE THREAD

**Issue by rpatterson** [vale-cli/vale#633]
### Check for existing issues

- [X] Completed

### Describe the feature

I often include URLs or code references in comments and find it valuable when others do as well.   For example:

```
#!/usr/bin/env python3

# Copied from https://foo.example.com/install.py
# Specifically from `FooClass.foo_method()`:

def foo_method():
...
```

Such comments clarify not only intention but also provide valuable clues for addressing future issues.  It would be valuable to find prose flaws in comments outside such content without disabling those rules altogether.

I'd be happy to adjust my comments to meet whatever convention Vale adopts.  I'm a reStructuredText fan, but I'd propose a general URL regexp and Markdown inline code regexp as a starting point.

**Comment by rpatterson** [comment]
Having thought about it a bit further, there's further value in standardizing on a particular markup.  If Vale chooses Markdown, as I would begrudgingly advocate for, then excluding `\([^)]+\)` is probably better than trying to use a URL regexp like `[a-z]+://*[a-z]?...` or whatever a "correct" URI regexp would be.

**Comment by jdkato** [comment]
You can do this with any combination (code/markup) of supported formats.

See [v2.19.0](https://github.com/errata-ai/vale/releases/tag/v2.19.0) for more information.

Also, there's no regex involved here: we use dedicated parsing libraries (goldmark, AsciiDoctor, rst2html, etc.), so you have access to any supported syntax.

(I know this needs to be documented better ...)

**Comment by jdkato** [comment]
There are more examples here:

https://github.com/errata-ai/vale/tree/v2/testdata/fixtures/fragments

**Comment by rpatterson** [comment]
> You can do this with any combination (code/markup) of supported formats.
> 
> See [v2.19.0](https://github.com/errata-ai/vale/releases/tag/v2.19.0) for more information.
> 
> (I know this needs to be documented better ...)

Grateful user here, so don't take this the wrong way, but yeah it needs to be documented better.  Not a comp-sci person, but I'm a developer with what I sometimes call senior experience and I can't figure out from that link how to accomplish what I suggest from your comment.  Can you give some hints here until such documentation happens?  Maybe it could even be a start.

(BTW, Vale would rightfully tell me to STFU and be more brief.  Vale is already [making me better](https://gitlab.com/rpatterson/project-structure/-/commit/91ddfbbff9daed953255eee0fde7591c36c38c48).  Just not here.)

**Comment by rpatterson** [comment]
> There are more examples here:

Can you help understand what there to focus on?  I started with the `./.vale.ini` and didn't find anything revealing.  I noted [the vocabularies](https://github.com/errata-ai/vale/blob/v2/testdata/fixtures/fragments/styles/Vocab/Base/accept.txt) but its not obvious to me how that applies?  Are you saying I should add a regular expression like I describe there?  Does it have to do with the rest of the sample code in that test fixture?

**Comment by jdkato** [comment]
Assuming you want Python + Markdown, all you need to do is add the following to your `.vale.ini`:

```ini
[formats]
# Comments (block and inline) will now be treated as Markdown.
py = md
```

One thing to note, though, is that  configuration for `md` files (e.g., `[*.md]`) now applies to all `py` files.

**Comment by rpatterson** [comment]
> ```ini
> [formats]
> # Comments (block and inline) will now be treated as Markdown.
> py = md
> ```

Oh, that's not what I understood from the documentation.  I thought that would mean that Vale would use its syntax-awareness to parse my `*.py` files as if they were `*.md` files in terms of isolating prose from markup.  No?

**Comment by rpatterson** [comment]
What about my question in response to your suggestion, @jdkato?

> I thought that would mean that Vale would use its syntax-awareness to parse my `*.py` files as if they were `*.md` files in terms of isolating prose from markup. No?

IOW, wouldn't that just mean that Vale would treat the *whole* Python file as if it were Markdown?  For example, wouldn't Vale then think the falling was spelling errors at least?:

```
def foo():
```

**Comment by jdkato** [comment]
Did you try it? Because this is not how it works.

The `formats` section changes *how* text is linted, not *what* text is linted:

<img width="816" alt="Screenshot 2023-05-18 at 4 56 02 PM" src="https://github.com/errata-ai/vale/assets/8785025/edee2601-dd37-4533-8586-5d3815be2c03">

**Comment by rpatterson** [comment]
> The `formats` section changes _how_ text is linted, not _what_ text is linted:

If true, the way you put it is much clearer than [the docs](https://vale.sh/docs/topics/config/#format-associations):

> Format associations allow you to associate an “unknown” file extension with a supported [file format](https://vale.sh/docs/topics/scoping/)...  In the example above, we’re telling Vale to treat MDX files as Markdown files.

But my testing indicates to me that the latter from the docs describes the current behavior, not what you describe.  I wrote a quick little script in an unsupported format and extension with:

1. a misspelling in a comment
2. Markdown inline code containing misspelling in a comment
3. Markdown inline code triggering a spacing error in a comment
4. and finally a non-comment source line containing a misspelling:

```
$ cat ./foo.sh 
# fdkjahgfe
# From: `afuihef`
# and `mdule.Class.method`
gtuohd
```

I added a basic configuration including no format mappings:

```
$ cat ./.vale.ini
StylesPath = ./styles
MinAlertLevel = suggestion
Packages = Microsoft

[formats]

[*]
BasedOnStyles = Vale, Microsoft
```

Without adding any format mapping, Vale reports errors on both comments and source.  Oddly, it does *not* report misspelling on the Markdown inline code but *does* report a spacing error on the other Markdown inline code.  So it doesn't seem like it's treating it the unsupported extension as text as I would expect *and* the handling of Markdown inline code seems inconsistent:

```
$ docker compose run --rm vale ./foo.sh 

 foo.sh
 1:3   error  Did you really mean             Vale.Spelling     
              'fdkjahgfe'?                                      
 3:12  error  'e.C' should have one space.    Microsoft.Spacing 
 4:1   error  Did you really mean 'gtuohd'?   Vale.Spelling     

✖ 3 errors, 0 warnings and 0 suggestions in 1 file.
```

Then when I map the format to a code extension supported by vale whose comment syntax is correct for the script, `sh = pl`, Vale stops reporting the misspelling in source, as expected:

```
$  docker compose run --rm vale ./foo.sh 

 foo.sh
 1:3   error  Did you really mean             Vale.Spelling     
              'fdkjahgfe'?                                      
 3:12  error  'e.C' should have one space.    Microsoft.Spacing 

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

If I change the format mapping to Markdown as you suggest with a `sh = md` format mapping, Vale reports *everything* as Markdown markup as described in the docs as opposed to the behavior you describe.  Note the comments are treated as headings:

```
$ docker compose run --rm vale ./foo.sh 

 foo.sh
 1:3  error       Did you really mean             Vale.Spelling      
                  'fdkjahgfe'?                                       
 1:3  suggestion  'fdkjahgfe' should use          Microsoft.Headings 
                  sentence-style capitalization.                     
 3:1  suggestion  'and ******************'        Microsoft.Headings 
                  should use sentence-style                          
                  capitalization.                                    
 4:1  error       Did you really mean 'gtuohd'?   Vale.Spelling      

✖ 2 errors, 0 warnings and 2 suggestions in 1 file.
```

So the `sh = pl` mapping is still the closest to the intended effect, but there's still an issue of how Vale is treating Markup inline code enclosed in back-ticks.  Why does Vale *not* report the misspelling in the back-ticks on line 2?  Why *does* Vale report the spacing issue in the back-ticks on line 3?

**Comment by jdkato** [comment]
This is a different case than what we've been discussing; as I said in my first comment, assigning an embedded markup format only works for a combination of already-supported formats (such as Python and Markdown).

In the case of `sh` files, what you're really trying to say is `sh = pl = md`, but that's not possible. 

In other words,

- if you run Vale on a `sh` file with no `[format]` configuration specified, the entire file will be linted.
- if you run Vale on a `py` file (or another language [listed here](https://vale.sh/docs/topics/scoping/#code-1)) with no `[format]` configuration specified, only the comments will be linted.

Assigning an embedded markup format with `[format]` will not change either of these facts.

If you'd like support for `sh` files (or others), they can be added here: https://github.com/errata-ai/vale/blob/v2/internal/core/format.go.

---

Also:

I understand that the docs are not perfect and my explanations may not always be clear to you, but I can assure you that my intent is not to mislead. 

This is a 1-person project and my time is divided between developing, documenting, *and* issues like this one (all in my free time).
