### ISSUE TITLE
Question: Can a Vocabularies be part of a package?

### ISSUE THREAD

**Issue by spier** [vale-cli/vale#634]
I have a setup where I want to share both **styles** and custom **Vocabularies** across multiple projects.

This is where I keep the styles/Vocabularies that I want to package up:
https://github.com/InnerSourceCommons/isc-styles/tree/main/styles

I followed these [instructions](https://vale.sh/docs/topics/packages/) but after a couple of failed experiments, I am no longer sure if a Vocabularies can be part of a package at all?

Hope it is alright to ask this question here, as I could not find another place to do so.

**Comment by jdkato** [comment]
Yes, see https://vale.sh/docs/topics/packages/#complete

**Comment by spier** [comment]
Thank you for the quick response @jdkato. 

While typing up a response I eventually figured out what the issue was:
The zip file needs to contain a top-level folder with the same name as the zip file (I think).

I guess that is implicitly documented through the examples in https://vale.sh/docs/topics/packages/#complete, still I missed it.

Below the description of the situation I had before resolving this.
I am happy to contribute further documentation about this, as I have been banging my head against this for way too long :)

## My previous (non-working) state

I must be getting something simple about the folder in my zip file wrong. 

The error I get when syncing my package:
> lstat /var/folders/vm/djb4bxks07v99vyvkv37ktkr0000gn/T/ISC516387942/ISC: no such file or directory

The content of `lstat /var/folders/vm/djb4bxks07v99vyvkv37ktkr0000gn/T/ISC516387942` is this:
```
.vale.ini
styles
```

So I suspect that `sync` is looking for an `ISC` folder directly in there, rather than in `styles`?

My zip file looks like this:

```
$ unzip -l ISC.zip
Archive:  ISC.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      147  05-21-2023 06:12   .vale.ini
        0  05-21-2023 06:11   styles/
        0  05-21-2023 06:10   styles/Vocab/
        0  05-20-2023 13:34   styles/Vocab/ISC_Organizations/
      119  05-19-2023 09:57   styles/Vocab/ISC_Organizations/accept.txt
        5  05-20-2023 13:34   styles/Vocab/ISC_Organizations/reject.txt
        0  05-20-2023 13:34   styles/Vocab/ISC_People/
      418  05-19-2023 09:58   styles/Vocab/ISC_People/accept.txt
        5  05-20-2023 13:34   styles/Vocab/ISC_People/reject.txt
        0  05-19-2023 09:34   styles/Vocab/ISC_General/
      693  05-20-2023 00:18   styles/Vocab/ISC_General/accept.txt
        5  05-20-2023 13:34   styles/Vocab/ISC_General/reject.txt
        0  05-19-2023 09:34   styles/ISC/
      445  05-19-2023 10:05   styles/ISC/InnerSource.yml
      145  05-19-2023 23:37   styles/ISC/Spelling.yml
```

The `.vale.ini` that is including this ZIP file looks like this:

```
StylesPath = .github/vale
MinAlertLevel = suggestion

Packages = <some local path>/ISC.zip

Vocab = ISC_General, ISC_Organizations, ISC_People

[*]
BasedOnStyles = ISC
```

And an extra strangeness that I discovered:

While the creation of the `ISC` styles folder fails, the folders/files below `Vocab` get created.
However all `accept.txt`/`reject.txt` files are empty!

Through experiments I found that this is the behavior of `vale sync` when it does not find the Vocab in the package i.e. it initializes the Vocab with empty files. Therefor I suspect that sync does not find the Vocabs in my zip file either.

**Comment by jdkato** [comment]
I'm not sure if you got it working or not, but here's a working example (also attached):

```
ISC
├── .vale.ini
└── styles
    ├── ISC
    │   └── Rule1.yml
    └── Vocab
        ├── ISC_General
        │   ├── accept.txt
        │   └── reject.txt
        ├── ISC_Organizations
        │   ├── accept.txt
        │   └── reject.txt
        └── ISC_People
            ├── accept.txt
            └── reject.txt
```

and

```ini
StylesPath = styles
MinAlertLevel = suggestion

Vocab = ISC_General, ISC_Organizations, ISC_People

[*]
BasedOnStyles = ISC
```

[ISC.zip](https://github.com/errata-ai/vale/files/11523955/ISC.zip)

**Comment by spier** [comment]
@jdkato thank you so much for taking the time to investigate and fix my example.

Yes, I had already gotten it to work while I was typing my previous response.

The thing that I had not realized was that the zip file needs to contain a top-level folder with the same name as the zip file. `ISC` in my case.

I think the **documentation** would benefit from some additional description about that. Your tree output as shown above would be helpful, as that highlights the top-level folder more clearly than the unzip output (to me at least).

Would you be happy for me to send a PR to improve the documentation?

**Comment by jdkato** [comment]
> The thing that I had not realized was that the zip file needs to contain a top-level folder with the same name as the zip file. ISC in my case.

I don't think I understand this point. How were you creating a ZIP file named `ISC` *without* meeting this requirement?

What were you naming the folder that contained your `.vale.ini` + `styles`?

**Comment by spier** [comment]
I think there are various ways to get this wrong, and I suspect I was trying many of them :)

One way to get an ISC.zip file without a top-level folder ISC:
- cd `<local folder with any name>`
- `zip -r ISC.zip .vale.ini styles`

Another way to get a non-importable zip file:
`zip -r ISC.zip <local folder with a name that is not "ISC">`

Therefore I think the two requirements to document are:
- the name of the zip file is the name of your package e.g. if the zip file is `ISC.zip`, then the package name is `ISC`
- there needs to be a single top-level folder in the zip file, with the same name as the package i.e. `ISC/`

It sounds like this issue did not get reported that frequently before, maybe not at all, did it?

When I was searching for examples I found no open source examples of packages that include both styles and Vocab. That might explain this?

**Comment by jdkato** [comment]
Ah, I see. For what it's worth, the command used to build the packages in the hub is:

```
zip -r Pkg.zip Pkg
```

As far as I know, this is also the default behavior when using the context menu in most OSes.

**Comment by spier** [comment]
Makes perfect sense. That shows both of the requirements "in code" :)

As I said, I am happy to contribute additional explanations to the vale documentation about this. Of course only if you think that this could be useful for others.
