### ISSUE TITLE
Question: How to reference dictionaries within a package?

### ISSUE THREAD

**Issue by spier** [vale-cli/vale#635]
I am including dictionary files (`.aff/.dic`) as part of a package.

Now I am wondering how to reference those files via `dicpath` in a style?
I am assuming that I need to use a **relative path**, so that the style also works when the package is included into another project.

I see in this [documentation](https://vale.sh/docs/topics/styles/#spelling) that a relative path can be used but I have no idea what the path is relative to.

Here the style that should reference the dictionaries:
https://github.com/InnerSourceCommons/isc-styles/blob/main/ISC/styles/ISC/Spelling.yml

And this is the repo that contains my vale package:
https://github.com/InnerSourceCommons/isc-styles

Btw, currently I am using the path `/ISC/..` in my Spelling.yml.
It seems to work but I honestly have no idea why :)

**Comment by jdkato** [comment]
See https://github.com/errata-ai/vale/issues/628#issuecomment-1544822233 for a related discussion.

My recommendation would be to make a subfolder for them:

```
styles
├── ISC
├── Vocab
└── dics
    ├── en_US.aff
    └── en_US.dic
```

and then specify that in your rule:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
dicpath: dics
dictionaries:
  - en_US
```

**Comment by spier** [comment]
Perfect, that works. Thank you!

Btw should I have posted this question in Discussions rather than as an issue?
