### ISSUE TITLE
sync feature can provide misleading error messages

### ISSUE THREAD

**Issue by jtiee** [vale-cli/vale#640]
### Check for existing issues

- [X] Completed

### Environment

OS: macOS Ventura 13.3.1 (a), on a Macbook M1 Pro.
Vale: 2.27.0 via direct download.

### Describe the bug / provide steps to reproduce it

If I configure the `Packages` field in my `vale.ini` with a URL, and the URL happens to be incorrect or inaccessible, Vale reports:

```
opening zip archive for reading: creating reader: zip: not a valid zip file
```

This is misleading. I spent a long time trying to diagnose that error and potential problems in the ZIP file when the problem was a lack of authorization to access the ZIP archive.

When a Package URL involves a non-existent domain, Vale does report:

```
Get "https://example.example/style.zip": dial tcp: lookup example.example: no such host
```

That's useful! 4xx or 5xx HTTP errors for package downloads should be reported as such instead of blaming the ZIP file.

**Comment by jdkato** [comment]
You will now see

> Could not fetch '\<url\>' (status code '404').

or similar.

**Comment by jtiee** [comment]
Thanks!

**Comment by ThomasMeyerDev** [comment]
Hi, I still get the error when I try to sync a package from a private repo, even though I have access to it.

The repo is hosted on organization Gitlab account and our team members access it with SSO. I tried to curl the file and got back a redirect to a login page. My guess is, that http.Get automatically follows the redirect and gets a 200 for the login page, which is an HTML page but not a zip as expected.
