### ISSUE TITLE
Existence with tokens seems to fail at catching angle brackets in raw scope

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#643]
### Check for existing issues

- [X] Completed

### Environment

vale version 2.26.0
Install from github

### Describe the bug / provide steps to reproduce it

See the Vale Studio example here: https://studio.vale.sh/s/8e11b73aa478768c4cc4bd8c84466ece

Why does `link[] `not get caught by this rule? 

The goal was to have something like the following but it seemed to be tripping over on angle brackets when using tokens.

````
tokens:
  - 'link:.*\[\]'
  - 'link:.*\[[cC]lick here\]'
````

**Comment by jdkato** [comment]
You need to add `nonword: true`.
