### ISSUE TITLE
[Question] Is Vale's scope-awareness able to tell me under which scope a style-check has been found?

### ISSUE THREAD

**Issue by adish-jain** [vale-cli/vale#648]
I am dealing with the following use case: I have a few different input sections that come together to create an article. Each of these sections is marked by an h2 header. So you can imagine the payload that might get sent to the Vale style checker looks like the following:

```
## Description
There is a misteake here.

## Summary
There is another isusue here.
```

Vale will find that on L2 there is a spelling issue and on L5 there is a spelling issue. Is there any way for the style checker to tell me that the first spelling mistake is under the first H2 header (or better yet, for it to tell me that it is under the Description section) and that the second spelling mistake is under the second H2 header (or better yet, for it to tell me that it is under the Summary section). 

The reason I want this is to display the suggestions back to the user broken down by section, so they can easily understand which section to look at when referencing certain style suggestions that are being shown to them. Is this possible?

**Comment by jdkato** [comment]
No, but the line and column information provide the exact location (as well as section, implicitly).
