### ISSUE TITLE
Vale doesn't pick up config file under Windows

### ISSUE THREAD

**Issue by wilhelmer** [vale-cli/vale#65]
Running Vale on Windows 10. I added vale.exe's directory to the PATH environment variable, so I can run vale.exe from anywhere. However, it doesn't pick up the .vale config file in the same directory. This means there's no global config file and I must place a seperate .vale file in every local folder.

**Comment by jdkato** [comment]
Hi,

Vale should support placing a global config file in `$HOME`, `%UserProfile%`, or `%HomeDrive%%HomePath%` (this logic comes from the [`go-homedir`](https://github.com/mitchellh/go-homedir) library).

Have you tried placing a config file in one of those places (assuming it has been defined as environment variable)?

**Comment by wilhelmer** [comment]
Yep, tried all of the above. I have a .vale file in %UserProfile% and %HomeDrive%%HomePath% (same dir on my machine) and also set $HOME to my Vale install dir in environment variables. Doesn't work.

**Comment by jdkato** [comment]
I was able to reproduce this (it seemed to only occur with directories nested > 6 levels).

I pushed a fix with [v0.11.2](https://github.com/errata-ai/vale/releases/tag/v0.11.2), which should now work as intended with `$HOME`, `%UserProfile%`, and `%HomeDrive%%HomePath%`. Let me know if you're still having issues.

**Comment by wilhelmer** [comment]
Works like a charm. Thanks for the quick bugfix, and thanks for this awesome tool! I just introduced it to our documentation team and we're all very excited about it. Keep up the great work!
