### ISSUE TITLE
Pulling `Vocab.zip` using `vale sync` removes all existing folders in my projects `styles/Vocab`

### ISSUE THREAD

**Issue by f-hollow** [vale-cli/vale#655]
### Check for existing issues

- [X] Completed

### Describe the feature

First and foremost, Vale is an indispensable tool for technical authors like me. Thank you very much for developing and maintaining Vale!

## My Intension

In `MyProject`, I would like to have the following directories in `styles/Vocab`:

- `terms1` maintained in MyProject directly.
- `terms2` maintained in another repo, archived into `Vocab.zip` using CI, and `vale sync`ed into MyProject as a package.

### My setup

Tested in the following environments:

| OS | macOS Catalina 10.15.4 |
| --- | --- |
| Install method | Direct download |
| Vale version | 2.24.2 |

| OS | Ubuntu 22.04 LTS |
| --- | --- |
| Install method | Direct download |
| Vale version | 2.27.0 |

### My FIles

Currently, I have the following:

- _MyProject_:

  ```
  MyProject # before running vale sync
  ├── styles
  │   └── Vocab
  │       └── terms1
  │           ├── accept.txt
  │           └── reject.txt
  ├── .vale.ini
  ├── README.md
  ```

- The file _.vale.ini_:

  ```
  StylesPath = styles
  Vocab = terms1, terms2
  Packages = /path/to/dir/Vocab.zip
  ...
  ```

- The package `Vocab.zip` on my server:

```
Vocab
└── terms2
    ├── accept.txt
    └── reject.txt
```

### My actions

After running `vale sync` in `MyProject`, the contents of the existing `Vocab` directory get deleted and replaced with the contents of `Vocab.zip`, like this:

  ```
  MyProject # after running vale sync
  ├── styles
  │   └── Vocab
  │       └── terms2
  │           ├── accept.txt
  │           └── reject.txt
  ├── .vale.ini
  ├── README.md
  ```

### Analysis

The [Packages](https://vale.sh/docs/topics/packages/#complete) documentation says:

> The packaged `StylesPath` will be merged with the active local `StylesPath` and any included configuration files ...

However, the content in the `Vocab` directory is not merged but replaced.

Please correct me if I did anything wrong!

## Enhancement Proposal

Assuming that I did not miss anything, this is my enhancement proposal.

I have the following thoughts:

- As resolving merge conflicts after running `vale sync` is not an option, so any `styles` directories with the same name should be replaced.
  - Pulling the Google or RedHat, etc. packages should replace existing Google or RedHat, etc. directories with all their content.
  - Pulling a Vocab subdirectory, such as `terms1`, should replace the existing `Vocab/terms1` subdirectory
- However, pulling the Vocab subdirectories with non-existent names, such as `terms2` should add this subdirectory to `Vocab` without touching `terms1`.
  - Alternatively, it might be worth placing vocabularies outside of `styles` and adding a variable `VocabPath` to `.vale.ini`.

## Conclusion

Unfortunately, I am not yet knowledgeable enough to offer a PR, so it would be great if somebody could consider this proposal for implementation. Thank you!

**Comment by jdkato** [comment]
As stated in the linked documentation, Vocabs must be distributed as part of a "complete" package (there's no support for a "Vocab-only" package).

In your case, it would look something like this:

```
pkg
├── .vale.ini
└── styles
    └── Vocab
        └── terms2
            ├── accept.txt
            └── reject.txt
```

and

```ini
# pkg/.vale.ini
StylesPath = styles

Vocab = terms2
```

**Comment by f-hollow** [comment]
Now it works! Thank you for your quick answer!
