### ISSUE TITLE
[Question] Vale Not Detecting Underscores ('_') in Token 

### ISSUE THREAD

**Issue by adish-jain** [vale-cli/vale#658]
### Check for existing issues

- [X] Completed

### Environment

OS - MacOS
Install Method - Homebrew
Vale Version - 2.25.2

### Describe the bug / provide steps to reproduce it

I am trying to configure a rule where I look for the `existence` of tokens that happen to have dashes and underscores in them. 

Dashes seem to be detected fine. For example, the below rule detects usages of 'abra-cadabra' correctly:
```
extends: existence
message: "bold it!"
link: /style/#bold
scope: raw
level: warning
ignorecase: false
tokens:
  - 'abra-cadabra'
```

However, underscores seem to not be getting caught. For example, the below rule is NOT detecting 'abra_cadabra'.
```
extends: existence
message: "bold it!"
link: /style/#bold
scope: raw
level: warning
ignorecase: false
tokens:
  - 'abra_cadabra'
```

I looked through previous issues and the solve was to include `scope: raw` within the rule body, which I have done. However, this is still not working. I'm wondering if I'm missing something here.

**Comment by jdkato** [comment]
I can't reproduce this. Could you provide an example of this failing?

**Comment by adish-jain** [comment]
@jdkato Thanks for your response. Here's an example:

**Rule Configuration**
<img width="258" alt="Screen Shot 2023-07-21 at 6 10 14 PM" src="https://github.com/errata-ai/vale/assets/25048098/aa8581e1-05f5-4499-a762-601287d85d0d">

**Postman Request to Local Server running Style Checks**
<img width="669" alt="Screen Shot 2023-07-21 at 6 10 53 PM" src="https://github.com/errata-ai/vale/assets/25048098/2e9ecb8f-f028-4a4e-bf2e-3eacd48e8b08">

As you can see, Vale is only detecting the variant with the dashes, and not the underscores.

**Comment by jdkato** [comment]
I still can't reproduce, even when using your test case. See this [Vale Studio session](https://studio.vale.sh/s/b9f678c25655454a9067c2528cedcdee) for an example.
