### ISSUE TITLE
Vale counts words per sentence wrong, if one word contains a dot. This triggers 'try to keep sentence short (<30 words)' warning.

### ISSUE THREAD

**Issue by Makki93** [vale-cli/vale#662]
### Check for existing issues

- [X] Completed

### Environment

Installed on macOS with pip and homebrew (both tried).
Vale version 2.28.1

### Describe the bug / provide steps to reproduce it

Vale counts words per sentence wrong, if one word contains a dot. This triggers 'try to keep sentence short (<30 words)' warning.

**Comment by Makki93** [comment]
Same thing with admonitions, like in MkDocs

The start with
!!! warning "This is a MkDocs admonition"
    And then here goes the text box, and the containing text is marked as too long (or sentence) is too long, because vale doesn't get the correct word count. I guess because it does not recognize the line break as delimiter.

**Comment by jdkato** [comment]
The issue here is not clear to me -- could you please provide:

1. The rule that you believe to be broken; and
2. an example of input that causes it?

> Same thing with admonitions, like in MkDocs

These "admonitions" are not valid syntax in any of Vale's supported formats, so they may not be handled correctly.

**Comment by Makki93** [comment]
Ok sure.

So the rule broken is
	"code": "Microsoft.SentenceLength",
	"severity": 2,
	"message": "Try to keep sentences short (< 30 words).",


Here's an example to reproduce it:

!!! success "Dos"
    * add meaningful tags and descriptions to your dataset so that it can be found easier
    * classify your data correctly - see [the house of rules](https://houseofrules.someCompanyName.de/display/SEC/Classification+and+Control+of+Information){target=_blank} for more information
    * add additional responsible to your dataset in case you are not available
    * delete data or datasets if it not used anymore to reduce costs
    * search for pre-existing datasets you might be able to use

The markdown code is for https://squidfunk.github.io/mkdocs-material/reference/admonitions/

Maybe this should belong into the Microsoft package, right?

**Comment by daobrien** [comment]
You might find that this is related to using a list. I *think* Vale processes all the list entries as one sentence. Or it used to.

**Comment by jdkato** [comment]
I still can't reproduce the issue:

<img width="1015" alt="Screenshot 2023-08-17 at 10 43 20 AM" src="https://github.com/errata-ai/vale/assets/8785025/55ac0ab3-e846-47b9-be58-ed4775f13b93">

You can see that only the sentence with more than 30 words is flagged.

> The markdown code is for https://squidfunk.github.io/mkdocs-material/reference/admonitions/

This is non-standard Markdown and not supported by Vale. Not necessarily related to this topic, but it can result in unexpected errors.
