### ISSUE TITLE
Markdown: Link in image markup is linted

### ISSUE THREAD

**Issue by davidsneighbour** [vale-cli/vale#665]
### Check for existing issues

- [X] Completed

### Environment

- Ubuntu 22.04
- direct download
- vale version 2.27.0

### Describe the bug / provide steps to reproduce it

A check fails inside of a Markdown image link:

The error message 

![Selection_026](https://github.com/errata-ai/vale/assets/83281/24a4d628-c400-4630-85f1-0bab9c95a5f6)

The location

![Selection_027](https://github.com/errata-ai/vale/assets/83281/75dffb29-23cd-4e0a-9131-85ebb2f3a81a)

According to #320 I would expect Vale to ignore the part in brackets - even if it's an "extension" of a link by adding a `!`?

![Selection_025](https://github.com/errata-ai/vale/assets/83281/1f69d382-1dc3-45cb-a1a0-f40b177b2e9d)

The full configuration:

```
StylesPath = .
MinAlertLevel = error # suggestion, warning, error
Vocab = dnb
Packages = RedHat, Microsoft, Google, Hugo, alex, proselint, Readability, write-good

# Ignoring scopes
IgnoredScopes = code, tt
SkippedScopes = script, style, pre
IgnoredClasses = highlight

[formats]
mdx = md

[*.{md,txt}]
BasedOnStyles = Vale, RedHat, Microsoft, Google, alex, proselint, Readability, write-good

Vale.Spelling = warning

# disable rules from RedHat
RedHat.TermsWarnings = NO
RedHat.TermsErrors = NO
# disable rules from Microsoft
Microsoft.Avoid = NO
Microsoft.FirstPerson = NO
Microsoft.We = NO
Microsoft.Contractions = NO
Microsoft.Quotes = NO
# disable rules from Google
Google.FirstPerson = NO
Google.Parens = NO
Google.Passive = NO
Google.We = NO
Google.Quotes = NO
# disable rules from alex
alex.ProfanityUnlikely = NO
# disable rules from proselint
# disable rules from Readability
Readability.FleschReadingEase = NO
# disable rules from write-good
write-good.E-Prime = NO
write-good.Passive = NO
```

I tried to add `link` to `IgnoredScopes` and `SkippedScopes` with no success.

**Comment by jdkato** [comment]
The scope you're after is `alt`:

```
SkippedScopes = script, style, pre, figure, alt
```

My recommendation, however, would be to provide alternative text that describes the image, rather than merely duplicating the file path:

```
![Example of creating a new Git repo in Keybase](keybase-git.png)
```

**Comment by davidsneighbour** [comment]
Thank you, that makes sense. I'll try and close if it fixes my issue.

**Comment by davidsneighbour** [comment]
It works as it was explained. And, yes, having a descriptive alt-text is just better. I am not sure why my brain stopped thinking at that point.
