### ISSUE TITLE
Release as NPM package

### ISSUE THREAD

**Issue by KyleTryon** [vale-cli/vale#668]
### Check for existing issues

- [X] Completed

### Describe the feature

The current methods of installation are great for an individual user or a CI environment in the case of the docker image, but it is difficult in a Node.js project to expect contributors to run the `vale cli` locally. While we can catch issues in CI, it would be ideal if we could install the CLI as a dev dependency in a node project and run a command such as `npm run vale`. This would help reduce friction in PRs and integrate will with pre-commit hooks (via Husky).

**Comment by jdkato** [comment]
I wouldn't object to someone making this (something similar for Python/pip  [has been done](https://github.com/daniperez/vale-python-package)), but I'm not particularly interested in maintaining this myself.

**Comment by ChrisChinchilla** [comment]
@jdkato and @KyleTryon I can take a look at this, so assign to me. It suits some other vale-related things I am experimenting with.

**Comment by jdkato** [comment]
There's also https://www.npmjs.com/package/@ocular-d/vale-bin

**Comment by ChrisChinchilla** [comment]
Then I think this looks like the preferred option really, as it already exists. Have you tried it @KyleTryon ?
