### ISSUE TITLE
"Edit" link in docs returns 404

### ISSUE THREAD

**Issue by wouter-veeken** [vale-cli/vale#67]
When I click the Edit symbol on the top-right corner of any page in the docs (e.g. https://valelint.github.io/docs/styles/), I get a 404.

**Comment by jdkato** [comment]
Thanks for the report.

The MkDocs theme I use ([mkdocs-material](https://github.com/squidfunk/mkdocs-material)) expects the docs to be hosted in the same repo as the source code, which isn't the case for Vale. 

I'm sure there's a way to fix this, but I'm actually working on a new Hugo-powered website already&mdash;so I'll probably just leave it for now.

**Comment by jdkato** [comment]
The new docs are now available: https://errata.ai/vale/getting-started/
