### ISSUE TITLE
Counter-intuitive behaviour of vocabularies accept.txt

### ISSUE THREAD

**Issue by j-wol** [vale-cli/vale#670]
### Check for existing issues

- [X] Completed

### Environment

OS: Ubuntu Linux
Install method: direct download
Vale version: 2.28.2

### Describe the bug / provide steps to reproduce it

In our project, we use the vocabulary accept.txt to list words that shall not be considered as spelling error. Now we found out that the misspelled word "configurtions" (instead of configurations) were not reported as error by Vale whereas it is of course not added to the accept.txt list.
After some investigation, I found out the root course: The entries "config" (used in our documents very often as abbreaviation of configuration) and "Ons" (first name of a colleague) are the reason that "configurtions" is not recognized as error.
More general, each word that contains a prefix or postfix of a word from accept.txt are excluded from spell check. For example the words "configxxxx" and "repressentations" are erroneously not marked as errors.

Here is a minimal example to reproduce the issue:

.vale.ini:

>StylesPath = styles
>Vocab = MyVocab
>MinAlertLevel = suggestion
>
>[*.txt]
>BasedOnStyles = Vale

test.txt:
>This text contains the miss-spelled words configurtions, configxxxx, and repressentations.

I am especially surprised that the word "Ons" (written with capital O) suppresses to detect the misspelled word "repressentations", because in the documentation it is mentioned that the entries in accept.txt are case-sensitive.
The documentation stated as well that the entries "may also be regular expressions". This "may" I understood that they could be regular expressions but they are not by default. But this understanding seems to be wrong, right? Each entry seems to be always treated as RegEx?
From my point of view, the behaviour that each word which contains a prefix or postfix of a word from accept.txt are excluded from spell check is weird. Could you please change the behaviour in Vale?

In comment (https://github.com/errata-ai/vale/issues/454#issuecomment-1172761393) I have read that pre- and postfixing a accept.txt entry with \b (\bSOME-WORD\b) can be used to get the behaviour I request. When you do not want to change the behaviour in general, would it be possible to at least introduce a configuration parameter in .vale.ini to change the meaning of each accept.txt entry to \bSOME-WORD\b without forcing to pre- and postfix each entry with a \b?

**Comment by jdkato** [comment]
The issue here is that vocabularies offer functionality that isn't specific to spell check (multi-word tokens, regex, etc.) and, as a consequence, you have to be very specific about what you want (such as denoting word boundaries).

If you'd like a simpler experience, you have a [few options](https://vale.sh/docs/topics/styles/#ignoring-non-dictionary-words). The closest to the behavior you're describing is to create a `spelling`-based rule with a custom `ignore` file:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  # Located at StylesPath/ignore.txt
  - ignore.txt
```

The format of `ignore.txt` is exactly one-word-per-line, as you describe above:

```text
config
configxxxx
```
