### ISSUE TITLE
vale-studio copy link not working

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#672]
### Check for existing issues

- [X] Completed

### Environment

Using studio.vale.sh.

### Describe the bug / provide steps to reproduce it

Using studio.vale.sh, I am getting the following error when I click the copy link button in the upper right:

`[2.27.0] error communicating with database: connection aborted`

Also the **open an issue** link in the About section shows a 404:
![image](https://github.com/errata-ai/vale/assets/104497497/84c0961a-80bc-4133-9c64-92083c4fed3b)

**Comment by jdkato** [comment]
Both issues should be fixed now.
