### ISSUE TITLE
Rules triggered by content in code format (backticks)

### ISSUE THREAD

**Issue by andie787** [vale-cli/vale#676]
### Check for existing issues

- [X] Completed

### Environment

macOS, homebrew, vale version 2.28.1

### Describe the bug / provide steps to reproduce it

Custom Spelling rule, which extends spelling, triggers on words within backticks in markdown. Note that we have our own extension `markerb` mapped to `md` files in the vale.ini file.

Any advice?

```
extends: spelling
message: "Is '%s' a typo?"
level: suggestion

# This disables the built-in filters. If you omit this
# key or set it to false, custom filters (see below) are
# added on top of the built-in ones.
#
# By default, filters for acronyms, abbreviations, and
# numbers are included.
custom: false

# A "filter" is a regular expression specifying words
# to ignore during spell checking.
filters:

  - '\w+_\w+' # ignore config option names
  - '--.' # ignore command options
  - 'v[0.9].' # ignore flyctl versions

ignore:
  - words2ignore.txt`
 ```

**Comment by jdkato** [comment]
Could you share an example of a `markerb` file that exhibits this behavior?

**Comment by andie787** [comment]
Sure! 
Here's our "draft" vale config so far: https://github.com/superfly/docs/pull/949
Here's an example of a file where the spellcheck is reading inside backticks: https://github.com/superfly/docs/blob/main/rails/cookbooks/databases.html.markerb
That file has a typo \`Vistor\` in it and gets an error: `72:8    suggestion  Is 'Vistor' a typo?             Fly.Spelling`

I'm almost sure I'm missing something obvious? I did test the file with a misspelled word in code markup that was not in a list, in case that was the issue, but it also triggered the spelling rule.

**Comment by jdkato** [comment]
You should remove this from your `.vale.ini`:

```ini
IgnoredScopes = div, section
```

It's overriding the default value (`code, tt`) and it's not clear to me what the intended purpose was.

**Comment by andie787** [comment]
OK thanks! That seems to have fixed it. :) 
I must have completely missed the "inline-level" part of the description for IgnoredScopes in docs. And thought it was for just html tags to ignore. 🤷 
Thanks again for responding!
