### ISSUE TITLE
Format specifier in occurence rules

### ISSUE THREAD

**Issue by dobaret** [vale-cli/vale#677]
### Check for existing issues

- [x] Completed

### Describe the feature

Hello!

It would be very helpful to be able to insert a format specifier in occurence rules.

I use Gitlab's [SentenceLength.yml](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/SentenceLength.yml) rule, and I wish I could know the number of words in sentences infringing this rule directly in the `message`.

**Comment by jdkato** [comment]
Supported as of [v3.4.0](https://github.com/errata-ai/vale/releases/tag/v3.4.0).
