### ISSUE TITLE
Question: How to use vale off/on with Antora/Asciidoc?

### ISSUE THREAD

**Issue by RCheesley** [vale-cli/vale#678]
### Check for existing issues

- [X] Completed

### Environment

MacOS Ventura, Vale version 2.24.1

### Describe the bug / provide steps to reproduce it

I'm struggling to exclude a line in a file using `.. vale off` with some docs for a project which uses Antora where I'm trying to help them improve the quality by implementing Vale. I'm not overly familiar with the Antora tooling as a new contributor having never used it before, I wondered if you can point me in the right direction. 

Reason for ignoring the single line is it's an image with the accompanying text in Spanish, and it's throwing errors as a result. So I want to exclude just that line of the file, other images are fine and should continue to be linted.

I've tried the traditional .. vale off / .. vale on and the HTML equivalent but neither are working, and I'm not sure if there's an equivalent for Asciidoc-based docs? Thanks in advance.

**Comment by jdkato** [comment]
There are some [examples here](https://vale.sh/docs/topics/config/#asciidoc).
