### ISSUE TITLE
Vale fails for missing XSLT when XSLT is not used or mentioned in the files it's examining.

### ISSUE THREAD

**Issue by cgwers** [vale-cli/vale#684]
### Check for existing issues

- [X] Completed

### Environment

windows 10/11, App: MadCap Flare (output is htm), installed with chocolatey, vale version 2.28.3.

Vale is used in a post-build batch file to examine the output specified with Flare build environment variables. Flare uses xlst internally against generated project files, but _never_ against htm files. XSLT is never used in the htm file and there's no mention of an xlst, only the XSD.

Flare's htm files start with these lines:

<?xml version="1.0" encoding="utf-8"?>
<html xmlns:MadCap="http://www.madcapsoftware.com/Schemas/MadCap.xsd">
    <head>
    </head>

LOG:

[18-Sep-23 12:47:16.03] Pre-build actions for project testbed.flprj-HTML5 
[18-Sep-23 12:47:24.13] Post-build actions for project testbed.flprj-HTML5 
{
  "Code": "E100",
  "Text": "E100 [lintXML] Runtime error\n\nno XSLT transform provided\n\nExecution stopped with code 1."
}
[18-Sep-23 12:47:30.59] Completed Vale linting for project testbed.flprj-HTML5 

**BTW, **the windows installation REQUIRES xsltproc** or it immediately fails. You need to mention that on the install page or bake it into the app.**

### Describe the bug / provide steps to reproduce it

Start my build
Pre-build script sets filesystem locations for Vale
Build (The builds are successful, no warnings or errors)
Post-Build.bat
  Fails with "Code": "E100",
  "Text": "E100 [lintXML] Runtime error\n\nno XSLT transform provided\n\nExecution stopped with code 1."

**Comment by jdkato** [comment]
> BTW, the windows installation REQUIRES xsltproc or it immediately fails. You need to mention that on the install page or bake it into the app.

This is not true. For anyone who may stumble upon this in the future, the issue here is that this user is running Vale on a project containing both `.htm` *and* `.xml` (which require xsltproc) files.

If you're only interested in the `.htm` (or other non-XML) files, you can avoid needing to install xsltproc by restricting Vale to certain file types:

```ini
StylesPath = styles
MinAlertLevel = suggestion

[*.{htm,txt}]
BasedOnStyles = Vale
```
