### ISSUE TITLE
How to configure rules to check for content in fenced code block?

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#686]
I'd like to check if URL quotation marks are added around a curl URL in markdown files.

For example,

```shell
curl http://something.com
```

should not be acceptable but this should:

```shell
curl "http://something.com"
```

My initial thought is to use the `existence` rule with a `token` set to `curl http`. However i quickly realized codes are escaped from these checks.

What are the other options I have?

**Comment by jdkato** [comment]
If you add `scope: raw` to your rule, you can target content in code blocks.
