### ISSUE TITLE
.vale.in and Working with different styles

### ISSUE THREAD

**Issue by 5u623l20** [vale-cli/vale#689]
### Check for existing issues

- [X] Completed

### Environment

We have been running it for a while and it was running fine but recently I can see that the directory specific rules/styles are not honored properly. I cannot exactly recollect like from which version this stopped working. For the translation directories I can see that all styles are enabled and are reporting errors.

https://github.com/freebsd/freebsd-doc/blob/main/.vale.ini

`
❯ vale -v
vale version master
`

I have gone through some of the previous issues:
https://github.com/errata-ai/vale/issues/403
https://github.com/errata-ai/vale-vscode/issues/63
https://github.com/errata-ai/vale/issues/245

But these are older and our situation worked after these fixes. So I wanted to know whether if there has been a recent changes which might have reintroduced the error?

### Describe the bug / provide steps to reproduce it

`
git clone https://github.com/freebsd/freebsd-doc.git
vale .
`
Precaution it will take 30-40 minutes to complete.

We will see Vale.Spelling errors on the translation documents which are not supposed to happen as those have been disabled.

**Comment by jdkato** [comment]
Nothing should have changed (certainly not deliberately).

Could you name one of the documents that had `Vale.Spelling` errors?

I tried to reproduce this by running Vale on the translation directories individually (e.g., `vale documentation/content/ja`) and was not able to.

**Comment by 5u623l20** [comment]
`
vale  website/content/zh-tw/
`

`vale  website/content/zh-cn/`

And if I am not mistaken with the problem I think it is the '**' that is creating the problem. It's supposed to mean zero or more but more like it's behaving like 1 or more.

**Comment by jdkato** [comment]
> And if I am not mistaken with the problem I think it is the '**' that is creating the problem. It's supposed to mean zero or more but more like it's behaving like 1 or more.

This is indeed the issue. It should be fixed in the next release.
