### ISSUE TITLE
Is it possible to use a regex in message field?

### ISSUE THREAD

**Issue by jputrino** [vale-cli/vale#69]
Is it possible to use regular expressions in the message field when customizing styles? 

I'd like to capture the entire sentence the offending word/phrase is part of, like so:

`message: "In '^.*(\'%s\').*\.', '%s' is passive voice."`

Example output:
`In 'The cat is driven mad by the smell of catnip.', 'is driven' is passive voice.`

I get a YAML syntax error when running vale with this customization.

`base.Passive: yaml: line 1: found unknown escape character`

Is this use supported and I'm just formatting it incorrectly? Or is this not allowed?

**Comment by jputrino** [comment]
Leaving this up for posterity, but I've discovered that it was just me formatting it incorrectly. 
I had to use double backslashes (as described [here](https://stackoverflow.com/questions/6770898/unknown-escape-sequence-error-in-go)). The regex didn't work, but at least I resolved the YAML error!

**Comment by jdkato** [comment]
This isn't supported.

I've experimented with storing the "context" (e.g., the line or sentence) of an alert in the past, but I found that its impact on performance (memory- and speed-wise) was too significant.

That said, this information is implicitly provided in Vale's standard output. So, you can create custom console output by writing a simple wrapper. For example (using Python),

```python
# Obviously this is a pretty simply example, but you could easily get more 
# structured / colored output by incorporating some libraries.
import sys
import json

messages = {'write-good.Passive': "In '{0}', '{1}' is passive voice."}

data = json.load(sys.stdin)
for src, alerts in data.items():
    with open(src) as f:
        context = f.readlines()
        for alert in alerts:
            msg = messages.get(alert['Check'])
            if msg:
                line = alert['Line'] - 1
                print(msg.format(context[line], alert['Match']))
```

Then, assumming you've named that file `format.py`,

```console
$ cat test.md
The cat is driven mad by the smell of catnip.
$ vale --output=JSON test.md | python format.py
In 'The cat is driven mad by the smell of catnip.', 'is driven' is passive voice.
```

**Comment by jputrino** [comment]
Thanks @jdkato!
