### ISSUE TITLE
vale webserver still on roadmap?

### ISSUE THREAD

**Issue by hazelement** [vale-cli/vale#690]
### Check for existing issues

- [X] Completed

### Describe the feature

Thanks for providing this project to the community. This has been great in improving my writing. I came across a vale server post but I can't find the github project. Is this still on the roadmap? I work with Google doc a lot so this will be tremendous. 

https://medium.com/valelint/taking-vale-server-to-the-web-4de44b32e547

**Comment by ChrisChinchilla** [comment]
@hazelement take a look at the discussion [here](https://github.com/errata-ai/vale/discussions/608), it’s in vague progress.

**Comment by hazelement** [comment]
> @hazelement take a look at the discussion [here](https://github.com/errata-ai/vale/issues/690), it’s in vague progress.

Is the link wrong? It's pointing at issue 690, which is this issue.

**Comment by ChrisChinchilla** [comment]
> > @hazelement take a look at the discussion [here](https://github.com/errata-ai/vale/issues/690), it’s in vague progress.
> 
> Is the link wrong? It's pointing at issue 690, which is this issue.

Sorry! Corrected.
