### ISSUE TITLE
Alerts should not be reported in assigned identifiers (AsciiDoc)

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#691]
Here is a complete test case: https://github.com/aireilly/vale-test/tree/test-case

This test case shows the error in Sublime vale-ls, CLI, VS Code.

_Originally posted by @aireilly in https://github.com/errata-ai/vale/issues/674#issuecomment-1737728128_

**Comment by jdkato** [comment]
This will be fixed in the next release.

**Comment by aireilly** [comment]
Ace! Thanks.
