### ISSUE TITLE
Spellcheck Not Working on some Words

### ISSUE THREAD

**Issue by p0fi** [vale-cli/vale#693]
### Check for existing issues

- [X] Completed

### Environment

OS: https://studio.vale.sh (same behavior on macOS)

### Describe the bug / provide steps to reproduce it

The spellchecking behaves strange. It does not seem to properly check some words. I can't explain why it behaves like this. The "word" `bfejkdgzashjgjHi` is considered an error (correctly since it's rubbish).`bfejkdgZashjgjHi` is no spelling error according to vale. 

Just replace the `z` with a `Z` and vale thinks it's fine.

Vale seems to ignore all words with more than one capital letter in it when it comes to spellchecking? 🤔 

See vale studio: https://studio.vale.sh/s/748b3db8aede321c26d43a9032846f5b

**Comment by jdkato** [comment]
See #527 and the [filters section](https://vale.sh/docs/topics/styles/#ignoring-non-dictionary-words) in the docs.
