### ISSUE TITLE
Add vale version info to studio.vale.sh

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#707]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello,

It might be helpful to see the version of Vale that is running for studio.vale.sh so that I can check if an issue is resolved in the release that Vale Studio is running, or not. 

Thank you!

**Comment by jdkato** [comment]
This is provided in the console:

![image](https://github.com/errata-ai/vale/assets/8785025/e56f92f0-ddc5-421d-8a62-f95e7a9050cb)
