### ISSUE TITLE
Vale 2.29.5 failing on Markdown URLs

### ISSUE THREAD

**Issue by andrewvaughan** [vale-cli/vale#709]
### Check for existing issues

- [X] Completed

### Environment

Docker container (Linux) plus macOS
Installed via Homebrew
Version 2.29.5 (latest stable)

### Describe the bug / provide steps to reproduce it

Apart from the sticky saying that URLs aren't linted, I have this failing:

```Markdown
  - [License](#license)
```

I have a Vocab file enforcing capitalization of `License`, so I'm getting these errors on the actual `#license` part of that line:

```
- Using [vale v2.29.5] https://megalinter.io/beta/descriptors/spell_vale
- MegaLinter key: [SPELL_VALE]
- Rules config: [/.vale.ini]
- Number of files analyzed: [11]
--Error detail:

 README.md
 56:16    error  Use 'License' instead of        Vale.Terms 
                 'license'.                                 
 209:127  error  Use 'Issue' instead of          Vale.Terms 
                 'issue'.                                   
 217:51   error  Use 'License' instead of        Vale.Terms 
                 'license'.                                 
 236:58   error  Use 'Issue' instead of          Vale.Terms 
                 'issue'.                                   
```

**Comment by jdkato** [comment]
I can't reproduce this. Can you share your `.vale.ini`?

**Comment by andrewvaughan** [comment]
My code has changed so much since this time! I can go back and get the commit - but I'm actually working on upgrading to v3 right now. I would say let's close this and I'll reopen and reference the issue if it persists. Thanks!
