### ISSUE TITLE
support Swagger formats (yml, json)

### ISSUE THREAD

**Issue by shudson310** [vale-cli/vale#71]
Some of our teams are using Swagger, and I'd like to find a way to check their code doc. The source formats are in yml and json, so I'm hoping it won't be a stretch to add support for them?

**Comment by jdkato** [comment]
There's really no way that Vale can "support" YAML or JSON beyond what it already does (lint each file line-by-line). The same goes for #68, too.

Have you had issues running Vale on Swagger files?

**Comment by shudson310** [comment]
YAML, JSON weren't specifically listed in the file formats, so I wasn't sure if Vale worked with them or not.

**Comment by jdkato** [comment]
Technically, it doesn't&mdash;most of Vale's scope-related features aren't applicable to data serialization formats.

However, Vale will fall back to simply linting line-by-line for "unrecognized" formats.
