### ISSUE TITLE
Unclear how to apply style to code

### ISSUE THREAD

**Issue by andrewvaughan** [vale-cli/vale#710]
Apologies in advance if this should be clear - I've read the documentation end to end three times and it's really unclear to me. How I go about adding support for prose in code comments is extremely difficult to understand.

If, as an example, I wanted Vale to apply the same `Google,Vale` style guide I use for Markdown to my Makefiles (`[Makefile,*.mak]`), but only the comments, how would I configure it to do so?

Right now, enabling linting on these files results in a plethora of errors on the code itself, wherein I have have only found a solution in adding a ton of syntax to a Vocab (bad, really bad). Is there a way to teach Vale what code looks like, both in blocks and in-line?  I imagine this has something to do with the `TokenIgnores` and `BlockIgnores`, but I find the documentation difficult to understand.

It seems to me that there would not be an ignore functionality, but the opposite - something to tell Vale "this is what a comment looks like, lint this." Does that exist? I assume this is the Scopes section, but that page almost reads like it started in the middle of explaining it - I'm completely lost as to what it's trying to explain, as from the beginning the page is describing elements as if I already understood the underlying Vale concepts behind them, which aren't explained.

Any help would be appreciated.

**Comment by andrewvaughan** [comment]
I'll just do a file association for now.

**Comment by jdkato** [comment]
Vale supports linting comments in a [certain file types](https://vale.sh/docs/topics/scoping/#code-1) (`Makefile` is not supported, currently).

There's no configuration option to "teach" Vale about new file types; support is hardcoded in `internal/core/format.go` (code) or `internal/lint/<markup_type>.go` (markup).

**Comment by andrewvaughan** [comment]
Got it, thank you - that may be something to consider either through plugin or configuration in the future to allow the community to extend functionality. For now, I was able to get away with it via assigning `Makefile` and `*.mk` to a Perl type commenting system. It doesn't lint any outputted text, but it's better than nothing.
