### ISSUE TITLE
Custom Scope Definitions

### ISSUE THREAD

**Issue by Jab2870** [vale-cli/vale#713]
### Check for existing issues

- [X] Completed

### Describe the feature

First off, thank you for creating and maintaining this tool.

We have a number of markdown extensions we use that (for example) turn a yaml block into a table.

For instance:

````
```{.table align=xX}
- Instance: Exmple 1
  Details: some detail
- Instance: Example 2
  Details: some different detail
```
````

Creates

![image](https://github.com/errata-ai/vale/assets/1909202/94fb4300-3772-456b-8025-fc88cb0722d0)

It would be nice if I could define a regex so that vale knows to treat this as a table, applying any `<th>` rules to the yaml keys, and `<td>` rules to the yaml values.

I have read through the documentation, and the [non-standard markup](https://vale.sh/docs/topics/scoping/#non-standard-markup) section, only appears to deal with ignoring markup, not treating it as a specific type of markup

**Comment by jdkato** [comment]
This doesn't fit well with the current markup-processing techniques, so it's unlikely such a feature will be implemented any time soon.
