### ISSUE TITLE
Feature request: CLI arg for config file path

### ISSUE THREAD

**Issue by guykisel** [vale-cli/vale#72]
Hi! Vale looks like a super cool tool. I have a static analysis bot I'm working on that monitors repos via webhooks and runs static analysis tools on pull requests with reasonable defaults (if no config files already exist in the repo). In order to do this, I have default config files built into the tool, and I pass those into the static analysis tools at runtime. Unfortunately, it appears that Vale only looks for config files in the current directory, parent directory, or home directory. I can work around this by just copying config files in, but it would be easier with a CLI option :)

**Comment by jdkato** [comment]
I've added a `--config` argument for specifying the location of `.vale.ini` file. For example,

```shell
$ vale --config='/path/to/file' test.md
```
This seems to be inline with what others linters offer. However, with Vale, you'll still need to have a custom style on disk somewhere (i.e., the value of `StylesPath` in your config file).

**Comment by guykisel** [comment]
Cool! Thank you so much <3
