### ISSUE TITLE
How is vale pronounced?

### ISSUE THREAD

**Issue by sfactor** [vale-cli/vale#720]
A question from a non-native speaker: how do you pronounce 'vale'?

Is it [VAYle] (rhymes with "gale"), as in English for "a vast space between two mountains", "a valley"?

Is it [VAH-leh], as in Latin for "be healthy", "goodbye"?

**Comment by jdkato** [comment]
> Is it [VAYle] (rhymes with "gale"), as in English for "a vast space between two mountains", "a valley"?

**Comment by ChrisChinchilla** [comment]
@sfactor Though this has come up before, especially amongst our non-English users, and there are a few in the community who pronounce it the Italian way as it’s what immediately jumps to mind to them. Naming is hard ;)
