### ISSUE TITLE
Vale action resulting in runtime error, $home not defined

### ISSUE THREAD

**Issue by RCheesley** [vale-cli/vale#721]
### Check for existing issues

- [X] Completed

### Environment

Github Actions: https://github.com/mautic/user-documentation/blob/main/.github/workflows/linting.yml

### Describe the bug / provide steps to reproduce it

I updated recently to [support Reviewdog](https://github.com/mautic/user-documentation/pull/205) based on a similar PR to our [dev docs](https://github.com/mautic/developer-documentation-new/pull/87), but it seems to have broken something and I'm struggling to figure out what!

The process doesn't seem to be working as expected with the GitHub Action, which is wrongly showing as passed when it hasn't actually run (see [example](https://github.com/mautic/user-documentation/actions/runs/6665926564)).

Would really appreciate a hand if anyone can point out the obvious!

**Comment by jdkato** [comment]
You need to update Vale to at least [v2.29.2](https://github.com/errata-ai/vale/releases/tag/v2.29.2).

(https://github.com/errata-ai/vale-action/issues/107)

**Comment by RCheesley** [comment]
Awesome, thanks! I'd searched but apparently not for the right words!
