### ISSUE TITLE
Massive CPU usage when used with VS Code

### ISSUE THREAD

**Issue by theletterf** [vale-cli/vale#722]
### Check for existing issues

- [X] Completed

### Environment

macOS 13.6
VSCode 1.83.1
Vale VSCode extension 0.17.5
Vale 2.29.6

### Describe the bug / provide steps to reproduce it

When doing search & replace operations in VS Code, the editor (or the add-on, I'm not sure) seems to spawn several vale processes, which end up consuming all available CPU cycles. See screenshot after performing a dozen search & replaces in an rST repository (without opening the files):

![](https://i.imgur.com/yZny1uv.png)

I had to close all the vale processes from the Activity Monitor, after which everything got back to normal. This doesn't seem to happen when editing single files. I wonder if this is an add-on issue, a VS Code issue, or a Vale bug.

**Comment by theletterf** [comment]
+CC @ChrisChinchilla

**Comment by jdkato** [comment]
This should be filed here: https://github.com/ChrisChinchilla/vale-vscode
