### ISSUE TITLE
How to make Vale spellchecker suggest alternatioves?

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#725]
### Check for existing issues

- [X] Completed

### Environment

* Debian Linux 12
* install: direct download
* vale version suggest	spellings
* used as a VSCode plugin

### Describe the bug / provide steps to reproduce it

i have the following rule:
```
extends: spelling
message: "'%s' is a typo!"
dicpath: /home/toba/devel/suse-documentation-dicts/build
append: true
custom: true
dictionaries:
  - en_US-suse-doc
ignore:
  - SpellingIgnorelist.txt
action:
  name: suggest
```

how do i make it suggest alternatives to mispelled words after hitting `CTRL+.` in VSCode based on the specified distionaries?

**Comment by ChrisChinchilla** [comment]
@tbazant Spell check suggestions are handled by the editor integration, so if you don't mind moving this over to https://github.com/ChrisChinchilla/vale-vscode, and i will respond asap.

**Comment by tbazant** [comment]
ok, thanks

**Comment by tbazant** [comment]
copied to https://github.com/ChrisChinchilla/vale-vscode/issues/15
