### ISSUE TITLE
Use of common prefix in vocabulary

### ISSUE THREAD

**Issue by nvitucci** [vale-cli/vale#726]
### Check for existing issues

- [X] Completed

### Environment

- OS: macOS 14.1
- Install method: Homebrew
- Vale version: 2.29.6

### Describe the bug / provide steps to reproduce it

Although a [similar issue](https://github.com/errata-ai/vale/issues/476) of non-deterministic behaviour has already been raised, this is more of a request for advice than an actual bug (at least given the current behaviour).

Let's assume the following:

* `accept.txt` vocabulary:

```
MyBrand
MyProduct
MyProduct Community
MyProduct Enterprise
```

* `.vale.ini`:

```
StylesPath = styles

Vocab = Basic

[*.md]
BasedOnStyles = Vale
```

* `test.md` document:

```
Use Myproduct.
Use Myproduct enterprise.
Use MyProduct enterprise.
```

When I run Vale, the output oscillates between this:

```
test.md:1:5:Vale.Terms:Use 'MyProduct' instead of 'Myproduct'.
test.md:2:5:Vale.Terms:Use 'MyProduct Enterprise' instead of 'Myproduct enterprise'.
```

and this:

```
test.md:1:5:Vale.Terms:Use 'MyProduct' instead of 'Myproduct'.
test.md:2:5:Vale.Terms:Use 'MyProduct' instead of 'Myproduct'.
```

Basically, the second line has two possible corrections and the third line is never detected as wrong. As I understand, this happens because `MyProduct` is a common prefix and the result depends on what rule is triggered first.

As a workaround, I put the `MyProduct` common prefix in a separate substitution rule and left only the two more specific lines in the vocabulary. This works, but of course it's not ideal, especially when this pattern is repeated many times and the overlapping elements expand over time. The other downside is that, since the term is not in the vocabulary, it has to be manually added as an exception to other rules (for example, a rule on capitalization of headings).

No amount of tinkering, with regex's and other combinations, to try and put all the definitions in the dictionary would get me around this, and I suspect it's really by design. Even trying to put all the definitions in the substitution rule has the same "competing rule" behaviour, unless I use a hack like this, which works but gives a less useful message as it doesn't capture the prefix:

```
swap:
  - myproduct: MyProduct
  - (?<=myproduct )enterprise: MyProduct Enterprise
```

Is this the best I can do or am I missing any useful Vale features? Or perhaps am I seeing it the wrong way? How would you tackle this problem?

**Comment by jdkato** [comment]
I would do this in two steps.

First, add an entry to `accept.txt` that matches all acceptable forms of the term:

```
MyBrand
MyProduct(?: Community| Enterprise)?
```

This will ensure that correct uses of these terms don't raise alerts in other places (such as your capitalization rule).

Second, create a `MyProduct.yml` rule to enforce the correct usage:

```yaml
extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  - MyProduct(?! Community| Enterprise): MyProduct
  - MyProduct Community: MyProduct Community
  - MyProduct Enterprise: MyProduct Enterprise
```

Here's an example that showcases both parts:

![Screenshot 2023-11-06 at 3 33 03 PM](https://github.com/errata-ai/vale/assets/8785025/0f66fd21-dedc-4146-a320-50555242699c)

**Comment by nvitucci** [comment]
Thanks for the answer. If I try this, though, the third line in my example (with `MyProduct` in the correct form but `enterprise` not) goes still undetected.

Anyway, why is it not possible to achieve this in the vocabulary alone?

**Comment by jdkato** [comment]
In the next release (v3.0.4), this will work with just a vocabulary:

```
Use Myproduct.
Use Myproduct enterprise.
Use MyProduct enterprise.
```

**Comment by nvitucci** [comment]
I just tried it and it seems to work properly. Thank you very much!
