### ISSUE TITLE
After adding a case-insensitive entry in accept.txt Vale does not validate other case-sensitive entries

### ISSUE THREAD

**Issue by sohailekline** [vale-cli/vale#727]
### Check for existing issues

- [X] Completed

### Environment

OS: macOS
Install method: Homebrew
Vale Version: 2.29.6

### Describe the bug / provide steps to reproduce it

I have added few entries in accept.txt (without ?i to make them case-sensitive/exact match), it works fine and Vale throws error if it's not exact match. However, when I am adding one more entry which is case-insensitive (like (?i)word), Vale stops throwing error on other exact-match entires.

Please have a look at following case:

```accept.txt```:

```
PLuG
(?i)GitHub
```

```.vale.ini```:

```
StylesPath = styles
MinAlertLevel = suggestion
Vocab = Base

[formats]
mdx = md

[*.md]
BasedOnStyles = Vale
Vale.Spelling = NO
Vale.Repetition = NO
```

```README.md```:

```
Plug
github
GitHub
```
The output of Vale is below. However, the expected output is it should give an error for Plug because it is not case-insensitive in accept.txt
<img width="432" alt="image" src="https://github.com/errata-ai/vale/assets/140367733/4dbb45de-25ac-47e7-98fd-f84bd6eaa744">

Now, I have changed ```accept.txt``` as per below and it seems working fine:
```
PLuG
GitHub
```
The output of Vale is below. 
<img width="451" alt="image" src="https://github.com/errata-ai/vale/assets/140367733/72ad5d47-488f-46da-ba01-c6b12fa39722">

##Observation

My observation is that if we define any case-insensitive entry all other entires become case-insensitive. This same issue is also found in reject.txt.

**Comment by puneet-ekline** [comment]
@jdkato  Do you have any suggestions here?

**Comment by jdkato** [comment]
Should be fixed now.

**Comment by sohailekline** [comment]
@jdkato Thanks for providing the fix.
