### ISSUE TITLE
Add Julia support

### ISSUE THREAD

**Issue by kellertuer** [vale-cli/vale#729]
### Check for existing issues

- [X] Completed

### Describe the feature

It seems that in this list

https://vale.sh/docs/topics/scoping/#code-1

Julia is not yet included.

Single comments are started with `# (comment)`
Multiline comments are between `#= ... =#`

and (cf https://github.com/errata-ai/vale/discussions/728) if doc strings (or strings in general?) could also be supported as scope that would be awesome!

**Comment by kellertuer** [comment]
I would of course also help adding it or at least be available for tests – just that I have never programmed Go, and I am not sure where to add the language myself, since I have not yet seen where the others are defined.

**Comment by jdkato** [comment]
If you'd like to submit a PR, #579 and #586 are good examples to get started with.

**Comment by kellertuer** [comment]
Thanks for the hint – I understand roughly half of the code in the example PRs and will try my best to extend that.

For example the second entry both have – I have exactly zero clue what that does and why the first reg expo is that super long for Python for example. Also – How I could include doc strings. But I will make that more precise in a first step of a PR then
