### ISSUE TITLE
Can't regex match empty lines 

### ISSUE THREAD

**Issue by wouter-veeken** [vale-cli/vale#73]
I'm trying to set up a simple rule to check that the third line in an admonition block like this starts with exactly four spaces:
```
!!! note "Getting started"

    If you are a developer working with (...)
```

I'm stuck because, no matter what regex pattern I try, nothing seems to match the empty line. For example, consider this:

```
extends: existence
message: "Broken admonition? Check indentation! (Look for: %s)"
ignorecase: true
nonword: true
level: error
raw:
   - '!!!\s(note|warning|tip)\s"[^"]+"'
   - '\W*'  # Matches any non-word character.
#   - '\w'  # Should match any word character, but when you uncomment this line, you'll get 0 matches.
```

Am I doing something wrong or is this a bug?

**Comment by jdkato** [comment]
This really isn't what Vale is designed to do. All markup formats are converted to HTML (which can be traversed in useful ways -- e.g., ignoring code blocks) prior to applying any patterns. This means, though, that attempting to match the markup syntax itself isn't going to be a good experience.

Tools like [markdownlint](https://github.com/markdownlint/markdownlint) or [remark-lint](https://github.com/remarkjs/remark-lint) are probably going to be more useful for cases like this.
