### ISSUE TITLE
TokenIgnores does not work per file path, only per file extension

### ISSUE THREAD

**Issue by zofrex** [vale-cli/vale#732]
### Check for existing issues

- [X] Completed

### Environment

macOS, Homebrew, 2.29.7

### Describe the bug / provide steps to reproduce it

This works:

```
[*.md]
TokenIgnores = something
```

This does not:

```
[some/path/**/*.md]
TokenIgnores = something
```

In the latter case it has no effect.

**Comment by jdkato** [comment]
This should be fixed in the next release.
