### ISSUE TITLE
Ignore/override specific parts of styles

### ISSUE THREAD

**Issue by thernstig** [vale-cli/vale#733]
### Check for existing issues

- [X] Completed

### Describe the feature

We have a setup where we prefer using open source styles, as to not maintain our own. Here is our config:

```ini
StylesPath = ./styles/
MinAlertLevel = warning

[*.md]
#  - Google
#  - Microsoft
#  - alex
BasedOnStyles = proselint,write-good,Readability,RedHat
write-good.Passive = OFF
write-good.TooWordy = OFF
# The following rule will suggest that "analysis" is replaced by
# "SmartState analysis".
RedHat.CaseSensitiveTerms = OFF
```

But the `write-good` style contains a file like write-good/Weasel.yml for [weasel words](https://en.wikipedia.org/wiki/Weasel_word). The definition for Weasel.yml can be found here: https://github.com/errata-ai/write-good/blob/master/write-good/Weasel.yml

We want to mark the term (token) `only` as being ok, but using the rest. This is not possible now in any way.

Is there any planned support for this, or is it a bad idea overall?

**Comment by ccoVeille** [comment]
The only solution I can see for the issue reported by @thernstig is to copy the weasel rules locally, as a new local package, and disable writegood one with `write-good.Weasel=NO`

**Comment by jdkato** [comment]
You can do this with a [vocabulary](https://vale.sh/docs/topics/vocab/).
