### ISSUE TITLE
Capitalization rule does not seem to account for vocabulary words that are capitalized

### ISSUE THREAD

**Issue by kolchfa-aws** [vale-cli/vale#735]
### Check for existing issues

- [X] Completed

### Environment

macOS, Homebrew, 2.29.7

### Describe the bug / provide steps to reproduce it

We have existing Vale workflows that check for sentence case capitalization in headings. When the Vale version was upgraded to 2.29.7, the rules started flagging correctly capitalized headings. This happens both when running Vale as a CI on GitHub and when running Vale locally. For example, it flags this heading:

````
# Example with Canada should not be flagged
````

Custom vocabulary words still are considered, but Vale vocabulary words seem to not be considered. The `BasedOnStyles` includes Vale and nothing has been changed except the Vale version upgrade. Would appreciate some help looking into it. Thanks!

**Comment by jdkato** [comment]
I can't reproduce this. 

Here's an example using the latest version (v2.30.0): https://studio.vale.sh/s/04105cc799b8ca4abd47378a51a6a0a3

What was your previous version of Vale before updating to 2.29.7?

**Comment by kolchfa-aws** [comment]
We have an additional setting `threshold: 1` for the capitalization rule. With this threshold, the example above is flagged.

**Comment by jdkato** [comment]
This appears to be working as intended. 

There is no built-in "Vale vocabulary," so if you have `threshold: 1` (the strictest setting), then `Example with Canada should not be flagged` is not correctly capitalized according to your rule.

You either need to lower the `threshold` or add the word to a vocabulary.
