### ISSUE TITLE
Supporting both in-repo and local rules

### ISSUE THREAD

**Issue by amyq** [vale-cli/vale#737]
### Check for existing issues

- [X] Completed

### Describe the feature

(I've been idly thinking about how to solve this problem for some time.)

On the technical-writing team at GitLab, we copy the GitLab style into every Git repository our writers work in, but not all the rules that we propose for the GitLab style get accepted. Several of us have wanted the ability to stack local / personal rules atop in-repo rules. I haven't thought of a smart way to do this. I've opened up https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139279 to look for a shorter-term solution, but Evan and Marcel both suggested I bring it up here, too.

Here's the real-life example: a rule called `MayMightCan.yml` wasn't accepted into the `gitlab` style. However, I'd still like to use it locally, because I'm (redacted) _terrible_ at remembering to use the right word. Ideally, I'd have a second location (let's assume in my user folder) where I could drop in this extra rule, and have it available to me in all the repos (10+) that I work in. 

https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139279 tries to find a kludgy path forward and proposes:

1. adding a second style folder to the `gitlab` repo
1. calling it either `personal` or `local`.
1. adding a line to the root `.gitignore` file to ignore everything in `doc/.vale/local`

This proposed kludgy approach would be fine. It beats the nothing I currently have. However, I'd love to use `MayMightCan.yml` regardless of what repo I'm working in at the time.

Feel free to tell me this is an edge case for someone who touches a LOT of projects. It might well be.

**Comment by jdkato** [comment]
This will be possible with the proposed changes in #688 (specifically, the notion of a default `StylesPath`).

**Comment by jdkato** [comment]
This is out now.

**Comment by amyq** [comment]
Wild. I ask and then … boom, added. Not gonna lie; this is some serious wish fulfillment here.
