### ISSUE TITLE
extends:spelling - bufio.Scanner: token too long

### ISSUE THREAD

**Issue by jpgerdeman** [vale-cli/vale#738]
### Check for existing issues

- [X] Completed

### Environment

- Windows 10
- podman using jdkato/vale
- vale version v2.29.7
- a repository to reproduce the error can be found at https://github.com/jpgerdeman/vale-issue-787
- hunspell dictionary used https://github.com/wooorm/dictionaries/tree/main/dictionaries/de

### Describe the bug / provide steps to reproduce it

When trying to integrate a german dictionary I get the following error 

```
E201 Invalid value [/docs/styles/base/german.yml:1:1]:

   1* extends: spelling
   2  message: "Did you really mean %s?"
   3  custom: true

bufio.Scanner: token too long

Execution stopped with code 1.
```

I based this approach on the comment found in https://github.com/errata-ai/vale/issues/481

--

I initially used the dictionary from libreoffice, but that could not be read due to encoding errors. This issue https://github.com/errata-ai/vale/issues/328 then pointed me at the woorm-repository

**Comment by jdkato** [comment]
The dictionary used in your reproduction repo is not valid: it appears that you downloaded the webpage source code instead of the actual dictionary files.

**Comment by jpgerdeman** [comment]
Thank you, so much. I got it working now.
