### ISSUE TITLE
BlockIgnore missing global flag?

### ISSUE THREAD

**Issue by andrewvaughan** [vale-cli/vale#746]
### Check for existing issues

- [X] Completed

### Environment

macOS, Homebrew

`vale version 2.30.0`

### Describe the bug / provide steps to reproduce it

Per the Regex here:
https://regex101.com/r/JnqtkN/1

The RegEx I provided should match and ignore each code block (\```.*```) independently. It finds 6 matches in my example Markdown.

However, with Vale, I lose all prose linting on the file with this `BlockIgnore` configuration set. My best guess as to what is occurring is that the RegEx query doesn't have the global flag set (maybe?) so it is ignoring everything in the file from the first \``` block to the last \``` block in the file, but it's hard to be certain.

**Comment by jdkato** [comment]
Fenced code blocks are [ignored by default](https://vale.sh/docs/topics/scoping/#markdown). 

Ignore patterns are intended for matching against [non-standard](https://vale.sh/docs/topics/scoping/#non-standard-markup) markup and are applied prior to conversion to HTML. If you target known constructs (such as code blocks) you can interfere with the conversion process.
