### ISSUE TITLE
Bug: `VALE_CONFIG_PATH` ignored since 3.0.0

### ISSUE THREAD

**Issue by chrisgrieser** [vale-cli/vale#750]
### Check for existing issues

- [X] Completed

### Environment

vale version 3.0.0 (download by the vale-ls)
macOS 14.1 (arm)

### Describe the bug / provide steps to reproduce it

The previously working `VALE_CONFIG_PATH` is being ignored since 3.0.0

![Pasted image 2024-01-10 at 15 48 29@2x](https://github.com/errata-ai/vale/assets/73286100/a0b2b1ac-a766-445b-ad7e-04f02e4ae6ed)

**Comment by charlesBochet** [comment]
We are facing the same issue on https://github.com/twentyhq/twenty

We are going to move the .vale.ini to the root folder temporarily but it would be great to fix it :)

**Comment by kKronstainBrown** [comment]
Same here:
```
{
  "Code": "E100",
  "Text": "E100 [vocab] Runtime error\n\n'config/vocabularies/WordUsageVocab' directory does not exist\n\nExecution stopped with code 1."
}
```
Hardcoded to version 2.3.0 as a temporary workaround.

**Comment by aireilly** [comment]
I did some testing this morning hoping that a symlink would work as a stop-gap but it appears that Vale does not see symlinks.

**Comment by jdkato** [comment]
This is fixed now. I'll put out a new release tomorrow.

**Comment by jdkato** [comment]
@kKronstainBrown: Your issue is unrelated to `VALE_CONFIG_PATH`; v3.0 expects vocabularies to be in `$StylesPath/config/vocabularies` as mentioned in the Breaking Changes section of the [release notes](https://github.com/errata-ai/vale/releases/tag/v3.0.0).
