### ISSUE TITLE
Cannot get packages to work with the new 3.0.0 release

### ISSUE THREAD

**Issue by karl-johan-grahn** [vale-cli/vale#751]
### Check for existing issues

- [X] Completed

### Environment

vale version 3.0.0

### Describe the bug / provide steps to reproduce it

I've spent considerable time trying to get packages to work, don't know if there is a regression in the new major release. Was looking at https://github.com/errata-ai/vale/issues/634 and https://vale.sh/docs/topics/packages/ and the release notes but cannot get a package to be properly installed.

Can you please provide a sample package and instructions for how to use it, with the parent `.vale.ini` as well, for full reproducibility? I get stuck in error after error and not progressing any further without a reproducible example, thank you!

**Comment by karl-johan-grahn** [comment]
With the new `config` directory in https://github.com/errata-ai/vale/releases/tag/v3.0.0 I am not able to understand how the package should be structured and how the parent `.vale.ini` should look like

**Comment by karl-johan-grahn** [comment]
https://github.com/errata-ai/vale/blob/v3/testdata/pkg/v3.zip provides some hints but it is missing an example `.vale.ini` file and I need an example of the parent `.vale.ini` file importing the package as well

**Comment by jdkato** [comment]
Does the latest release and the new [test examples](https://github.com/errata-ai/vale/tree/v3/testdata/fixtures/pkg) help?

If not, could you provide the error message and your package layout?

**Comment by aarongoldenthal** [comment]
I have the same issue. My `.vale.ini`:

```ini
StylesPath = .gitlab/vale/styles
Packages = https://<my-custom-package>/GCIU.zip
MinAlertLevel = suggestion
Vocab = GCIU

[*]
BasedOnStyles = Vale, GCIU
```

The downloaded `GCIU.zip` has 2 files:

```
GCIU/config/vocabularies/GCIU/accept.txt
GCIU/Readability.yml
```

When I try `vale sync`, I get:

```sh
/app # vale sync
E100 [vocab] Runtime error

'config/vocabularies/GCIU' directory does not exist

Execution stopped with code 1.
```

If I create the missing directory `.gitlab/vale/styles/config/vocabularies/GCIU` then `vale sync` installs everything properly. If I then run `vale` the `GCIU.Readability` rule (and others) are working, but the `GCIU` vocabulary is not loaded. If I add an `.gitlab/vale/styles/config/vocabularies/GCIU/accept.txt`, that vocabulary is used.

None of the examples linked above use a package vocabulary, so wasn't sure if it needed to be called out differently.

This is with v3.0.3.

**Comment by aarongoldenthal** [comment]
@jdkato I re-read [the docs](https://vale.sh/docs/topics/packages/#complete) and checked the [updated example](https://github.com/errata-ai/vale/tree/v3/testdata/fixtures/pkg/complete) in v3.0.4 and I understand the structure now. Thanks for the clarification.
