### ISSUE TITLE
Allow StylesPath to be set without changing the .vale.ini

### ISSUE THREAD

**Issue by alexeagle** [vale-cli/vale#755]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm looking to wire vale into a hermetic build tool (Bazel). It wants to manage dependencies itself, so I have a path to the `styles/` directory at runtime that a user shouldn't need to predict and hard-code into their config file.

I'd like to be able to run with environment `VALE_STYLES_PATH=/some/path` or else possibly a new flag `--stylesPath=/some/path`

**Comment by jdkato** [comment]
The next release will add support for `VALE_STYLES_PATH`.

**Comment by alexeagle** [comment]
Thank you! That allowed me to simplify the installation instructions for Bazel users. https://github.com/aspect-build/rules_lint/pull/148

**Comment by jdkato** [comment]
A general comment on re-packaging Vale assets: I would personally discourage implementing alternative means of managing a `StylesPath` -- but if you do, you need to understand the difference between a *style* and a *package*.

A *style* is a collection of rules (that is, a folder of YAML files). Styles could, in theory, be managed by alternative systems that merely copy their contents into the user's `StylesPath`. 

A [*package*](https://vale.sh/docs/topics/packages/), however, cannot be managed this way. Packages should in general be thought of as complete Vale configurations, including a `.vale.ini.` file and an entire `StylesPath` (which can contain styles, vocabularies, dictionaries, ignore files, and output templates). You can't just copy these into an existing `StylesPath`; each asset type needs to be handled appropriately.

The entries listed at https://github.com/errata-ai/packages should be considered to be *packages*. While many of them are currently [style-only](https://vale.sh/docs/topics/packages/#style-only), this is not a safe assumption in general.

cc @bollwyvl
