### ISSUE TITLE
Vale 3.0.5 treats vocabulary slightly different when installed from Brew versus GitHub release artifacts

### ISSUE THREAD

**Issue by karl-johan-grahn** [vale-cli/vale#756]
### Check for existing issues

- [X] Completed

### Environment

vale version 3.0.5 on macOS

### Describe the bug / provide steps to reproduce it

My vocabulary contains:
```txt
vpn
VPN
```

Sample content:
```txt
Here is some text containing the word VPN.
```

I install vale locally using brew:
```sh
$ brew install vale
$ vale -v
vale version 3.0.5
```

I then get this error for the above content:
```sh
$ vale content
...
error  Use 'vpn' instead of 'VPN'.  Vale.Terms
```

When I run vale via GitHub actions I install vale via:
```sh
$ wget https://github.com/errata-ai/vale/releases/download/v3.0.5/vale_3.0.5_Linux_64-bit.tar.gz -O vale.tar.gz
$ tar -xvzf vale.tar.gz vale
```

When the GitHub workflow runs, it does not return this error, it expects `vpn` to be spelled `VPN`.

Any clue why the difference in error handling between brew vale and the GitHub release artifact?

**Comment by jdkato** [comment]
See https://github.com/errata-ai/vale/issues/706#issuecomment-1771748870.
