### ISSUE TITLE
StylesPath does not get updated after vale sync

### ISSUE THREAD

**Issue by karl-johan-grahn** [vale-cli/vale#757]
### Check for existing issues

- [X] Completed

### Environment

vale version 3.0.5 on macOS

### Describe the bug / provide steps to reproduce it

After having done a `vale sync` for a package, it seems the default `StylesPath` does not get updated. I had to remove it to get it synchronized again. I think we need to add an option to enable more verbose output for vale, for this issue the output for `vale sync` need more info in particular.

**Comment by jdkato** [comment]
I can't reproduce this.

Can you share your `.vale.ini` and the resulting `StylesPath` after running `sync`?

**Comment by karl-johan-grahn** [comment]
I can't reproduce it now either, and must have had some incorrect configuration, because vale was initially using the config from `/Users/<user>/Library/Application Support/vale/styles/.vale-config`, and that is the folder I was referring to that did not get updated after `vale sync`.

Now I have this config and it correctly synchronizes the local `styles` folder:
```sh
$ cat .vale.ini
StylesPath = styles
MinAlertLevel = warning

Packages = https://github.com/stakater/vale-package/releases/download/v0.0.3/Stakater.zip
Vocab = Stakater

# Only check MarkDown files
[*.md]

BasedOnStyles = Vale
```

My request is still valid though, that I would like more comprehensive logging. I just get:
```sh
**vale sync
 SUCCESS  Downloaded package 'Stakater'
Downloading packages [1/1] ███████████████████████████████████████████████████████████████████████████████████ 100% | 1s**
```

At a minimum, it should specify exactly where it downloaded the package.

**Comment by aarongoldenthal** [comment]
I haven't been able to reproduce it, but saw it as well (for example [here](https://gitlab.com/gitlab-ci-utils/container-images/vale/-/jobs/6068440681)).

**Comment by karl-johan-grahn** [comment]
Got it today:
```sh
$ vale sync
 SUCCESS  Downloaded package 'Stakater'
Syncing 1 package(s) to '/Users/karljohangrahn/git/repo/styles' [1/1]  100% | 1s
$ vale content

 content/file.adoc
 22:4  error  Did you really mean 'Trello'?  Vale.Spelling

✖ 1 error, 0 warnings and 0 suggestions in 12 files.
$ rm -rf "/Users/karljohangrahn/Library/Application Support/vale/styles/config/"
$ vale content
✔ 0 errors, 0 warnings and 0 suggestions in 12 files.
```
