### ISSUE TITLE
snapcraft.io package oudated

### ISSUE THREAD

**Issue by hex-m** [vale-cli/vale#758]
### Check for existing issues

- [X] Completed

### Describe the feature

The [vale-version users get via Snap](https://snapcraft.io/vale) is [2.15.4](https://github.com/errata-ai/vale/releases/tag/v2.15.4) which is more than 18 months old. It's not a recommended installation type in the [manual](https://vale.sh/docs/vale-cli/installation/) but users still find an install from this seemingly unmaintained channel.

Seemingly @jdkato is the owner of the package on snapcraft.

**Comment by alexmurray** [comment]
@jdkato I would be happy to help maintain the snap if needed - I couldn't find an existing snapcraft.yaml but I just created one that bundles both vale and vale-ls together if you want to take a look - https://github.com/alexmurray/vale-snap

**Comment by jdkato** [comment]
That would be great, thanks!

If my understanding is correct, you'll also need to bundle `rst2html` and `asciidoctor` for users who want to use reStructuredText or AsciiDoc. Hugo does something similar here: https://github.com/gohugoio/hugo/blob/ca31b95f30e01ef027bf0cabc39692e673faa602/snap/snapcraft.yaml#L165

**Comment by alexmurray** [comment]
Thanks - added in https://github.com/alexmurray/vale-snap/commit/e4ea1bd6ec11079c76031e6ff4d7b2674bc6302e

**Comment by alexmurray** [comment]
Would you be willing to add me as a collaborator to the snap? You should be able to do this at https://dashboard.snapcraft.io/snaps/vale/collaboration/ and add the email `alex.murray@canonical.com`.

Is the existing snapcraft.yaml maintained somewhere or would you want me to switch it to the one under my own github username?

**Comment by jdkato** [comment]
I sent the invite. You can switch it to the new repo.

**Comment by alexmurray** [comment]
Thanks - I've just done that but on second though, in general I think it would be best if the repo with the snapcraft.yaml was either in your own github namespace or the errata-ai one - since you are still listed as the publisher on snapcraft.io (which I think is great, as you are the upstream author it lets users gain more trust in the snap). Thoughts? I'll add you as a collaborator on the current repo but let me know if you want me to transfer it to you instead (but then if you want I can stay on as a collaborator on the github repo and keep it up-to-date as needed).

**Comment by jdkato** [comment]
We can transfer it to this org and keep you as a collaborator, if you'd like.

Another option is to build it with GoReleaser (which already handles the GitHub releases and Chocolatey) in this repo. I'm not totally sure of the process, but it seems possible: https://goreleaser.com/customization/snapcraft/

**Comment by alexmurray** [comment]
I'm not sure if GoReleaser supports all the architectures that are available in the store - whereas if we build it via the store itself then we will get them all, so I think I would prefer to keep it that way. I'll transfer the repo when I'm not on my phone. Cheers.

**Comment by alexmurray** [comment]
I tried to transfer it but Github says: "You don’t have the permission to create public repositories on errata-ai"

So I think you will have to do that @jdkato - thanks.

**Comment by alexmurray** [comment]
@jdkato so I think perhaps if I transfer ownership of the repo to you, then you can transfer it to errata-ai - would that work? Unless you are able to do it yourself directly as a collaborator?

**Comment by jdkato** [comment]
I can't transfer the repo as a collaborator.

**Comment by alexmurray** [comment]
Ah ok - I just transferred the repo to you - can you then transfer it to errata-ai? Then I'll update the webhook on build.snapcraft.io to refer to the new location. Thanks.

**Comment by jdkato** [comment]
I transferred it.

**Comment by alexmurray** [comment]
Hmm I can't seem to see the new repo via the build.snapcraft.io service - so I think either I would need to be added to the errata-ai organisation on github OR you might need to browse to https://snapcraft.io/vale/builds and set up the webhook to point at the transferred repo. Thanks @jdkato
