### ISSUE TITLE
Bug with Asciidoc image macros

### ISSUE THREAD

**Issue by nvitucci** [vale-cli/vale#764]
### Check for existing issues

- [X] Completed

### Environment

- OS: macOS 14.3
- Install method: Homebrew
- Vale version: 3.0.7

### Describe the bug / provide steps to reproduce it

There seems to be a bug with image macros in AsciiDoc.

Let's assume the following:

- `.vale.ini`:

```
[*.adoc]
BasedOnStyles = Vale
```

- `test1.adoc`:

```
Some image.

image::privatelink_01.png[title="Some title"]
```

- `test2.adoc`:

```
Some image.

image::privatelink_01.png[title="Some title"]

Another image.

image::privatelink_02.png[title="Another title"]
```

Running Vale on `test1.adoc` gives no errors, while running it on `test2.adoc` results in the following error:

```
 7:8  error  Did you really mean             Vale.Spelling
             'privatelink'?
```

(The same happens with the inline macro `image:` instead of the block macro `image::`.)

**Comment by jdkato** [comment]
This is an edge case similar to "bare links" mentioned in https://github.com/errata-ai/vale/issues/320.

You need to either provide alternative text (which I recommend):

```asciidoc
image::privatelink_01.png["My alt text", title="Some title"]
```

or disable the `alt` scope:

```ini
SkippedScopes = script, style, pre, figure, alt
```

**Comment by nvitucci** [comment]
Thank you, I can confirm that adding alt text fixes it.
