### ISSUE TITLE
Vale not taking config file from `doc/.vale.ini`

### ISSUE THREAD

**Issue by dipinknair** [vale-cli/vale#765]
### Discussed in https://github.com/errata-ai/vale/discussions/761

<div type='discussions-op-text'>

<sup>Originally posted by **dipinknair** January 30, 2024</sup>
With new vale version 3.0.6 , vale --config='doc/.vale.ini'  sync is giving the error [Windows]

`open : The system cannot find the file specified. `

I can see most of the repo has .vale.ini in root folder. Is this a requirement with new version?
It was working fine with same vale config path with 2.29.6
Tested with github repo and getting the same error where no file found [failed documentation check](https://github.com/ansys/pymechanical/actions/runs/7713867790/job/21024793579?pr=582)

</div>

**Comment by thisislawatts** [comment]
Thanks for sharing @dipinknair, I had something similar when using vale via the CircleCI orb. In the end I moved the .vale.ini file back to the root to unblock myself. I have been force pushing, so I have no commit left to proof it :) 

Failing build: https://app.circleci.com/pipelines/gh/ONEARMY/community-platform/7968/workflows/6175a4c8-df72-4124-bcb1-4a97a0076e08/jobs/68539

**Comment by jdkato** [comment]
This should be fixed in v3.0.7. Note, however, that the "workaround" mentioned in #761 will not work: in v3.0, vocabularies are *required* to be in `<StylesPath>/config/vocabularies`.

**Comment by dipinknair** [comment]
Thanks @jdkato  for fixing the doc/.vale.ini issue. I have tested with v3.1.0. I would like to mention here that I am still using old path for vocabularies and I am able to use vale with `Vocab = ../../Vocab/ANSYS`
Here is the changes and result
changes: https://github.com/ansys/pymechanical/pull/582/files
result : https://github.com/ansys/pymechanical/actions/runs/7968483374/job/21753970607?pr=582#step:2:176
