### ISSUE TITLE
Document style sharing across projects

### ISSUE THREAD

**Issue by alexfauquette** [vale-cli/vale#770]
### Check for existing issues

- [X] Completed

## Context

I added vale to MUI projects a year ago to enforce consistency in naming conventions for the documentation. It's going well, contributors start to add their own rules when they face typing issues :+1:

I extended it to another repository. But now, it implies that to add 1 rule you need to open a PR in each repository.

## Request

Is there a recommended way to define rules once and share them across repositories?

I expected to find in a docs something like create a GitHub repository with your vocabulary and link your configs to it.

**Comment by jdkato** [comment]
You can do this with [Packages](https://vale.sh/docs/topics/packages/).

**Comment by alexfauquette** [comment]
Thanks for the direction. I missed the bullets point will reading it :+1:

If I correctly understand this section the solution is to host it as a zip files.

> The Packages key accepts four types of values:
>
> - A name of a package hosted in the official [Package Hub](https://vale.sh/hub/);
> - a URL to an externally-hosted package;
> - an absolute or relative path to a .zip file located in the local file system; or
> - an absolute or relative path to a directory containing package files.

Because we only have very few rules, I would have expected to be able to import a single style without having to zip them.

But for now, I will take the pipeline of https://github.com/errata-ai/packages as an example
