### ISSUE TITLE
How to add per-project spelling ignore list

### ISSUE THREAD

**Issue by AliSajid** [vale-cli/vale#774]
### Check for existing issues

- [X] Completed

### Describe the feature

First, this is an amazing tool and I've starting pushing for $WORK to adopt this as a standard for our docs.

However, I am a little confused about how to ignore words in specific contexts on a per-project basis.

I know that you can add an ignore file using the [ignore](https://vale.sh/docs/topics/styles/#spelling) section while generating rule but I'm unsure how I can add a per-project file.

I use cSpell and a few other things that use a single word list to ignore and this would be helpful.

Thank you.

**Comment by jdkato** [comment]
You can do this with [Vocabularies](https://vale.sh/docs/topics/vocab/).
