### ISSUE TITLE
terms in reject.txt not working

### ISSUE THREAD

**Issue by AnabasisXu** [vale-cli/vale#783]
### Check for existing issues

- [X] Completed

### Environment

OS: Window 10
Vale version 3.2.0

### Describe the bug / provide steps to reproduce it

I put one and only term in the rejct.txt: `test`;
Then I run `vale rejct.txt` and another file on another location with `test`, both showed no error.

I also put `asdf` and `Grammarly` in accept.txt and then run  `vale accept.txt`. Result in a warning of Grammarly but not `asdf`: 
```
 accept.txt
 2:1  warning     Use correct American English    RedHat.Spelling
                  spelling. Did you really mean
                  'Grammarly'?
```

My ini file:
```
StylesPath = "G:\vale\styles"

MinAlertLevel = suggestion

Vocab = Base

[*.{txt,md,org,html}]

BasedOnStyles = RedHat

```

**Comment by jdkato** [comment]
You need to enable the `Vale` style to use the built-in rules:

```ini
BasedOnStyles = Vale, RedHat
```

**Comment by AnabasisXu** [comment]
Sorry I just could not get it working even after the following setting.

```
BasedOnStyles = Vale, RedHat
```

File structure of config file:

```
G:\VALE\STYLES\CONFIG
├─dictionaries
├─ignore
└─vocabularies
    └─current
```
Current ini file:

```
StylesPath = "G:\vale\styles"
MinAlertLevel = suggestion
[*.{txt,md,org,html}]
BasedOnStyles = Vale, Google, RedHat

Vocab = current

Vale.Repetition = off
Vale.Terms = NO
```

Content of the accept.txt
```
cybersecurity
Grammarly
```

run `vale 1.md` which has the same content as accept.txt and it showed:
```

 1.md
 1:1  error       Did you really mean             Vale.Spelling
                  'cybersecurity'?
 1:1  suggestion  Grade level (31.15) too high.   RedHat.ReadabilityGrade
 2:1  error       Did you really mean             Vale.Spelling
                  'Grammarly'?
 2:1  warning     Use correct American English    RedHat.Spelling
                  spelling. Did you really mean
                  'Grammarly'?
````

Before running into this problem, I used scoop to install vale and deleted the old vale.exe. Now scoop installed vale at `C:\Users\Administrator\scoop\shims\vale.exe`. Could it be the problem caused by scoop?

**Comment by jdkato** [comment]
You want this:

```ini
StylesPath = "G:\vale\styles"
MinAlertLevel = suggestion

Vocab = current

[*.{txt,md,org,html}]
BasedOnStyles = Vale, Google, RedHat

Vale.Repetition = off

# NOTE: this disables half of the vocab-related functionality.
Vale.Terms = NO
```

**Comment by AnabasisXu** [comment]
Hi @jdkato! Than you  so much! Now it works.

A further minor issue: I found that I must keep the first line of the `accept.txt` empty and start from the second line. 
For example, if I put `Grammarly` at the first line of `accept.txt`, then it will not work. Move it to the second line will work.
