### ISSUE TITLE
Use tree-sitter libraries for parsing

### ISSUE THREAD

**Issue by cpkio** [vale-cli/vale#785]
### Check for existing issues

- [X] Completed

### Describe the feature

Using tree-sitter parsers will allow scoping without losing line numbering (obviously, if you want to edit, you need original line numbers, not after processing). Markdown flavours and reStructured text are available.

Sadly, asciidoc tree-sitter parser is still not available though.

**Comment by jdkato** [comment]
Vale doesn't lose line number information; its alerts are returned accurate to the original source file.

That said, I have considered tree-sitter for source code (there's actually a branch that implements this). However, the dependency more than triples the size of Vale's binary and the benefits (for Vale's use case) aren't that significant.

**Comment by cpkio** [comment]
Setting tree-sitter aside, what I meant by "loses" is I mostly don't get original (source) line numbers when linting asciidoc, which means I cannot go to that line immediately. And if I use `--ignore-syntax`, I lose scoping capabilities. I understand this is because of Asciidoc to HTML conversion which does not preserve source line numbering.

If there's a way to have both scoping and line numbers from original asciidoc file, I'm all ears.

**Comment by jdkato** [comment]
Could you provide an example of this?

**Comment by cpkio** [comment]
[here](https://workupload.com/file/SmERJ9hdZKd), `vale index.adoc`

**Comment by jdkato** [comment]
This is a bug related to #414 and multi-byte (non-English) characters. It should be fixed in the next release.
