### ISSUE TITLE
Titles with 'To' (with T in caps) reported as error when following title-style capitlization

### ISSUE THREAD

**Issue by dgomezg** [vale-cli/vale#787]
### Check for existing issues

- [X] Completed

### Environment

OS: macOS
Install method: direct download
vale version 3.2.2

### Describe the bug / provide steps to reproduce it

Given the following rule:
```
extends: capitalization
message: "'%s' should use title-style capitalization."
level: error
scope: heading.h1
match: $title
```

and the following input

```
<h1>Pages To Improve</h1>

<h1>Welcome To Product Library</h1>
```

both raise a violation of the rule:

```
build/site/contribution_guide/reference/improvements.html
 150:30  error  'Pages To Improve' should use title-style capitalization.

 build/site/home/index.html
 113:30  error  'Welcome To Product Library' should use title-style capitalization.
```

If I change the input to have the `t` in `to` in small caps, then the error disappears.

```
<h1>Pages to Improve</h1>

<h1>Welcome to Product Library</h1>
```

**Comment by dgomezg** [comment]
Before (at least in v 2.23) the rule it was passing with both 'To' and 'to'. Which I'm not sure if it's correct either (I would expect that To should always be in CAPS)

**Comment by jdkato** [comment]
In both of Vale's supported title-case styles, `AP` (default) and `Chicago`, this is the expected result.

It seems like you're looking for a "always capitalize every word" style, which you can implement with a `match` pattern:

```yaml
extends: capitalization
message: "'%s' should use title-style capitalization."
level: error
scope: heading.h1
match: '^(?:[A-Z\d][^\s]+ ?)*$'
```

**Comment by dgomezg** [comment]
Oh! I wasn't aware of that subtle nuance with $title.

Thanks for the clarification.
