### ISSUE TITLE
Styles path not found after following initial setup documentation

### ISSUE THREAD

**Issue by wezm** [vale-cli/vale#788]
### Check for existing issues

- [X] Completed

### Environment

OS: Arch Linux
Install method: AUR
Vale version: vale version 3.2.2

### Describe the bug / provide steps to reproduce it

I followed the [Quick Start](https://vale.sh/docs/vale-cli/structure/#quick-start) to setup Vale:

1. Generate `.vale.ini` with [the config generator](https://vale.sh/generator)
2. cd to my project
3. `vale sync`
4. `vale README.md`

The last step produces this error:

```
E100 [NewE201] Runtime error

The path '/home/wmoore/Projects/rsspls/styles' does not exist.

Execution stopped with code 1.
```

Here is a transcript of my session including my config and ouput of `vale ls-dirs`:

```
$ cd rsspls
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Syncing 1 package(s) to '/home/wmoore/.local/share/vale/styles' [1/1]  100% | 2s
$ vale README.md
E100 [NewE201] Runtime error

The path '/home/wmoore/Projects/rsspls/styles' does not exist.

Execution stopped with code 1.
$ cat .vale.ini
StylesPath = styles

MinAlertLevel = suggestion

Packages = RedHat

[*]
BasedOnStyles = Vale, RedHat

$ vale ls-dirs
Asset       | Default Location                             | Found
StylesPath  | /home/wmoore/.local/share/vale/styles        | ✓
.vale.ini   | /home/wmoore/.config/vale/.vale.ini          | ✗
vale-native | /home/wmoore/.config/vale/native/vale-native | ✗

$ env | grep VALE
# no matches
```

It appears to be syncing to the default `StylesPath` but looking for a project local one when performing checks.

**Comment by dgomezg** [comment]
In case it may help you temporarily: I solved the problem changing the `StylesPath` property in the .dev.ini to `.`:

```

#StylesPath = styles
StylesPath = .

MinAlertLevel = suggestion

Packages = RedHat
```
