### ISSUE TITLE
ls-metrics command does not work on .mdx files

### ISSUE THREAD

**Issue by puneetar** [vale-cli/vale#792]
### Check for existing issues

- [X] Completed

### Environment

2.29

### Describe the bug / provide steps to reproduce it

It seems the `ls-metrics` command is not working for *.mdx files. 

When I update them to be *.md the command works fine. 

Here is my .vale.ini
```
StylesPath = styles


[formats]
mdx = md

[*.md]
BasedOnStyles = myStyle
Vale.Spelling = NO
```

```
$> vale ls-metrics src/solutions.mdx
{}

```
```
$>  vale ls-metrics src/solutions.md
{
    "characters": 14128,
    "complex_words": 384,
    "heading_h2": 7,
    "heading_h3": 16,
    "list": 31,
    "long_words": 709,
    "paragraphs": 107,
    "polysyllabic_words": 450,
    "pre": 1,
    "sentences": 200,
    "syllables": 4582,
    "words": 2881
}

**Comment by jdkato** [comment]
MDX is not a supported format. Associating it with Markdown requires a number of configuration adjustments to achieve good results.
