### ISSUE TITLE
Vale Studio error [[object Object]] TypeError: Failed to fetch

### ISSUE THREAD

**Issue by pwalleni** [vale-cli/vale#795]
Visiting https://studio.vale.sh/ displays the following error message:

![image](https://github.com/errata-ai/vale/assets/44832734/d7c90d2b-bd0c-4b61-8110-680dbc767042)

Thanks for making Vale Studio!

**Comment by jdkato** [comment]
I've recently switched hosting providers (and to a free tier), but there have been a number of performance issues.

I'm evaluating options to hopefully resolve this.

**Comment by jdkato** [comment]
This should be fixed now.
