### ISSUE TITLE
Improve our documentation

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#80]
We've been through a number of iterations on our documentation (hosted at a few different places) but, now that we've reached a stable release, I think it's time to stop moving around.

The final resting place for our docs will be at https://errata-ai.github.io/vale/, with the actual source included in this repo ([`docs/`](https://github.com/errata-ai/vale/tree/master/docs)). There's a lot that could be improved, but I'll start by listing topics that aren't documented (well) at all:

- [x] The CLI arguments (and when to use them) [44aed256d18f382b8168aee5d38a32cb1043f61b].
- [x] Vale's built-in rules&mdash;e.g., [`Repetition`](https://github.com/errata-ai/vale/blob/master/rule/vale/Repetition.yml).
- [x]  The [contributing guide](https://github.com/errata-ai/vale/blob/master/.github/CONTRIBUTING.md) (outdated) [44cc1ee803268284f154805baa3d03acf55b5040].
- [ ] Discuss using Vale with languages other than English.
- [x] Discuss using Vale with unsupported file formats.
- [x] Discuss the performance tradeoffs of various features.
- [ ] The [`pos` key](https://github.com/errata-ai/vale/blob/master/check/defintions.go#L54).
- [x] Rule [templates](https://github.com/errata-ai/vale/blob/master/check/templates.go) (outdated) [47ed93b57ea4a4b6b0c30c8247aa75a4ac2bbd33].
- [x] Using Vale and Docker
- [x] Improve the [config](https://errata-ai.github.io/vale/config/) docs [e2b3737d974726a0ddcf09410d044947d5c223df; WIP]
- [x] Create a Quickstart section [859a4ebba4873bd32214119323d1b90718187043]

**Comment by jpoesen** [comment]
May I also suggest adding a quickstart section with the most minimal configuration example possible?
Such as: 

1. choose one of the install methods
2. copy the following example text file demo,md (full of errors that should be caught) to a location of your choice
3. cd into that location
4. run 'vale demo.md'
5. if everything went well, you should see the following output.

The above should unambiguously demonstrate that the tool is installed and working correctly. The beginning user can then move on to more complex configuration options.

I'd be happy to help write this and other docs  - it's the best way to learn after all.

Thanks!

**Comment by jdkato** [comment]
I agree - that sounds like a good idea. And, yes, I'm open to documentation PRs.

Thanks for the input!

**Comment by ChrisChinchilla** [comment]
I will have a go at this soon, and tie it in to our Test the Docs work. I have a huge run of conferences that will finish around mid-November, and then have more time :)

**Comment by ChrisChinchilla** [comment]
Started here, but will do some more polish before I make a PR.

**Comment by jdkato** [comment]
@ChrisChinchilla, have you started on the "Quickstart" guide mentioned above? If not, I'm going to try to write that this weekend.

**Comment by ChrisChinchilla** [comment]
@jdkato I'm on the "built-in rules"

**Comment by gtuckerkellogg** [comment]
Is anyone working on documentation for the `pos` key? I'm trying to create a rule to warn use of "pretty" when followed by an adjective (e.g., "pretty good") but I haven't been able to figure out how to manage regexps and the POS. What I've got right now is `pos: 'pretty \w+/JJ'`, guessing from the example in the current doc and another example in the boilerplate, but my use of the key key does nothing that I can tell.

**Comment by jdkato** [comment]
@gtuckerkellogg: This sort of use case isn't supported (yet). I discussed some ideas for incorporating POS tags into rules in #110, but it's still a work in progress.

The `pos` tag is only supported in `substitution` rules and, essentially, says "match this token (a provided value) when it has a certain tag"; it doesn't support matching all tokens (a variable) that have a certain tag.
