### ISSUE TITLE
`minalertlevel` via CLI

### ISSUE THREAD

**Issue by ArthurFlag** [vale-cli/vale#825]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm certain I've overridden the minAlertLevel setting in my ini via the CLI but I can't remember what the flag was. `vale -h` also doesn't show it, and I cannot find it in the docs. 

Would it be possible to have added to CLI help and to the docs? 

Thanks!

**Comment by jdkato** [comment]
The intended way to do this now is through a [filter](https://vale.sh/manual/filter/), which can reference any key (not just `level`):

```shell
$ vale --filter='.Level=="error"' docs
```
