### ISSUE TITLE
Provide a way to add exclusions to repetitions

### ISSUE THREAD

**Issue by jvoisin** [vale-cli/vale#826]
### Check for existing issues

- [X] Completed

### Describe the feature

[repetitions](https://vale.sh/docs/topics/styles/#repetition) don't provide a way to handle exclusions, only inclusions.

I'd love to implement a `%s is repeated` check, but it's ripe for false-positives without exclusions, like "oh oh oh", "sapiens sapiens", "did did", …

**Comment by jdkato** [comment]
This will be available in the next release.
