### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by vladmoroz** [vale-cli/vale#829]
### Check for existing issues

- [X] Completed

### Describe the feature

Is there a recommended way to use Vale in the JS ecosystem? [@ocular-d/vale-bin](https://www.npmjs.com/package/@ocular-d/vale-bin) is mentioned on the website, but that package is outdated and marked as deprecated.

**Comment by jstirnaman** [comment]
I've been using `@vvago/vale`, which does the same thing, but so far is still maintained.

**Comment by jdkato** [comment]
I've removed the mention of `vale-bin`. I don't have another recommendation currently.

**Comment by oliviertassinari** [comment]
I'm facing the same problem; keeping a single coherent version of Vale is hard. We have 4 different versions of vale to sync:

1. VS Code Vale https://marketplace.visualstudio.com/items?itemName=ChrisChinchilla.vale-vscode.
2. Vale running locally
3. Vale running in CI for full linting
4. Vale running in GitHub Action for annotations

And we want 5. Auto update logic.

Using `@vvago/vale` allows to fix 2. 3 and 5 (renovate). For 4, this can be worked around with a bash script that extracts the value from the pnpm lock file. But for 1, I couldn't find a solution. Final solution: https://github.com/mui/material-ui/pull/46029.

It would be great to have a versioning concept built into Vale, so all the tools' versions can be synced more easily.
