### ISSUE TITLE
Please release 1.0.4

### ISSUE THREAD

**Issue by docwhat** [vale-cli/vale#83]
I just spent about an hour trying to figure out why my configurations were not working only to discover that this commit 3e118bf5a70928a359adbb9b5fa48ca8b468df1f was not present in v1.0.3 (that I got via Homebrew).

Please release v1.0.4 just to prevent this kind of frustration for others.

Thanks!

**details**

I kept trying to configure my global setup but `vale dc` wasn't showing anything.  I tried all kinds of work arounds, fixes, etc.

**Comment by jdkato** [comment]
It's out.
