### ISSUE TITLE
existence rule skips match in RST

### ISSUE THREAD

**Issue by mikemckiernan** [vale-cli/vale#831]
### Check for existing issues

- [X] Completed

### Environment

Ubuntu 20.04 in WSL2
Direct download
3.4.1 (and compiled from source 3.4.2)

### Describe the bug / provide steps to reproduce it

Difficult to rep, but the screencap of [mached.PNG](https://github.com/mikemckiernan/troubleshoot-vale/blob/main/not-matched.PNG) in a reproducer repo shows that "BIG needles" is flagged as an existence match several times, but on line 15 it is not matched.

You can rep the issue by cloning https://github.com/mikemckiernan/troubleshoot-vale, and then running `vale --config ./.vale.ini ./Needle.rst`.  Line 15 is not included in the response.

I've spent some time trying to narrow this down more.  Unfortunately, I'm not familiar with the code or much with Go.

I did step through some of the code in the VS Code debugger and can say that an alert object is created on lint.go:283, but it's somehow discarded by subsequent processing that I haven't noodled through.

**Comment by jdkato** [comment]
Thanks for the report.

This is caused by the TOC inserting content into the generated HTML that doesn't exist in the source document.

It should be fixed in the next release.

**Comment by mikemckiernan** [comment]
Cool, TY!  Is there a branch that has the fix?

Closing.
