### ISSUE TITLE
Different rules for different file types?

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#832]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm facing the following problem: our company is using XML DocBook and AsciiDoc as source languages. As of now, we share the same set of style rules. Although 95% of rules apply to both languages, some are correct in one language and not applicable in the other one. For example, `Replace " with <quote/>` does not apply to AsciiDoc, same goes for `Use &nbsp; to join number and unit` in 10 GB. Is there any solution how to pick rules that differ based on the file source language except for creating a whole new set of rules?

**Comment by jdkato** [comment]
You can do this in your `.vale.ini` file:

```ini

[*.adoc]
# AsciiDoc rules ...

[*.xml]
# DockBook rules ...
```

Or at the rule-level by using a format-specific scope:

```yaml
scope: text.adoc
```

**Comment by tbazant** [comment]
> You can do this in your `.vale.ini` file:
> 
> ```ini
> [*.adoc]
> # AsciiDoc rules ...
> 
> [*.xml]
> # DockBook rules ...
> ```
> 
how about having 2 subdirs, `adoc`, `xml`, `common` and use
```
[*.adoc]
BasedOnStyles=adoc/
[*.xml]
BasedOnStyles=xml/
[*.adoc, *.xml]
BasedOnStyles=common/
```
is that possible?
> Or at the rule-level by using a format-specific scope:
> 
> ```yaml
> scope: text.adoc
> ```
can there be more scopes combined? such as
```
scope: text.adoc, raw.adoc
```

**Comment by jdkato** [comment]
Yes:

```ini
[*.adoc]
BasedOnStyles = Common, AsciiDoc

[*.xml]
BasedOnStyles = Common, XML
```

where `Common`, `AsciiDoc` and `XML` are custom styles on your `StylesPath`.

> can there be more scopes combined?

Yes, see [Multi-scope rules](https://vale.sh/docs/topics/scoping/#multi-scope-rules). However, `raw` shouldn't be combined with any other scope.
