### ISSUE TITLE
How do I view spelling suggestions?

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#834]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm working with VSCode, have hunspell files for custom dictionaries and the following rule file:
```
extends: spelling
message: "'%s' may be a typo."
dicpath: /usr/share/hunspell
append: true
custom: false
dictionaries:
  - en_US-suse-doc
```
spellchecking works fine, but how do i make VSCode offer me suggestions to mispelled words after clicking the yellow bulb or pressing `CTRL + .` ? currently, it says `No suggestions found`

**Comment by jdkato** [comment]
Please open this issue here: https://github.com/ChrisChinchilla/vale-vscode
