### ISSUE TITLE
Incorrect suggestions with extends: substitution and ignorecase: true

### ISSUE THREAD

**Issue by natalia-laptieva** [vale-cli/vale#835]
### Check for existing issues

- [X] Completed

### Environment

v3.4.1 in Vale Studio
v3.4.2 in IDE (WebStorm), macOS, Vale installed with Homebrew

### Describe the bug / provide steps to reproduce it

When I use the `extends: substitution` extension point with the `ignorecase: true` parameter, I expect that if I specify a word in lowercase, the matched word is corrected with lowercase and the same with uppercase. 
For example, `e-mail` will be replaced with `email` and `E-mail` with `Email` accordingly.
```
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: true
action:
  name: replace
swap:
  e-mail: email
```
This is how it worked before (can't specify the version): 
![Screenshot 2024-03-28 at 15 22 28](https://github.com/errata-ai/vale/assets/145927872/25a643e9-cc0d-49a8-9d1e-1ebd78ff2659)
Now, it doesn't work like that, so `E-mail` is to be replaced with `email`, and the corresponding tests are failing:
![image](https://github.com/errata-ai/vale/assets/145927872/2a951c2f-a2ed-4429-8f33-9f0d3b3d4abd)
Example with Microsoft rules: 

- [Test in Vale Studio with v3.4.1](https://studio.vale.sh/s/70ce6cecad56a7064790151c5bb7d1d6)
- [Test case](https://github.com/errata-ai/Microsoft/blob/7db88c42fd9d11d2367c24f2db1c2a3eb5523be7/fixtures/Contractions/test.md?plain=1#L15) 
- [Expected result](https://github.com/errata-ai/Microsoft/blob/7db88c42fd9d11d2367c24f2db1c2a3eb5523be7/features/rules.feature#L83)

The same behavior in the IDE with v3.4.2.

**Comment by jdkato** [comment]
This behavior has been moved behind the `capitalize` key:

```yaml
# Will attempt to match capitalization of original token.
capitalize: true
```

The reasoning for this is that it's undesirable in any case with a fixed capitalization style (such as "iOS" or "JavaScript").
