### ISSUE TITLE
Add a correct word marked as misspelled into a custom ignore file

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#836]
### Check for existing issues

- [X] Completed

### Describe the feature

cSpell offers this functionality that makes life much easier - when a word is marked as misspelled but still it's correct, users can collect such words into a specified file. We can then enhance our official wordlist based on these collected custom ignore files.

**Comment by jdkato** [comment]
This already supported [3 different ways](https://vale.sh/docs/vale-cli/structure/#config): Ignore files (1 word per line, spelling only), Dictionaries (Hunspell-compatible dictionaries, spelling only), or Vocabularies (all rules).

**Comment by tbazant** [comment]
ok, where should i file issues for the vscode-vale extension then? i'd like to have such functionality in GUI as quickfix with the yellow bulb
