### ISSUE TITLE
Why did you stop maintaining the NPM library version?

### ISSUE THREAD

**Issue by moritzWa** [vale-cli/vale#849]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/ocular-d/vale-bin

> This repository has been archived by the owner on Nov 12, 2023. It is now read-only.

**Comment by jdkato** [comment]
This project was maintained by a third party, so I can't speak for their decision to archive it.

**Comment by moritzWa** [comment]
cc @svx @ocular-d

**Comment by ChrisChinchilla** [comment]
What's your use case @moritzWa ? As also, some use cases are now covered by the language server, I am nearly done with implementing that in the VSCode extension and could provide instructions on how to use that with javascript
