### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jpds** [vale-cli/vale#86]
It'd be neat if there was an official Docker image on dockerhub for Vale. :)

**Comment by jdkato** [comment]
I've been meaning to do this as part of the [GoReleaser](https://goreleaser.com/docker/) process. I'll try to include it in the next release.

**Comment by jdkato** [comment]
A Docker image will now be published with each [release of Vale](https://github.com/errata-ai/vale/releases/tag/v1.0.6):

```shell
$ docker pull jdkato/vale
```
More detailed documentation will be added soon. Let me know if there's any issues with the image; I'm admittedly not a big Docker user.
