### ISSUE TITLE
Repetition based rule does not function across new lines

### ISSUE THREAD

**Issue by SecondSkoll** [vale-cli/vale#865]
### Check for existing issues

- [X] Completed

### Environment

Testing performed in Vale Studio and on Linux via Python install.

### Describe the bug / provide steps to reproduce it

When a repeated word is separated by a line break, Vale does not report the word as repeated - even if a line break is the only character between them. 

A simple modification to the library repetition example can test this, [here is a link to it in Vale Studio](https://studio.vale.sh/s/4b36e7f54b3d0cf24d17f386a53e9372). Does not function in raw scope either.

Repeated words can occur frequently with documents written in non-wrapping IDEs, so I would expect Vale to pick these cases up - but I may be incorrect about this (though it's not mentioned in the documentation). From a brief look at the codebase [this](https://github.com/errata-ai/vale/blob/3c73133d3d0e647e3e2ba63d6bf3bf202d5a34a1/internal/check/repetition.go#L98) might have been in place to address this, and might not be working, but I really don't know Golang very well and can't say for sure.

**Comment by Ravlen** [comment]
@jdkato If it helps, here are a variety of examples of this: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/172468

There's also some other edge cases in there of duplicate words that are being missed that I can't figure out why they aren't being caught. Like:

- `As as result, they may need to be scaled as well.` (`As as`, capitalization problem?)
- ``| Alert event  |   | `alert` | A a new, unique alert is recorded. |`` (`A a`, capitalization/table-related problem?)
- `1. Follow the job under "View Logs" until the pipeline completes completes. Here's an example of a successful output:` (`completes completes`, ordered list problem?)
- (`Registry registry`, ordered list problem?):

  ```md
  1. Connect your Artifact Registry repository to your GitLab project by following the
     instructions in [Set up the Google Artifact Registry registry in a GitLab project](../../user/project/integrations/google_artifact_management.md).
  ```

Also, doesn't work across link text, but that's might be expected:

- `see the Mermaid [Mermaid user guide](https://mermaid.js.org/intro/getting-started.html)`

**Comment by jdkato** [comment]
This should be dramatically improved now. If you're so inclined, you can build from the `v3` branch to try it out.

**Comment by Ravlen** [comment]
Thanks so much, I'll test it as soon as I can!
