### ISSUE TITLE
Hanging on large text file

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#87]
After installing 1.0.5, I found that it would hang trying to scan this file https://github.com/w3c/html/blob/master/diff/html5to51diff.html
It is an 11.5MB text file, so it is a little unreasonable.

**Comment by jdkato** [comment]
When passing `--ignore-syntax`, this now takes about a minute for me:

```
vale --ignore-syntax test.html  70.05s user 0.91s system 106% cpu 1:06.42 total
```
