### ISSUE TITLE
Exclude paths that are in .gitignore automatically

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#88]
I was trying to figure out the correct way to exclude results from packages like `node_modules`. I didn't figure out the syntax yet, but I figured that using the `.gitignore` paths to exclude results would make sense since the author has already indicated they are not sources.

**Comment by jdkato** [comment]
In general, the best way to exclude results from directories like `node_modules` is to avoid calling Vale from the repository root (i.e., not using `vale .`). It's hard to say for sure without seeing the particular structure, but many projects will have some form of a `docs/` directory that can be passed directly to Vale.

In any case, respecting `.gitignore` patterns shouldn't be particularly difficult. There's some previous work that we could probably leverage:

- https://github.com/monochromegane/go-gitignore
- https://github.com/monochromegane/the_platinum_searcher/blob/master/ignore.go

**Comment by nschonni** [comment]
You're right that targeting folders is the simplest solution to this. I've found that Vale has been good at catching things in code comments so I've been running it at the root of repos. That's not an issue when running on a freshly cloned repo, but catches as soon as packages are restored.

**Comment by jdkato** [comment]
I've looked into this more and I don't think it's something that I want to do for a few reasons:

- it adds non-trivial overhead: (1) you have to find the `.gitignore` (it could be in parent or child directories from where Vale is called), (2) you have to parse its patterns (which [`go-gitignore`  doesn't fully support](https://github.com/monochromegane/go-gitignore#features)), and then (3) you have to check every file against it.
- There are other source control options (e.g., `.hgignore`) that I'm not interested in supporting.
- it's something that can be done better (IMO) and fairly easily by wrapping Vale in a shell script that leverages tools designed for this task. [There are some examples here](https://unix.stackexchange.com/questions/358270/find-files-that-are-not-in-gitignore).
