### ISSUE TITLE
lint more than comments in code

### ISSUE THREAD

**Issue by ilrudie** [vale-cli/vale#884]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if code types, go/rust/c/etc..., could do more than just lint the comments. I'm thinking static strings would be very handy to lint especially if it is something that can be toggled in settings. Ignoring things like function names, variable names and structures makes a lot of sense but often static strings are things that will be output to a user so the ability to lint those would be great.

**Comment by ccoVeille** [comment]
I can confirm.

misspell (Go) helps a lot on finding typos, but I would love getting linting on string literals and fmt.Sprinf family

**Comment by jdkato** [comment]
If I were to change this, I'm almost certain someone would come along and dislike that strings are now linted. So, I'm going to close this in favor of #769.

The idea is to allow users to write tree-sitter queries to specify exactly what they'd like to lint.

**Comment by ilrudie** [comment]
Yup. Any change like this is bound to upset someone. Configurable seems like a good alternative. TY
