### ISSUE TITLE
Regex case sensitivity workaround in accept.txt doesn't work as expected 

### ISSUE THREAD

**Issue by jrahal-mx** [vale-cli/vale#901]
### Check for existing issues

- [X] Completed

### Environment

OS: macOS 13.4.1
Install Method: Homebrew
Vale Version: 3.7.1

### Describe the bug / provide steps to reproduce it

In accept.txt, if I add `[Oo]bservability` per the example in the docs, Vale will accept `observability` and `Observability`.

I'd expect `oBservability` to trigger an alert because it doesn't match the pattern of:

- Case sensitively matching a single character in the list `[Oo]`
- Case sensitively matching `bservability`

Instead, it seems that Vale ignores casing on the rest of the string outside of `Oo`.

Do I need to build the regex differently to get it to match only lower-case `bservability`?

**Comment by jdkato** [comment]
This will be fixed in the next release.

**Comment by jrahal-mx** [comment]
Thank you!
