### ISSUE TITLE
Implement netrc support for sync

### ISSUE THREAD

**Issue by jackwhelpton** [vale-cli/vale#905]
### Check for existing issues

- [X] Completed

### Describe the feature

In order to sync private packages, it would be handy for `vale sync` to respect the `.netrc` configuration; this is not without precedent for HTTP(S), as `curl` behaves that way (and would be the model for the behavior to be introduced).

This would allow authentication via basic auth in a consistent manner across a variety of hosts, and both locally and in CI/CD scenarios.

Happy to work on a PR for this (although my time is constrained so can't make a promise on how quickly I can get it done).

**Comment by jdkato** [comment]
My suggestion here is usually to use `curl` (or whatever else you'd like) to download the package and then `sync` using a local file path.

It's always difficult to define the scope of a tool, but re-implementing this functionality in Vale is not something I see great value in.

**Comment by jackwhelpton** [comment]
Ah, I could maybe use a bit more detail on how that approach would work: I thought `vale sync` would read package URLs from the local `.vale.ini`, as per https://medium.com/valelint/introducing-packages-1a079ed712f7; I'm unclear on how I can insert a manual sync into this process.

Wouldn't I need to rewrite the `.vale.ini` to refer to the local copies, and how would this work? In a CI/CD pipeline I can see a route through, but it's still a lot of work: parse `.vale.ini`, download the resources locally and then update the references.

Locally, with this in place, you just need to tell collaborators "run `vale sync`". Without it, if the references in `.vale.ini` are to local copies that aren't committed (because we want to centralize them and avoid multiple separately maintained copies), how do they know where to fetch the copies from, via `curl` or any other tool?

Hopefully that helps elucidate the value. Vale already enables this for public packages (including those hosted at arbitrary URIs): if the HTTP get functionality was _entirely_ absent from the tool I could understand wanting to avoid feature creep, but the way it currently operates we need a different workflow only in those cases where the package is privately hosted.

I agree it's overhead to implement this, but not without precedent (`git`, `curl` and the `go` binary all do this).

Fwiw, the change itself would look something like https://github.com/errata-ai/vale/compare/v3...jackwhelpton:vale:feature/netrc

**Comment by jdkato** [comment]
> Wouldn't I need to rewrite the .vale.ini to refer to the local copies, and how would this work? In a CI/CD pipeline I can see a route through, but it's still a lot of work: parse .vale.ini, download the resources locally and then update the references.

No, you don't need to do any of this. The `packages` key accepts [multiple types of input values](https://vale.sh/docs/topics/packages/#structure-and-hosting), one of which is a relative path to the `.zip` file.

```ini
StylesPath = styles

Packages = MyPackage.zip

[*.md]
# other config
```

The steps are (1) download the file and (2) run `vale sync`. Presumably, you could combine this into one command, `setup-vale` (or whatever), that you use in CI and for local collaborators.

**Comment by jackwhelpton** [comment]
Moved the conversation back to Slack as there doesn't seem to be an appetite for this, but in the interest of completeness I'll repeat the same query here...

By moving to local package references we remove from `.vale.ini` any reference to where the package _really_ lives, so something else has to maintain that: if it's a setup script, we potentially have that mapping duplicated in every repo that needs to use the same remote package.

From the aforementioned Slack thread:

>The workaround recommended is to use local (relative) paths, but I'm still missing a crucial piece of config that would make that reusable without a lot of duplication and a maintenance headache. To see my problem, consider using remote URIs:
>
>Packages = https://my-private-repo/style-1/vale-package.zip,https://my-private-repo/style-2/vale-package.zip
>
>All the information about where to pull the packages is neatly encapsulated in `.vale.ini`. The suggestion appears to be to use relative URIs for these, so something like:
>
> Packages=./style-1.zip,./style-2.zip
>
> and a separate `vale-setup.sh ` or similar.
>
>You can see my quandary - what "knows" that `style-1.zip` needs to be downloaded from https://my-private-repo/style-1/value-package.zip? That configuration is no longer reflected in the `.vale.ini`, so we need to encode that information into our `vale-setup.sh`, which is potentially duplicated across multiple repos.

**Comment by jdkato** [comment]
Yes, you'll have to maintain a setup script or document the required commands.

There are ways to avoid duplicating it in every repo (such as hosting it somewhere), but I really don't think this is much of a "maintenance headache" -- the script only needs to be one or two commands.

On the other hand, I think you're vastly underestimating the scope of supporting authentication mechanisms in Vale. Storing credentials in plain text `.netrc` files is generally not an acceptable solution. And most of the tools you've cited as examples include both alternative methods and some notion of a "credential helper" to integrate with the OS.


I understand you may disagree, but  I feel such a request is out of scope for Vale.
