### ISSUE TITLE
Vale checks MadCap Flare-specific attribute values

### ISSUE THREAD

**Issue by konradkolo** [vale-cli/vale#906]
### Check for existing issues

- [X] Completed

### Environment

- OS: Windows
- Install method: choco
- Vale version: 3.4.0

### Describe the bug / provide steps to reproduce it

I'm using Vale to check `.html`, `.htm`, and `.flsnp` files in MadCap Flare. I can't get Vale to ignore attribute values of MadCap Flare-specific elements, such as snippets or variables.

I tried excluding the Flare-specific tags with `IgnoredScopes` and `SkippedScopes`, as well as classes with `IgnoredClasses` as per docs, but couldn't get it to work.

### Source code

In the following HTML content, Vale picks up the `informat` string from the attribute value (**informat**ion-signal-word.flsnp).

```html
<MadCap:snippetBlock src="../Resources/Snippets/notices/signal-words/information-signal-word.flsnp" />
```

### Vale alert

```
Check the spelling of 'informat' Vale(Custom.SpellingAmE)
```

### Triggered rule

Path: `.vale\styles\Custom\SpellingAmE.yml`

```yaml
extends: spelling
message: "Check the spelling of '%s'"
level: warning
dicpath: config/dictionaries
dictionaries:
    - en_US
```

### Vale config

```yaml
StylesPath = .vale/styles
MinAlertLevel = suggestion

Vocab = Base

Packages = <URL to the internal package, irrelevant to the problem>

[formats]
flsnp = html

[*.{html,htm,flsnp}]
BasedOnStyles = Vale, Custom

# Disable the default Vale spellchecker
Vale.Spelling = NO
```

**Comment by jdkato** [comment]
You'll need to convert the Flare-specific tags to valid HTML using XSLT. 

See the [XML](https://vale.sh/docs/topics/scoping/#xml) docs for more information. Most of the relevant information here will probably be provided by the Flare docs, though.

**Comment by konradkolo** [comment]
@jdkato Do you think it would be possible to extend the [Non-standard markup](https://vale.sh/docs/topics/scoping/#non-standard-markup) mechanisms to other formats than currently supported?

Having the ability to de-scope/ignore specific regex patterns (for example, targeting Flare's `<MadCap:snippetBlock/>`) from the Vale check for HTML (or XHTML, in Flare's case) would be a really cool feature.
