### ISSUE TITLE
Add support for YAML

### ISSUE THREAD

**Issue by dblock** [vale-cli/vale#911]
### Check for existing issues

- [X] Completed

### Describe the feature

Coming from https://github.com/opensearch-project/opensearch-api-specification/issues/599 and an attempt to use Vale in https://github.com/opensearch-project/opensearch-api-specification/pull/620, we'd like to use Vale as a style guide for content in YAML files. Our YAML files are source code for an OpenAPI spec, so we would like to be able to say things like "only check the field called description".

(Could attempt to contribute with some pointers of where to start.)

**Comment by kolchfa-aws** [comment]
@dblock Seems that there is a similar [closed issue](https://github.com/errata-ai/vale/issues/412), which contains a link to the [blog with implementation options](https://medium.com/valelint/vale-the-openapi-specification-8a7cfae135fb)

**Comment by jdkato** [comment]
I think such processing of data-serialization formats is out of scope for Vale. https://github.com/errata-ai/vale/issues/383 is another related issue.

**Comment by dblock** [comment]
@jdkato That's surprising, Vale has support for things like [Docbook XML](https://github.com/errata-ai/vale/issues/114) for example, is this that different?

**Comment by dblock** [comment]
FYI in https://github.com/opensearch-project/opensearch-api-specification/pull/620 I pruned YAMLs from all markup leaving only text and ran vale on it with `--ignore-syntax` successfully. It's a bit hacky but it works. I think a generic way to pre-process structured content like YAML would make things easier to use.
