### ISSUE TITLE
[lintRST] Runtime error rst2html not found after upgrading Vale GitHub Action

### ISSUE THREAD

**Issue by RCheesley** [vale-cli/vale#915]
### Check for existing issues

- [X] Completed

### Environment

GitHub Actions using this repo: https://github.com/mautic/mautic-community-handbook 

Failing action: https://github.com/mautic/mautic-community-handbook/actions/runs/11451197888/job/31860005118?pr=241. 

Trying to fix in this PR including upgrading the GitHub Action: https://github.com/mautic/mautic-community-handbook/pull/241.

### Describe the bug / provide steps to reproduce it

I think this might be related to https://github.com/errata-ai/vale/issues/157 and https://github.com/errata-ai/vale/issues/326 but I'm struggling to find a fix for it.

I have tried explicitly adding rst2html or docutils in our requirements.txt file to no avail, and I'm a bit stuck now how to proceed. 

We had this working before, but it stopped working as we were very out of date with our GitHub Action. 

After upgrading the GitHub Action things have ground to a halt due to this new error, so trying to figure out what we can do to get things flowing again as we've got a tonne of new contributors via Hacktoberfest making PRs! 😅 

Would really value any help!

**Comment by RCheesley** [comment]
Figured it out - in the past we didn't need to install/build Python in the GitHub Action but now we do: https://github.com/mautic/mautic-community-handbook/pull/241/commits/ffffbb7c30bef0396149ec735578780acd525225 posting in case someone else comes across it!

**Comment by jdkato** [comment]
https://github.com/errata-ai/vale-action/issues/138#issuecomment-2427931672

**Comment by RCheesley** [comment]
Aha thanks @jdkato - totally missed that in any of the Vale docs :)
