### ISSUE TITLE
Words prefixed with a quote are ignored by spell check

### ISSUE THREAD

**Issue by alecthegeek** [vale-cli/vale#920]
### Check for existing issues

- [X] Completed

### Environment

macOS

Home brew

Vale 3.8.0

### Describe the bug / provide steps to reproduce it

When a word is prefixed with a quote (" or ') it is ignored for spell checking. for example (using a Posix shell)

```sh
vale \\\"Helloxxxx
```

Does not return a spelling error

`vale \"Helloxxxx` returns `1:2  error  Did you really mean 'Helloxxx'?  Vale.Spelling`

If this is working as intended then we should update the docs.

(when I say "we" I mean me)

**Comment by jdkato** [comment]
I can't reproduce this.

I would need to see your `.vale.ini` to say for sure, but I'd guess that you are't applying any rules to `stdin`:

```console
$ vale \\\"Helloxxxx
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
$ vale --ext=".md" \\\"Helloxxxx  
stdin.md
 1:3  error  Did you really mean             Vale.Spelling 
             'Helloxxxx'?                                  

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```
The rules are applied from your `.vale.ini` based on file extension, which needs to be assigned when using `stdin`.

**Comment by alecthegeek** [comment]
Adding a the `--ext` does change the behaviour so spell checking is consistent.

```
$ vale --ext=.md \\\"helloxxxxx

 stdin.md
 1:3  error  Did you really mean             Vale.Spelling
             'helloxxxxx'?
``` 

However `vale helloxxxxx` and `vale \\\"helloxxxxx` are not consitent?


```ini
; Add some some pre-defined style guides (packages)

; Ignore anything above error. Options “suggestion”, “warning”, or “error” (defaults to “warning”).
MinAlertLevel = error

; Where all the Vale related files live
StylesPath = .styles

; Third party style guides for download
Packages = write-good, Readability

; Settings for all Files
[*]

; Which style guides apply
BasedOnStyles = Vale, write-good, Readability

```

**Comment by jdkato** [comment]
> However vale helloxxxxx and vale \\\"helloxxxxx are not consitent?

These are different inputs, and they're different yet again if you assign a markup format:

```console
$ vale helloxxxxx
 stdin.txt
 1:1  error  Did you really mean             Vale.Spelling 
             'helloxxxxx'?                                 

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

`helloxxxxx` triggers `Vale.Spelling`

---

```console
$ vale \\\"helloxxxxx
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```
`\"helloxxxxx` does *not* trigger `Vale.Spelling` because it matches the built-in, [nonword filter](https://vale.sh/docs/checks/spelling#filters).

--- 

```console
$ vale --ext='.md' \\\"helloxxxxx
 stdin.md
 1:3  error  Did you really mean             Vale.Spelling 
             'helloxxxxx'?                                 

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

`"helloxxxxx` triggers `Vale.Spelling`. Note the difference between a word starting with an escaped `"` (Markdown) and a word starting with `\"` (plain text).

---

I think using contrived `stdin` examples is only serving to make this harder to understand.
