### ISSUE TITLE
Option to ignore keys in JSON/YAML

### ISSUE THREAD

**Issue by infotexture** [vale-cli/vale#922]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to run Vale on the JSON files that contain the UI text for a web app.

If I pass the files to Vale it works, but returns lots of false positives because the string IDs in the keys don't follow the rules _(and don't need to)_, so I'm looking for a way to ignore the **keys** in each `"key": "value"` pair, and only run on the **values**.

These files store strings in [i18next’s nested JSON](https://www.i18next.com/misc/json-format) format, so there are multiple levels like this:

```json
{
  "level1": {
    "level2": {
      "stringOnLevel3": "Modal dialog title",
      "nestedObjectOnLevel3": {
        "level4": {
          "stringOnLevel5": "Body text in the dialog with a nasty tttypo.",
          "nestedObjectOnLevel5": {
            "saveStringOnLevel6": "Save",
            "cancelStringOnLevel6": "Cancel"
          }
        }
      }
    }
  }
}
```

I realize I can add the keys to a vocabulary’s `accept.txt` file to avoid the false positives and make sure any new keys get reviewed, but that could be a bit fiddly and extra work to maintain.

Given that this use case is similar to the challenges in [linting OpenAPI files](https://medium.com/valelint/vale-the-openapi-specification-8a7cfae135fb), I'm wondering whether a more generic approach would be useful, so you would have a way to tell Vale to ignore _(or skip)_ all keys _(or all values)_ and run on the rest of the file without having to script a mechanism to extract the text you want to lint.

Perhaps the [Scoping](https://vale.sh/docs/topics/scoping/) mechanism could be extended, so you could do something like this in the config file:

```ini
[*.{json,yaml,yml}]
SkippedScopes = keys
```

or like this:
```ini
[*.{json,yaml,yml}]
IgnoreKeys = YES
```

**Comment by jdkato** [comment]
This has been requested many times (https://github.com/errata-ai/vale/issues/911, for example).

My response has been that I see this as being out of scope for Vale. It's a fundamentally different task than the existing scoping system is designed to handle. 

It's more about having a semantic understanding of the format than a structural one, as there's no consistent scopes. 

Some want to just ignore keys, while others want to only lint values associated with certain keys. In both cases, the content may contain embedded markup.

https://github.com/errata-ai/vale/issues/769 is the issue to watch here. I'm not exactly sure of the route that is going take, but it will hopefully help in cases like this.

**Comment by infotexture** [comment]
> This has been requested many times

Apologies for overlooking those. 🙇 (I did try searching for related issues, but apparently not with the right terms.)

The use cases in issues like https://github.com/errata-ai/vale/issues/383 and https://github.com/errata-ai/vale/issues/412 are indeed quite similar, so it certainly seems to be a common request.

Glad to hear it's on the radar, will keep an eye on https://github.com/errata-ai/vale/issues/769.

Thanks for your work here. 🙏
