### ISSUE TITLE
Bug: typo "lesbiens" in LGBTTerms rule file

### ISSUE THREAD

**Issue by CristinaRO** [vale-cli/vale#93]
Expected: "lesbians"

Found: "lesbiens"

https://github.com/errata-ai/vale/blob/64d9f922d8612685e9b06bac8c46fed93c955deb/rule/proselint/LGBTTerms.yml#L8

**Comment by jdkato** [comment]
Thanks -- I've fixed this in b833459. I'll release a new version relatively soon, I'm just hoping to resolve #92 first.
