### ISSUE TITLE
Version controlling packages by archive name

### ISSUE THREAD

**Issue by rainecheck** [vale-cli/vale#931]
### Check for existing issues

- [X] Completed

### Describe the feature

I've been trying to get `vale sync`/packages working, but need to version control my packages in a repository (in this case, Sonatype Nexus). General practice which involves having the version of the package in their name, e.g. `foobarbaz-1.0.0.zip`. From what I can tell from experimenting with the packages feature, the .zip file's name *must* match the contained folder and name of the style exactly:

- for a Style-only package, the name of the zip must match the name of the style folder, which must match the name of the style itself
- for a Config-only package, the name of the zip file must match the name of the folder containing the .ini file
- for a Complete package, the name of the zip file must be "styles.zip". The contents must be a .ini file at ground level, and a `styles/` folder containing arbitrary other folders. 

The general error produced isn't hugely helpful, usually looking something like this:
```
$ vale sync
Syncing foobarbaz [1/1] ██████████████████████████████████████████████ 100% | 0s
lstat /var/folders/mp/r39r3cbx7rq9qt4cj2457_vm0000gq/T/foobarbaz389805829/foobarbaz: no such file or directory
```

Other notes, happy to spin these off into other issues if it would be useful:

- When making a Complete package, I haven't been able to get an included .ini file to populate to `StylesPath/.vale-config`. If the .ini file is on the same level as the `styles/` folder, it doesn't populate. If the .ini file is inside the `styles/` folder, _only_ the .ini file populates.
- I can't find any examples of an existing Complete package. Do you have any you can provide?

**Comment by jdkato** [comment]
The name of the package is what you use to reference it in your `.vale.ini`. There are no other requirements, so, notably,

> for a Complete package, the name of the zip file must be "styles.zip". The contents must be a .ini file at ground level, and a styles/ folder containing arbitrary other folders.

is not true.

I would recommend versioning through the URL (such as with GitHub Releases) rather than the name of the package. However, if you choose, you can still do something like this:

```ini
StylesPath = styles

Packages = v3-1.0.0.zip

[*.md]
BasedOnStyles = Vale
```
There are examples in [this repo](https://github.com/errata-ai/vale/tree/v3/testdata/pkg) as well as in [the docs](https://vale.sh/docs/keys/packages#complete).
