### ISSUE TITLE
Vale sync fails when githubusercontent.com is not available

### ISSUE THREAD

**Issue by acarnefixw** [vale-cli/vale#932]
### Check for existing issues

- [X] Completed

### Environment

- OS: Linux
- Install method: Direct download
- Version: 3.9.1

### Describe the bug / provide steps to reproduce it

I am working in an environment that does not have access to the open web. We have created our own Vale package that is hosted on a local GitLab instance; however, when I try to install it using `vale sync` I get this error:

`Get "https://raw.githubusercontent.com/errata-ai/styles/master/library.json": dial tcp: lookup raw.githubusercontent.com on <IP-address>: no such host`

Looking at the source code it seems like this is probably an error when it looks at the Vale package hub. Since I do not need access to the hub, it would be nice if the `sync` command could still work for my locally hosted package.

**Comment by jdkato** [comment]
This will be fixed in the next release.

(Related to #870.)
