### ISSUE TITLE
StylesPath in config file doesn't expand user directory / $HOME

### ISSUE THREAD

**Issue by lionawurscht** [vale-cli/vale#94]
Hey, I just struggled a bit with setting up my own style for a project I'm working on at the moment.
One problem that arose was that vale doesn't seem to expand either, `~/` nor `$HOME` to the users home directory. Since I synchronize my config files over several machines it would be very much appreciated if you could add this functionality.

On a side note: another problem was that vale only accepts `*.yml` but not `*.yaml` as an extension. Maybe this should be noted explicitly in the docs somewhere? Also, vale doesn't seem to follow symlinks in the StylesPath. (I'm not used to opening issues, should these points be put in seperate issues?)

Thanks in advance  :+1:  and sorry if I missed this in the docs, I scanned them several times but couln't find any allusion to this behaviour.

**Comment by jdkato** [comment]
Hi,

1. Yes, Vale currently doesn't expand `~/` or `$HOME`. That said, it should still be possible to synchronize Vale's configuration across different machines: assuming your `.vale.ini` is also stored in `$HOME`, you can simply specify your `StylesPath` relative to it&mdash;meaning that you can move the configuration without changing any path values.
2. I'll add a note about `.yml` vs. `.yaml`.
3. Yes, Vale currently doesn't evaluate symbolic links. This functionality is included in the standard library ([`EvalSymlinks`](https://golang.org/pkg/path/filepath/#EvalSymlinks)), but there were a number of upstream bugs on Windows when I implemented `StyesPath` handling (see the issues at [`golang/go`](https://github.com/golang/go)). I'd like to keep path handling simple and easy to test, so I can't guarantee that I'll change this any time soon.

**Comment by lionawurscht** [comment]
Hey,

1. Stupid me, I didn't even consider that. That helps a lot. 
2. Great, I'm sure I could've guessed if I had just read the docs more carefully but maybe it helps someone else.
3. Ah okay, that's a pitty, I tried to somehow fix that myself but I never worked with go and failed at building the project 😓

Anyways, thanks for the quick answers and thank you for working on this project 😁

**Comment by wouter-veeken** [comment]
@lionawurscht @jdkato I found this issue because I'm having a similar struggle. I'm not fully grasping this proposed solution... 😬
> it should still be possible to synchronize Vale's configuration across different machines: assuming your `.vale.ini` is also stored in `$HOME`, you can simply specify your `StylesPath` relative to it—meaning that you can move the configuration without changing any path values.

What would this setup look like, exactly? Thank you for your trouble!

**Comment by jdkato** [comment]
@wouter-veeken: Something like this:

```text
$HOME/
├── styles/
│   ...
├── .vale.ini
```
Where `StylesPath = styles`.

**Comment by nkcfan** [comment]
If I create a symlink of .vale.ini in a project directory, which is not under $HOME, the relative path solution does not work.

**Comment by ChrisChinchilla** [comment]
@nkcfan What OS do you use? I have my config setup like this on macOS and it works fine

**Comment by nkcfan** [comment]
Debian 4.19.118-2
