### ISSUE TITLE
[Question] Customizing vale to handle java swagger core annotations

### ISSUE THREAD

**Issue by gaurav-nelson** [vale-cli/vale#96]
I am working on an API specification, which is generated using swagger core annotations (https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X) in `java` files.

If I want to use vale for linting these annotations in `java` files, would following modifications be sufficient?
in file `vale/core/format.go`: 
- creating a new regex for `blockstart` and `blockend` 
- updating `java` entry in `FormatByExtension` to handle those as new regex as comments.

sample `java` file:
```
public class ABCD{
    @ApiModelProperty(value = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam mi nibh, malesuada sit amet viverra sit amet, rhoncus non massa. Pellentesque fringilla eros dolor.")
    private final Integer idABCD;

    @ApiModelProperty(value = "malesuada hendrerit. Vestibulum vel purus auctor arcu sodales vehicula in accumsan.")
    private final CD cd;

    @ApiModelProperty(value = "Praesent cursus sed ex at viverra. Nullam at libero est. Proin ut orci mattis dui tincidunt tincidunt. Morbi fringilla porttitor est, nec venenatis elit rutrum eget.\n" +
            "- Integer quis diam et dolor malesuada hendrerit. Vestibulum vel purus auctor arcu sodales vehicula in accumsan leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id purus eu neque consequat consequat eu eget tellus. " +
            "Nullam viverra eros rhoncus risus volutpat viverra. Vestibulum non neque et orci tincidunt porta at sed risus. In consequat congue neque sed mattis. ")
    private final Integer XYZ;

...

```

Or will it require more than that?

**Comment by jdkato** [comment]
Those changes would be enough to add a new *comment* type. In this case, though, the target text is actually a *string*&mdash;which Vale currently doesn't have the ability to lint properly (it would really need an AST-level understanding of Java to do this).

I'd suggest using something like [`javaparser`](https://github.com/javaparser/javaparser) to extract the annotations to a Vale-compatible file format (plain text, most likely).
