### ISSUE TITLE
Browser Integration

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#97]
[Continuing #10]

The basic idea here, as far as I see it, is to expose Vale's functionality through an API that we call in the browser extensions. This is similar to, for example, How [LanguageTool](https://languagetool.org/#firefox_chrome) implements their browser extensions.

That said, the challenge with Vale is figuring out how to handle its configuration options when running it remotely. My initial thought is that we should provide a selection of pre-made styles that users can choose from&mdash;i.e., we wouldn't accept external customizations (with the possible exception of a spelling vocabulary file maintained in the extensions in-browser config).

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

**Comment by ChrisChinchilla** [comment]
Great! I am looking into this slowly, open to ideas from others :)

**Comment by ChrisChinchilla** [comment]
Adding this screenshot here to park it somewhere related to this issue. Possible solution to chrome blocking access to local files.

![2018-12-31 16 11 09](https://user-images.githubusercontent.com/42080/51624469-8c61cb80-1f43-11e9-8795-b23ca58ead6b.jpg)

**Comment by jdkato** [comment]
After trying out practically every possible solution (including hosting an API, using Native Messaging, and building a more full-featured web application for Vale), I've convinced myself that a hybrid approach will be the best fit for dealing with sandboxed applications like browsers and Google Docs.

I'll be developing and discussing this technique over at the [vale-server](https://github.com/errata-ai/vale-server) repo.

(I'll also be releasing a Google Docs Add-on very soon!)
