### ISSUE TITLE
Support multiple Hunspell dictionaries

### ISSUE THREAD

**Issue by eskwayrd** [vale-cli/vale#98]
Hunspell supports multiple dictionaries: a word is "correct" if it appears in one of the specified dictionaries.

I've been using Hunspell for years, and have a number of custom enterprise-specific dictionaries that I use in addition to the standard `en_US-large` dictionary. My custom dictionaries make extensive use of their associated affix configuration.

It would be great if Vale could support multiple dictionaries. The `ignore` facility can work, but I need to expand all of the affix permutations to match the spell results I currently get from Hunspell.

**Comment by jdkato** [comment]
This is actually a limitation of the library we use to read the dictionaries (see https://github.com/client9/gospell/issues/7).

That said, it's definitely on the list of changes I'd like to make to that library (either via PRs or a fork), but I'm not sure when I'll get around to doing it.

**Comment by eskwayrd** [comment]
Oh, I see. I'm not blocked by this, since I can unroll affixes.

Thanks for the update! I look forward to that someday when this issue is addressed.

**Comment by makew0rld** [comment]
> Oh, I see. I'm not blocked by this, since I can unroll affixes.

@eskwayrd What do you mean by this? I'm trying to use vale with Canadian English and I can't see a way to do that.

**Comment by jdkato** [comment]
The first version of this will be available in the next release. 

There'll probably still be performance-related work that needs to be done for multiple, large dictionaries, but the basics are in place.

**Comment by jdkato** [comment]
Initial support is out in [v2.8.0](https://github.com/errata-ai/vale/releases/tag/v2.8.0).

**Comment by eskwayrd** [comment]
Awesome! Thanks so much for your work to support this issue!

**Comment by ChrisChinchilla** [comment]
That is really cool! Especially as I like to mix UK and US English… @jdkato do you need a docs update for this? I am happy to handle that if so.

**Comment by jdkato** [comment]
@ChrisChinchilla: I had an update ready, but I just pushed it: https://docs.errata.ai/vale/styles#spelling. Feel free to suggest modifications, though.

**Comment by ChrisChinchilla** [comment]
> @ChrisChinchilla: I had an update ready, but I just pushed it: https://docs.errata.ai/vale/styles#spelling. Feel free to suggest modifications, though.

Seems reasonable, I actually just want to test this feature for my own use :)
